### ISSUE TITLE
cauldron emptying

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#10]
the research page on alchemy states that the cauldron can be emptied by shift right clicking with an empty hand, however this does not work. Shift right clicking with an empty gauntlet empties the cauldron. Not sure if its a bug or a mistake in the research page.

Additionally, emptying a cauldron overflowing with aspects also seems to clear the aura of any flux that has escaped. I threw multiple stacks of voidmetal blocks into a cauldron until a nasty plume of flux was wafting into the air, and the thaumameter read that the chunk was saturated with flux (i had also used a gauntlet to drain the chunk of vis) and so i tried to dump the cauldron to get the flux out faster, but doing so completely restored the chunk to perfect, fluxless, health.

**Comment by Azanor** [comment]
Yup, it should be an empty hand.

I am unable to reproduce the flux bug though - it works like it should for me.

**Comment by gabeernie** [comment]
When I dump upwards of 6 or so  64 stacks of void metal, and the aspect found reaches the 8/9,000's the thaumameter usually reads full flux levels within a few moments. However, emptying the crucible, with still thousands of aspects inside, seems to clear all the flux out of the chunk. It may just be an issue with the gigantic amount of aspects I have boiling over that causes some sort of error, as I haven't tried to empty a crucible that has a reasonable (aka non-creative) amount of aspects inside.

**Comment by Azanor** [comment]
You might be hitting some sort of numerical overflow. I'll put a check in to block the addition of flux beyond a certain point.
