### ISSUE TITLE
[B16] Balance Suggestion: Lower essentia cost of metal purification recipe

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1005]
This is mostly concerning the Ordo cost, though the Metallum cost might be considered a bit much, as well.

This is also primarily considering the crucible crafting phase, when the alchemical metal purification is the most useful. (early in game, desperatly need extra ores to advance) The midgame "I dupe the metals with the essentia smelter" is also somewhat short lived, since the arcane bore with a Refining Pickaxe doesn't cost essentia and doesn't cause flux and could be considered the vastly superior option.

The reason for me considering the Ordo cost too high is that there simply is no "good" source of Ordo. Most things that do have ordo have a considerable bit of other aspects, none of which you can get rid of easily through adding other recipes. The arguably best source, simply because of the minimal amount of trace aspects, is the chiseled stone bricks (3 Terra, 1 Ordo). You *can* get rid of the terra through the Lava Bucket recipe, but it's painful, because Ignis is also not easily obtained in a cleanish way.
So to create 8 Native clusters (8 because that's the smallest amount you smelt with one piece of coal), you end up with 8*5*3=120 points of excess Terra.
So unless you are willing to drown the environment in flux, you can barely use the recipe.
Flux aside, this has the additional non-neglible time consumption cost of having to mine 40 cobble stone and having to burn it all into stone. Multiply by 8 if you want to turn a whole stack of ore into clusters.
Of course you could say "just use Ordo Vis Crystals", but that'd be 40 crystals for the same 8 clusters, which you can't really replenish easily at that point in the game.

As for the Metallum cost:
Illustrating this with Iron Ingots and Native Iron Clusters, you basically spend 1 Iron Ingot to create 3 extra Iron Ingots (ignoring the extra nuggets from the infernal furnace for simplicity reasons), giving you a net gain of 2 Iron Ingots per 3 Iron Ore. This 66.67% increase does not compare favorably at all to the 100% you get when you eventually misuse the Arcane Bore as a purification machine. Lowering the Metallum cost of the recipe from 5 down to 3, 2 or 1 would turn this into a 80%, 86.67% or 93.33% increase, respectively.

The way things are balanced now, I'd recommend decreasing the recipe cost down to 1 Ordo and 1 Metallum. This will keep the recipe relevant throughout the game and make it a lot less painful in terms of flux and cobblestone mining. At the same time, you still end up with 192 excess Terra for every stack of clusters, so the flux still stays non-trivial, as I feel it should be.

**Comment by androshalforc** [comment]
redstone
unless im wrong redstone is an excellent source of potentia which breaks down to ordo

**Comment by MalkContent** [comment]
A piece of redstone dust has 10 potentia, but that doesn't break down in the crucible, so you should be at the essentia smelter stage anyways, so it's comparatively easy to get rid of excess terra with void jars.
But even having that in mind, when you centrifuge it, you get on average 5 ordo per piece of redstone dust (pretending the essentia smelter has 100% efficiency for simplicity reasons), which means you need one piece of redstone dust per native cluster, which is more reasonable than using Ordo Vis Crystals, but still not easy to support your ore doubling with it.
With the essentia smelter, I'd just go for char coal from a tree farm, gives you 15 ignis and 5 ordo. And you can use Ignis very easily for more tallow/lava, if you don't just wanna voidjar it.
...
Anyways, thanks. Didn't even think of centrifuging potentia. But the centrifuge is fairly advanced now, so you can't rely on it until mid-late game.
I'd just like the recipe to be usable a bit less painstakingly before automating everything. At that point the essentia cost doesn't matter anymore anyways.

**Comment by AbortRetryFail** [comment]
Honestly I think the balance for this works OK. Waste only becomes a problem if you attempt large scale mass production of magic, which I sorta feel like is _the whole point of Flux._

Nether Bricks are a good early source of Ordo. It's not as rare in TC6 as it was in previous versions. This makes the lava bucket recipe more feasible as a way to deal with the excess, since they have Ignis too.

**Comment by MalkContent** [comment]
I am not saying there should be no flux from this, but more than 100 points of flux for just 8 clusters is just not feasable for a recipe that you would want to repeat. A lot.
And once you hit automation with essentia smelters and the centrifuge, ordo cost doesn't really matter anymore because charcoal is a great source and easy to come by.

Also: Nether Bricks are much the same as Chiseled Stone Bricks in terms of ordo and mining involved. You have to smelt 40 Bricks to craft just 8 native clusters. And those 40 Nether Bricks give you 40*3=120 points of Ignis and 40*5=200 points of Terra. You can get rid of all the Ignis and 40 points of Terra, but you end up sitting on a whopping 160 points of excess Terra that way, which is even more than from Chiseled Stone Bricks (which'd give you 3*40=120 points of excess Terra).
You can get rid of it with loads of Blaze Rods, because those net you 10 extra Ignis, if you use 5 Ignis and 5 Potentia towards crafting Alumentum or Nitor, but it is beyond painful to craft.

**Comment by Raumis** [comment]
You should never have any flux produced by using the crucible, that is what the quartz slivers are for.

**Comment by MalkContent** [comment]
120 points of excess terra, per 8 clusters. you don't soak that up with quartz, at least not in a recipe that you want to repeat a lot...
I'm not saying that you can't do it, but it's just an additional level of mining to add on top of the rest.

**Comment by Raumis** [comment]
Thats 60 slivers which about 7 quartz which is about 1 vein, even easier with fortune pick.  Starting out is inefficient that's why you would progress to get the Pickaxe of the Core, and then boost then Refining enchant so you have a greater chance of clusters.  Then you don't have to use crucible at all.

On a side note looks another alternative could be to find Packed Ice, which has 15 Gelum and 5 Ordo.

**Comment by MalkContent** [comment]
Infusion/Pickaxe of the Core means you are at the Essentia Smelter/Automation stage already anyways, at which point the Ordo cost is mostly irrelevant. Packed Ice is from a super rare biome unless you rely on other mods.
The point here is to make this very early and very useful recipe actually usable early on. A Pickaxe with Fortune isn't really something that comes to mind for me there. And if i have to mine 7 Quartz to get 8 extra iron ingots, I can just go dig 8 extra iron ores and save me the "dig up 40 cobble" time.
Let me just ask you this: Have you played the current version and used the metal purification recipe during the crucible stage?

**Comment by AbortRetryFail** [comment]
I've got a 4-player SMP game going (well, broken at the moment due to the stabilizer bug...) where we've purified dozens of gold ore via the crucible and successfully built up a sizable alchemy lab. Those extra Terra crystals get used for Salis Mundus for a Praecantio source or for making Arcane Stone, so it's really not a waste of Quartz.

The #1 source of flux around the house in that game is the smelter by far and we've still not opened a rift in the house...

**Comment by Sumguy62** [comment]
Just get more metal the old-fashioned way: mine more.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#351
