### ISSUE TITLE
[b16] Touch focus is actually a projectile.

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#1008]
Thus rendering it useless against Endermen.

**Comment by Azanor** [comment]
Nope it is defintely not. Enderman however will teleport if they take any damage that is listed as unblockable (such as many magic type damages) or damage sources marked as "indirect" which some focus damage sources are. No real way to get around it unfortunately and very annoying tbh.

**Comment by AnrDaemon** [comment]
I clearly see endermen teleport before they are being hit.

**Comment by Azanor** [comment]
Where in my post did I say they would not?
