### ISSUE TITLE
Compatibility Issue With EvilCraft

### ISSUE THREAD

**Issue by princessbinas** [Azanor/thaumcraft-beta#1009]
I am not crashing of this moment, but however, upon installing BETA16 of Thaumcraft, EvilCraft's Vengeance Focus, an item that pushes defeated mobs' ghosts in to a Box of Eternal Closure. The version of EvilCraft is not the problem as I have had it prior to installing Thaumcraft and it worked as intended. With Thaumcraft installed, the Vengeance Focus loses all functionality and is rendered useless.

I have Thaumic JEI, Thaumic Periphery, and Thaumcraft Inventory Scanning installed as well. I am also using the most recent forge version, 2707.

**Comment by Azanor** [comment]
I have no idea how TC would be able to influence the EC item at all. You might want to report it to whoever codes Thaumcraft Inventory Scanning however.

**Comment by princessbinas** [comment]
I did here.
https://github.com/CyclopsMC/EvilCraft/issues/701

**Comment by princessbinas** [comment]
I will do so and come back with the link.

**Comment by Geethebluesky** [comment]
If the conflict is confirmed to be on their side, please close this issue. Thanks!
