### ISSUE TITLE
[B16] Tripple Meat Treat appears to be uncraftable

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1018]
tried it in the crafting table and the workbench, tried different shapes and nugget combos
didn't get the recipe to work
basically can shelve the world for now, not worth playing without my treats :/
if someone else manages to do it, let me know :)

only other mods are JEI and JourneyMap

**Comment by Geethebluesky** [comment]
Duplicate of #697

**Comment by MalkContent** [comment]
dammit. i did a search for tripple.
