### ISSUE TITLE
Thaumonomicon suggestion

### ISSUE THREAD

**Issue by Cenotaffio** [Azanor/thaumcraft-beta#102]
premise that i have not yet played all the beta version(i want to play in survival).
so i'm not aware of all the new content.

it would be cool if the Thaumonomicon appeared different reached a certain level of warp?
for example, you could see an eye on the cover or a slightly different background.
I always thought the book was "alive".
it seems to me quite natural that at a certain degree of paranoia one begins to perceive it as threatening. would add an interesting effect to the warp.

Sorry for eventual bad english.
and congratulations for the mod azanor!

**Comment by Cenotaffio** [comment]
I had another idea.
I assume the thaumonomicon wants the player to concentrate on the book.
if you add the effect that if it is kept in the hotbar (or even in hand) the warp or its effects are slightly reduced (until it is moved), the players will be incentivized to keep it compulsively close at hand.

**Comment by Goof245** [comment]
Hotbar slots are a premium commodity as it is, _especially_ in heavily modded MC....

Not sure taking up a slot for this would be a great idea IMO.

**Comment by nnystyxx** [comment]
That said, I do like the idea of the Thaumonomicon itself exhibiting odd behavior from Warp. Maybe striking through certain backgrounds with purple or red as the Warp builds, or occasionally garbling or replacing text with something threatening a-la Eternal Darkness' sanity effects.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#163
