### ISSUE TITLE
[Beta 16] Other Mods' Bookshelves Not Valid For Research Table Bonus Draws

### ISSUE THREAD

**Issue by TechnoMysterio** [Azanor/thaumcraft-beta#1025]
Quite simple, bookshelves from other mods, Quark's alternate wood bookshelves in this case, are not valid bookshelf blocks for the bookshelf bonus draws in the research table. In the case of Quark, this may be annoying if you only have access to non-oak wood, and can only make Quark bookshelves.

Thaumcraft: B16
Forge: 14.23.4.2708

**Comment by Azanor** [comment]
Unfortunately doing this would either require a large amount of special-case coding that should be avoided, or changing the API, which could break addon mods. I might implement this during the next big code change (for MC 1.13 for example), but not now.
