### ISSUE TITLE
Thaumcraft 6 Crucible crafting

### ISSUE THREAD

**Issue by Chelebi** [Azanor/thaumcraft-beta#1027]
* **Modpack Version**: FTB Revelation (v2.0.0) Thaumcraft 6.1.Beta16

* **Issue**: Thaumcraft 6.1.Beta16 Crucible crafting not working

* **Is it Repeatable?**: Yes

So to craft in TC6 with the Crucible you put a Crucible over a heat source and add water, then you drop items in to get the essence required to make the item you want and at last you drop in a catalyst to create the item, but right now the catalyst just gets added to the essence pool and does not trigger the crafting as it's suppose to do.

I tried multiple times in SP and MP crafting with the Crucible does not work the catalyst doesn't trigger the crafting

**Comment by goron111** [comment]
What did you try to make? Did you unlock the recipe by progressing in TC?

**Comment by Chelebi** [comment]
i was trying to make Alchemical Brass ingots, so i dropped some tools in for the tool essence and then a iron ingot but the iron ingot just added the metal essence

**Comment by EricBuist** [comment]
Hi, I'm having problems with the crucible for the lesser blank focus. It worked once, then it started to fail. Seems I have to be super quick for essentia not to evaporate, but I'm not. I cannot check quick enough the essentia counts until some evaporate. So this mechanic is pretty much unusable for me, excesively painful and frustrating. I cannot play this mod without thaumic energistics, which is not in any 1.12 packs I know of. Seems I have to cheat the items or create fake recipes with CraftTweaker. This is just insane.
