### ISSUE TITLE
Thaumcraft Crucible issues

### ISSUE THREAD

**Issue by mkempster22** [Azanor/thaumcraft-beta#1028]
Version: 6.0BETA8 (Bit more of everything modpack)

No matter what recipes I try putting into the crucible I cant get it to change colour or produce the result. I have alchemy unlocked in the thaumonomicon, adding the correct vis for nitor wont work at all for me

**Comment by Geethebluesky** [comment]
Please note any versions for 1.10.2 won't get any bugfixes, development has moved over to 1.12.2.

Your best chance is to update to the last beta available for MC 1.10 and try again, but if the problem is still there it's likey you'd be stuck with it.
