### ISSUE TITLE
[B16] Stabilizer Research either disappeared, or is craftable without

### ISSUE THREAD

**Issue by katzenpapst** [Azanor/thaumcraft-beta#1030]
Crafted two stabilizers, and just wanted to look them up in the Thaumonomicon. The entry wasn't there.

I looked the recipe up in ThaumicJEI and was able to craft it, seemingly without having researched it. However, I remember reading the Thaumcraft entry of the stabilizer before. But I might have done it in creative mode...

ThaumicJEI is ThaumicJEI-1.12.2-1.3.1-12

**Comment by Azanor** [comment]
Very strange - I can't duplicate this at all.  So the entry isn't present in the infusion chapter at all?

**Comment by katzenpapst** [comment]
It wasn't present there, no. And I was able to craft the stabilizer.
Maybe this is ThaumicJEI's fault? It has always been able to display recipes even before you researched them, maybe it is somehow able to bypass your "has user even researched that?" check?

**Comment by Gravityowl** [comment]
I'm getting this as well, but not only from the stabilizers, the only mod i have in besides Thaumcraft and baubles is JEI. every recipe that uses the arcane workbench i can craft before I'm anywhere near it in the research tree
