### ISSUE TITLE
Just a suggestion:  Make it possible to destroy the Flux Rift.

### ISSUE THREAD

**Issue by Furious1964** [Azanor/thaumcraft-beta#1031]
I would like to see this, but the process has to be labor intensive and time sensitive...meaning that it will require more resources and time to close a Rift depending on the amount of time the Rift has been open.

**Comment by Reassembly** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/922#issuecomment-394286769

It's in the works.

**Comment by Furious1964** [comment]
Thank you.
