### ISSUE TITLE
[B16] 1.12 the 'HEDGEALCHEMY' research bug

### ISSUE THREAD

**Issue by NextdoorPsycho** [Azanor/thaumcraft-beta#1032]
_This was a problem a bit  ago @Azanor _, regarding the alchemy side of things (by a bit ago, im regarding the thaumcraft beta pre-release ext... this was an issue)
the research for **HEDGEALCHEMY** _(tossin' stuff to make more of what you tossed)_ catalyst doesn't trigger the crucible to output out what you were trying to make

**Example:**
The cost for gunpowder is 
_(this is not correct, this is an example)_

**5-Ignis 5-Fabrico 5-Perditio** _(again this is just an example, replace this with whatever the ingame cost is)_
you toss in gunpowder and instead of getting 2 in return you get nothing in return but a bunch of vis _(of the type that is already in the crucible)_ and a _sad aura_ that needs to _eat all that_

This occurs with the of the first of 2 stages of HEDGEALCHEMY, however, I am unsure of the second tier because of the block it makes, but I'm sure its still the same

**Version**: _**Thaumcraft-1.12.2-6.1.BETA16**_ 

**Related Threads**:
**#1027** (for the wording and issue- but not the problem)
^^ 

> "I tried multiple times in SP and MP crafting with the Crucible does not work the catalyst doesn't trigger the crafting"

 but the issue is not 

> "ok i found my error :( i had to klick the alchemy tab in the Thaumonomicon, didn't see it at first but now it's working ..."

**#980** (regarding that the fix opened up a new wall of issues) same category, issue was a child of this

_[can provide anything on request: pictures, logs, anything. just ask 👍  ]_

**Comment by MalkContent** [comment]
Well this is a mildly confusing read. The issue is just that your catalysts don't trigger the recipe output and consequently add more aspect points to the crucible? And that is limited to Hedgealchemy?
If you got other mods installed, please try a pure TC install to check that this isn't a bad mod interaction.

**Comment by NextdoorPsycho** [comment]
on a clean or mixed mod interaction _(with and or without other mods)_ I'm able to reproduce this Perhaps its the forge version, but I doubt it
Thanks for keeping tabs on this @MalkContent

**Comment by MalkContent** [comment]
can you make a screenshot of your hedge alchemy research page and a screenshot of the crucible with the aspects in it needed for one of the recipes
i don't experience this issue and if this was a general issue happening to many people, it probably would have come up in the thaumcraft discord. so you are either doing something wrong or are experiencing something very rare, so lets get as much info as possible

**Comment by Schattenn** [comment]
Have you tried putting in just a bit too much of each aspect needed for crafting? It's unlikely since you seem to have tried several times, but maybe an aspect decayed and left the recipe incomplete right when you were adding the catalyst. Happened to me when I was too slow once.

**Comment by NerdimusPrime** [comment]
I've been having the same problem, and as a quick test I tried right-clicking the ingredients into the crucible, but tossing in the catalyst. My thinking was maybe that's how it differentiates between what's an ingredient and what's a catalyst, especially when the same item can be both? Anyway, it worked for that particular test, but not when I tried making lava buckets. I hope to have time today or tomorrow for a more rigorous test on a pure TC install.

**Comment by princessbinas** [comment]
I think this is also my issue too.
https://github.com/Azanor/thaumcraft-beta/issues/1043

**Comment by Azanor** [comment]
Is this still happening in b17?

**Comment by scalpingsnake** [comment]
This is happening to me in b17. I tried to make a lesser focus and it wouldn't accept the catalyst. I updated to b19 and still had the issue.

**Comment by MalkContent** [comment]
@scalpingsnake  can you provide pics of setup and research, as well as mod list? might help getting to the bottom of this

**Comment by scalpingsnake** [comment]
Hey, sorry, I should have deleted this. I am pretty sure I was doing it wrong because I am an idiot :/

**Comment by NextdoorPsycho** [comment]
@Azanor ill be able to test this a bit later
