### ISSUE TITLE
[B16] Infernal Furnace Flux output not affected by bellows

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1033]
The Thaumonomicon entry of the Infernal Furnace says that attaching Arcane Bellows to the Infernal Furnace reduces the flux generated by it. Poking through the code, the chance to generate flux seems to be unaffected by the bellows (I may just have overlooked something though).

Generally, I wouldn't care if the Thaumonomicon entry or the flux chance changed, as long as it meant consistency.
For the current state of the beta though, I'd really like the flux chance to be lowered by the bellows, because for now there is no non-volatile way to get rid of flux and using the Infernal Furnace is a real liability.
(Okay, you can make primal vis crystal clusters turn to into vitium vis crystal clusters, but since we can't control the flow of flux [unlike vis, with the vis batteries], that is difficult/dangerous and also very arduous and of little effect)

**Comment by Azanor** [comment]
That must be some old leftover text - they are not supposed to reduce the flux anymore.

**Comment by MalkContent** [comment]
thanks :) and sorry for the code poking
