### ISSUE TITLE
[B16] QoL: The active recipe in the Thaumatorium can only be seen with an inserted item

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1035]
The active recipe in the thaumatorium can only be seen in the GUI when you insert an item into the catalyst slot (I didn't test it with multiple active recipes).
This means in order to deactivate the recipe you have to insert any kind of item (preferably not the active recipe's catalyst, seeing as that you don't want to craft it, when you want to disable it).
This can be a minor nuisance up to genuinly annoying, say, when you had the recipe for Alchemical Brass activated and want to craft some Thaumium.

**Comment by AlekseiVoronin** [comment]
I Agreed.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#350
