### ISSUE TITLE
[B16] Inventory blocks can be scanned again and again with different inventories

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1036]
At least I explain it to myself with the different Inventories part.
So far successfully tested with Chests, Hungry Chests and Immersive Engineering crates.

Didn't work for Furnaces or Essentia Smelters though.

**Comment by goron111** [comment]
This is a feature so you can easily scan all the items in the chests. Its not a bug

**Comment by MalkContent** [comment]
huh. TIL. thanks
