### ISSUE TITLE
Feature request: Capability-based interfaces

### ISSUE THREAD

**Issue by rubensworks** [Azanor/thaumcraft-beta#1037]
_I posted this a while back on the API repo (https://github.com/Azanor/thaumcraft-api/issues/18), but I'm not sure if you are tracking those issues, so I'm reposting it here to make sure._

Would you be willing to move interfaces (such as `IEssentiaTransport`) towards to the Forge capability system?

This would allow for a lot more flexibility and dynamic injection of capabilities for tiles and items for addon developers.

**Comment by Azanor** [comment]
Yup, I did see it and I might do it at some point, but for now it is fairly low priority.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#349
