### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by groting** [Azanor/thaumcraft-beta#104]
![2018-01-25_19 24 12](https://user-images.githubusercontent.com/5873866/35396435-db39eb66-01fd-11e8-96ec-4068cbca3a67.png)
![2018-01-25_19 31 32](https://user-images.githubusercontent.com/5873866/35396512-025875b4-01fe-11e8-9620-9cd2272c4bec.png)

**Comment by DCVHacker** [comment]
Since this is beta, the localization is not yet completed, there is not even a section of the ancients ready, so do not pay attention to it. 

Google Translator

**Comment by groting** [comment]
Beta 3 solved
