### ISSUE TITLE
Advanced Control Seal: Empty not crafting

### ISSUE THREAD

**Issue by Gavran** [Azanor/thaumcraft-beta#1040]
The Control Seal: Empty is not working as a valid catalyst with sufficient aspects (10 Sensus, 10 Cognitio, confirmed with goggles) and water in the crucible. Recipe matches in JEI and in Thaumonomicon.

**Comment by Azanor** [comment]
What version of TC are you testing with? There was an older bug that caused crucible crafts to not work.

**Comment by Gavran** [comment]
Oops, silly of me to not include that especially since I believe the pack just did a downgrade for stability. 6.1Beta13.

**Comment by Azanor** [comment]
Tested this again and it still works fine for me. Clicking on the crucible with a seal does not work, you need to drop it in.

**Comment by Jaeiya** [comment]
@Azanor 
I have this bug on BETA26... just throwing the control seal onto the crucible causes it to be absorbed and not transform into the advanced seal.

**Comment by dstephens1980** [comment]
Can confirm [BETA26] Stoneblock 2 modpack, no Advanced Seals can be crafted as crucible will absorb seal if "dropped" in and place seal on crucible if right clicked.
