### ISSUE TITLE
suggestions and a question

### ISSUE THREAD

**Issue by aycfes** [Azanor/thaumcraft-beta#1041]
so, many mods use the amulet bauble slot, for manny interesting items, but that slot is always taken up by a vis stone or the (amulet of which the name i forgot). similar, item charging, baubles that can be placed on other slots would solve that

also will more gauntlets be added? as in, higher level ones or some kind of costumization/upgading to them, akin to the good 'ol wands?

(thaumostatic harness for the body baubles slot, btw :3)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#348
