### ISSUE TITLE
Making New Vis Crystals In Crucible Bug

### ISSUE THREAD

**Issue by princessbinas** [Azanor/thaumcraft-beta#1043]
When I try to make new Vis Crystals of any sort (Motus, etc). In this example I will use Mortus. I use the Water and Atrophy Vis Crystals in the Crucible around fifty times, literally. I do not get a Mortus Vis crystal. I may get one of the components back, a completely random Vis crystal like Bestia or any other, or absolutely nothing. I am doing the steps correctly too. I am tossing the Water and Atrophy Vis crystals in then right clicking with a quartz sliver. The crucible is full of water and there is a heat source underneath. This is in BETA16.

**Comment by MalkContent** [comment]
you can't combine essentia into a higher aspect
you can only use the centrifuge to split higher aspects into its components

**Comment by princessbinas** [comment]
I am not trying to make a higher aspect. I am trying to to use the crucible to progress. I was finding it near impossible to progress in the alchemy section because I could not combine what was needed to make alchemy brass and such. I had to cheat the requirements in to get anywhere.

**Comment by MalkContent** [comment]
you threw in water and atrophy vis crystals (which i assume means aqua and perditio) to get a mortuus vis crystal. that sounds like you wanted to combine aqua and perditio to mortuus.. ?

**Comment by princessbinas** [comment]
Yes. I want to get that and a few other combinations so that I can progress. Right now, making the essentia required for Alchemy Brass is infuriating me because I cannot get the Potentia Vis (Ignis and Odor) to form at all.

**Comment by MalkContent** [comment]
you can't. combine them. ... did you even read what i wrote?

**Comment by Necrolythe** [comment]
@princessbinas The Crucible can only break down raw items (ingots, blocks, etc) into their aspects/essentia. You are not able to combine essentia/aspects to create complex ones. If you are trying to get Mortuus essentia/crystals, I'd recommend throwing in some drops from hostile mobs, such as Spiders or Skeletons. (HINT: ThaumicJEI will be immensely helpful when trying to search for proper items to process for this)
