### ISSUE TITLE
[B16] Bolt focus fired from a boat goes nowhere

### ISSUE THREAD

**Issue by AbortRetryFail** [Azanor/thaumcraft-beta#1047]
If you fire a focus with the Bolt medium from a boat, the hit effect happens right in front of the player and the bolt does not hit its target.

Don't know if it's hitting the boat or not, but it doesn't cause the boat to break.

**Comment by Azanor** [comment]
That is because the player is technically inside the boats hitbox and that confuses the current wand system. No easy workaround for this unfortunately.
