### ISSUE TITLE
[B16] Bringing the game to 0 FPS using spellbats

### ISSUE THREAD

**Issue by Gravityowl** [Azanor/thaumcraft-beta#1049]
I'm not entirely sure whether the Blank Greater Focus is implemented or not as i have yet to find a way to unlock it, however this is possible on smaller scales with multiple casts.   
Alright, so i have managed to bring the game to less than 1 fps using this spell:
![image](https://user-images.githubusercontent.com/39000677/41683382-4a72d354-748f-11e8-8906-db95d14df925.png)
Basically what it does is attempt to lag out my game to the highest degree possible and does so in a less than spectacular fashion with just one cast, according to the spell and my math (I may have gotten the math wrong), It should only be spawning 729 bats but when the game lags out i get upwards of around 3450 entities that are solely spellbats. This only really happens to this degree i think because spellbats can trigger their own mines, however it can still happen fairly easily if cast in a closed off space. Here are some pictures of the f3 menu before and after the bat apocalypse hopefully they are helpful somewhat
![2018-06-20_13 49 37](https://user-images.githubusercontent.com/39000677/41684251-cb409f28-7491-11e8-9adf-577e2543e626.png)
![2018-06-20_13 55 34](https://user-images.githubusercontent.com/39000677/41684265-d4ed1b46-7491-11e8-972b-639dd62837b6.png)
![2018-06-20_13 52 49](https://user-images.githubusercontent.com/39000677/41684272-d8fdaee4-7491-11e8-818f-7e09381cfa38.png)
Perhaps adding a cap on the number of bats in an area or from a spell could stop this?

**Comment by aycfes** [comment]
i did something similar with only projectiles and scatter, but my game just straight up crashed and i had to uninstall and re-install thaumcraft to be able to play again ._.
so, i agree that something should probably be done...

also, nice graph, seeing it makes me happy

**Comment by Morinor** [comment]
9 forks that create 9 forks that create nine forks... etc.
guess you have to expect that the game cant handle that.
maybe a forced despawn when at, dunno, 5 fps for spellbats would be the solution...

**Comment by Azanor** [comment]
Bravo sir, bravo.  :)

**Comment by Azanor** [comment]
What I'm going to do is limit it so that scatter can only be used once in a focus. It might be a big nerf, but it will prevent situations like this.
