### ISSUE TITLE
Focus pouch bug

### ISSUE THREAD

**Issue by groting** [Azanor/thaumcraft-beta#105]
If you dress focus pouch in baubles slot, when you remove focus with shift+f it is not displayed in pouch,

Before:
![2018-01-25_19 35 07](https://user-images.githubusercontent.com/5873866/35396969-37d702c2-01ff-11e8-8cf2-1841479574fd.png)

After:
![2018-01-25_19 35 15](https://user-images.githubusercontent.com/5873866/35396989-473df054-01ff-11e8-884a-ad4ae80dda30.png)

Pouch:
![2018-01-25_19 41 23](https://user-images.githubusercontent.com/5873866/35397027-6085da0e-01ff-11e8-80c8-3937d718a6de.png)

If use pouch in inventory it work fine.

**Comment by MainFreak** [comment]
Can confirm. However if you equip a different focus it reappears.

**Comment by groting** [comment]
Beta 3 solved
