### ISSUE TITLE
[B16] Saturation defeats Unnatural Hunger

### ISSUE THREAD

**Issue by MarEe0** [Azanor/thaumcraft-beta#1050]
Got some Unnatural Hunger, and before I went hunting for zombie flesh, I ate some cooked beef until I was full. Hunger then stopped going down while the saturation effect lasted. 3 beefs and I defeated 4mins of un. hunger. Bug?

**Comment by Morinor** [comment]
saturation effect? you dont mean the potion effect, right? 
because im pretty sure that one will fill your hungerbar even if you have unnatural hunger

**Comment by MarEe0** [comment]
No, I mean normal saturation from food.

**Comment by Azanor** [comment]
Saturation acts as a buffer for your food stat so unnatural hunger will be lowering it till it is gone. Unfortunately there is no easy way to bypass that directly, nor do I think there is a real need to.
