### ISSUE TITLE
[B16] Using Salis Mundus to create Workbench, Thaumonomicon, or Cauldron all result in a crash.

### ISSUE THREAD

**Issue by EinarAsgeir** [Azanor/thaumcraft-beta#1051]
Well, the title clears it out pretty well. I tried it without mods, and with them, although its probably an Optifine bug since Optifine is only really good for lag issues, and not mods. But without it, or any other mods in play, using Salis Mundus to turn the bookshelf into the Thaumonomicon, or any such with that ingredient, results in a total crash that causes the game to shut off, and have to be restarted in order to get it working. - Dainn/Einar

**Comment by MalkContent** [comment]
are you sure that you are on B16 and not on B15?

**Comment by Azanor** [comment]
Without a log I can't do much so closing this for now.
