### ISSUE TITLE
Catch myself on fire, but nothing comes of it.

### ISSUE THREAD

**Issue by Mijithemidge** [Azanor/thaumcraft-beta#1052]
I had been trying to do the step of base auromany where you "examine fire very closely", and I had found online that this means that you catch yourself on fire. I did so many times and also died many times doing that. I don't know why it won't give me the research. I am using a mod that modifies myself, but I don't think it affects fire values (vampirism- become a vampire). I just have no idea why dying of fire damage is not working of all things. I ended up having to give myself the full research.

**Comment by Sketaful** [comment]
"I am using a mod that modifies myself, but I don't think it affects fire values"
Please try without any other mod first to be sure. ;)

**Comment by androshalforc** [comment]
Yeah fire protection buffs prevent you from getting the research 

Its possible that anything that modifies fire resist might as well

While i dont know the specifics of your mod vampires usually have some kind of effects with burning

**Comment by Mijithemidge** [comment]
It does seem to work fine without vampirism. Just the presence or the vampire mod (without being a vampire) still allows it to work. However, it seems that being an actual vampire makes it no longer function. So I guess the only thing to do is get your thaumaturgy well on it's way before you become a vampire.

**Comment by princessbinas** [comment]
Or you can reset yourself if you find/make a cleansing altar. But you would need to make sure you have the stuff you needed to get back to where you were as a vampire. I reported this on the Vampirism mod issues page to see what Maxanier can do to get around this.

**Comment by maxanier** [comment]
As a workaround you can go to your config directory (or use the GUI Main Menu -> Mods -> Vampirsm -> Config -> Balance) and open the Balance - vampire_player.cfg (Vampire Player General) and change fire_vulnerability_type to 0 and fire_vulnerability_max_mod to 1. Thereby the increased fire vulnerability added by Vampirism is deactivated.

It would be nice to somehow avoid this by triggering the research in a different way. Maybe the threshold for getting the research can be reduced (at least if Vampirism is installed) or Vampirism could trigger the research in a different way
