### ISSUE TITLE
Thaumcraft + Ice and Fire produces crash

### ISSUE THREAD

**Issue by aridhol** [Azanor/thaumcraft-beta#1053]
https://paste.dimdev.org/hiconuyesu.mccrash

I've talked to Ice and Fire, and apparently some of your code is overriding theirs - any word on when this will be fixed potentially?

**Comment by aycfes** [comment]
i have no problems running both simultaneously

**Comment by thrashmodule** [comment]
Revert back to Beta 13 until the problem gets fixed. This will eliminate the ticking entity issue.

**Comment by Azanor** [comment]
This should be fixed in b18
