### ISSUE TITLE
Sand on Infusion altar

### ISSUE THREAD

**Issue by SingleTonne** [Azanor/thaumcraft-beta#1055]
Yeah I accidentally let some sand drop onto my altar and where it landed on the infusion pillars, it stayed there as a falling sand block, which you can't mine or remove so was forced to take down and rebuild the altar. Not a massive issue at all, but a bug nonetheless.

**Comment by enderger** [comment]
Push the entity with a piston.

**Comment by Azanor** [comment]
Unfortunately not really something I can do anything about - this is a vanilla issue.
