### ISSUE TITLE
Silverwood leaves despawn even if placed by a player

### ISSUE THREAD

**Issue by pizzaThis** [Azanor/thaumcraft-beta#1057]
I realized this when trying to make my own silverwood tree. When harvested with shears or silk touch, the silverwood leaves retain the despawn properties of natural silverwood leaves. The only way to make them not despawn is by placing a silverwood log near. So, you can't place them anywhere in the world without strategically placing silverwood logs near.

**Comment by apmax** [comment]
Yes, this is how leaves work in minecraft.

**Comment by pizzaThis** [comment]
You are able to use shears or silk touch to harvest and place any vanilla
leave type anywhere in the world without it despawning. I do it all the
time :)
