### ISSUE TITLE
Command suggestion

### ISSUE THREAD

**Issue by generrosity** [Azanor/thaumcraft-beta#1059]
Hello!

Could I suggest that being able to "get"/"list" a player's warp be added (or referenced in the help if already exists)?

Trying to diagnose something for a single user, at the stage of deleting player profiles - know she has bad interactions with someone else's base,

**Comment by enderger** [comment]
Sanity checker while holding shift?

**Comment by generrosity** [comment]
I didn't think that worked for other players? Or does that work differently for Ops?

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#375
