### ISSUE TITLE
Basic Auromancy Stage 2/3 Bug in BETA16

### ISSUE THREAD

**Issue by princessbinas** [Azanor/thaumcraft-beta#1065]
When I try to complete "Examine Fire Very Closely," nothing happens. I know I am supposed to step into the fire and get burnt, but getting burnt does nothing but get me killed. I am using the Dark MagicTech modpack made by iamtpage.

**Comment by Azanor** [comment]
Does this still happen in b17?

**Comment by princessbinas** [comment]
It indeed still occurs in BETA17 when you are a vampire.
