### ISSUE TITLE
[Beat8]thaumcraft-beta8 1.10.2 Unable to synthesize Alumentum

### ISSUE THREAD

**Issue by Cityofdawn** [Azanor/thaumcraft-beta#1067]

**Comment by MalkContent** [comment]
This is for beta8... current version is beta16 and it definitly works there.

**Comment by Geethebluesky** [comment]
@Cityofdawn Development of TC has moved to 1.12 entirely, the 1.10 version is not going to be supported in the future so it won't get any fixes. You might want to consider moving to 1.12.
