### ISSUE TITLE
No good source of Gelum

### ISSUE THREAD

**Issue by Grygon** [Azanor/thaumcraft-beta#1069]
Currently, to obtain essentia smelting 2, you need to obtain a gelum vis crystal. The only way to obtain gelum is through ice blocks or the frost walker enchantment--effectively locking that research and all derived research (most of alchemy, all of golemancy, probably a few other things) behind obtaining one of two enchantments--silk touch, or frost walker on a book.

I believe snow used to give gelum in previous versions, which would be an easy solution. I'm not sure what else would work well, but I don't think it's a good idea to have a huge section of midgame content locked behind being lucky enough to get a specific enchantment, since that's quite difficult without the proper setup.

![image](https://user-images.githubusercontent.com/647846/42005599-59b33070-7a43-11e8-8290-ee7ceb57f0da.png)

**Comment by Reassembly** [comment]
...I just checked - both snowballs and snow blocks contain Gelum [version b16]. Do they not in your game/version?

**Comment by Grygon** [comment]
Oh, interesting. I'm playing on the new DW20 pack (also b16), they must've removed it for some reason. Sorry!

**Comment by Serifina** [comment]
It's not a DW20 pack choice. There's an addon or something using the API that's disabled it somehow (I haven't tracked down which one yet.)

**Comment by Lohoydo** [comment]
Other items such as Coal are also missing aspects in DW20 2.0.  I've heard elsewhere that this is an issue caused by other mods fooling around with NBT

**Comment by wamc2017** [comment]
Hmm, maybe that's the same bug as https://github.com/SleepyTrousers/EnderIO/issues/4688

**Comment by princessbinas** [comment]
I have this issue too. Though, I did not realize it was an issue....

**Comment by scribbler957** [comment]
I just had this happen because of Vanilla Food Pantry. I'm going to go find a way to manually add 1 gelum to snowballs and see if it propagates properly.

**Comment by Haelnorr** [comment]
I am also having this issue. Sandstone is also missing aspects. A few others it seems too. Running Direwolf20 1.12.2

**Comment by biddabadladbrendan** [comment]
If anyone is still having this issue, Ice is a good source of Gelum. If you need to pick it up, you can chisel the block (left click with chisel) once and then break it. That will let you pick up the ice :)
