### ISSUE TITLE
Wrong image placement

### ISSUE THREAD

**Issue by groting** [Azanor/thaumcraft-beta#107]
In "Ores" image for crystals from addendum 3 was placed before addendum 2.

![2018-01-25_20 23 12](https://user-images.githubusercontent.com/5873866/35399610-af1b54d6-0205-11e8-804b-28e7aeab543c.png)
![2018-01-25_20 23 14](https://user-images.githubusercontent.com/5873866/35399615-b390ebb6-0205-11e8-89f3-29a86b8afc75.png)

**Comment by Azanor** [comment]
Formatting is very broken in the beta 2 release. It is fixed for beta 3.

**Comment by groting** [comment]
Beta 3 formating is awesome
