### ISSUE TITLE
Thaumcraft BETA16 Configs Cause Crashes

### ISSUE THREAD

**Issue by princessbinas** [Azanor/thaumcraft-beta#1070]
In BETA16, messing with any of the config options, such as the "Show Tabs" under the "Graphics" tab, will cause the game to crash upon the next time you load Minecraft unless you delete everything related to Thaumcraft in your config folder.

The nature of the crash is very weird, in of itself. It pins the blame on EnderIO/EnderCore and Optifine, making it were you need to remove EnderIO/EnderCore to load up the game. This made me think it was EnderIO/EnderCore for a while as removing Optifine did not fix it, same with updating Optifine. When I cleaned out my entire config folder, the game actually loaded up. When I started messing with Thaumcraft configurations again, the next time I loaded up Minecraft to crash upon loading. When I decided to mess with only Thaumcraft related configs, I crashed again when I loaded up Minecraft.

The mod pack I use is Dark MagicTech, which has Thaumcraft.

So basically, something goes horribly wrong in the config settings for Thaumcraft. I am not sure what, but I hope these crash reports help:

[crash-2018-06-27_14.26.25-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143469/crash-2018-06-27_14.26.25-client.txt)
[crash-2018-06-26_17.06.58-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143470/crash-2018-06-26_17.06.58-client.txt)
[crash-2018-06-26_17.03.04-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143471/crash-2018-06-26_17.03.04-client.txt)
[crash-2018-06-26_17.00.00-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143472/crash-2018-06-26_17.00.00-client.txt)
[crash-2018-06-26_16.55.55-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143473/crash-2018-06-26_16.55.55-client.txt)
[crash-2018-06-27_20.49.14-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2143474/crash-2018-06-27_20.49.14-client.txt)

**Comment by F9Alejandro** [comment]
Please use something like pastebin or gist for crash logs as it will be easier to read and don't have to download stuff (this is not gist this is github).

**Comment by princessbinas** [comment]
But then why would a Thaumcraft configuration be the trigger? Did code between the two overlap or something?

**Comment by F9Alejandro** [comment]
`at com.enderio.core.common.util.stackable.Things.cleanCachedValues(Things.java:226)
	at com.enderio.core.common.util.stackable.Things.add(Things.java:220)
	at com.enderio.core.common.util.stackable.Things.add(Things.java:150)
	at com.enderio.core.common.util.stackable.Things.add(Things.java:109)
	at com.enderio.core.common.util.stackable.Things.invalidate(Things.java:434)
	at net.minecraft.item.crafting.Ingredient.invalidateAll(Ingredient.java:105)`
This points to something the enderio is trying to clear and shouldn't be clearing and causes an `java.lang.IndexOutOfBoundsException: Index: 0, Size: -1`

**Comment by princessbinas** [comment]
It's posted on their end. Hopefully that both you, Azanor, and the EnderIO creator can fix this.

**Comment by tterrag1098** [comment]
We've been looking for the cause of this one for ages. What happens here is that there is multi-threaded access to crafting recipes. How else can you explain a negative sized list? Threaded access to recipes should not be done.

**Comment by princessbinas** [comment]
Well, EnderIO's developer is denying it by putting the "Other Software's Problem" and "Duplicate" labels on it without giving any reasons as to why nor a link to the non-existent duplicate. I checked and it doesn't exist.
https://github.com/SleepyTrousers/EnderIO/issues/4746

**Comment by tterrag1098** [comment]
It's been reported before and we came to the conclusion that it cannot be caused by us. The only way a negative size list is even possible is threaded access to recipes during startup. I don't know what Thaumcraft is doing to cause this specifically, that is a job for the developers of this mod.

**Comment by princessbinas** [comment]
I am just highly confused right now. It is a modification config that shows essentia without needing to hold shift while hovering in the items that triggered the issue to begin with. Only Thaumcraft config alterations are causing it, yet I am told it is EnderIO because that's what my configs says and the other player here. Like I said, this is just very confusing for me.

**Comment by F9Alejandro** [comment]
@princessbinas could i have the copy of your modified config? i would like to test it on a clean profile to see what it does.

**Comment by princessbinas** [comment]
Okay. Will do. And I will recreate the config files necessary regardless to help you out.

**Comment by F9Alejandro** [comment]
Version 1.0.1.5 has the latest versions of Ender Core and Ender IO. Also the issue was originally with the older version of Ender IO/Core. The Solution to fix that error is to update EnderIO and EnderCore. @princessbinas you have the final say on this issue being marked closed or not.

**Comment by princessbinas** [comment]
Okay. I will close it since latest EnderIO/EderCore fixed it.

**Comment by HenryLoenwind** [comment]
Forge's recipe code also is not thread-safe and is crashing from this at times...

```
java.lang.ArrayIndexOutOfBoundsException
    at it.unimi.dsi.fastutil.ints.IntArrays.grow(IntArrays.java:264)
    at it.unimi.dsi.fastutil.ints.IntArrayList.grow(IntArrayList.java:308)
    at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:322)
    at net.minecraftforge.oredict.OreIngredient.getValidItemStacksPacked(OreIngredient.java:83)
    at net.minecraft.client.util.RecipeItemHelper$RecipePicker.getUniqueAvailIngredientItems(RecipeItemHelper.java:212)
    at net.minecraft.client.util.RecipeItemHelper$RecipePicker.<init>(RecipeItemHelper.java:121)
    at net.minecraft.client.util.RecipeItemHelper.canCraft(RecipeItemHelper.java:79)
    at net.minecraft.client.util.RecipeItemHelper.canCraft(RecipeItemHelper.java:74)
    at net.minecraft.item.crafting.ShapelessRecipes.matches(ShapelessRecipes.java:88)
```
