### ISSUE TITLE
[b16/b17] Thaumometer appears to read aura from block at Z+1

### ISSUE THREAD

**Issue by Reassembly** [Azanor/thaumcraft-beta#1071]
Using F3+G to show chunk boundaries, the Arcane Workbench shows a change in available vis when moved from one chunk to another. On the other hand, the Thaumometer changes its reading when crossing the block boundary one block towards negative Z away from the chunk boundary - i.e. the Thaumometer reads the aura of the chunk belonging to the block at Z+1 from where the player is standing.

Measurements taken at points shifted along the X axis seem consistent between the Thaumometer and Arcane Workbench, and line up with the chunk borders.

**Comment by Reassembly** [comment]
Small update: Issue persists in b17.

**Comment by MCOfficer** [comment]
same issue in B20, but only along the X axis? not sure if read your description wrong, or if the issue has changed. see the images (coordinates are below the journey map)

![javaw_2018-08-08_14-46-43](https://user-images.githubusercontent.com/22377202/43837869-1bfdfbdc-9b1a-11e8-94e0-2ca0a1f71cf5.png)
![javaw_2018-08-08_14-46-50](https://user-images.githubusercontent.com/22377202/43837870-1c37eee6-9b1a-11e8-91db-b3eff77cd37a.png)
