### ISSUE TITLE
Foci Power [Suggestion]

### ISSUE THREAD

**Issue by Niconoko** [Azanor/thaumcraft-beta#1072]
Not quite a problem here, but I'm thinking I would like to see the Foci Manipulator can be able to upgrade more fire power into Foci (more damage) and that will cost more vis, flux or warp to happen to counterpart the power it got.

Fighting the vanilla mobs is okay with normal power in TC, but with stronger modded mobs, it's kinda saddening with the less power to deal with them.

That's what I'm thinking, and thanks for reading. :3

**Comment by mastoid** [comment]
Try this(using up 25 complexity of an advanced focus):
projectile(chase enemy, speed 4) scatter scatter scatter fire.
This means 8 projectiles of 4 damage (32 long-ranged damage in total for 1 cast).

Or bolt-scatter*3-flux(power 2) of 8* 5-damage mid-ranged bolt (40 armor-piercing damage per cast).
Some Others like multiple scatter modifier can largely amplify your damage. Already high enough for mid-game.

**Comment by Morinor** [comment]
Just experiment a bit more, there are very powerful combinations possible, even for fighting strong enemies.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#346
