### ISSUE TITLE
Focal Maipulator GUI is blank

### ISSUE THREAD

**Issue by 0cuIus** [Azanor/thaumcraft-beta#1078]
Whenever I right click the focal manipulator to open it's gui, a few symbols flash very briefly and disappear, leaving the gui blank. 
I'm using the DW20 pack ver. 2.0 with just torchmaster 1.6.1.53 added into it. I also tried removing torchmaster but that made no difference.
I use the twitch launcher to start the modpack but also tried using the FTB launcher which left me with the same result.

![screenshot_1](https://user-images.githubusercontent.com/16278744/42124629-b48dfffa-7c66-11e8-8cc9-10388c0d584f.png)

[FTB launcher log.txt](https://github.com/Azanor/thaumcraft-beta/files/2151645/FTB.launcher.log.txt)

**Comment by Reassembly** [comment]
Your screenshot shows that you have no blank focus in the Manipulator (bottom left slot). Did you try putting a focus in there?

**Comment by 0cuIus** [comment]
I actually missed that.
Thanks for pointing it out and sorry for posting.

**Comment by Reassembly** [comment]
Nah, the symbols appearing briefly without a focus is still a (minor) cosmetic bug. You still found _a_ bug, just not the one you thought you found. 😃
