### ISSUE TITLE
Thaumonomicon crashing Minecraft

### ISSUE THREAD

**Issue by jusjudge** [Azanor/thaumcraft-beta#1083]
I'm currently on 6.1.BETA16 and for some reason when I opened my book and tried clicking on the different tabs, my game just crashed. I relaunched it and now I can't even open the book itself without my client crashing. These are the two crashes I got.

When I tried clicking on a different tab in the thaumonomicon 
https://paste.dimdev.org/wihajagahu.mccrash

When I tried opening the book itself
https://paste.dimdev.org/sazilowine.mccrash

**Comment by wamc2017** [comment]
Hmm, I guess that's the same issue as [here](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63) and has nothing todo with thaumcraft....

Try downgrading ctm to 1.12.2-14.23.4.2717

**Comment by jusjudge** [comment]
@wamc2017 I will definitely try that right now and let you know what happens. Thank you!

**Comment by jusjudge** [comment]
@wamc2017 That did the trick! Thanks once again! 👍
