### ISSUE TITLE
Thaumcraft crashing at startup

### ISSUE THREAD

**Issue by Xx-plzhelpme-xX** [Azanor/thaumcraft-beta#1084]
I'm getting a persistent crash with this

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)

[crash-2018-07-01_14.32.58-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2153231/crash-2018-07-01_14.32.58-client.txt)

idk whats goin on

**Comment by wamc2017** [comment]
Hmm, you're using 6.1.BETA11 have you tried updating to 6.1.BETA16?

**Comment by Xx-plzhelpme-xX** [comment]
Idk if anything changed but it still crashes with 6.1.BETA16

[crash-2018-07-01_14.50.25-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2153242/crash-2018-07-01_14.50.25-client.txt)

**Comment by wamc2017** [comment]
Hmm, could you add a full modlist?

I see micdoodlecore in your log but no Galacticraft or Galacticraft-Planets, which should crash the game anyway....

**Comment by Xx-plzhelpme-xX** [comment]
alright but i got quite a few, and i took out galacticraft cause it was causing its own problems im also trying to deal with.
Heres Everything:

Antique Atlas
Baubles
BiblioCraft
BiomesOPlenty
Bookshelf
Chisel-MC
CodeChickenLib
DarkUtils
Dungeons2
DynamicLights
GalacticraftCore
GalacticraftPlanets
GottschCore
Gravestone
iChunUtil
JEI
MalasisCore
MalisisSwitches
MalisisDoors
MicDoodleCore
MobAmputation
MobDismemberment
NaturesCompass
NEI
PlayerAPI
RenderPlayerAPI
RoughMobs2
RunisDungeons
SereneSeasons
Thaumcraft
ToughAsNails
Tumbleweed
TwilightForest

**Comment by wamc2017** [comment]
> RunisDungeons

I think that should be Runic Dungeons and that mod is only available for Minecraft 1.7.10 (there's no 1.12.2 version) and it had Thaumcraft support, I guess that's why it's crashing, try to remove it...

**Comment by Xx-plzhelpme-xX** [comment]
yep that did it. thank you, you bare a kind soul
