### ISSUE TITLE
Is crafttweaker support possible?

### ISSUE THREAD

**Issue by q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH** [Azanor/thaumcraft-beta#1085]
I am in the process of developing a pack and it would be very useful to be able to add, change or remove infusion, crucible or arcane workbench recipes in the latest version, and by far I have only seen aspect support. I would appreciate if you could implement this feature.

**Comment by wamc2017** [comment]
I guess modtweaker already added Thaumcraft support for version 6: https://github.com/jaredlll08/ModTweaker/blob/1.12/test_scripts/thaumcraft.zs

**Comment by q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH** [comment]
Oh umm ok I will try that, thanks
