### ISSUE TITLE
TC Beta17 - NullPointerException at ThaumcraftCraftingManager, server and client

### ISSUE THREAD

**Issue by maxell45146** [Azanor/thaumcraft-beta#1087]
https://paste.ee/p/wK6wy
^-- Crash log from client.

On the client it reaches the post initialization then crashes. 
On the server it crashes with a error referencing the same thing, NullPointerException at ThaumcraftCraftingManager.

**Comment by wamc2017** [comment]
Try it without Thaumic Additions I guess it's not compatible with beta17.

**Comment by maxell45146** [comment]
Looks like that was it, thanks. :)
