### ISSUE TITLE
golem seal duplication in beta 16

### ISSUE THREAD

**Issue by jdratlif** [Azanor/thaumcraft-beta#1090]
I don't know how it happened, but when I loaded up my world, seals that I had removed and placed elsewhere had been recreated at their past locations. I took them out and I had extra seals that I didn't make.

Happened with a collect seal, 3 use seals, and a lumberjack seal. The collect and lumberjack seals were on the ground (grass blocks on the top), the use seals were placed on saplings that weren't there anymore because I moved my tree farm, so they were on empty air blocks.

It's only happened once so far.

**Comment by Azanor** [comment]
I have not been able to duplicate this. I suspect something happened while your world was being saved that caused to removal of the old seals not to be saved so when you reloaded the world they were still in place. 
Please let me know if this happens again, but I am going to close this for now.
