### ISSUE TITLE
Suggestion: Faction opposite of the Crimson Cult (Good Guys)

### ISSUE THREAD

**Issue by Lusaphor** [Azanor/thaumcraft-beta#1091]
Adding in a Faction with good intentions, ie fighting flux and warp effects, researching to benefit the world and battling Crimson Cult members. You could add a hard Thauminomicon choice to take one side or the other, Later if the eldritch dimensions return from TC4, we could have portals to respective fortress realms, maybe even a battlefield. This idea could be a dynamic to allow more "story " to the mod.

**Comment by TonyMestre** [comment]
Good idea

**Comment by aycfes** [comment]
in my opinion, that's a position better fitted for us players, especially on servers

**Comment by tyler489** [comment]
the Cyan Club hahaha I like this idea

**Comment by aycfes** [comment]
the cyan club is difenently material for a thaumic potatoes-esque addon \o/

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#345
