### ISSUE TITLE
Flux Jug (suggestion)

### ISSUE THREAD

**Issue by aycfes** [Azanor/thaumcraft-beta#1094]
for map making's sake, mainly, it would be very useful if there was a counterpart to the flux sponge, that fills a radius of 9 chunks to the brim with flux

currently to make a tainted biome or something akin to so, one has to either set up a crucible in a few different areas, fill them with whatever, and wait a while, or throw taint bottles everywhere for a similar to greater amout of time.

making such an item would make this way simpler and faster, i also don't think it would be hard to code it.

thank you for your time.

**Comment by Morinor** [comment]
Personally Id like to see a command to set the amount of flux and vis and the maximum amount for vis in a chunk. This would be really helpful for mapmaking, server administry and creative testing worlds.

**Comment by Azanor** [comment]
I might do something like this, but you can also just place a crucible and dump it full of stuff - that is what I usually do when testing :p

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#344
