### ISSUE TITLE
Decorative Effects [Suggestion]

### ISSUE THREAD

**Issue by lordrhubarbs** [Azanor/thaumcraft-beta#1096]
The effects for Static Field and Dimensional Tear are excellent. They can be placed in the world but decay shortly there after.

It would be nice to have versions of these effects that can be placed just to create ambiance in arcane workshops, eldritch constructions and plain old wizard towers.

**Comment by Reassembly** [comment]
Potentially, something like this could have practical uses, too. Consider a "decorative" effect/item that you could see through walls when wearing Goggles, the same way you can see rifts through walls. This could be placed as a sort of "underground beacon" to help with pathfinding/navigation in underground caves, or to keep yourself aligned and oriented correctly when digging out a series of underground rooms/tunnels.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#343
