### ISSUE TITLE
Right clicking the crucible with the thaumometer to try and scan it drops the entire thaumometer into the crucible

### ISSUE THREAD

**Issue by Sixmorphugus** [Azanor/thaumcraft-beta#1098]
This has been a major issue for me. It's really annoying and has caused my world to fill with flux multiple times, especially since the Thaumometer has such a high amount of Vis energy for multiple elements.

The only way to drop the thaumometer into the crucible should be to hit Q and throw it in.

**Comment by wamc2017** [comment]
Duplicate of #557
