### ISSUE TITLE
OK, OK, so this is just a little thing ...

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#110]
...Remember the discussion in an issue a while back about what is and isn't proper Latin?  Well, I'm finding that I can no longer think of ... well, Sal Mundi as Salis Mundus.  Now that I know it's "correct", my mind wants to correct it to Sal Mundi all the time.

I don't suppose this is something that could be a user-set preference, is it?  Purist vs. traditionalist?  :)

(Just a whim.  No action required.  Unless you want to ...)

**Comment by Azanor** [comment]
Just alter your .lang file if it bothers you that much :p
