### ISSUE TITLE
Thaumcraft exception

### ISSUE THREAD

**Issue by IBriXXI** [Azanor/thaumcraft-beta#1101]
i am trying to setup my Server, (it works on client side btw) and when I start it, it shows me this exception...

 Crash Log:
https://pastebin.com/xGPidCTp

**Comment by wamc2017** [comment]
You're running beta 13, have you tried beta 17?

**Comment by IBriXXI** [comment]
yes, (probably) same problem

https://pastebin.com/MFX9iW7k

**Comment by wamc2017** [comment]
Hmm, can't reproduce it with only thaumcraft installed on my testserver...

Can you provide a full logfile? 
Is this a fresh world you're starting on the server? (If not could you try a new one?)

Also your forge version (14.23.3.2675) is kinda outdated, you could try updating it.

**Comment by IBriXXI** [comment]
The World is new, i cant update forge because a mod (I think Twilight Forest) needs this version, and sure, let me send the logfile in a moment

**Comment by IBriXXI** [comment]
https://pastebin.com/Y2WTNEtG

**Comment by IBriXXI** [comment]
ah okay, no sponge, but I added some Mods recently (one of them must cause that because it worked earlier)

-JustEnoughIDs 1.0.0-6
-openmodularpassivedefense 3.0.0-36
-openmodularlib 3.0.0-148
-openmodularturrets 3.0.1-257
-pneumaticcraft-repressurized 0.6.8-219
-immersivetech 1.3.10
-Ceramics 1.3.4
-SimplyJetpacks2 2.2.7.45
-Mekanism 9.4.13.349 (updated from 346)
-BetterFps
-MekanismGenerators 9.4.13.349
-MekanismTools 9.4.13.349

**Comment by wamc2017** [comment]
Hmm, you could try removing them one by one and see if that solves the problem.
