### ISSUE TITLE
[Suggestion] Command for giving Theories

### ISSUE THREAD

**Issue by Lohoydo** [Azanor/thaumcraft-beta#1104]
I would like to ask for a command for giving (or a config for removing the need for) the theories required for research.  Once you've gone through everything a couple times, the theory part becomes a large hassle as well as a time/resource sink.  I know its possible to flat out give the researches themselves, but just removing the theories gives a nice balance between progression through the mod and time/resources for the more experienced player

**Comment by aycfes** [comment]
just get a ton of curiosities in creative and use them 
(curiosities are items that give you theories and the such)

**Comment by Lohoydo** [comment]
Well.  That works then, thanks.  Though... is there any information the the thaumonomicon about the curiosities?  I didn't see any under ores, which is where I would think they would be since they drop from amber

**Comment by Morinor** [comment]
you get aracne curios from pechs, afaik. the other types arent obtainable afaik
