### ISSUE TITLE
research.c_voidstuff.text has no label. What does it mean?

### ISSUE THREAD

**Issue by WhisperFire26** [Azanor/thaumcraft-beta#1106]
To study "Alchemical Metallurgy" it says that I need to scan something called "research.c_voidstuff.text" I tried to cause some flux and scan the small purple smoke but it didn't work. How do you get past that point in research?

**Comment by wamc2017** [comment]
Dupe of #55 
Third part of Alchemical Metallurgy is still WIP!

**Comment by WhisperFire26** [comment]
Is there a solution?

**Comment by wamc2017** [comment]
The Eldritch/Voidmetal stuff isn't finished yet, so the only solution is waiting, until Azanor is ready to implement it... :p

**Comment by F9Alejandro** [comment]
Chances are that if the research isn't able to be completed there is a reason behind it, and other things behind that research might not work or may cause instability.
