### ISSUE TITLE
[B17] Cloudstepper ring seems to not reduce fall damage at all.

### ISSUE THREAD

**Issue by AbortRetryFail** [Azanor/thaumcraft-beta#1107]
Running on SMP, upgraded from Beta 16. Cloudstepper ring doesn't seem to stop even the tiniest fall damage despite it's description in the Thaumnomicon.

Repro: 
- Make a platform 3.5 blocks high.
- Walk off it wearing nothing, observe 1/2 heart damage.
- Wear cloudstepper ring.
- Walk off it wearing the ring, observe 1/2 heart damage.

**Comment by Frosthaven** [comment]
Reported this back in B16: https://github.com/Azanor/thaumcraft-beta/issues/968

It was marked as done, but still occurs. Applies to all featherfall effects game-wide.

**Comment by aycfes** [comment]
did you recover from said damage instantly?

**Comment by AbortRetryFail** [comment]
Not instantly, the half heart regenerated after a couple seconds and it dings runic shielding as if I actually took damage.

**Comment by Morinor** [comment]
seems like its patched in b17

**Comment by Frosthaven** [comment]
Did some more testing. Starting fresh, I installed only Thaumcraft + Baubles (latest of each up to this date) on both the client and a quick server spin-up.

SinglePlayer:
- Falling makes the damage sound but health remains full (which indicates an instant refill of hp)

MultiPlayer Forge Server:
- Falling in the same map location from single-player while on the standalone server kills me

**Forge Version: 14.23.4.2705**
**Minecraft Version: 1.12.2**
**Thaumcraft Version: Thaumcraft-1.12.2-6.1.BETA17**
**Baubles Version: 1.12-1.5.2**

**Comment by Frosthaven** [comment]
Ah, when I say die I mean that it would potentially kill me whereas in single player no damage was taken at all from the same height. I can spin up a fresh client and server again to do some more testing and record some footage, if it would help you.

**Comment by Frosthaven** [comment]
Alright retested and this time it wasn't causing me to take any damage. I'll report back if anything changes I guess. It still doesn't work on our primary multiplayer server but that might be some weird mod interplay.

**Comment by Azanor** [comment]
Actualy in b13 it was indeed removing all fall damage if you fell far enough, but that was a bug :)
Bad math was bad.
