### ISSUE TITLE
Suggestion: A posibility to obtain "Strange Dreams" again

### ISSUE THREAD

**Issue by GiorgioMC** [Azanor/thaumcraft-beta#1109]
if someone lost their first book and cant step up to progress?. It should have the posibility to obtain again the book while you never crafted the thaumonomicon and, and a map with the crafting recipe for noobs. The item "Strange Dreams" dont exist in the toolbar, it will be better if exist.

I suggest like: if you dont crafted the thaumonomicon, everytime you sleep, you will get the book but whit a different words, like: "you are obsessed to do it", something like that (a variation of "Strange Dreams") Off course, the message will not appear if you have the book in your inventory.

**Comment by apmax** [comment]
The written book isn't necessary to progress in the mod.  All you need to do is receive it once, you can delete the item immediately if you so desire. 
Follow up by crafting salis mundus and creating your thaumonomicon.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#342
