### ISSUE TITLE
Thaumic Dioptra projection turns invisible when seen in front of water

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#111]
![2018-01-25_16 57 46](https://user-images.githubusercontent.com/9127495/35416373-ecf36bf4-01f6-11e8-885e-ca0c34463a45.png)

**Comment by Azanor** [comment]
That is one of the wonderful problems with render ordering in minecraft. Not much I can do about it without some seriously hacky code that I would rather avoid.
