### ISSUE TITLE
Crafting tasks accept vanilla crafting methods

### ISSUE THREAD

**Issue by purpleposeidon** [Azanor/thaumcraft-beta#1112]
Eg, hedge alchemy requires you to craft slimeballs. Crafting slimeballs by uncrafting a slime block counts as a craft.

**Comment by Azanor** [comment]
Hmmmm. I will allow it...  ;)

And not because I'm too lazy to figure out a way differentiate where the craft comes from. I'm pretty sure there isn't one.
