### ISSUE TITLE
Can Barely do a moderate infusion

### ISSUE THREAD

**Issue by IMewco** [Azanor/thaumcraft-beta#1115]
I don’t know why I can’t even do moderate infusions peacefully! I have 12 candles and 24 skulls around my altar. I have 5 stabilizers directly pointing at the matrix that are receiving from a source producing 16k RF per tick and everything is symmetrical, even the stabilizers. Even with all that, my altar goes crazy at a moderate level infusion. It starts out as Very Stable and goes to dangerously unstable within a few seconds. I have 4 speed boosters if that matters. I’m not sure how I’m supposed to make the item that closes rifts if I can't even handle a moderate infusion!

**Comment by aycfes** [comment]
so, first off, now you are limited to only 10 occult items, such as candles and skulls.
secondly, did you place the items in radial symetry or bilateral symetry (the correct is the prior).
did you place the items in the pedestals in the same arrengement as in the thaumonomicon and, once again, with radial symmetry?
if possible can you provide me/us with pictures of your setup and it doing an infusion?

infusion is quite broken currently, but with such a ridiculous (positively so) setup as yours, i don't think it would be so unstable.

also, sorry if i sound rude, i tend to, but that is not my intention.

**Comment by IMewco** [comment]
![2018-07-06_21 46 36](https://user-images.githubusercontent.com/29665124/42406066-45b4eaee-8166-11e8-94c6-2351ca6e7ec3.png)
![2018-07-06_21 46 49](https://user-images.githubusercontent.com/29665124/42406067-45d145c2-8166-11e8-82f6-0fb9427a6bcc.png)
![2018-07-06_21 46 56](https://user-images.githubusercontent.com/29665124/42406068-4602bf30-8166-11e8-9442-2a30a4f7484
ignore the area beyong the arcane stone floor, its either decorational or essentia

**Comment by Reassembly** [comment]
Oh wow...you're using a powerful RF source from an external mod instead of the wimpy Vis Generators, and a Moderate infusion is _still_ dangerously unstable?

That's extremely troubling. Your setup _looks_ like it should not just be fine, but over-the-top excessively fine.

**Comment by IMewco** [comment]
I managed to pull off a brain in a jar infusion but it was extremely irritating and it was always at dangerous instability. I tried headband of knowledge and it almost destroyed my entire setup

**Comment by IMewco** [comment]
Wow, that was a lot to process. But now I understand how these stabilizers work but I have 6 stabilizers so I should have 0.73. According to your calculations moderate takes 0.8 to 1 so removing speed would probably bring me up to that and adding cost stones while would increase my boredom level from 0.5 to 1 would allow time to do all moderate infusions. I still find it a little insane that 5 stabilizers with 10 vis generators each are required to do moderate infusions in a Thaumcraft only world. Seems a little overkill

**Comment by apmax** [comment]
The numbers are obviously still being balanced, but I find it incredibly interesting.  Actually needing to swap out the cost/speed stones based on the recipe you're making is really cool, and the careful stability balance feels like it could be super fun if it were a tiny bit more forgiving.

**Comment by IMewco** [comment]
I managed to do a moderate infusion that left the altar switching between stable in very stable mid infusion by having max candles 6 max stabilizers and 4 cost stones. But I still doubt I’ll be able to do a very high infusion

**Comment by belathus** [comment]
It looks like you can have more than 6 stabilizers. From my experience, stabilizers do not block each other and can stabilize a matrix through solid blocks. In other words, you can have up to around 22 stabilizers on an infusion matrix.

**Comment by Reassembly** [comment]
@belathus  I've just tested that - you can fit 23 within range of the Matrix. (Three below, four in each other direction.) It seems to work, although some of the stabilizers seemed to cut out midway through a Moderate infusion - that many Vis Generators in a small area might be putting a strain on the aura. I think I might get even better results after building a few dozen more Vis Batteries to keep the Generators fed.

@apmax @IMewco  Agreed - while it's been _interesting_ working out the details of how to perform infusions under such unforgiving conditions, the current balance seems to be tilted towards _absurdly_ aggressive min-maxing.

**Comment by corhydrae** [comment]
@Reassembly I'm afraid just a few dozens of vis batteries will not be enough. In my tests with a series of runic shield infusions, each infusion used around 300k RF for +1 (moderate instability), 650k RF for +2 (moderate) and 1.1M RF for +3 (high). Another test with grinning devil infusion (very high) used around 1.8M RF. These values correspond to around 30 vis batteries for runic shield +1, around 65 for +2, around 110 for runic shield +3, and around 180 for grinning devil.  (As a side note, 10 candles + 13 fully powered stabilizers were enough for the grinning devil infusion.) The balance does indeed seem to be off.

**Comment by IMewco** [comment]
Do the stabilizers have to be directly facing the matrix?

**Comment by belathus** [comment]
They do.

**Comment by IMewco** [comment]
How would one set up 20 stabilizers? There would need to be a block or wire connecting them to a power source between each stabilizer

**Comment by apmax** [comment]
If they take up 2 blocks each in the axis pointing towards the matrix, you could fit about 4 in each direction within an 8 block range, with 5 directions possible, for roughly 20 of them total.
Needing 20 stabilizers seems wholly unintended, though it's very possible there will end up being more ways to improve the function of your infusion altar beyond the stabilizers, as more development occurs.

**Comment by IMewco** [comment]
I managed to fit 16 and I’ll try to make a collapser hopefully I don’t run into any errors

**Comment by belathus** [comment]
Sounds like it worked. Awesome.

**Comment by yunruiwatts** [comment]
Related to the issue I created earlier - https://github.com/Azanor/thaumcraft-beta/issues/1093

**Comment by Reassembly** [comment]
@yunruiwatts  Thanks for linking that - I was just thinking of looking that up myself. If Azanor is making Stabilizers able to accept power on five sides, that _should_ increase the amount of stability they're able to output (without RF mod wires) - requiring fewer Stabilizers using more Generators each.

@corhydrae _**180?!?**_  ...I'm going to need more quartz.

**Comment by corhydrae** [comment]
@Reassembly I am fairly certain that the power of just 23 generators is not even near to the power required for very high instability infusions. Note that my grinning devil infusion test was actually finished in roughly a minute I think, because my setup was using 1300 RF/t (13 stabilizers * 100 RF/t/stabilizer), which corresponds to the power of 130 vis generators.

**Comment by IMewco** [comment]
I think rather then increasing the power of a single stabilizer a good solution would be to provide better generators (20RF/t, 30RF/t, etc) and a way to transfer energy from afar (some sort of wire maybe) so that players will be able to max stabilizer power. Another enhancement I can think of is that stabilizers need not be facing the matrix directly instead anywhere within a 4 block radius or 8 block diamanter of the matrix. And maybe add a stabilizer limit as well so it doesn’t go out of hand. Upgraded stabilizers could also be another solution

**Comment by Azanor** [comment]
Hmm, looks like the numbers need some tweaking.

**Comment by Azanor** [comment]
Also I should note - having MORE than 10 candles/skulls/etc. around the altar will actually worsen the stability.

In b18 I will up the stability they provide to .02 and up the max amount to 16 (for a total of .32 stability). I will also make it a bit clearer in the research entry that 16 is the limit.

**Comment by Reassembly** [comment]
@Azanor  Did that change _very_ recently? There doesn't _seem_ to be anything in the code (b17) that would reduce stability for more than 10 candles. Also, after running a few tests (identical except for number of candles, restoring from backup between tests) there doesn't seem to be an observable difference between 10, 12, and _68_ (symmetrical) candles - but there was a _very_ noticeable loss of stability between 10 and 0 candles.

**Comment by Azanor** [comment]
Nope, you are right. I checked the code again and more than the 10 candles won't do anything.
