### ISSUE TITLE
Using foci while riding

### ISSUE THREAD

**Issue by Minamikaze392** [Azanor/thaumcraft-beta#1117]
When riding a horse (or other animals), Spell foci often hit the mount instead of the entity targeted by the player.

**Comment by F9Alejandro** [comment]
Think that has more to do with the way how minecraft is in general with mounts. Try using a bow and arrow in vanilla from a mount and see what happens.

**Comment by Minamikaze392** [comment]
No arrows won't hurt the mount while riding it.
