### ISSUE TITLE
Crash when clicking on Golem Press in Clockwork Minds (TC-B17)

### ISSUE THREAD

**Issue by mikeThePlayer** [Azanor/thaumcraft-beta#1119]
When trying to open the tab for visualization of the multiblock structure for Golem Press, the game crashes. Tried 3 times in a row. There is no problem with the visualization of the Infernal furnace tho.

Image of what I mean: https://imgur.com/a/AUbc3Lo

Do not know if it helps, attaching crash report.
[crash-2018-07-07_20.44.18-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2173023/crash-2018-07-07_20.44.18-client.txt)

**Comment by wamc2017** [comment]
Looks like a Optifine crash to me, have you tried without it?

**Comment by mikeThePlayer** [comment]
Tried it now and yeah... Optifine was the problem. Thanks
