### ISSUE TITLE
Beta 2; Issue: Crucible suspends with no heat source

### ISSUE THREAD

**Issue by LordPinkerton** [Azanor/thaumcraft-beta#112]
Don't know if it's intended, but the issue is that the crucible is suspended completely with no heat source. Because of this, any essentia that is in the crucible that would normally dissolve and produce flux just sits indefinitely until a heat source is reapplied.

**Comment by Azanor** [comment]
Wow, this bug must have been around forever. Maybe even since TC 2. Good catch.
