### ISSUE TITLE
game crashing when i open the recipe for  essentia filter

### ISSUE THREAD

**Issue by diablo184** [Azanor/thaumcraft-beta#1125]
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2173914/latest.log)

i have spent a few hours thread jumping on here and have been unable to find any resolve for this i am currently using beta 17, also crashing when i click on the arcane infusion tab
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2173936/latest.log)

**Comment by Azanor** [comment]
Unfortunately the only error in those logs seem to be related to journeymap. I am not sure why it would happen when you open the filter recipe however.

**Comment by diablo184** [comment]
it had turned out to be a mod conflict with the more commands mod http://www.9minecraft.net/more-commands-mod/ after deleting that mod all issues i had been having thaumcraft were resolved aside from a very large lag spike when looking at how to make the infernal furnace.
