### ISSUE TITLE
Mod interaction with Twilight Forest, New Foci Effects [Suggestion]

### ISSUE THREAD

**Issue by maxell45146** [Azanor/thaumcraft-beta#1126]
Was going over the TF wiki and had a idea when I read about the Lich Scepters. 
Encase someone reading this doesn't know there is three (Summon Zombie, Life Drain and Twilight).
The idea was wouldn't it be neat that once you've managed to get your hands on one of them that scanning it would unlock a foci research coinciding with the corresponding scepter, basically giving you the effect for use when making new foci. 
So say for example instead of using spell bats you managed to complete the zombie scepter research and are now able to craft a foci that has a effect of creating zombies, maybe even going a step further and allowing the summoned zombies to apply effects like the spell bats. 
Life draining would be a nice way to heal yourself while damaging mobs or fits thematically with spellbats turning them into life draining blood suckers. 

PS, 
Thank you for creating such a great mod, definitely one of the mod pillars and always a game changer. :)

**Comment by apmax** [comment]
The specific idea here seems more in the realm of a twilight forest integration addon, but a generally wider variety of focus effects or media would be interesting.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#340
