### ISSUE TITLE
[Beta 17] Aspect assignment from infusion recipes doesn't work

### ISSUE THREAD

**Issue by the-realest-stu** [Azanor/thaumcraft-beta#1128]
A number of items that used to have aspects before Beta 17 don't have aspects anymore because item aspects are no longer being assigned automatically based on infusion recipes.

**Comment by Reassembly** [comment]
Which items have you observed as having lost aspects? This _might_ be related to the fix that was added for #1013.

**Comment by Mii1128** [comment]
Thaumium fortress armor

**Comment by Azanor** [comment]
Fortress armor does have the proper aspects for me. Any other items that you guys can report?

**Comment by the-realest-stu** [comment]
![](https://i.imgur.com/5FEeNsG.png)
Thaumium Fortress Armor only has the aspects it gets from its armor value, not the ones it should get from its recipe.

### Full list of affected items
- Lamp of Growth
- Lamp of Fertility
- Brain in a Jar
- Magic Mirror
- Essentia Mirror
- Biothaumic Mind
- Arcane Bore
- Magic Hand Mirror
- Axe of the Stream
- Sword of the Zephyr
- Shovel of the Earthmover
- Pickaxe of the Core
- Hoe of Growth
- Boots of the Traveller
- Thaumium Fortress Helm
- Thaumium Fortress Cuirass
- Thaumium Fortress Thigh Guards
- Amulet of Vis
- Verdant Heart CHarm (all 3 variants)
- Headband of Curiosity
- Cloudstepper Ring
- Charm of Undying
- Blank Advanced Focus
- Blank Greater Focus
- Control Seal: Harvest
- Control Seal: Butcher
- Control Seal: Block Breaker
- Causality Collapser

I didn't include items that don't have any recipe on the list since those wouldn't be expected to have aspects anyway. The only items that do have recipes that are lacking the aspects that should be assigned from their ingredients are all of the items that are made via infusion crafting.

The only mods installed are Thaumcraft 6.1 Beta 17, Baubles 1.5.2, and Forge 14.23.4.2726.
I also tested this with Forge versions 14.23.3.2655 and 14.23.4.2738 and the problem persisted on both.

**Comment by Azanor** [comment]
In b18 those items all have aspects so I suspect this is a bug I may have already fixed. B18 will be coming out soon.
