### ISSUE TITLE
Infusion Tab Crashing BETA17

### ISSUE THREAD

**Issue by Emethian** [Azanor/thaumcraft-beta#1129]
Hello, as you can tell from the title when ever I try to click on the infusion tab my entire game crashes. Has anyone encountered the same problem and managed to fix it? or can you tell me what could possibly be going wrong with my game? any support would be greatly apreciated.

[crash-2018-07-09_11.25.08-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2177563/crash-2018-07-09_11.25.08-client.txt)

**Comment by wamc2017** [comment]
Update CTM to 0.3.1.16, it's a known compatibility problem between CTM and newer forge versions and has nothing todo with Thaumcraft....

https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63

**Comment by Emethian** [comment]
Thanks, that fixed it so I'm good now.

**Comment by FanghanHu** [comment]
please close the issue if it is fixed.
