### ISSUE TITLE
Thaumcraft 6; Foci/Focus Menu

### ISSUE THREAD

**Issue by AnyaDinky** [Azanor/thaumcraft-beta#1131]
One of the focus in my bag/inventory arent appearing (EX: I have 8 foci in my inventory but only 7 appear when trying to choose a foci)

![a](https://user-images.githubusercontent.com/41029817/42483747-e85ecd3c-83b4-11e8-909e-2cdc463e578a.PNG)

![capture](https://user-images.githubusercontent.com/41029817/42483748-e875598a-83b4-11e8-8243-39d9715d7fa2.PNG)

UPDATE= It seems that the only foci affected is the fire focus. Can anyone give me any help to fix this?

**Comment by mrsteal123** [comment]
one is in your gauntlet

**Comment by Alcamore** [comment]
@mrsteal123 It shows in the image that the gauntlet has no focus in it.

**Comment by OmegaDragon32** [comment]
Maybe, but it seems that there are two foci that may have the same abilities. It's possible that one isn't being shown cause one's ability might be too similar to the other.

**Comment by Azanor** [comment]
Yup, two identical foci will only display in the foci ring once. Was that the issue?

**Comment by AnyaDinky** [comment]
no i have 8 different foci and only 7 show up

EX/ Ice, fire, healing, air, earth.
but only ice, healing, air and earth show up.
