### ISSUE TITLE
Duplicate Language key with 7 mods

### ISSUE THREAD

**Issue by TartaricAcid** [Azanor/thaumcraft-beta#1132]
### Here is the list:
`tile.mirror.name`
- cfm `Mirror`
- thaumcraft `Magic Mirror`

`recipe.type.workbench`
- hammercore `Crafting`
- thaumcraft `Workbench`

`recipe.type.construct`
- hammercore `Multiblock Structure`
- thaumcraft `Mystical Construct`

`recipe.clickthrough`
- hammercore `Click to View Recipe`
- thaumcraft `Click for recipe`

`item.amber.name`
- jurassicraft `{stored} in Amber`
- thaumcraft `Amber`

`tile.barrier.name`
- minecraft `Barrier`
- thaumcraft `Warding Aura`

`tile.stone_porous.name`
- mist `Porous Foggy Stone`
- thaumcraft `Porous Stone`

`item.void_seed.name`
- primal core `Equisetum Ineris Spore`
- thaumcraft `Void Seed`

`tile.flesh_block.name`
- thaumcraft `Block of Flesh`
- tiny progress `Compressed Flesh Block`

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#338
