### ISSUE TITLE
Flux/Taint Abuse

### ISSUE THREAD

**Issue by triffman33** [Azanor/thaumcraft-beta#1133]
### The Issue

Hey, I've been made aware that there's an issue with people abusing the flux/taint mechanic where they'd log into a server and then spam flux in the area until multiple (over 20) huge rifts spawn which would then make a lot of giant taint seeds. This is an issue because players can single handedly taint a large portion of a world if they want to, and currently there's no way to stop it other than checking everywhere for said giant taint seeds or keeping an eye out for a large amount of rifts. I'm an Admin on the KC Network and found that doing /cofh killall rift or taint and then manually destroying all the blocks is a temporary fix for this issue when one of these is found
____
#### Potential Solution 1
 One way would to implement a command which clears all taint/giant taint seeds/rifts from an area (so it sort of reverts it)
____
#### Potential Solution 2
Another would be to detect whenever players are making a large amount of flux and pop up a warning, this way if they are doing it unintentionally then they will stop, and at this point (before there is too much) also create some sort of save point for the flux/vis in the area. If that is possible then maybe there could also be a command thats implemented where an admin of the server could run the command to revert the area from any flux/taint issues.
____

Again, not sure if any of this is possible but I believe it needs to be addressed either way.

**Comment by Mii1128** [comment]
You can use the flux sponge for flux and rifts (shift right click) and a vanilla command for all the taint stuff.

**Comment by triffman33** [comment]
Hey Mii1128, can you please elaborate on the vanilla commands you’re talking about? Thank you.

**Comment by Mii1128** [comment]
These two commands will kill all taint seeds (second one for giant taint seeds in a radius of 100 blocks)

/kill @e[type=thaumcraft:taintseed,r=100]
/kill @e[type=thaumcraft:taintseedprime,r=100]

taint should go away when the seeds are killed

**Comment by Mii1128** [comment]
/kill @e[type=!Player,r=100]

would be more drastic, killing everything but Players

**Comment by triffman33** [comment]
Yeah we have commands for that, /cofh killall taint and /cofh killall rift will deal with the giant taint seeds and the rifts, but is there any way to deal with the taint spreading in the ground? or would the flux sponge also suck that up?

**Comment by triffman33** [comment]
Oh just assumed that it would constantly spread, since thats how it was in previous versions^^ thank you for all the help!

**Comment by Lohoydo** [comment]
also you can use the /fill command to replace tainted soil/rock with regular dirt/stone /fill <x1> <y1> <z1> <x2> <y2> <z2> <taintblock> 0 replace <regularblock>
