### ISSUE TITLE
[Suggestion] Arcane Workbench NEEDS an overhaul!

### ISSUE THREAD

**Issue by Mr3DAlien** [Azanor/thaumcraft-beta#1134]
So let me explain. The Arcane Workbench is really boring now. The Amazing Thing about the Arcane Workbench was that you had to upgrade the Workbench with your wand and also the System that you could automate the Table and Craft whenever you want. For Example: In Thaumcraft 3 you simply put your wand in the Table and could craft if your wand was the right Tier because the Wand would charge up every Time. In Thaumcraft 4 You could make a wand only for crafting and link your node on the Table to charge up the wand automatically and Craft whenever you want. So my Idea is to implement Wands (Not for spells like in TC4/5) only for Crafting like in TC 3. So the Wands would act like a Vis Charge Relay now. It would increase your Vis Storage in your Workbench. So a better Wand is better Crafting. Now the Crystals should only allow to stack to 1 Crystal. This should because the Vis Charge Relay should now be there to take out the 6 Primal Aspects from Jars with the Essentia in them. So with this System, you would be able to simply use Crystals. But if you want at some Point of the Game to Craft whenever you want without the need of refilling Crystals all the Time, you Simply But a Vis Charge Relay on top and it would take the Essentia out of nearby Jars. So with This System, we would have back the Arcane Workbench upgrade system AND we would have the choice again to automate the Workbench again without doing or refilling anything, just craft whenever you want. I really hope this makes it into the Game because the Arcane Workbench was every time my favourite Workbench because it was so cool, but now it is just boring as hell. So please Azanor think about that because I love Thaumcraft and played all Versions (even ArcanaCraft). And sorry for the bad English, I was typing this fast :P

**Comment by LlamaTea** [comment]
There are vis batteries in the newer versions and there is also an upgrade for the table that allows it to pull vis from multiple chunks. Which is essentially the same thing that you want, just not in wand form.

**Comment by Mr3DAlien** [comment]
I know how the Arcane Workbench Works, that has nothing to do what my Idea is. Nothing against you, but can't you guys not just read the Text right and then give a Feedback about this ?

**Comment by Chicken9000** [comment]
I feel the opposite, it would defeat the purpose of the aura being stronger and weaker in areas. 

Your idea will disregard the need to watch the aura and then your made a base thing of Thuamcraft 6 pointless.

**Comment by Mr3DAlien** [comment]
Who said this, this is complete the opposite of what I mean. The Wand should simply do what the Charging Thing now does and the Charging thing should be there to pull out the Essentia from Jars nearby. So you would use up the Vis in the Aura that's the point. But not the Charging Thing on top would increase the Chunks around the Table.. The wand would and a better wand would give you more Chunks around the Table.

**Comment by Chicken9000** [comment]
I rather see upgrades in the form of Eldritch then bringing back wands, myself.

**Comment by Mr3DAlien** [comment]
Also doesn't sound that bad I just want to be able to Automate the Table so you can Craft whenever you want without having the need to replace Crystal I know it is easy. But I like to know that I can make things work automatically. But what do you have specifically against the Wands? I mean Yes it is a new Thaumcraft but I personally Think that Thaumcraft was THAT mod with the cool Wands and now that they're gone, it feels like we lost the coolest Mod with the Wands. I liked the Idea of having a Wand in a specific Slot and let him do Things. So my Idea was just to bring them back in a Thaumcraft 3 way with the only difference that a Wand wouldn't storage the Vis in it rather than he would just Increase the Chunks the Table can take.

**Comment by Chicken9000** [comment]
A Few Reasons:

1. Wands don't fit in with the story and feel of TC 6 to me. TC 6 feels more mechno magic and wands dont feel like they will fit in the theme.

2. Would confuse old players in how start TC 6 and progress.

3. To me TC 6 new system of stuff is refreshing and wands feel like we will be taking steps backwards.

**Comment by Mr3DAlien** [comment]
To be real TC 6 kinda feels a step backwards to me, I mean it feels more like a mix of TC 4 and TC3 with less cool stuff. I loved the Nodes and I loved the System you had to make laser beams and so on to Automate Things. Don't get me wrong I also love TC 6, but I think it shouldn't be a Problem to add Wands again. I mean Azanor even wanted to add Wands to TC 6 just the Bug with your hand that goes up and down stopped him implementing them because the would look weird with that. This bug is really annoying I made two maps for MC Realms and had to fight with this "Bug" too. I mean be real what looks cooler

This one (TC 4)
![2018-07-17_17 03 51](https://user-images.githubusercontent.com/28678215/42833643-f0257bf6-89f4-11e8-8f65-e92278dcda3f.png)

Or this one (TC 6)
![2018-07-17_19 10 33](https://user-images.githubusercontent.com/28678215/42833689-1e3546b6-89f5-11e8-8d16-df0580d6e8dd.png)

If you say the second one... I wont believe you :D

**Comment by Mr3DAlien** [comment]
Maybe it had something to do with a mod... I mean didn't you had a Chunk Loader. I transported Vis about big distances and it was never a problem nit in SinglePlayer and also not in Multiplayer

**Comment by Chicken9000** [comment]
Nope got the issue when only had TC 4 and some quality of life mods.(NEI, map and the such.)

**Comment by Mr3DAlien** [comment]
Ok I never had this Problem, but as I said wands wouldn't be the problem I think. ^^

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#337
