### ISSUE TITLE
[Beta 17] Arcane Ear Doesn't Support New Vanilla MC Instrument Types

### ISSUE THREAD

**Issue by TechnoMysterio** [Azanor/thaumcraft-beta#1135]
The arcane ear doesn't support the new note block instruments added around 1.12. This means that it doesn't work with the note block playing the bell from the Gold Block, the flute from Clay, the chimes from Packed Ice, the guitar from Wool and the xylophone from the Bone Block.

Thaumcraft: Beta 17
MC: 1.12.2
Forge: 14.23.4.2732

**Comment by Azanor** [comment]
o.O 
I did not even know new instruments were added.
