### ISSUE TITLE
Strange golem behavior Beta17

### ISSUE THREAD

**Issue by OmegaDragon32** [Azanor/thaumcraft-beta#1137]
@Azanor I'm sure that the golems kinks aren't entirely worked out, but I made a Thaumium Golem with these traits: Climber, Heavy Frame, Blast-proof, Smart (He has an Armored Smart Head), Deft, and Fireproof. He also has extra armor. I put him near a harvest control seal targeting Nether Wart, he broke the nether wart just fine, but he refused to plant it, and just kept spinning around in circles until a new piece of Nether Wart grew, and it would repeat it. He also went up the blocks normally instead of climbing up the ledge when I was testing if it was a bug with the nether wart. Also if I commanded him to follow me, after reaching me, he would continue walking around in a tight circle. One more thing: If I were to place him in certain areas, He'd appear like a normal golem. But if I were to put him inside the area that the seal marked, his appearance would change to what I think he was supposed to look like. Thank you for your time. Also, huge fan :D

Thaumcraft: Beta 17
MC: 1.12.2
Forge: 14.23.3.2677

**Comment by Chicken9000** [comment]
Same with guard golems, after they kill, they spin in circles.
