### ISSUE TITLE
Strange Golem Render Issue beta17

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-beta#1138]
I noticed golems wont keep there settings if placed down. It doesn't always happen. Its mostly a graphic issue doesnt effect the ability.

The golem I made.

![2018-07-12_01 04 13](https://user-images.githubusercontent.com/7864666/42613652-109348c0-8570-11e8-931f-3d9cd396a5b8.png)

And what I got, some golems look like the golem that was made. While others look default.

![2018-07-12_01 04 17](https://user-images.githubusercontent.com/7864666/42613665-2949caba-8570-11e8-812d-9fa13d118eb6.png)

**Comment by Mii1128** [comment]
reload and it should fix itself. still a bug though.

**Comment by OmegaDragon32** [comment]
Huh, a lot like how I described my golem's appearance issue (and their strange behavior).
