### ISSUE TITLE
[Bug] [Suggestion] Foci equip animation too slow, add option to disable.

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft-beta#1141]
The speed at which the animation plays is dependant on framerate, instead of time. This results in the animation taking much longer to complete on low framerates. This can result in the player dying due to them being unable to equip a weaponized focus quickly enough.

Even if this is fixed, I prefer being able to instantly switch between foci instead of waiting through a delay. An option to disable this animation would be appreciated.

**Comment by Crusher48** [comment]
I mean, I'm even considering making multiple gauntlets for the sole purpose of being able to switch spells more quickly instead of waiting 2 seconds each time (likely in the middle of combat).

**Comment by Azanor** [comment]
Do you mean the speed at which the foci wheel pops up?

**Comment by ViciousVinnyD** [comment]
Yes, it is too slow. An option to disable the animation completely would be very nice.

**Comment by ViciousVinnyD** [comment]
I disagree, I think it should just be user preference that decides UI behavior. I do, however, think that the gauntlet could use a buffer upgrade.
