### ISSUE TITLE
Greatwood & Silverwood leaves lack contrast on fast graphics.

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft-beta#1142]
Normal leaves have a dark background where there is usually transparancy. Greatwood and silverwood leaves lack this contrast and look strange on fast graphics. Adding a bit of contrast to the opaque texture would help.
<a href="https://imgur.com/mdqAK02"><img src="https://i.imgur.com/mdqAK02.png" title="source: imgur.com" /></a>

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#335
