### ISSUE TITLE
AURAS TAKING X ms LONGER THAN NORMAL IN DIM 0

### ISSUE THREAD

**Issue by dpeter99** [Azanor/thaumcraft-beta#1144]
I have a Mc server witch starts up and than it uses all the CPU.

This is the log from the server:
https://pastebin.com/C16k6dzx

this is on the latest forge version for 1.12.2
and on Beta17 6.1 of Thaumcraft 

Similar: #950

**Comment by androshalforc** [comment]
i thought someone said this was caused by a mod constantly loading and unloading dim 0 causing which has the result of making it look like TC is causing the problem
although i cant find that post now

**Comment by Azanor** [comment]
Yes, that message is simply a warning that something is causing a crazy high tick rate. The problem may not be TC related.

**Comment by Azanor** [comment]
There are several tools you can use to check out what is the cause of the poor server tick rate.

**Comment by Azanor** [comment]
Any further info on this issue?
