### ISSUE TITLE
[Beta 17] Crucible Bug/Error & Add-on Incompatibility

### ISSUE THREAD

**Issue by AnyaDinky** [Azanor/thaumcraft-beta#1147]
- I was trying to make the brass ingot when I was finished, I tried to SHIFT + RIGHT CLICK... nothing happened. I have tried to test out any mods I have recently downloaded including the update from [BETA 16] to [BETA 17]. The version before I have tried and worked and thing version, It didn't. I haven't tried Alchemy until just now. Water in the crucible will not go away.

- Another thing is one of the add-ons for the mod will cause the alchemy recipe/instructions to completely disappear, leaving a black page with no words or symbols. The mod causing this is [Thaumic Periphery 0.2.4]

**Comment by Riyshn** [comment]
The Thaumic Periphery bug should be reported over there, not here.

As for the Crucible issue, were you holding anything at the time? In either hand?

**Comment by Azanor** [comment]
Could you maybe post some screenshots of what you are trying to do exactly? Are you trying to empty the crucible since you are shift-right clicking?

**Comment by Azanor** [comment]
Unfortunately I can't duplicate this. Is the problem still occurring?

**Comment by Arukudou** [comment]
I have the same issue over here, i can't fill the Crucible with water, The only mods were playing in my server is Aether II, Thaumcraft 6 & Baubles 
![issuethaumcraft6](https://user-images.githubusercontent.com/41450495/42966398-9d10a782-8b62-11e8-9a5e-466aa844a8b4.PNG)

**Comment by AnyaDinky** [comment]
@Azanor The problem stopped long ago is when I removed an add-on but I don't know about the situation of @Arukudou ^^^
