### ISSUE TITLE
[Beta17] Fortress Armour Glitch.

### ISSUE THREAD

**Issue by GrimRT** [Azanor/thaumcraft-beta#1150]
This is what it looks like
![2018-07-15_19 19 28](https://user-images.githubusercontent.com/41257998/42732432-f2d192ae-8864-11e8-9fa8-240f5c350177.png)

**Comment by Hubry** [comment]
Do you have Mo' Bends? If you do, try messing with its options or remove it.

**Comment by Azanor** [comment]
:)
