### ISSUE TITLE
Alchemical Metallurgy - Step 3/5 not possible or minor bug?

### ISSUE THREAD

**Issue by chaos234** [Azanor/thaumcraft-beta#1152]
Hey,

I am not sure why this happends but this is what I get shown in the Thaumonomicon:

https://i.imgur.com/btMKFbe.png

Maybe it is caused by any of the Addons but it could also be a main (minor) issue be.
Would be nice to get feedback on this :)

**Comment by Azanor** [comment]
Not a bug - void ingots and so forth still needs to be implemented.

**Comment by chaos234** [comment]
Ah ok, that's why it show unlocalized name? Thanks for the information :)
