### ISSUE TITLE
[Question] How to dismantle focis?

### ISSUE THREAD

**Issue by chaos234** [Azanor/thaumcraft-beta#1157]
I am not sure why but it seem that it is impossible to dismantle focis like you can do it with wands in 1.7.10. Is this correct or is this a (known) bug? Would be nice because nothing for this is stated in the Thaumonomicon (yet).

Would be nice to know what is going on there :)

**Comment by Chicken9000** [comment]
What exactly do you mean by dismantle?

Take them off the gauntlet or unmake them?

**Comment by chaos234** [comment]
Take them off the gauntlet like you did it with wands in 1.7.10 where you could simply remove the foci with Shift+F

**Comment by Reassembly** [comment]
...I'm sorry if this seems flippant, but have you tried Shift+F?

**Comment by chaos234** [comment]
Ok, with Shift + F (or which key ever is defined in the key-controls) it is working which is funny. Maybe adding a hint in the Thaumonomicon to this would be nice :)

Sometimes the solution is in front of you but you can't see it :D
