### ISSUE TITLE
Possible memory leak with Greatwood Trees

### ISSUE THREAD

**Issue by superfluke** [Azanor/thaumcraft-beta#1158]
Version: Thaumcraft-1.12.2-6.1.BETA17

It looks like greatwood trees work the same way as vanilla BigTree and suffer the same memory leak where references to worlds can hang around. You can see the bug report for the vanilla big tree's leak here: https://bugs.mojang.com/browse/MC-101232
And forge's patch for it here: https://github.com/MinecraftForge/MinecraftForge/blob/ab228832f24e53436d058a96ff9483376a917b02/patches/minecraft/net/minecraft/world/gen/feature/WorldGenBigTree.java.patch#L36

**Comment by Azanor** [comment]
Yeah, greatwoods are just a modified version of the bigtree's. Thanks, I'll take a look
