### ISSUE TITLE
Infinite Cycle of "Using"

### ISSUE THREAD

**Issue by Nuclos1** [Azanor/thaumcraft-beta#1159]
Whilst a golem is "using" a use seal, it will use one item and then just sit there infinitely using the other items it has on that same block. The idea was to have a fully automated lumber farm where there is a tree-cutting golem and a planting golem, however, I can't find a way to make a golem plant a sapling. I've tried somehow using the harvest seal, that doesn't work with saplings and I have also tried using just use seals but the use seals just makes the golem stay at one use seal infinitely trying to plant a sapling where it has already planted one. I don't want to have to have 49 separate golems for each block that requires a sapling and so I came here.
My main suggestion is to implement some sort of "use once" or "use if" feature to the use seals, either that or add a new seal called "plant seal" where you can have a harvester and a planter golem on the same farm.

**Comment by Azanor** [comment]
To prevent the behaviour above use the 'only on empty space' toggle in the use seal and place the seal itself on the blockspace where you want the sapling to be.
