### ISSUE TITLE
Ideas for nodes. (Written in Russian.)

### ISSUE THREAD

**Issue by Shurik1236** [Azanor/thaumcraft-beta#116]
Извините, но я не знаю английский чтобы это грамотно перевести.
(Google)
Sorry, but I do not know English in order to translate this correctly.

Предлагаю такую механику ауры и узлов:
Жезлы не заряжаются сами (Как в Thaumcraft 4). Для этого нужно найти узел.
И узлы с аурой содержат аспекты.
Аура требуется для создания механизмов, предметов и работы механизмов.
При этом будут штрафы и поощрения за создание предмета.
Например, для набалдашника позволяющего копать требуется чтобы при создании в области было не менее 30%, но и не более 35% ауры Terra.
Чем ближе концентрация аспектов будет к центральному значению, тем более качественным получится конечный результат.
И если не соблюдены условия, то механизм\инструмент получит негативные эффекты.
Если условия соблюдены, но не идеальны, то получится без эффектов.
А если аура была очень близко приближена к идеальной концентрации, то будет добавлен положительный эффект который другими способами получить нельзя.

В Thaumcraft 5 было добавлено очень много механизмов требующих vis.
Предлагаю вернуть механику с vis relay, но расширить.
Механизмы не могут работать от ауры. Для их работы потребуется vis relay.
Получать пригодный для работы машин vis можно двумя способами.

Первый способ: специальный коллектор вытягивающий vis из окружающий ауры.
Дешевый, мобильный, но "грязный" метод. Он накапливает в ауре warp. Очень мало, но накапливает. А если ещё и аспект в ауре закончится, то warp будет накапливаться ещё быстрее.

Второй способ: Знакомая всем механика с Node Stabilizer и Node Transducer. :)
Но немного другая.
Node Stabilizer будет выполнять функцию очистителя, изолятора и аккумулятора, а Node Transducer извлекать vis.
Узел помещённый в сферу над Node Stabilizer (Он автоматически сдвинется к центру сферы) будет изолирован от ауры и не сможет её пополнять аспектами.
Так же узел будет производить меньше vis чем обычно.
Внутри сферы будет накапливаться vis пригодный для vis relay и зарядки жезла. Больше чем может хранить узел. А подключив новый Node Transducer можно будет направить vis в vis relay.
В отличии от коллектора ауры warp при этом пассивно не накапливается.
Warp будет накапливаться только если Node Transducer будет пытаться вытянуть больше vis чем может произвести узел.
Накопленный warp не будет выделятся в мир, он будет копится в сфере Node Stabilizer и постепенно уменьшаться.
И вот тут самое страшное! Если в Node Stabilizer накопится слишком много warp, то он сломается (Больше не сможет работать), а вся гадость выльется в окружающею ауру!
Более того узел станет типа "Tainted" и сам начнём портить ауру!
Что при этом произойдёт с миром и жилищем игрока описывать не требуется...

Надеюсь кто нибудь переведёт это...

**Comment by groting** [comment]
Не уверен что это необходимо в TC 6. Так как система ауры была полностью переписана. Узлы были полностью устранены так же как и деление ауры на первичные аспекты. Да и жезлы уже убраны.

**Comment by Shurik1236** [comment]
Но без этого у него же словно отвалилась энергетическая система и вместо неё поставили протез.
Какой бы не была нудной механика четвёртого, она была с очень широкими возможностями.
Да только её использовали очень мало. В пятом система была более глобальная, да только её загубила бессмысленность.
А вот это решение сделает нужной механику пятого и используемой механику четвёртого.
И более того, даже по отдельности механики четвертого и пятого лучше чем то что представлено в шестом.
Нет правда, запутанную механику шести аспектов заменили на "сырую энергию"! Это тоже самое как перевести TC на ману из botania...

**Comment by groting** [comment]
На мой взгляд Азанор принял верное решение вернув систему вис из ТС 2. Потому что система разделения на аспекты подерживается в алхимии, и её добавление ещё в ауромантию было бы перегрузкой общего дизайна. Насчёт узлов ауры возможно их можно было бы вернуть как элементы энд гейма для получение усилений генерации вис в чанках, или усиления тауматургических устройств.

In my opinion, Azanor made the right decision returning the system from the TС 2. Because separation into aspects is supported in alchemy, adding it to auromancy would be an overload of the general mod design. As for the nodes of the aura, they could possibly be returned as elements of the end game for gaining amplification of the Vis in chunks, or strengthening of thaumaturgic devices.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#162
