### ISSUE TITLE
[Suggestion] Some Shield Ideas

### ISSUE THREAD

**Issue by Voxelo** [Azanor/thaumcraft-beta#1161]
I think a shield could be useful a addition.

**Shield of Unyielding -**
  Could be linked to elemental tools and runic shielding. It would have all the properties of a vanilla shield but more durability. In addition it would have runic shielding and could augment the recharge speed of it while  equipped. Also would be enchant-able.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#333
