### ISSUE TITLE
[Suggestion] Ability to edit a golem's components without having to start from scratch / ability to disassemble golems to retrieve components

### ISSUE THREAD

**Issue by Naphrym** [Azanor/thaumcraft-beta#1162]
So, I've run into this problem a few times now, mostly because I forget to check what a golem needs in order to do a specific job: I make a little friend with expensive components, only to neglect to add *just one* important feature. Now, I am forced to start all over and hope I don't forget again.

I think it would be a good, lore-friendly addition to allow an experienced Thaumaturge to dismantle his golems (with a reasonable chance for the disassembling to fail, losing items) to retrieve some or all of the components of the golem In addition to or in lieu of this, the ability to make changes to a golem that's already been been assembled, perhaps with additional essentia and material costs, would be super helpful as well.

If this is already in the works or already in the mod, I apologize. I couldn't find any info online.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#332
