### ISSUE TITLE
Brass plate not craftable over TC6 itself?

### ISSUE THREAD

**Issue by chaos234** [Azanor/thaumcraft-beta#1163]
Hey Azanor,

I am not sure if this is related to the used mods/modpack (a slightly changed FTB Revelation ones) but the Essentia Smeltery uses *Brass Plates* which are not easy to craft.

Recipie: https://i.imgur.com/VTaHgiQ.png
Brass Plate Recipes: https://i.imgur.com/cl3N7cv.png (Thermal Expansion), https://i.imgur.com/AuY7pZD.png (TiCon, by smelting Alchemical Brass Ingot, which creates *Molten Brass* - which can also be made with 2 mB copper and 1 mB Zinc, added by Rockhounding Mod: Surfaces) or by using the Immersive Engineering Metal Press (https://i.imgur.com/nZ9b3FV.png).

I am not sure if this is intended because what will be the recipie without the mods mentioned above? Would be nice to have for this a TC 6 only/fallback recipie.

**Comment by Reassembly** [comment]
The non-modpack TC6 recipe for Brass Plates is three brass ingots in a horizontal row - in fact, very easy. It's possible that some modpack compilers might be deliberately disabling that recipe, if other mods in the pack are supplying other means of crafting plates that are more complex, for balance reasons or something.

**Comment by Azanor** [comment]
Yup, that recipe must have been disabled in the modpack

**Comment by chaos234** [comment]
Thanks for the info :)
