### ISSUE TITLE
(Suggestion)Thaumic Flight

### ISSUE THREAD

**Issue by Wotzinator** [Azanor/thaumcraft-beta#1169]
it would be cool to have a flight possibility again and i had 2 ideas for it the first one would be re-adding the thaumostatic harness(maybe as a bauble)and let it be powered by vis.the second thing would be re-adding the flying caret from thaumcraft 2(i believe it was 2) i don't really know how it works i just discovered it while i was trying older versions of the mod.

**Comment by wamc2017** [comment]
https://github.com/Azanor/thaumcraft-suggestions is maybe the best place for suggestions...

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#373
