### ISSUE TITLE
Can't start if there's no wand in this mod

### ISSUE THREAD

**Issue by Eincurt** [Azanor/thaumcraft-beta#1170]
My friend and I can't get started because we cant use the iron ingots to make iron caps.
When I went offline to check, I found out that there's no caps in the mod, after this I go and check, but there's not even a wand in the mod.
Is there's any problem that I miss?
Or do I need to do something in order to make things work?

**Comment by Shirukenu** [comment]
Did you gather any crystals from the world and get a message when you slept? Did you follow the instructions in the book given?

**Comment by CastielAngelow** [comment]
**Thaumcraft**, my dear, is well composed to give you magical feel with tip of science on each magic cake.
You do not get instruction manual. That would ruin whole mystically-magically entertaining part.
You get little hints, though. And I think this is self-explanatory, to take a bed, although, discover rest to yourself is what makes it most beatiful journey. O:)
