### ISSUE TITLE
massive memory leak

### ISSUE THREAD

**Issue by CharCharthemonkey** [Azanor/thaumcraft-beta#1174]
latest thaumcraft beta on twitch is causing my memory to max out at 7.42gb ram when i load a pack up but in previous versions it didnt so wat do i do?
[FML.txt](https://github.com/Azanor/thaumcraft-beta/files/2212295/FML.txt)

**Comment by CastielAngelow** [comment]
I recommending reproducing this "lag" with Thaumcraft itself. If its not happening again, problem is elsewhere, also, crash seems related to FoamFix ;-)

**Comment by CharCharthemonkey** [comment]
actually from wat i could tell its a combo of mekanism thaucraft aspect for JEI foamfix and JEI not playing well together

**Comment by Azanor** [comment]
So not TC itself then?

**Comment by CharCharthemonkey** [comment]
TBH idk azanor cause the log was saying a few things bout thaumcraft too so thats y i figured since ure the mod dev u might atleast be able to point me in the general direction if its not thaumcraft pretty please?

**Comment by Azanor** [comment]
There is nothing in the log TC related that seems unusual. The only problem seems like it could be with foamfix.

**Comment by Mike-U5** [comment]
I have  similar issue with Thaumcraft and the Flying Things mod. No other mods used besides Tc, Baubles and Flying Things.

**Comment by Azanor** [comment]
There might be a leak related to golems that should hopefully be plugged in B25
