### ISSUE TITLE
[Suggestion] Give the ability to bind custom textures for research tasks.

### ISSUE THREAD

**Issue by TimeConqueror** [Azanor/thaumcraft-beta#1176]
It will be cool, if you give the ability to bind custom textures for research tasks.
What I mean? I say about tasks that are represented below:
![image](https://user-images.githubusercontent.com/25156941/43001854-8699c2fe-8c2f-11e8-800b-e97c3033c466.png)
The textures, that are bound to them, are strictly limited (only map, flask and chest textures and nothing more). If you allow to use custom textures for them, addons' auhors can let players to be more immersed in the atmosphere of Thaumcraft. 

For now it's just a texture of question mark. :c
![image](https://user-images.githubusercontent.com/25156941/43002257-cb04931e-8c30-11e8-80a0-50a359dc2958.png)

**Comment by Azanor** [comment]
In B25 I've added the ability to add custom textures in the following format:
`"required_research":["EXAMPLE_RESEARCH;thaumcraft:textures/items/thaumonomicon.png"]`

**Comment by Azanor** [comment]
Using special codes like "!", "m_", etc. will override this texture and proper research entries will still use their own icons.
