### ISSUE TITLE
[Beta 19] Slight annoyance

### ISSUE THREAD

**Issue by PokeMaserJ** [Azanor/thaumcraft-beta#1177]
The Cloudstepper Ring will prevent any Fall Damage, like it's supposed to, but it plays the hurt animation / sound when you would take fall damage w/o it on

**Comment by PokeMaserJ** [comment]
a bit of an update. Azanor seems to of nerfed the cloud stepper ring in Beta 14 to reduce fall damage, instead of negating it. And the effect still happens in Beta 19 as well

**Comment by davue** [comment]
Yeah it should not play the hurt animation / sound on 0 damage.

**Comment by Azanor** [comment]
Unfortunately I cannot prevent that sound/animation from being played - that is on the MC side.

**Comment by PokeMaserJ** [comment]
Beta 13 didn't have the sound / animation. Was that b/c you canceled fall damage entirely ?
