### ISSUE TITLE
TC6 B16 Hedge Alchemy - crucible not recognising catalyst

### ISSUE THREAD

**Issue by BennehR** [Azanor/thaumcraft-beta#1181]
Im trying to complete the hedge alchemy quest stage 2/4 but the crucicble is not recognising slime balls as a catalyst and just adds the essentia into the mix

Ive successfully done glowstone, gun powder and inksacs, but slimeballs are just being added to the mix rather than popping out another ball and completing the quest

This appears to be the same as #1032 but for a different item
![2018-07-21 01_58_31-minecraft 1 12 2](https://user-images.githubusercontent.com/5487055/43030565-b88f8f1e-8c89-11e8-82b6-0b8d2b181f2f.png)

I have ensured ive got enough essentia by using 2 slime balls to have double the essentia required, the third was consumed rather than used as catalyst. Same result when using essentia crystals to create the mix then using a slime ball, also does not act as a catalyst

**Comment by BennehR** [comment]
also if theres a way i can OP past this somehow without giving myself a full book of research id love to know so i can continue

**Comment by BennehR** [comment]
So this appears to be Tinkers Construct mod integration, i was using Tinkers slime balls and not vanilla one, just realised as i spawned in some in creative and it worked without issue

**Comment by wamc2017** [comment]
Have you tried updating to beta 19 and tried to replicate this issue?

**Comment by BennehR** [comment]
No I'm running All The Mods 3: Lite on a private server so will get it when
the pack/server updates, I'll duplicate the profile and update tc to test
it out for the sake of resolution

**Comment by enderger** [comment]
I just modify my modpacks to fit my needs

**Comment by androshalforc** [comment]
i believe theres a bug where you can make a slime block and then break it down into slimeballs that counts for completing the research

**Comment by enderger** [comment]
That is because the thaumonomicon does not care what recipie is used to craft any item for research.
