### ISSUE TITLE
Thaumcraft crashing in GradleStart

### ISSUE THREAD

**Issue by Hallowizer** [Azanor/thaumcraft-beta#1183]
I was trying to write an add-on for Thaumcraft, so I ran Minecraft, then I added Thaumcraft and Baubles to the mods folder, and when I restarted the game, the mods were loaded properly, but I opened a world and tried to look at Thaumcraft items. When I did, the test client crashes with a ReportedException that was caused by an AbstractMethodError. This occured in class net.minecrsft.client.renderer.color.ItemColors.getColorFromItemstack on line 139. I searched both Thaumcraft and Baubles for the phrase "IItemColor", and all I found was thaumcraft.client.fx.particles.FXBoreParticles. Does anybody know why the test client is crashing?

**Comment by MCOfficer** [comment]
i _assume_ [here](https://github.com/Azanor/thaumcraft-api), but frankly, i have little idea.

**Comment by Hallowizer** [comment]
That is just the api, which is packaged in Thaumcraft anyway. I'm looking for the 1.12.2 version of 47135879:Thaumcraft:1.8.9-5.1.6:deobf.

**Comment by Azanor** [comment]
Instead of putting TC in your mods folder, add the deobf version as a library. It will automatically be counted as a mod and you will get access to the API. Same goes for baubles.
I'm not saying this is the best option, but it works :)
