### ISSUE TITLE
Ender IO Thaumcraft API integration problem

### ISSUE THREAD

**Issue by jdratlif** [Azanor/thaumcraft-beta#1184]
EnderIO is adding thaumcraft aspects to its items by calling the API functions to get aspects from other items. They have an item "coal dust", whose aspects would be the same as coal.

You've said that this is not a good idea to call getAspects on an Item during initialization because it's not possible to know whether your aspect generation code has run yet.

But why does calling the getAspects function of the library remove aspects on coal entirely? This still seems like a bug, even if the library function should not be called here.

**Comment by enderger** [comment]
This probably should be sent to enderio.

**Comment by Azanor** [comment]
This should be solved in B20+
