### ISSUE TITLE
Summoning Flux Rift crashes game [Beta19]

### ISSUE THREAD

**Issue by OmegaDragon32** [Azanor/thaumcraft-beta#1185]
The title is pretty self explanatory, discovered this a few moments ago (by that I mean as this was posted).
Is it still safe to enter the world, or has it been consumed from a potentially massive rift?, Or will it crash me every time I enter it? (good thing it was in a creative world and not my main one) 
Since it's been asked for, here's my crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/21/18 1:51 AM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.entities.EntityFluxRift.func_70071_h_(EntityFluxRift.java:269)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.entities.EntityFluxRift.func_70071_h_(EntityFluxRift.java:269)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: thaumcraft:fluxrift (thaumcraft.common.entities.EntityFluxRift)
	Entity ID: 271
	Entity Name: Flux Rift
	Entity's Exact location: -46.52, 86.62, 179.09
	Entity's Block location: World: (-47,86,179), Chunk: (at 1,5,3 in -3,11; contains blocks -48,0,176 to -33,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MegaEnderLord'/283, l='MpServer', x=-43.95, y=86.62, z=175.60]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-236,64,256), Chunk: (at 4,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 179717 game time, 179717 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityChicken['Chicken'/256, l='MpServer', x=-41.43, y=92.00, z=159.81], EntitySheep['Sheep'/257, l='MpServer', x=-42.86, y=95.00, z=151.55], EntityItem['item.tile.dirt.default'/258, l='MpServer', x=-36.73, y=82.00, z=173.58], EntityItem['item.tile.dirt.default'/259, l='MpServer', x=-37.13, y=81.00, z=175.88], EntityItem['item.tile.dirt.default'/260, l='MpServer', x=-37.86, y=81.00, z=174.12], EntityItem['item.tile.gravel'/261, l='MpServer', x=-37.88, y=80.00, z=173.88], EntityItem['item.tile.sapling.spruce'/262, l='MpServer', x=-36.65, y=83.00, z=175.96], EntityItem['item.tile.dirt.default'/263, l='MpServer', x=-44.49, y=80.00, z=169.12], EntityItem['item.tile.dirt.default'/264, l='MpServer', x=-42.13, y=82.00, z=168.67], EntityItem['item.tile.dirt.default'/265, l='MpServer', x=-43.13, y=81.00, z=173.25], EntityItem['item.tile.dirt.default'/266, l='MpServer', x=-41.58, y=82.00, z=170.15], EntityItem['item.tile.dirt.default'/267, l='MpServer', x=-45.43, y=82.00, z=172.44], EntityItem['item.tile.dirt.default'/268, l='MpServer', x=-42.95, y=82.00, z=168.13], EntityItem['item.tile.dirt.default'/269, l='MpServer', x=-41.16, y=81.00, z=171.51], EntityChicken['Chicken'/270, l='MpServer', x=-36.47, y=94.00, z=160.84], EntityFluxRift['Flux Rift'/271, l='MpServer', x=-46.52, y=86.62, z=179.09], EntitySpider['Spider'/272, l='MpServer', x=-45.24, y=74.00, z=228.39], EntityBat['Bat'/284, l='MpServer', x=-4.27, y=16.83, z=226.73], EntityBat['Bat'/300, l='MpServer', x=6.24, y=44.10, z=221.33], EntitySquid['Squid'/301, l='MpServer', x=12.20, y=62.00, z=219.40], EntityItem['item.item.egg'/303, l='MpServer', x=17.05, y=83.00, z=125.91], EntitySheep['Sheep'/304, l='MpServer', x=13.73, y=73.00, z=141.48], EntityChicken['Chicken'/305, l='MpServer', x=3.98, y=88.00, z=136.53], EntityChicken['Chicken'/306, l='MpServer', x=8.87, y=88.00, z=129.48], EntityItem['item.item.egg'/307, l='MpServer', x=5.13, y=85.00, z=137.13], EntityChicken['Chicken'/308, l='MpServer', x=10.55, y=86.00, z=131.83], EntityChicken['Chicken'/309, l='MpServer', x=9.87, y=87.00, z=130.52], EntityBat['Bat'/310, l='MpServer', x=-16.07, y=22.03, z=212.26], EntityBat['Bat'/438, l='MpServer', x=16.22, y=38.90, z=227.49], EntitySkeleton['Skeleton'/311, l='MpServer', x=-27.50, y=43.00, z=230.50], EntityBat['Bat'/439, l='MpServer', x=16.05, y=40.22, z=228.49], EntityBat['Bat'/312, l='MpServer', x=-24.46, y=47.10, z=229.75], EntitySquid['Squid'/440, l='MpServer', x=18.16, y=62.43, z=235.56], EntityBat['Bat'/313, l='MpServer', x=-27.93, y=43.12, z=225.76], EntityChicken['Chicken'/314, l='MpServer', x=-27.52, y=79.00, z=150.20], EntitySquid['Squid'/442, l='MpServer', x=16.29, y=60.02, z=230.06], EntityChicken['Chicken'/315, l='MpServer', x=-25.42, y=80.00, z=151.82], EntitySheep['Sheep'/316, l='MpServer', x=-28.27, y=85.00, z=146.50], EntityItem['item.item.egg'/317, l='MpServer', x=-30.55, y=93.00, z=152.03], EntityItem['item.item.egg'/318, l='MpServer', x=-20.15, y=82.00, z=158.62], EntityItem['item.item.egg'/319, l='MpServer', x=-21.14, y=81.00, z=155.74], EntitySheep['Sheep'/320, l='MpServer', x=-28.25, y=80.00, z=151.43], EntitySheep['Sheep'/321, l='MpServer', x=-31.50, y=95.00, z=147.51], EntitySheep['Sheep'/322, l='MpServer', x=-31.50, y=95.00, z=146.74], EntitySheep['Sheep'/323, l='MpServer', x=-31.55, y=97.00, z=154.44], EntityItem['item.item.egg'/324, l='MpServer', x=-10.15, y=93.00, z=128.88], EntityBat['Bat'/197, l='MpServer', x=-105.82, y=35.19, z=127.68], EntityChicken['Chicken'/326, l='MpServer', x=-7.93, y=72.00, z=203.81], EntityChicken['Chicken'/327, l='MpServer', x=-6.51, y=73.00, z=198.79], EntityChicken['Chicken'/328, l='MpServer', x=-3.79, y=73.00, z=207.51], EntityItem['item.item.egg'/329, l='MpServer', x=-14.38, y=73.00, z=197.63], EntityItem['item.item.egg'/330, l='MpServer', x=-4.27, y=73.00, z=207.11], EntityItem['item.item.egg'/331, l='MpServer', x=-10.05, y=72.00, z=205.36], EntitySheep['Sheep'/333, l='MpServer', x=7.27, y=70.00, z=164.18], EntityChicken['Chicken'/334, l='MpServer', x=-10.90, y=71.00, z=170.42], EntityItem['item.item.egg'/335, l='MpServer', x=-5.67, y=71.00, z=178.68], EntityChicken['Chicken'/336, l='MpServer', x=-8.49, y=92.00, z=120.18], EntitySheep['Sheep'/337, l='MpServer', x=-21.51, y=97.00, z=130.76], EntityZombieVillager['Zombie Villager'/338, l='MpServer', x=5.51, y=20.00, z=229.81], EntityZombie['Zombie'/339, l='MpServer', x=12.54, y=23.00, z=225.72], EntityZombie['Zombie'/340, l='MpServer', x=14.50, y=24.00, z=227.50], EntitySkeleton['Skeleton'/341, l='MpServer', x=3.93, y=43.00, z=224.50], EntityBat['Bat'/214, l='MpServer', x=-96.65, y=29.31, z=137.15], EntityCreeper['Creeper'/342, l='MpServer', x=14.50, y=38.00, z=224.50], EntityChicken['Chicken'/215, l='MpServer', x=-98.50, y=70.00, z=188.77], EntityCreeper['Creeper'/343, l='MpServer', x=3.30, y=43.00, z=224.50], EntitySquid['Squid'/344, l='MpServer', x=15.67, y=56.78, z=225.08], EntityChicken['Chicken'/348, l='MpServer', x=-18.10, y=72.00, z=198.53], EntityItem['item.item.egg'/350, l='MpServer', x=18.92, y=83.00, z=132.03], EntitySheep['Sheep'/351, l='MpServer', x=12.45, y=71.00, z=149.26], EntityChicken['Chicken'/352, l='MpServer', x=-30.86, y=97.00, z=118.71], EntityChicken['Chicken'/353, l='MpServer', x=-30.80, y=96.00, z=125.59], EntitySheep['Sheep'/354, l='MpServer', x=-26.82, y=98.00, z=127.52], EntityChicken['Chicken'/227, l='MpServer', x=-94.78, y=69.00, z=172.52], EntityItem['item.item.egg'/355, l='MpServer', x=-30.62, y=96.00, z=125.13], EntityItem['item.item.egg'/228, l='MpServer', x=-94.32, y=69.00, z=171.78], EntityItem['item.item.egg'/356, l='MpServer', x=-31.00, y=97.00, z=118.75], EntityPlayerSP['MegaEnderLord'/283, l='MpServer', x=-43.95, y=86.62, z=175.60], EntityChicken['Chicken'/229, l='MpServer', x=-88.39, y=72.00, z=189.89], EntityItem['item.item.egg'/230, l='MpServer', x=-84.70, y=72.00, z=192.11], EntityItem['item.item.egg'/231, l='MpServer', x=-83.42, y=72.00, z=192.23], EntityChicken['Chicken'/241, l='MpServer', x=-75.52, y=72.00, z=194.55], EntitySheep['Sheep'/245, l='MpServer', x=-49.75, y=82.00, z=163.43], EntityChicken['Chicken'/255, l='MpServer', x=-39.42, y=90.00, z=142.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 571630896 bytes (545 MB) / 1040187392 bytes (992 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2677 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.3.2677.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.3.2677 | forge-1.12.2-14.23.3.2677.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar      | None                                     |
	| UCHIJAAAA | thaumcraft | 6.1.BETA19   | Thaumcraft-1.12.2-6.1.BETA19.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4425' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2677
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4425, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3540 @ 2.16GHz
-------------------------------------------------------------------------------------------------------------------
But I do know for a fact that the crash happened when I tried to summon the Flux Rift. Also, the world is now unusable cause of my curiosity :3 It was deleted.

**Comment by enderger** [comment]
18 did indeed exist, but probably had a fatal compilation error.

**Comment by enderger** [comment]
Changelog

**Comment by wamc2017** [comment]
Beta 18 was only available for patreons.

Please post your crashlog at gist/pastebin and post the link here...

**Comment by OmegaDragon32** [comment]
@wamc2017 Crash Report up :3

**Comment by enderger** [comment]
Please use pastebin/gist
