### ISSUE TITLE
Alchemical metallurgy stays blinking on update [B19]

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#1187]
So I updated thaumcraft to B19 after reaching the void metal stage of alchemical metallurgy(where you previously could not continue) and, upon updating, the last stage of the research was removed. Without a countermeasure in place, the research thought that it was incomplete despite being complete.

**Comment by KizerKitty** [comment]
I have encountered the same issue. It says progress is 3/3 but remains blinking and the void metal nugget research will eat my research points but not complete in the eldritch tab.

**Comment by enderger** [comment]
I found a way to fix this: load the world and type (Azanor should be able to use the code that does this on world load if the player discovered thaumium to achieve this) /tc research @p METALLURGY

**Comment by enderger** [comment]
Creative testing worlds can be useful indeed!

**Comment by PassiveBrain** [comment]
Same thing happend to me. I cheated mettallugry and eldritch (eatin theory points). wonder if there any other method to get void seeds besides blowing rifts. Hope it will be soon)
