### ISSUE TITLE
Sprinkling salis mundus over bookshelf doesn't do anything

### ISSUE THREAD

**Issue by leSamo** [Azanor/thaumcraft-beta#1189]
I am using Thaumcraft beta-19 and after using salis mundus on bookshelf particles appear but nothing happens. After refreshing inventory (with inventory tweaks sort) the salis mundus is back in my inventory.

**Comment by enderger** [comment]
It works fine on my end.

**Comment by wamc2017** [comment]
Hmm, did you receive the strange dreams book (after sleeping) before you tried to use salis mundus on a bookshelf?

**Comment by leSamo** [comment]
Yes, I did.

**Comment by wamc2017** [comment]
Hmm, do you have other mods installed? (A modlist may be helpful)
Are you playing single or multiplayer?

**Comment by enderger** [comment]
Did you restart the game?

**Comment by leSamo** [comment]
Restarting game fixed the issue.

**Comment by kurtawirth** [comment]
I am having this same problem on a server and there's no way to "restart" the game here.

https://github.com/Azanor/thaumcraft-beta/issues/1257
