### ISSUE TITLE
[B19] alchemical brass and iron plate receipe not working.

### ISSUE THREAD

**Issue by KizerKitty** [Azanor/thaumcraft-beta#1190]
Can't make alchemical brass/iron plates with the three ingots in a row. can make it through tinkers, IE, or thermal.

**Comment by wamc2017** [comment]
Maybe a dupe of #1163 

Could you provide a modpack/a modlist? Maybe the plate recipe is disabled through crafttweaker if you're playing a modpack...

**Comment by KizerKitty** [comment]
Direwolf20 modpack 1.12 v2.1.0. I updated TC to 19 from 17.

**Comment by wamc2017** [comment]
Yeah, in direwolf20 all plate recipes in the crafting table are removed through crafttweaker...
You could try removing "mods.unidict.removalByKind.get("Crafting").remove("plate");" from scripts/01_unification.zs, but don't know if this breaks anything else...

**Comment by KizerKitty** [comment]
How do i work with crafttweaker? I do not see a config file for it.

**Comment by wamc2017** [comment]
Crafttweaker works with script files found in the scripts folder (not the config folder)
Like I said, it should be the 01_unification.zs...

**Comment by KizerKitty** [comment]
that fixed it. so annoying.
