### ISSUE TITLE
Issues while trying to start Thaumcraft 6 Beta 19

### ISSUE THREAD

**Issue by KatanaKruger** [Azanor/thaumcraft-beta#1191]
Hello everyone, as you guessed, I have issues with the latest Thaumcraft 6 upadate.
I correctly installed forge-1.12.2-14.23.3.2655, (which is not the latest or more optimized version, but this version worked in Youtube tutorials). Even though I tried with a more recent version of forge: forge 1.12.2-14.23.4.2705, but nothing.

When I start the game with forge 2655, it instantly crashes and displays this error: The game crashed whilst initializing game, Error: java.lang.NoClassDefFoundError: bnk.
If you have any tips that would help me understand why it does not work, it would be very helpful.

Btw I am running on Windows 8

**Comment by KatanaKruger** [comment]
This is all I can get, I cannot provide anything more.

**Comment by wamc2017** [comment]
There should be a crash-reports folder inside your minecraft folder, if not provide the latest.log from the log folder (use gist or pastebin please)

**Comment by KatanaKruger** [comment]
Ok So I looked at the logs, and I found the problem !
I had old mods that were for 1.8.9, I just had to delete them and it works
So thanks for your help ahah !
