### ISSUE TITLE
Opening cheat sheet spams player with all research given

### ISSUE THREAD

**Issue by Boundarybreaker** [Azanor/thaumcraft-beta#1192]
This isn't as much a bug as it is an expected behavior leading to an undesirable outcome. When someone opens a cheat sheet, it will give them the research complete toasts for every research in thaumcraft. Because minecraft only shows three toasts at a time, this can take forever to complete. This happens with using the /tc command to give research as well for all prerequisites. Would it be possible to add a mode to give research that doesn't send the toasts?

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#372
