### ISSUE TITLE
Use seal doesnt work properly beta19

### ISSUE THREAD

**Issue by FloxyTek** [Azanor/thaumcraft-beta#1193]
My golem doenst replant sapplings he tries to plant it over and over again forever. Tried every option in the seal but nothing works,

My normal setup is click on empty air in the use seal after sticking it on the side of a sapling with an oak sappling in my whitelist. Its like the blocks are protected

Im playing the FTB Revelation pack on a private server and updated to Beta19 myself

**Comment by enderger** [comment]
Is there not the lumberjack seal and a place seal?

**Comment by enderger** [comment]
My point being that there are other seals meant for farming and placing blocks

**Comment by FloxyTek** [comment]
Lumberjack is for the breaker golem to cut down the trees yes, but you need a use seal and a second golem and a use seal for replanting the sapling. 

The harvest seal is for crops or other harvestable plants, but doesnt work for saplings
