### ISSUE TITLE
Research does not exists

### ISSUE THREAD

**Issue by Ziolo99** [Azanor/thaumcraft-beta#1194]
I tried to get some researches using /tc research but whatever I write it says Research does not exists. can I get any list of all researches with working names?

**Comment by enderger** [comment]
In a test world...
do /tc research @p all
then do /tc research @p list

**Comment by enderger** [comment]
That will give you a list of researches that you can do and you can use all of them.

**Comment by Ziolo99** [comment]
thx but I found those names in TC files
