### ISSUE TITLE
Question - bug or requirement not met? beta 17

### ISSUE THREAD

**Issue by Eldhelion** [Azanor/thaumcraft-beta#1195]
So I dont know if this is normal or is a bug, but I'm playing Thaumcraft 6 with ftb revelation, I pretty much unlock all research tabs (except eldritch, that is locked), but one thing is bugging me.

despite being able to create a rift, scan taint stuff ,  I'm yet to unlock the "flux research" that was suposed to be in the "Fundamentals" tab.

or so I was led to believe watching Direwolf and Mischief of mice spotlights.
Is this a bug, or I'm just missing a requirement?

[print of fundamentals tab](http://prntscr.com/k9nbez)

**Comment by enderger** [comment]
The flux level must reach 50 in your current chunk to get the research. You must have a small-capacity aura in your chunk to not recieve the research and still get taint.
