### ISSUE TITLE
focus visuals suggestion

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#12]
Im not sure if it's already planned, but adding sounds and gauntlet animations for when the spells are cast would make the whole experience much more immersive (currently the break effect is silent, even when the block breaks itself)

Also, are the current foci item textures still placeholders, or is the current system (strange glyphs in different orientations on the focus) the final product? the textures as they are now seem kinda cluttered and a bit awkward. maybe rather than the little symbols, different overlays of animated effects could be layered over the base color of the focus. Like a fire focus would be red, if its a projectile it has a little glowing nodule in its center, if its a bolt, it could have a sort of fractured look. Potency could be represented by a glowing wave that movies from the bottom of the focus to the top, and frugal could be a similar animation but moving inwards from the edges to the center (or vice versa) rather than top to bottom.  Something more stylized than a couple of colored markings seems more appropriate to the general feel of thaumcraft.

**Comment by Azanor** [comment]
There are a lot of limits with the current MC system and doing animation are harder than it may look. Almost impossible in fact.
I do agree that the current symbols on the foci are not the best, but unfortunately that is also a serious limitation in the current system that I won't be able to get around without serious performance-eating voodoo.

**Comment by gabeernie** [comment]
what if the symbols were just removed? in tc4 and 5 we we had the focus upgrade system but it didnt change the focus' appearance so we just relied on the tooltips, couldnt the same go for tc6? that way there would only have to be one focus texture for each of the different effects (fire ice etc).  Perhaps we could get the option to name the focus in the crafting table  before we make it, that way people could have their own way to quickly classify and recognize the foci they make.

**Comment by Azanor** [comment]
That is one way to go. I am considering most of the focus and gauntlet visuals placeholders at the moment till I find a better solution.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#175
