### ISSUE TITLE
Vis stops regenerating when Daylight cycle is stopped.

### ISSUE THREAD

**Issue by mangafanatic** [Azanor/thaumcraft-beta#1200]
Not sure if its intentional or a bug, but the Vis regeneration stops when you use the following command:
/gamerule doDaylightCycle false

Figured I'd post it here, in case it was a bug. Nothing really game breaking however.

**Comment by Morinor** [comment]
Vis regeneration depends on moonphases and stuff afaik, so I guess its not a bug

**Comment by F9Alejandro** [comment]
Test different moon phases like @Morinor is suggesting, if it still isn't regenerating then it would be a bug, not unless it is completely intended.
