### ISSUE TITLE
Suggestion: Simple tool like compass/clock to display current moon phase

### ISSUE THREAD

**Issue by dash16** [Azanor/thaumcraft-beta#1202]
Since scanning the moon's phases are necessary for progression via Research, it'd be nice to have a utility item I could keep on my hotbar or something that will show the current moon phase.  If I'm strip mining for random ore and it becomes nighttime, it'd be cool to have an indicator that shows the current moon phase so I can go up to the surface and snap a quick picture.  Maybe even make it so you can tag a certain phase of the moon and notify you another way, like make the item start glowing like it is enchanted.

Edit: Recipe suggestion - 4 Alchemical Brass ingots around a Vis Crystal, similar to how a Compass or Clock is made.  Could require a specific crystal, or be created on an Arcane Workbench.

**Comment by destator** [comment]
This suggestion violates the game balance. These studies should not be too simple.

**Comment by dash16** [comment]
Waiting until nighttime just to see a moon phase seems pretty grindy.  I wouldn't say the studies are overly complicated, just repetitive.  If you need a specific phase for research and you miss it in the cycle, you don't really have a clear way of obtaining the research short of checking every single night, or keeping track of nights some other way.

Let's say I need Waning Gibbous to complete a research option.  I go outside and check the moon, and it's on Waxing Crescent.  Looking at the [wiki](https://minecraft.gamepedia.com/Moon#Phases) entry, I have to wait 4 more nights until Waning Gibbous appears again.  That means keeping track of the day/night cycle for 40 real world minutes at best, assuming I can sleep in a bed to skip the night.  If I lose track or forget, the cycle starts over.

This suggestion simply makes it easier to keep track of the current moon cycle without resorting to calculations taking place outside the game itself.  Build a compass, put it on your hotbar, look at it every once in a while to determine whether the data it displays is relevant.  Would this make research simpler?  Maybe.  More importantly, it makes it less grindy.  I've got a bookshelf full of random pictures of the moon and quadrants of the sky, haphazardly taken whenever I can remember to.  This would free up focus in an intuitive, ingame way.

**Comment by OmegaDragon32** [comment]
@destator after reading this, this dude's got a pretty good idea, but I agree with ya, this outright would unbalance it. So, I'm proposing a "counter-balance". The device will be able to resonate with the moon phase, but it will have to be calibrated quite precisely by using a research note of the corresponding phase, and a "puzzle", I'm thinking similar to TC4-TC5's aspect puzzles. If attuned incorrectly, (changing the recipe dash came up with to include a Morphonic Resonator) the device will malfunction, and have to be repaired to a degree, depending on how badly it was tuned. And no, no solution from one person will work for another, as each phase, i'm thinking can have a randomly generated puzzle. Finally, the reason you'd want to go through this hassle: this device can be used to produce highly accurate research notes that are more beneficial than normal ones. Thank you for your time, if you read all this. :P

**Comment by PassiveBrain** [comment]
@dash16 You don't have to wait for the moon everytime you're trying to get into theory. A little bit of thinking might lead you to that you can study skyes every minecraft day and store these scrolls in chest for future possible needs. Also you can use more than one theory table to ditch some good theory till the right moment you'll get what you need for it 
(I think everyone knows about scrap theory button)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#371
