### ISSUE TITLE
B19: Can not start theory

### ISSUE THREAD

**Issue by destator** [Azanor/thaumcraft-beta#1203]
After up to B19, several theories ended correctly in Research Table, but new ones can not be started (maybe it not the cause of the version, but before (B17) everything was fine). Click on the question mark on the page does not lead to any reaction. "Scrap" does not give anything.

Sorry. I can't upload the screenshot because of the GitHub problem, in multiple browsers :(

**Comment by Azanor** [comment]
Do you have enough ink and paper? Have you tried removing the table and replacing it?
