### ISSUE TITLE
Suggestion for Arcane Bore. More Control?

### ISSUE THREAD

**Issue by Shadowfire86** [Azanor/thaumcraft-beta#1204]
A few things I'd like to be able to do with the arcane bore:

1) adjust the radius it digs through the GUI since the Molten Pick is the only one I know of that gives native clusters?(I think?) 

2)The ability to attach an arcane lamp or something to light up areas it has dug. 

3) some way to improve the dig depth past 48 blocks? I tend to dig like 256 or more block Tunnels and it seems like a waste to only move 48 blocks deep.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#370
