### ISSUE TITLE
[b19] Lumberjack golems cannot pathfind to trees

### ISSUE THREAD

**Issue by Reassembly** [Azanor/thaumcraft-beta#1207]
If a golem (with Breaker and Smart attributes) is in range of a Lumberjack seal, the golem will not chop down any trees in the seal's range if all available trees are more than one block away from where the golem is currently standing.

If the golem is placed, or is pushed, next to a tree, it will immediately center itself over the block it is standing on and begin chopping down all trees within reach of the golem and within the seal's range. However, the golem will not actually _walk up to_ any trees to begin chopping them down. It appears that golems (acting on a Lumberjack seal) can detect trees, but cannot pathfind to them - even if the tree is only two blocks away.

**Comment by Reassembly** [comment]
@Azanor  It wasn't, but I can test that...

- Setting the lumberjacking area to 2 blocks up/down allows Lumberjacking golems to pathfind to non-adjacent trees - but only _after_ the tree has been stripped of leaves up to at least two blocks above ground level. I am using Oak saplings, which can generate trees which have only one block of exposed "trunk" at ground level - these "short trunk" Oaks are not detected/pathfound-to as trees (when non-adjacent) until their leaf blocks two blocks above ground level are removed. (I am using an indoor tree farm, so due to limited vertical clearance, I am growing a higher-than-normal fraction of "short trunk" Oaks.)
- Setting the lumberjacking area to the height of the tree trunk or greater seems to allow Lumberjacking golems to detect non-adjacent tree trunks immediately, regardless of trunk exposure height - but also causes them to attempt to climb to the top of the tree before harvesting it, which undermines the purpose of their Burrowing-enchantment-like effect, and can cause fall damage to the golem when the leaves decay from under them.

**Comment by Azanor** [comment]
With the update to golems in B24 onwards, did this behaviour improve at all?
