### ISSUE TITLE
Thaumcraft 6.1.BETA19 Focus Effect: Break consuming incorrect items

### ISSUE THREAD

**Issue by Catzador** [Azanor/thaumcraft-beta#1208]
When completing Focus Effect: Break, it consumes the first two items in your hotbar, and can be completed even if you do not possess a fortune or silk touch book.

It happened in my main world, and I have not crafted an enchanting table yet. I retried it in a test world and it repeated the same issue
![image](https://user-images.githubusercontent.com/41758049/43282337-d7db7064-90e3-11e8-8d8b-730dfd4e80e2.png)
![image](https://user-images.githubusercontent.com/41758049/43282338-db5c3fd4-90e3-11e8-92e1-7653796461fc.png)
![image](https://user-images.githubusercontent.com/41758049/43282342-e07f32aa-90e3-11e8-8ad4-92b931c9fbed.png)
![image](https://user-images.githubusercontent.com/41758049/43282404-0b35115e-90e4-11e8-8ade-36e2dd13d3e2.png)
The only other mods I have installed are Just Enough Items version 4.11.0.202, Baubles version 1.12-1.5.2, and Xaero's Minimap version 1.15.3

**Comment by enderger** [comment]
This bug ate both my backpack and my /dank/null, both full of resources.
