### ISSUE TITLE
Right-clicking on the Arcane Bore causes a blank screen and crash

### ISSUE THREAD

**Issue by WhisperFire26** [Azanor/thaumcraft-beta#1210]
I am playing BETA 19. I just researched the arcane bore and placed it in the world. Then I right-clicked on the arcane bore and my screen went blank. The game doesn't respond, it is just blank. I put my game into spectator mode and restarted my game, then I completely restarted my computer and it crashed. (Please see attached crash report) I tried to roll back to BETA 17 and got the same result. Ultimately, I had to use a backup of my game to a time before I got the Arcane Bore to try to recover my game.

CRASH REPORT:
[crash-2018-07-26_16.36.09-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2233560/crash-2018-07-26_16.36.09-client.txt)

**Comment by wamc2017** [comment]
> at elucent.blockcraftery.model.BakedModelEditable.func_188616_a

Looks like blockcraftery crashed your game, not Thaumcraft, did the arcane bore try to break a block from blockcraftery?

**Comment by WhisperFire26** [comment]
No I just placed it in the world and right clicked on it to try to change directions. I have removed blockcraftery from the pack to see if this will fix the issue. It had no effect. The screen was still black.

**Comment by F9Alejandro** [comment]
do you have a crash log from after the removal of the blockcraftery mod?

**Comment by WhisperFire26** [comment]
I have a video on documenting the issue. It is about 24 minutes in. https://youtu.be/Nob8xVke7QA

**Comment by Azanor** [comment]
That is extremely strange.
I've made some other bugfixes to the bore in b20. Could you please check if this still happens once it is released?

**Comment by WhisperFire26** [comment]
Sure. I will check the arcane bore when it updates.
