### ISSUE TITLE
[b19] Choked connections on Essentia Buffers are disregarded if Buffers have exactly equal suction

### ISSUE THREAD

**Issue by Reassembly** [Azanor/thaumcraft-beta#1212]
This seems like it'll be a bit tricky to describe in a way that communicates the issue. Please read the description _completely_ before dismissing it as "working as intended". (If this _is_ "working as intended", it's a seemingly bizarre and illogical choice of mechanics.)

Choked connections (red/blue bands) on Essentia Buffers seem to be intended to reduce the suction passed by that Buffer on that side to 1 or 0, allowing Buffers to apply stronger suction in un-choked directions while allowing Essentia to be pulled from choked sides. This can allow, for example, a Buffer with two Bellows (64 suction) to pass Essentia to a Buffer with one Bellows (32 suction), or even zero Bellows (1 suction) if the Buffers are connected directly.

However, choked connections do not appear to function in this way if the two Buffers have _exactly equal_ suction. Choked connections permit Essentia to pass from lower suction to higher suction (no choke needed, but still works with choke), _or_ from higher suction to lower suction (choke needed), but not between equal suction levels.

To illustrate: Consider two directly connected Essentia Buffers, A and B. A has one Bellows (suction 32), and the connection on A's side is choked to 0 (red band) - so A applies no suction in B's direction. Despite having no Bellows directly attached, B can still pull Essentia from A with its measly 1 suction, due to the choked connection. _Adding_ one Bellows to B will _remove_ its ability to pull Essentia from A, despite now having _stronger_ suction than its previous zero-Bellows state. Adding a second Bellows to B will restore its ability to pull Essentia from the choked side of A, just as when B had zero Bellows.

This can lead to some strange behavior, requiring unintuitive and sometimes ugly workarounds. For example, to pass Essentia down a line of several Buffers, with the connections all choked in one direction, consecutive Buffers must always have a different number of Bellows attached to them, such as 1/2/1/2/1/2 or 1/0/1/0/1/0. Connecting the same number of Bellows to any two consecutive Buffers in line will stop the Essentia from flowing into the first buffer with matching suction. As long as the entire line has "mismatched" suction, greater _or_ lesser, Essentia will be able to flow from choked sides into un-choked sides.

**Comment by Azanor** [comment]
This should be solved in B25. There was a bug with buffers pulling stuff they were not supposed to that seemed to cause the behavior above as well.
