### ISSUE TITLE
[B19] Caster Gauntlet, Foci, and Enchanted Pickaxe disappeared

### ISSUE THREAD

**Issue by TinyKawaiiSatan** [Azanor/thaumcraft-beta#1216]
Logged out and had all these items in my inventory, plus more, but when I logged in the next day my foci, gauntlet, and pickaxe were gone. I checked all the chests, checked the empty spaces by clicking on them, made sure they weren't on the ground somewhere nearby and couldn't find them.  
I remade them and a few days later the same thing happened to more of my foci, my new gauntlets, and my new pickaxe.

**Comment by nickcool9999** [comment]
This seems related to my issue affecting the same items, duly noted.

**Comment by SancaVIP** [comment]
U research Focus:Break?

See that post: https://github.com/Azanor/thaumcraft-beta/issues/1234

**Comment by TinyKawaiiSatan** [comment]
@SancaVIP  I did not. As I said, all of the listed items were in my inventory before logging out and as soon as I logged in the next day they were all gone. 
I hadn't done anything but log in.

**Comment by Azanor** [comment]
I could not replicate this issue, nor dit anyone else report something like this. Closing it for now.
