### ISSUE TITLE
Eldricht page Bug - Thaumcraft Beta 17

### ISSUE THREAD

**Issue by DJciurman** [Azanor/thaumcraft-beta#1217]
![2018-07-28_10 03 28](https://user-images.githubusercontent.com/41820013/43354596-65abdce6-924f-11e8-9ab6-f52b982ba1fb.png)
![2018-07-28_10 03 48](https://user-images.githubusercontent.com/41820013/43354597-65ffc87e-924f-11e8-8abf-9e0a5353812f.png)
When I use Thauminomicon with all research I have this problem, can you help me?

**Comment by wamc2017** [comment]
This is not a bug, in beta 17 the Eldritch stuff wasn't implemented...

**Comment by DJciurman** [comment]
Ok, thx for help
