### ISSUE TITLE
B19 silverwood items causing client crash/ disappeared

### ISSUE THREAD

**Issue by netish** [Azanor/thaumcraft-beta#1222]
Minecraft loads both server side and client side with no problem. The silverwood logs are fine, but when you try to put the logs in the crafting bench, inventory, etc the game crashes straight to the desktop. Furthermore the silverwood items are missing from jei/nei. None of the mods are showing errors either.
Pastebin of crashlog:
[https://pastebin.com/AMwwqTkM](https://pastebin.com/AMwwqTkM)

**Comment by wamc2017** [comment]
You're using version 0.2.3.12 of ctm, which doesn't work with newer forge versions, update to 0.3.2.18

**Comment by netish** [comment]
thanks very much for the prompt reply - I tested this and it worked - no more crash and the items are showing up in the jei/nei again!
