### ISSUE TITLE
[Suggestion] Stabilizers Suggestion

### ISSUE THREAD

**Issue by osa519** [Azanor/thaumcraft-beta#1223]
Suggestions;
Giving stabilizers ranks similar to the Thaumium Essentia Smeltery
Or,
Have them work like the Levitator with a toggle to increase rf per tick = increasing stabilize per tick.
Or,
Have the stabilizers connectable, Tip -> butt, and the RF will travel through slightly increasing Stabilize per tick per each stabilizers connected.

I have 8, stabilizers, working on 12 around my matrix and I must say, it is quite weird as they have to be in front of each other's LOS.

**Comment by PassiveBrain** [comment]
I've heard that you have to power up stabilisers with vis generators on each side. Haven't tried though.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#369
