### ISSUE TITLE
[Bug] Automatic alchemy

### ISSUE THREAD

**Issue by SancaVIP** [Azanor/thaumcraft-beta#1224]
If u make this machine, and destroy an alchemical construct, this is the drop:

![2018-07-28_14 18 25](https://user-images.githubusercontent.com/41808472/43493564-fb1da9dc-9504-11e8-9f20-f4d7afba07a9.png)

**Comment by F9Alejandro** [comment]
That doesn't help as we don't know what block it is supposed to be. a screen shot of the item name and item id would be lovely.

**Comment by SancaVIP** [comment]
@F9Alejandro 
The item is named "alchemical construct" and u can obtain the item "bugged" destroying a Thaumatorium whit a pickaxe...
![alchemicalconstruct](https://user-images.githubusercontent.com/41808472/43617713-835f1290-969a-11e8-8aec-f5053495de83.png)
