### ISSUE TITLE
[¿Bug?] Infusion altar

### ISSUE THREAD

**Issue by SancaVIP** [Azanor/thaumcraft-beta#1225]
I have 5 stabilizers, 121 candles, 4 heads, and a lot of batterys (to the stabilizers) in a magical forest (All symetrical), and cant make a "moderate" infusion because this EVER become "dangerously unstable" and destroy the items, so many times :c 
PD: The stabilizers need a redstone signal to work the first time (by default this is off the first time, also if there aren't a redstone signal)

![2018-07-30_16 34 08](https://user-images.githubusercontent.com/41808472/43493649-6b2df8ee-9505-11e8-9084-2cf390c1bb59.png)

**Comment by osa519** [comment]
Max candles and heads all together shouldn't be over 12 b19 I believe azanor wanted to make having more a bad thing. IDK if it is actually included in b19.
I have 8 stabilizers and 2 cost blocks =) can only do up to moderate without much issues.

**Comment by Reassembly** [comment]
Individual Vis Generators don't provide much power (compared to RF sources from _any other RF-providing mod_). To fully-power a Stabilizer, you can (and should) attach Vis Generators to all four sides of your Stabilizers, as well as the back.

**Comment by SancaVIP** [comment]
Okey thanks :D
 yep i use now 5 Vis generators to every single stabilizer and i can now make moderate infusions whit 4 cost blocks <3
