### ISSUE TITLE
[Bug] Golemancy's Seals

### ISSUE THREAD

**Issue by SancaVIP** [Azanor/thaumcraft-beta#1226]
I dont know how this work, but it happen every time i try to configure a lot of seals... (Collect, store, empty, harvest)
![2018-07-31_13 57 50](https://user-images.githubusercontent.com/41808472/43493787-287c9766-9506-11e8-98f4-4f0e3bf35ad4.png)

**Comment by Azanor** [comment]
Do you have any inventory 'helper' mods?

**Comment by SancaVIP** [comment]
Nop only thaumcraft, and is a visual bug.. I can take the duplicated items but a few moments later this disappear... The problem is: I can't use or drop any item, but it can be repaired reloading the world... I will try to replicate the bug to find possibles causes
