### ISSUE TITLE
Focus: break research consumes any item, not just ones with the right enchant

### ISSUE THREAD

**Issue by cdfa** [Azanor/thaumcraft-beta#1234]
It says on the research it will consume any item with fortune 1 or silk touch but when viewing the research, it marked those as complete while I didn't have items with those enchant in my inventory. After clicking complete, it consumed the first 2 items in my hotbar, which were a backpack and a iron pickaxe without enchants. Lost those forever... :(

**Comment by SancaVIP** [comment]
OOOHHH So i dont forget where i put my sword and my bow.. xD

X2 same bug
