### ISSUE TITLE
Thaumatorium doesn't work

### ISSUE THREAD

**Issue by vdrake77** [Azanor/thaumcraft-beta#1239]
Thaumcraft beta 20

Forge 2746

The new thaumatorium GUI looks great, but I can't select anything.  It's like something else is selected and it won't let me un-choose it.

I get the little buzzing sound when I click something, but no essentia is drawn and it never highlights.

**Comment by mconwa01** [comment]
I have the same issue when connected to a remote dedicated server (not in singleplayer). Thaumatoria created and configured in BETA19 or earlier retain their configuration, and previously configured recipes continue to work, but I'm unable to select new recipes or deselect old ones; the sound plays but nothing changes.

Thaumcraft 6.1.BETA20
Forge 14.23.4.2707
(A number of other mods as well; I can list them if necessary.)

**Comment by PassiveBrain** [comment]
B20 same to us two playing on my server. singleplayer working well, but not server. Same not working, only buzzing sound, and can produce only thaumium ingots selected before in B19

**Comment by TheFloydman** [comment]
I can't confirm that things were working before, but I'll add my experience that this is broken in B20 on our server.
