### ISSUE TITLE
Thaumatorium not forming.

### ISSUE THREAD

**Issue by VT-14** [Azanor/thaumcraft-beta#124]
I am unable to form the Thaumatorium.  I have changed the block placement order, the heat source, and whether the Crucible has water in it or not.  I have also attempted to right click it with various items ranging from an empty hand, Caster's Gauntlet, Thaumometer, Thaumonomicon, etc.

I have both naturally unlocked the research on a survival world, and unlocked all research via commands on a creative test world.  The attached picture is from a test world where the only mods are Forge, Thaumcraft, and Baubles.

![2018-01-26_15 54 37](https://user-images.githubusercontent.com/12564251/35460479-2ce004a0-02b2-11e8-88fa-8fee74f7ac43.png)

![2018-01-26_15 54 44](https://user-images.githubusercontent.com/12564251/35460526-54ee4c18-02b2-11e8-976b-5a61f1c337f9.png)

Temporary workaround: Spawning the completed structure in using JEI appears to work in a test world.

Thaumcraft 6 Beta 3 (also observed in Beta 2)
Forge 12.18.3.2511
Baubles 1.3.13

FML Log: https://gist.github.com/VT-14/0c7231dffd7baee81541f55ef6f282fa

Manual Debug Crash Log: https://gist.github.com/VT-14/2cce0356918caf9a43d1457c63fb03cf

**Comment by groting** [comment]
Salis Mundus?

**Comment by VT-14** [comment]
Salis Mundus is exactly what I was missing.  Thanks.
