### ISSUE TITLE
thaumometer getting stuck in wall

### ISSUE THREAD

**Issue by theduke101** [Azanor/thaumcraft-beta#1242]
Using FTB revelations 2.3 Reported issue there as well. When clicking on a drying rack my thaumometer dissapears from inventory and gets stuck in the air below the the drying rack. Happened in survival and then twice in creative mode.
![2018-08-04_14 01 18](https://user-images.githubusercontent.com/42106175/43682564-1575ea38-983e-11e8-86e9-f5cb5aabb632.png)

**Comment by Azanor** [comment]
That would be an issue with the drying rack.
