### ISSUE TITLE
Aspects not visible in Applied Energistics ME System [Beta 19]

### ISSUE THREAD

**Issue by Sora-Canstavia** [Azanor/thaumcraft-beta#1244]
Been using Thaumcraft since I Found it was available for 1.12.2 and have just made an ME System on my server to put all my stuff in and noticed that aspects icons on items don't display while they're in the ME System, the tooltip extends like it should to display where the aspects should be, but just displays blank space. Works fine outside of the system, wasn't sure whether to post it here or over on AE2, figured since it's the aspects it should be here? 
![screenshot_1](https://user-images.githubusercontent.com/28876886/43688739-8ffcefec-98e6-11e8-91ee-d52185318a67.png)
![screenshot_2](https://user-images.githubusercontent.com/28876886/43688740-90163132-98e6-11e8-8405-0e58a71b20d9.png)

**Comment by nern9** [comment]
I also have noticed this issue. Is there any word on a fix?

**Comment by Azanor** [comment]
This isn't something that will be easily fixable from my side.
