### ISSUE TITLE
Client crash with java.lang.ArrayIndexOutOfBoundsException: -1 [Beta 17]

### ISSUE THREAD

**Issue by flanigomik** [Azanor/thaumcraft-beta#1245]
i and my friends are playing FTB Revilation 2.3 (current) on a server which currently uses Beta 17 of thaumcraft. i intentionally burned a few stacks of high Vis items so as to start up a taint infection in the area. just passing by nothing happens but when players AFK in the area minecraft crashes to desktop with the following crash report

[crash-2018-08-05_11.22.03-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2260615/crash-2018-08-05_11.22.03-client.txt)

there are a few active taint seeds and warp rifts about with two seperate infection sites from the same cauldron

![2018-08-05_12 06 00](https://user-images.githubusercontent.com/35189361/43689014-5ed70b16-98a8-11e8-89c4-4ef7b453f5a5.png)

we also had the server itself crash once while a player was AFK in this area, that particular crash only occured after three hours, the player was the only one online at the time, the client crashes have been observed between 20 minutes and 5 hours.

[crash-2018-08-05_02.49.09-server.txt](https://github.com/Azanor/thaumcraft-beta/files/2260618/crash-2018-08-05_02.49.09-server.txt)

if a never version of the mod has already corrected this please advise myself so i can update my server and the FTB team so they can update their pack

**Comment by Azanor** [comment]
Update to the latest version of TC
