### ISSUE TITLE
Focal Manipulator GUI bug

### ISSUE THREAD

**Issue by everydayidocoke** [Azanor/thaumcraft-beta#1247]
![2018-08-06_02 20 33](https://user-images.githubusercontent.com/42124676/43691102-622240ca-991f-11e8-8e09-95a5357b0c95.png)
That is how my Focal Manipulator looks like. I was playing with BETA-19, updated it to BETA-20 but the problem didnt get fixed. I didnt find anyone with this type of Issue so i think that i could be connected with another mod, if you know what could cause it - answer please

**Comment by RareKiwi** [comment]
For future reference this is caused by legacy textures in the faithful modded texture pack. Delete resourcepacks\Faithful32_MC#_v#.zip\assets\thaumcraft\textures\gui\gui_wandtable.png from your resourcepack.
