### ISSUE TITLE
Description of Sanity Soap seems off [B20]

### ISSUE THREAD

**Issue by dcgaines** [Azanor/thaumcraft-beta#1249]
Just installed Beta 20 (going great so far) but the Thauminonicon entry for Sanity Soap seems a bit off to me. It says "When used it has a small chance of reducing non-permanent warp and will remove all temporary warp." Should it be "small chance of reducing permanent warp"? I'm new to Thaumcraft so I could be wrong, but non-permanent and temporary sound like the same thing to me.

**Comment by Riyshn** [comment]
There's 3 types of Warp;

Temporary: Decreases slowly over time. Is cleared by Sanity Soap.
Regular: Does not decrease over time, but can be reduced by Sanity Soap.
Permanent: As the name says; there is no legit way to remove it.
