### ISSUE TITLE
Salis Mundus Doesn't Work On Server

### ISSUE THREAD

**Issue by kurtawirth** [Azanor/thaumcraft-beta#1257]
I am running a large modpack on a server and Salis Mundus isn't working on the server (BETA-19). While I would just give myself the objects required, the research can't unlock unless the Salis Mundus is working. Any ideas?

Edit: The mod works fine on single player, just not on the server.

**Comment by kurtawirth** [comment]
FYI - I've gathered crystals, slept, got the book of strange dreams, etc. I then create Salis Mundus, use it on a bookshelf, and it does nothing other than producing the sound and visual effects it's supposed to when creating a Thauminomicon.

**Comment by wamc2017** [comment]
Have you tried beta20? Are you using other mods? Is your server running sponge? Could you provide logfiles from the server and client?

**Comment by kurtawirth** [comment]
I have a modpack provided by a server company so I'm not sure how to update it on my end to 20. The server is running sponge now, I believe, as the helpdesk folks installed it. Log file from today attached!
[2018-08-07-1.log.gz](https://github.com/Azanor/thaumcraft-beta/files/2267693/2018-08-07-1.log.gz)

**Comment by wamc2017** [comment]
Hmm, can't reproduce this on a freshly installed sponge server with only Thaumcraft (tried beta 19+20), Baubles and JEI, maybe Azanor can help here, but it may be some compatibility issue with another mod...

**Comment by kurtawirth** [comment]
I'm really grateful for you spending the time to do that. It might be, I just don't know what could be causing it. I *love* Thaumcraft and really want to dig into it with my friends.

**Comment by Nuclearfarts** [comment]
Does the italicized blue text in WALIA when you look at the bookshelf say "Minecraft" or something else? I don't know how it is now, but mods used to override vanilla blocks and cause this sort of problem sometimes.

**Comment by kurtawirth** [comment]
Nuclear - you are a genius. The game was overlapping the definition of the bookshelf with another mod. I used another type of bookshelf (Maple) and it worked just fine. THANK YOU! :)

**Comment by Nuclearfarts** [comment]
That's REALLY weird, since maple wood isn't vanilla.

**Comment by kurtawirth** [comment]
Right? I guess the mods talk with one another but the one overlapping with
the vanilla crafting table was confusing Thaumcraft. *Shrug*

**Comment by Nuclearfarts** [comment]
Wonder what's doing it? Probably one of the countless aesthetic mods. What mods are you using (if you're using a pack, what pack)?

**Comment by enderger** [comment]
To “restart the game”, close and reopen the server

**Comment by kurtawirth** [comment]
That hadn't worked (the server closing) but using another crafting table
did. Is there an easy way to get a list of the installed mods? We have 131,
I believe. Would it be in the server files or something?

**Comment by enderger** [comment]
I believe that the mods are in the mods folder in the server files

**Comment by enderger** [comment]
Or esc then mod options in one of the connected clients.

**Comment by kurtawirth** [comment]
I know where the mods are but I don't know how to easily find a list. I put
one together below, with supporting necessary mods mostly not included:

-Galacticraft 4:
https://wiki.micdoodle8.com/wiki/Galacticraft_4#Download_Galacticraft
-Thaumcraft: https://www.curseforge.com/minecraft/mc-mods/thaumcraft
-LotsOMobs: http://minecraftred.com/lotsomobs-mod/
-Decocraft: http://www.9minecraft.net/decocraft-mod/
-Not Enough Items: http://www.9minecraft.net/not-enough-items/
-Natura: https://minecraft.curseforge.com/projects/natura/files
-Chisel: https://minecraft.curseforge.com/projects/chisel
-Ender IO: https://minecraft.curseforge.com/projects/ender-io/files
-Extra Utilities:
https://minecraft.curseforge.com/projects/extra-utilities/files
-OpenBlocks: https://minecraft.curseforge.com/projects/openblocks/files
-Pam's HarvestCraft:
https://minecraft.curseforge.com/projects/pams-harvestcraft/files
-Bibliocraft: https://minecraft.curseforge.com/projects/bibliocraft/files
-Project Red:
https://minecraft.curseforge.com/projects/project-red-base/files
-Optifine: https://optifine.net/downloads
-MineCraft Comes Alive:
https://minecraft.curseforge.com/projects/minecraft-comes-alive-mca/files
-Draconic Evolution:
https://minecraft.curseforge.com/projects/draconic-evolution/files
-Extra Planets: http://www.9minecraft.net/extra-planets-mod/
-Planet Progression:
https://forum.micdoodle8.com/index.php?threads/1-8-9-1-10-2-1-11-2-1-12-2-planet-progression-updated-16-06-2018.6847/
-Dungeons 2: http://www.9minecraft.net/dungeons-2-mod/
-Customized Dungeon Loot:
https://www.planetminecraft.com/mod/customized-dungeon-loot/
-VanillaFoodPantry: http://minecraftsix.com/vanillafoodpantry-mod/
-FyreCraft: http://minecraftsix.com/fyrecraft-mod/
-Reactioncraft 3: Rebirth:
http://minecraftsix.com/reactioncraft-3-rebirth-mod/
-Advanced Inventory Management:
http://minecraftsix.com/advanced-inventory-management-mod/
-Zoo and Wild Animals Rebuilt:
http://minecraftsix.com/zoo-and-wild-animals-rebuilt-mod/
-Applied Energistics 2:
https://minecraft.curseforge.com/projects/applied-energistics-2/files
-Biomes O' Plenty:
https://minecraft.curseforge.com/projects/biomes-o-plenty/files
-BuildCraft: https://www.mod-buildcraft.com/pages/download.html
-Alternate Terrain Generation:
https://minecraft.curseforge.com/projects/alternate-terrain-generation/files
-CodeChicken Core:
https://minecraft.curseforge.com/projects/codechicken-core-1-8
-CoFH Core: https://minecraft.curseforge.com/projects/cofhcore/files
-Compact Solar Arrays:
https://minecraft.curseforge.com/projects/compact-solars/files
-ComputerCraft:
https://minecraft.curseforge.com/projects/computercraft/files
-More Bees: http://www.mc-mod.net/more-bees-mod/
-Extra Bees:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1284348-1-7-10-1-6-4-forestry-binnies-mods-1-8-0-2-0-dev
-Binnie’s Mods: https://minecraft.curseforge.com/projects/binnies-mods/files
-BuildCraft Factory Module:
http://www.9minecraft.net/buildcraft-factory-module/
-Forge Multipart:
https://minecraft.curseforge.com/projects/forge-multi-part/files
-Hopper Ducts: https://minecraft.curseforge.com/projects/hopper-ducts/files
-IndustrialCraft 2:
https://wiki.industrial-craft.net/index.php?title=Download
-Inventory Tweaks:
https://minecraft.curseforge.com/projects/inventory-tweaks/files
-Iron Chests: https://minecraft.curseforge.com/projects/iron-chests/files
-JABBA: https://minecraft.curseforge.com/projects/jabba/files
-JourneyMap: https://minecraft.curseforge.com/projects/journeymap/files
-Backpacks: https://minecraft.curseforge.com/projects/forge-backpacks/files
-BdLib: https://minecraft.curseforge.com/projects/bdlib/files
-Gendustry: https://minecraft.curseforge.com/projects/gendustry/files
-MobiusCore: https://minecraft.curseforge.com/projects/mobiuscore/files
-MineFactory Reloaded:
https://minecraft.curseforge.com/projects/minefactory-reloaded/files
-MystCraft: https://minecraft.curseforge.com/projects/mystcraft/files
-NEI: https://minecraft.curseforge.com/projects/not-enough-items-1-8/files
-NEI Addons: https://minecraft.curseforge.com/projects/nei-addons/files
-NEI Plugins: https://bitbucket.org/mistaqur/nei_plugins/wiki/Home
-Big Reactors: https://minecraft.curseforge.com/projects/big-reactors/files
-RFTools: https://minecraft.curseforge.com/projects/rftools/files
-OpenMods Lib: https://openmods.info/
-OpenPeripheralAddons:
https://minecraft.curseforge.com/projects/openperipheraladdons/files
-OpenPeripheralCore:
https://minecraft.curseforge.com/projects/openperipheralcore/files
-Energy Converters:
https://minecraft.curseforge.com/projects/energy-converters/files
-PowerCrystalsCore:
https://minecraft.curseforge.com/projects/powercrystalscore/files
-Immersive Railroading:
https://minecraft.curseforge.com/projects/immersive-railroading/files
-ReactorCraft: https://sites.google.com/site/reikasminecraft/reactorcraft
-DragonAPI: https://sites.google.com/site/reikasminecraft/dragonapi
-RemoteIO: https://minecraft.curseforge.com/projects/remote-io/files
-RotaryCraft:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more
-bspkrsCore: https://minecraft.curseforge.com/projects/bspkrscore/files
-ArmorStatusHUD:
https://minecraft.curseforge.com/projects/armorstatushud/files
-StatusEffectHUD:
https://minecraft.curseforge.com/projects/statuseffecthud/files
-Steve’s Carts Reborn:
https://minecraft.curseforge.com/projects/steves-carts-reborn/files
-MalisisSwitches: http://www.9minecraft.net/malisisswitches-mod/
-Thermal Expansion 5:
https://minecraft.curseforge.com/projects/thermalexpansion/files
-Tinkers’ Construct:
https://minecraft.curseforge.com/projects/tinkers-construct/files
-TiC Tooltips: https://minecraft.curseforge.com/projects/tic-tooltips/files
-Tinkers’ Mechworks:
https://minecraft.curseforge.com/projects/tinkers-mechworks/files
-WAILA: https://minecraft.curseforge.com/projects/waila/files
-WR-CBE: http://chickenbones.net/Pages/links.html
-Landlust: http://www.mc-mod.net/landlust-furniture-mod/
-Forestry: https://minecraft.curseforge.com/projects/forestry/files
-Level Up! Reloaded: https://www.curseforge.com/minecraft/mc-mods/level-up
-Tinkers’ Tools Leveling:
https://www.curseforge.com/minecraft/mc-mods/tinkers-tool-leveling
-Storage Drawers:
https://www.curseforge.com/minecraft/mc-mods/storage-drawers
-Baubles: https://www.curseforge.com/minecraft/mc-mods/baubles
-Baubleicious: https://www.curseforge.com/minecraft/mc-mods/baublelicious
-Baubles Stuff: https://www.curseforge.com/minecraft/mc-mods/baubles-stuff
-Thaumic Periphery:
https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery
-Cooking For Blockheads:
https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads
-Botania: https://www.curseforge.com/minecraft/mc-mods/botania
-Advanced Generators:
https://www.curseforge.com/minecraft/mc-mods/advanced-generators
-Farming For Blockheads:
https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads
-Roots: https://www.curseforge.com/minecraft/mc-mods/roots
-RFToolsControl:
https://www.curseforge.com/minecraft/mc-mods/rftools-control
