### ISSUE TITLE
Possible Issue With Mod clashing/World Corruption

### ISSUE THREAD

**Issue by MaatPlays** [Azanor/thaumcraft-beta#1258]
I built my house out of blocks from chisel, after a lot of mining and such I logged off for the night & looked at my world again and it wasn't there. Figured out that it was corrupted, fixed it & now this happened when there was none of this before, & the building I made my hut out of was all out of thaumcraft blocks, not sure if this was from thaumcraft or any other mod. This has also happened with my other world today. I also noticed a bug while I was messing around with thaumcraft alone, the essentia mirror, hand mirror do not have a icon in the thaumonomicon atm. 
BETA-20

Will be attaching files of the house after the corruption/fix and what was new, any help or anything is appreciated. 
![2018-08-07_14 03 58](https://user-images.githubusercontent.com/42189249/43802951-3a3a42a0-9a4c-11e8-92f5-4bc5a5aa6458.png)
![2018-08-07_14 04 03](https://user-images.githubusercontent.com/42189249/43802953-3a5b661a-9a4c-11e8-8417-1a28462d54ff.png)
![2018-08-07_14 03 46](https://user-images.githubusercontent.com/42189249/43802954-3a7d06da-9a4c-11e8-927c-bde299cc8c7a.png)
![2018-08-07_14 03 52](https://user-images.githubusercontent.com/42189249/43802955-3aaeca8a-9a4c-11e8-99b9-b3e5107557aa.png)

Mod List (If its needed):
Advanced Combat
Astral Sorcery
AutoRegLib
BabyMobs
Backpacks (The one we usually use)
Baubles
BetterBedrockGenerator (Flatbedrock)
Bibliocraft
Biomes O Plenty
Botania
Creeper Confetti
cxlibrary (Idk what this is for)
Cyclops Core (Same as above)
Dailies (Bailey's Dailies)
Decocraft (You can take it out if u want xD)
EnderCore/EnderIO
EvilCraft
extrautils2
mrcrayfish's furniture mod
Galacticraft Core/Planets
Hwyla
Inventory Pets
JEI
J-Map
Just enough resources
MicDoodleCore
More-Planets
Optifine E2
PTRLib
Quark
Refined Storage
Reliquary
Roots
SimpleGrinder
Thaumcraft
Thaumcraft JEI
TreeCHopper
Twilight Forest
Veinminer
Wawla
Worldedit

**Comment by MaatPlays** [comment]
1st pic:Gesyers/Blocks were not there to begin with.
2nd pic: The hut was all made of greatwood logs as well as the weird cluster of the logs in the background.
3rd pic:  my house after the corruption

**Comment by F9Alejandro** [comment]
The missing icons is already known as it has to do with something in forge that changed how blocks are displayed or something along those lines. You will notice that the icons (block renders) don't show in creative properly it is just an empty inv space with a name.
