### ISSUE TITLE
Thaumatorium Missing Vis Pattern

### ISSUE THREAD

**Issue by msrnk044** [Azanor/thaumcraft-beta#1260]
So when I was researching I needed a Spiritus Vis Crystal. When I put a quartz shard into the thaumatorium I couldn't find a pattern for Spiritus. I'm not sure if this is intentional or if there are others that are missing as well. Just thought I would mention it. This is in B20 by the way.

**Comment by davue** [comment]
Just double checked it.
Seems like only the pattern for the Spiritus Vis Crystal is missing.

**Comment by Reassembly** [comment]
I just checked mine - I have a Spiritus crystal recipe in my Thaumatorium (near the end of the list).

It doesn't help that the list of Vis Crystal recipes in the Thaumatorium are in nothing resembling a sensible order, alphabetical or otherwise, making it quite annoying to try to scroll through the list hunting for the type you want, guided only by approximate essentia color (if you happen to know it).

**Comment by msrnk044** [comment]
was that in B20? I noticed a new beta just came out a today and haven't checked it yet.

**Comment by Reassembly** [comment]
My mistake - I was running b21 when I checked that. Try upgrading, and see if the pattern for Spiritus Crystals appears in your Thaumatorium. If it still doesn't, then further investigation will be needed.

**Comment by msrnk044** [comment]
So I updated to the new beta and spiritus is still missing. Only 26 of the 27 aspects show up as vis patterns. I even broke my thaumatorium and rebuilt it to see if that changed anything. I'm curious why it is showing up for you and not me. I'm not running any mods and I'm not on a server. I don't know a thing about programming so that might not even matter.

**Comment by Reassembly** [comment]
Okay, that's even weirder. I'm also not on a server, but I am running several mods other than Thaumcraft - if anything, that should give _me_ problems, not _you._

Bit of a Hail Mary, but have you actually _scanned_ anything containing Spiritus with your Thaumometer? I don't know if that's even a Thaumcraft game mechanic, but it's _possible_ that the Thaumatorium only shows recipe types for Essentia you've scanned, and Spiritus is one of the slightly-less-common varieties.

**Comment by msrnk044** [comment]
Tried out what you suggested. Still nothing; the only thing I can think of is that it is a glitch from an older beta that didn't clear as I updated to newer betas. Really weird! I mean the game allows me to make the crystals in a regular crucible but it's much easier to do it with the Thaumatorium.

**Comment by Azanor** [comment]
This is very strange. Not sure what could be causing that.

**Comment by Azanor** [comment]
I finally tracked down this error. It seems spiritus was last on the list of crystal recipes and the gui was losing the last recipe in certain circumstances.
