### ISSUE TITLE
Thaumatorium not working on server

### ISSUE THREAD

**Issue by UxiT** [Azanor/thaumcraft-beta#1262]
I made a thaumatoriam, added Nitor as heat source and when i put catalisator and click on recepies nothing happening. Just sound and nothing else

**Comment by wamc2017** [comment]
Dupe of #1239

**Comment by UxiT** [comment]
Does fix of this issue exist? Or what i have to do to fix that?

**Comment by davue** [comment]
Wait until B21 gets released
