### ISSUE TITLE
[B20] Flux Condenser works with a clogged lattice & comment

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1267]
The Flux Condenser with a single lattice will work regardless of weither it is clogged or not. A single clogged lattice will also see the same speed on the condenser as an unclogged one.
I don't know weither this is intentional, but the Thaumonomicon suggests otherwise. For now it is pretty handy for say, keeping the flux at bay in your herba production facility, giving you the ability to set up a flux neutral automated essentia production without having to set up a gold farm.

I really like the fluxiness of the game right now, and I don't want to argue for an easy system to clean up flux, but I don't much like the condenser. It mostly feels like an extra tax on essentia smelting (i.e. a thaumium essentia smelter with 3 vents will have a chance of about 3% to create flux (if you are cheeky and get it up to 4 vents by breaking the essentia smelter and placing it back down in a different rotation, you can get it down to 2%, just nesting a little bug report :D). This means on average smelting 100 points of essentia will create 3 points of flux while giving you 90 points of essentia, of which you'd have to use up at least 30 to clean up the mess you've made, giving you an additional 33% decrease in essentia yield.
Now while this is an okay deal for automating stuff, I find it rather boring to set up this somewhat more involved thing that is essentially just a beefed up flux vent.

Maybe if unclogged lattices were required handling the automation of the now required cleaning would put some more fun into setting this up, but as of now that does require gold and I just go "eugh" in my head at the thought of <having> to set up a gold farm just because I want my potato farm go faster.
Maybe allow just cleaning it with water bottles or crafting a clogged lattice with a water bucket, creating some thaumic slime instead of a vitium crystal or something.

Or maybe have the condenser require specific essentia to work, like ignis, aqua or gelum (or any combination of those, seeing that it has 4 side inputs, it could well support different suction types)

I don't know, I don't have any good ideas in this heat and maybe I'm just being cranky over nothing and I apologize. It's too warm. :c

**Comment by Ulysses2** [comment]
I believe the condenser is intended to be a sink for "junk" essentia. People were asking for a way to use their excess terra/herba/etc. If you intend to use all the essentia you produce, the smelter becomes a lot less appealing, but it does at least provide a way to safely automate production.

**Comment by Reassembly** [comment]
Flux condenser lattices seem to need a rebalance. The intent appears to be that adding more elements to a lattice would produce a trade-off between speed and efficiency, and that the geometry of the lattice (straight line vs. branched network) is a significant factor in that trade-off. In practice, the increase in flux cleanup speed from additional elements is _miniscule_ compared to the increased essentia costs for additional lattice elements. These increased costs can also quickly approach the point of consuming 100% or more of the essentia smelted to clean up the flux from smelting that very essentia, depending on how hard you cheese the flux vents (or not). The most efficient setup for flux condensers (maximizing both speed and efficiency) appears to be not one condenser with an array of lattice elements, but an array of condensers with one or two lattice elements each, rendering lattice geometry irrelevant.

**Comment by Azanor** [comment]
Hmmm, you guys make some good points. Honestly I am not happy with flux condensers either.

**Comment by Azanor** [comment]
I am fixing the bug listed above, but would one of you mind creating a suggestion post on this issue with your thoughts?
