### ISSUE TITLE
Runic Matrix provides cards for Artifice instead of Infusion when used as research aid

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#1269]

**Comment by F9Alejandro** [comment]
Give examples please, and steps on how to recreate it. It is difficult to fix if there is nothing provided that can reproduce effectively.

**Comment by Ulysses2** [comment]
1. Place matrix near research table.
2. Select it as a research aid.
3. Research. You will get more Artifice cards than usual, and they will have a gold border that indicates that they were given because of your research aid.

**Comment by F9Alejandro** [comment]
It might be intended or a config was changed. @Azanor will be the one to say if this is intended or not.

**Comment by esotericist** [comment]
Considering the Enchanting Table counts as an Infusion research aid, it seems to be intentional.

**Comment by Azanor** [comment]
Nope, that is not intended.
