### ISSUE TITLE
Flux Rifts crash

### ISSUE THREAD

**Issue by tyler489** [Azanor/thaumcraft-beta#1271]
I saw that flux rifts when overlaping have an interesting texture.. i went into my test world and /summoned one and the game crashed https://pastebin.com/0hG0X7Qw.
im guessing this is because it has no entity data?

**Comment by F9Alejandro** [comment]
It isn't there for you to summon in, you have to create it via flux increase. @Azanor has already mentioned this in a different issue stating the summon command for it shouldn't be used.

**Comment by Ulysses2** [comment]
I believe this issue has been reported before and was fixed. Are you on the latest version?

**Comment by tyler489** [comment]
Nope... apparently i missed an update
