### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ResponsibleBear** [Azanor/thaumcraft-beta#1274]
Hello, when i break a void siphon, server will crash.
Crash-report here: https://pastebin.com/5u2sByi7
Thaumcraft-1.12.2-6.1.BETA21

**Comment by Nuclearfarts** [comment]
Try breaking the stabilizers first.

**Comment by davue** [comment]
At this point I can't anymore.
The server crashes as soon as I connect and the blocks get loaded.
I guess I'll have to remove the Stabilizers and Void Siphon via an external world editor to be able to play again.
