### ISSUE TITLE
Crucible not accepting items after water refill BETA2

### ISSUE THREAD

**Issue by XoviaHarmile** [Azanor/thaumcraft-beta#128]
When the crucible has had it's water use up and is then refilled, adding another item does not work until one of the aspects already in there has been used up by one.

**Comment by Azanor** [comment]
Are you sure you didn't just have to wait for the water to boil again?

**Comment by XoviaHarmile** [comment]
Well I'm dumb, should I get delete the issue or leave it for when someone else makes the same mistake?
