### ISSUE TITLE
Crash with Mystcraft Tooltips

### ISSUE THREAD

**Issue by TheFloydman** [Azanor/thaumcraft-beta#1282]
Mystcraft has several custom GUIs, and when you press shift while displaying a tooltip in them, the game crashes if Thaumcraft is also installed. (Crash log here: https://pastebin.com/kTue5K2Y) I don't know if this is a Thaumcraft issue or a Mystcraft issue or both, so I'm bringing it up here.

Here is the same issue posted on the Mystcraft issue tracker: https://github.com/XCompWiz/Mystcraft-Issues/issues/301

**Comment by Azanor** [comment]
I suspect the itemstack passed in the event from Mystcraft is null which is bad for a few reasons. I added a null check just in case, but it should probably not be happening.
