### ISSUE TITLE
Iron Nuggets Don't Work

### ISSUE THREAD

**Issue by KittenKoder** [Azanor/thaumcraft-beta#1284]
Because of the vanilla iron nuggets, the mod requires using another mod to alter the iron nuggets you get from crafting. This mod either needs a special recipe or use the oredict Forge implemented just to avoid this problem.

**Comment by Azanor** [comment]
It should be impossible to obtain the TC version of iron nuggets at the moment. What is giving you iron nuggets?
I will however add a recipe to turn them into normal nuggets.
