### ISSUE TITLE
[B21] Possible Dupe Bug with Anvil and Primoridial Pearl

### ISSUE THREAD

**Issue by Xobra** [Azanor/thaumcraft-beta#1293]
Insert an enchantable item in the left spot of the anvil, an enchanted Book on the right, swap the left item with the Primordial Pearl, and you can craft the enchanted Item with the Pearl (Pearl is consumed).
[Imgur](https://imgur.com/a/ZPEZn2N)

**Comment by F9Alejandro** [comment]
How did you switch the items? (shift click sword out and placed pearl in it, click sword out and shift click the pearl in, use number keys to take sword out and shift click pearl, etc.)

**Comment by Xobra** [comment]
left click on the pearl and then left click on sword, while it is in the anvil with an enchanted book. place the sword anywhere in the inventory, and then left click on the enchanted sword in the anvil

**Comment by Azanor** [comment]
Unfortunately this would be a vanilla bug and probably works with a lot of other damageable items. There is nothing particularly special about the pearl that would be causing this.

**Comment by Ulysses2** [comment]
It doesn't happen for any vanilla items as far as I can tell, only the pearl. You must be doing something wierd with the anvil - I can't enchant one in creative, even though that overrides the usual restrictions on enchantments for items and lets you enchant whatever you want (though not conflicting enchants like silk touch and fortune or infinity and mending)

**Comment by DoomRater** [comment]
There is absolutely something going on with the pearl in the anvil.  Using PiTweaks, a mod that allows me to apply EVERY enchantment to any item, I cannot apply anything other than Unbreaking 1, unbreaking 2, or unbreaking 3 to the Pearl.  Clearly there is special handling going on to ensure someone sneaky doesn't add Mending to a pearl.
