### ISSUE TITLE
[¿Bug?] Tainted animals and spiders

### ISSUE THREAD

**Issue by SancaVIP** [Azanor/thaumcraft-beta#1297]
The tainted animals and these invisible spiders dont cause damage, but still try to hurt me

PD: Invisible spiders make transparents blocks invisibles too..

![2018-08-12_13 19 17](https://user-images.githubusercontent.com/41808472/44006613-9a7221dc-9e5d-11e8-9882-345de48c2e64.png)
![2018-08-12_18 06 14](https://user-images.githubusercontent.com/41808472/44006615-a1814426-9e5d-11e8-8255-fbe89ccda3d4.png)

**Comment by PassiveBrain** [comment]
Mind spiders sometimes attacks you and drop exp (cause I on max warp?)

**Comment by Azanor** [comment]
Some of the invisible spiders are not supposed to be able to damage you - they are just figments.
The tainted animals is a different story though.
