### ISSUE TITLE
ice effect bug

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#13]
when using a focus with the ice effect while underwater, the block of ice that form do not melt like the iceblocks that form when you use it on the surface of the water

**Comment by Azanor** [comment]
I believe that is a vanilla thing - I am pretty sure there needs to be air above the block for it to melt. I will look into it - I might prevent the ice from forming without an air block above it.

**Comment by Azanor** [comment]
Actually just went to check and it is based off light levels. I am not going to call this a bug as it falls within the logic of the MC universe.

**Comment by xenxero1** [comment]
Question/suggestion: Couldn't you do something with the frostwalker enchantment for this? Allow ice to check before forming what's above it? If it's air, then it becomes normal ice. else, it becomes frost walker cracked ice.


P.s. How does one get into the beta?

**Comment by Azanor** [comment]
I am actually creating cracked ice, not normal ice.

**Comment by Lgmrszd** [comment]
> I am not going to call this a bug as it falls within the logic of the MC universe.

But this is still an issue. On SMP, players may abuse it, creating large paths of ice in the oceans, which causes server lag.
