### ISSUE TITLE
Suggestion: Focus Part Ideas

### ISSUE THREAD

**Issue by nnystyxx** [Azanor/thaumcraft-beta#130]
I'd like to see expansions upon the modular focus system. Here are some of my ideas and those of the Thaumcraft Discord server. This post may be updated in time to remove any items that are added to the game officially.

**Medium**
_Spray_: Fires lots of little particles/rays in a sustained cone. (May reduce potency but ignore invincibility frames.)
_Beam_: Coalesces the projectile into a beam. Variable range, potentially lessening power over a distance.
_Trap_: Creates a nugget of potential that activates when touched by living creatures, triggering one or multiple uses of the focus. Extend causes it to turn into a faintly visible beam trap, like a tripwire.
_Self_: Applies the focus' on-hit effects directly to the user. Ranges from helpful to very dangerous.

**Effect**
_Wind_: Does little to no inherent damage; heavy knockback. Possibly some vertical lift. Potency increases distance and speed. Lingering applies Levitation as well.
_Shock_: Causes a silencing/paralyzing effect that disables (non-movement?) abilities. Players cannot use items; creepers cannot explode (or are charged); skeletons cannot fire; etc.
_Charm_: Causes enemies to fight each other or the caster's enemies. Lingering increases duration.
_Taint_: Functions as a powerful poison on creatures; corrupts blocks into Tainted versions.
_Mend_: Restores health of the target. Potency increases healing; Lingering applies Regeneration. Hurts undead. 
_Ward_: A la the Warding focus, makes blocks immensely durable. Revoked by a second usage.
_Pull_: Creates a tether between the caster and the target when the projectile or bolt makes contact. Used on a block, it pulls the caster. Used on an enemy, it pulls the enemy to the caster. (Grapple focus!) Potency removes the travel time and mimics an ender pearl, directly warping the user or target to the destination.
_Life_: Turns blocks into temporary, rabid golems.

**Modifier**
_Burst_: Causes an area of effect 'burst'/explosion of the chosen element on impact. Touch allows an AoE cast; projectile creates throwable bombs; etc. 
_Delay_: Ties with Burst; adds a timer to projectiles, such that they wait a while before exploding instead of on impact.
_Extend_: Lengthens the reach of beams, bolts and the like.
_Bounce_: Various effects: beams will ricochet 1-3 times off of surfaces; projectiles will bounce off of walls and possibly enemies before disintegrating.
_Seek_: Causes projectiles to curve towards targets, a la the Primal focus.
_Slow_: Projectiles move much slower, but are more accurate.
_Accelerate_: Projectiles move much faster, but are less accurate.
_Choke_: Tightens the spread of scattered projectiles and sprays.
_Spread_: Expands the spread of scattered projectiles and sprays.
_Pierce_: Projectiles, beams, etc. can go through a small number of enemies and potentially blocks.

**Comment by fingersome** [comment]
I love all of these

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#161
