### ISSUE TITLE
Cloudstepper Ring shouldn't work when underwater

### ISSUE THREAD

**Issue by aaronhowser1** [Azanor/thaumcraft-beta#1303]
When I try to swim up, it flings me up like 3 blocks and then I can't use the Ring when I get out of the water, I think it should disable itself when under water.

**Comment by MalkContent** [comment]
Personally I feel like it should just have a cooldown as an additional reset condition. It would feel pretty "cloud steppy" if you could fall from a great height and jump again multiple times due to the length of the fall.
