### ISSUE TITLE
6.1.BETA21 no such method error on dedicated server running forge b2749

### ISSUE THREAD

**Issue by kreezxil** [Azanor/thaumcraft-beta#1304]
does not happen all the time
Server Crash Report: http://paste.ubuntu.com/p/2RgyWxgWQx/

**Comment by F9Alejandro** [comment]
Try downgrading forge a version or 2 back, it could be something that was changed in the build and was an accident or broke.

**Comment by Azanor** [comment]
Yup, it's not always a good idea to use the cutting edge versions of forge. It often contains changes the mod doesn't yet account for.

**Comment by kreezxil** [comment]
Sorry but I'm one of the people that push cutting edge versions of forge
and grab the latest mod updates that also push for it. I rolled thaumcraft
back and that solved the problem.
