### ISSUE TITLE
Cloudstepper Ring doesn't negate fall damage when you double jump after a fall

### ISSUE THREAD

**Issue by aaronhowser1** [Azanor/thaumcraft-beta#1305]
I just jumped off the giant's cloud in the Twilight Forest and then did the double jump right above the ground, and then after softly landing I died from fall damage. I think that the fall damage should be based on where you double jumped instead of just where you started.

**Comment by Azanor** [comment]
Is this with version b21?

**Comment by aaronhowser1** [comment]
I was on b17 when I submitted the bug, but I just tried it out again on b21 and it still happened. Just made a big tower and jumped off of it, then double jumped again right above the ground and lost 7 hearts.
