### ISSUE TITLE
[System Problem?] When I create/load a file it crashes

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [Azanor/thaumcraft-beta#131]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 18-1-27 ����3:06
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_71312_k
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(SourceFile:74)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(SourceFile:131)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 661980880 bytes (631 MB) / 1064304640 bytes (1015 MB) up to 1073741824 bytes (1024 MB)
	Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@1b4dc28
	LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@18b4706
	LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@89d613
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
	UCHIJA	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UCHIJA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJA	texfix{4.0} [TextureFix] (TexFix+V-1.10.2-4.0.jar) 
	UCHIJA	thaumcraft{6.0.BETA3} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA3.jar) 
	UCHIJA	ThaumicJEI{1.0-SNAPSHOT} [ThaumicJEI] (ThaumicJEI-1.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Goof245** [comment]
Driver issue? Using a 32-bit build of windows XP in 2018 is probably not the greatest for software compatibility either :S

**Comment by Azanor** [comment]
Yeah there are a lot of problems going on:
_"No OpenGL context found in the current thread."_
Either way it is not TC causing the crash - Minecraft itself seems to be crashing.

**Comment by Lazy-Rabbit-2001** [comment]
So can you now make it work on XP, too? @Azanor :)
Thanks and sorry for taging you.
