### ISSUE TITLE
[B22] Infusion Stabilizer energy intake/speed issues, aka supercharging your stabilizer

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1311]
Using The One Probe i noticed that the Infusion Stabilizer's internal energy storage would drop down to 0 a lot and I was worried that I somehow didn't give it enough juice, even though I was supplying more than the required 100 RF/t.
So I added another power connector to another intake to see what would happen.

Long story short: If you supply RF through more than 1 connector, the Infusion stabilizer runs at roughly double the speed, while at the same time not using up more RF to achieve the same task (here: stabilizing a newly placed runic matrix from base stability to very stable, when the Infusion Stabilizer stops working)
Takes about 15 seconds with two connectors in use and 30 seconds with just one.

However, using 5 Vis Generators will also require 30 seconds.

Skimming over the code, I think the issue lies with the refill speed of the Stabilizers internal storage and the way it uses up it's energy.
It has an internal storage of 1000 RF and it will try and use ALL of it every 5 ticks, meaning it potentially uses up 200RF per tick, on average. While the intake is limited to 100RF per tick, that appears to be only per connector, meaning that you can match the 200RF max usage using two connectors.

Just reporting this, because I don't think that it is intentional, looking at the changelog of 6.1.BETA18.

I recommend simply changing
`int m = this.energy / 100;`
to
`int m = min(this.energy, 5*<n>) / 100;`
effectively setting the maximum usage to n RF per tick (n would be 100, but maybe that can be turned into a variable for ease of later adjustment)

If I wrote something unintelligibly, please notify me. I wrote this issue alongside discovering the mechanics and also am feeling a bit daft atm.

**Comment by Azanor** [comment]
Good catch.

**Comment by Azanor** [comment]
Actually, now that I looked at the code and ran some tests to double-check this is not the case. It does indeed as as much RF as it can, and it does consume as much RF as it tried to use. Later in the code the multiplier (m variable) is used to actually consume the RF from the energy store.
One minor issue is that it cannot receive more than 100 RF per side. I am going to up this to 1000 RF, but overall it will still be limited by it's capacity of 1000 RF.

**Comment by MalkContent** [comment]
Will vis generators be able to fully power a stabilizer then?
