### ISSUE TITLE
[Beta 21] Tin ore not producing native tin clusters

### ISSUE THREAD

**Issue by MorzanTLD** [Azanor/thaumcraft-beta#1314]
When using the pickaxe of the core on tin ore it will not drop its native ore cluster. Other ores added by the same mod will drop its native ore cluster equivalent. Furthermore native tin clusters are missing from the metal purification recipe.

**Comment by wamc2017** [comment]
Which mod is adding the tin ore? Have you checked if the ore is registered as oreTin in the oredictionary?

**Comment by MorzanTLD** [comment]
The mod is Embers and I tried to check and I believe it is registered in the oredictionary but I may be mistaken.

**Comment by wamc2017** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/957

That was fixed in Embers Rekindled (which was released yesterday). I guess you've no luck with the old embers, because the ore registration is too late for TC to pick it up...
