### ISSUE TITLE
Perditio Vis Crystal

### ISSUE THREAD

**Issue by doonak** [Azanor/thaumcraft-beta#1316]
Any idea where to look for perditio crystals? Do they spawn is specific biomes? Where do I have highest possibility of finding them?

**Comment by Ulysses2** [comment]
If I remember right they spawn more often in swamps, but that shouldn't be an issue, as long as you keep exploring caves you should be able to find all the primal vis crystals before long.

**Comment by MalkContent** [comment]
This is not a bug, please go to the forums with this or try this unofficial thaumcraft discord: https://discord.gg/Z6XDgH

**Comment by PassiveBrain** [comment]
I think it's random - more caves exploration. Also try Magic Forest biome, crystals may more frequently spawn here, and for more amount for sure
