### ISSUE TITLE
chunk boundaries dont line up - minor off by 1 error

### ISSUE THREAD

**Issue by Azrazal** [Azanor/thaumcraft-beta#1330]
when looking at the vis amounts in current chunk, while holding a thaumometer, it seems to change chunk 1 block off of the chunk boundary. this happens one block early when moving south or east

client info:
Minecraft version: 1.12.2
modpack: Enigmatica 2: Expert Skyblock
Thaumcraft version: 6.1.Beta17

**Comment by Reassembly** [comment]
Duplicate of #1071?

**Comment by Azrazal** [comment]
i tried searching issues with 'chunk' mentioned, didnt see...
only difference between mine and that one, is i saw on both X and Z directions, as that one was one or other. but yes, close enough to duplicate. thank you
