### ISSUE TITLE
[B22]A bug of Unbreaking

### ISSUE THREAD

**Issue by Suigar** [Azanor/thaumcraft-beta#1332]
![lchpdd 6qe vz0 q k37 le](https://user-images.githubusercontent.com/23564874/44306185-2d0ff600-a3bc-11e8-88bb-ed67a9bd9b99.png)

**Comment by Glease** [comment]
I guess you should give more details like how you get this happening, instead of just posting a random image.

**Comment by Azanor** [comment]
I suspect the vanilla MC item destruction code derped up somehow. I added a bit of extra checking on my side just in case.
