### ISSUE TITLE
[B22] Focus Effect: Curse

### ISSUE THREAD

**Issue by lOmicronl** [Azanor/thaumcraft-beta#1333]
Unsure if the following behavior is intended or not:

The Thaumonomicon entry became available for me upon scanning a Pech. However, the entry itself talks about having found and examined a Pech wand. I have not found any such item.

Perhaps the inventory-scanning function is messing with this? If the Pech carried a wand, and I scanned the Pech, would it have scanned the wand as well?

**Comment by Azanor** [comment]
It is indeed supposed to be the pech wand, not the pech itself.
