### ISSUE TITLE
Graphical Bug With Rift Focus

### ISSUE THREAD

**Issue by R0NAM1** [Azanor/thaumcraft-beta#1338]
So it was working fine one day, looking like the Ender portal, when the next day it looks like this: https://imgur.com/gallery/8yiwk7x

A flat, 2d star field,  I do not know if this is because a compatibility issue or a setting set wrong, but here is a mod list: https://imgur.com/gallery/0QiM4JC

Note: I do not believe this is caused by any resource pack due to them all being present when it was working.

**Comment by Azanor** [comment]
I am unable to reproduce this, but I suspect it might be a shader related issue. Do you still have the issue?

**Comment by R0NAM1** [comment]
Since I have updated the mod the issue is no longer present
