### ISSUE TITLE
Add TAB autocomplete support for /thaumcraft command

### ISSUE THREAD

**Issue by Hubry** [Azanor/thaumcraft-beta#1339]
An enhancement suggestion: 
When pressing TAB with any vanilla command, the expected behavior is for a valid argument to be provided, with a list of valid arguments to cycle through - for example, the coordinates of the block the player is looking at, an online player, all block/item/entity registry names matching the current input... 

This is very useful when using commands and the /thaumcraft command does not support it, which means the user has to manually type in every argument, especially when they have to check the console log to find the specific research name.

**Comment by Ulysses2** [comment]
This was a feature in some of the earlier betas, but it got broken at some point, probably during the transition to 1.12.2.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#441
