### ISSUE TITLE
Could we get infusion stabilizers buffed for a version, experimentally?

### ISSUE THREAD

**Issue by lOmicronl** [Azanor/thaumcraft-beta#1342]
It seems like frequently beta versions are the ideal testing ground for such a thing. You could for example up the benefit that each candle provides, as well as the benefit from powered stabilizers per unit of power invested, by a flat 50%. Then see what people say, and how endgame setups change. You can easily roll it back a week later if it turns out that it makes things too easy.

Though with some of the screenshots I have seen of the ridiculous setups people have been building, I have a hunch that it it'll be more likely welcomed than shunned... ;)

**Comment by TechnoTadhg** [comment]
I believe it was mentioned that they're being buffed at some point, well more of a bugfix that leads to a buff. I believe it was allowing them to take in more RF/t
Hopefully, this just makes them more useful at the cost of more RF required, which is what I hope.

**Comment by lOmicronl** [comment]
That wouldn't really change anything, because even right now, the powered stabilizers are limited by the amount of thaumic generators you can connect. You can feed them only half as much as they can consume, even if you utilize all five connections (or so I have read).

And yes: perhaps if you can use cables and generators from other mods, you can power them better. But, Thaumcraft is not an addon to EnderIO or Thermal Expansion. Thaumcraft is a stand-alone mod. Therefore, it needs to be viable completely on its own. And further increasing the power throughput merely results in Thaumcraft becoming _less_ viable on its own, because the mod would clearly be designed with third party power generation in mind.

I'd much rather have a situation where Thaumcraft's own generators can max out the powered stabilizers, and a reasonable number of stabilizers in turn is able to stabilize every infusion recipe. What that reasonable number is, that's up for discussion and testing. Right now I believe that number is somewhere north of 20 (stabilizers, not generators), and that is really not reasonable. It results in ugly setups that are a drudgery to farm ingredients for.

In an ideal world, we would not have to stack stabilizers in a row at all, and wouldn't be able to fire them through blocks either. But right now, that would limit you to five stabilizers, which may or may not be too low a number for Azanor's tastes. Perhaps if we could point diagonally, or even more freeform - like signs in vanilla. That would allow us to build setups that have large amounts of stabilizers without looking stupid. But then of course the connections to neighboring generators wouldn't work out.

Another idea might be reflectors. You could bounce around and combine the beams of various stabilizers before shunting the beam towards the infusion matrix. That, too, would result in awesome-looking setups... but, as a downside, it requires asset-making work, and a big change to how the stabilizers currently work.

None of this is the point of the thread, anyway. The point is to try and figure out where that "reasonable number of stabilizers" lies for most people. What feels both somewhat challenging yet also achievable; what results in a decent, steady progression from one difficulty tier to the next (which right now honestly feels like a sheer cliff - even getting "Minor" stable takes resource farming effort). And it should be examined not only with third-party mods in mind, but also for Thaumcraft on its own.

**Comment by TechnoTadhg** [comment]
I think one simple change would be a method to fuel the generators with essentia, to increase their generation. Or a form of energy pipe within the mod.
I'd love energy cables that were in the thaumcraft style rather than the bright blue Integrated Dynamics ones I use atm.
I think in general we need more methods to reduce instability, Stabilizers are nicer than arranging candles, but I think some other methods would always be nice, 3 or 4 options ideally.
And the idea of bouncing beams is super neat too, although the angled option sounds much more easy to implement in comparison, something like mana spreaders from Botania.

**Comment by Azanor** [comment]
They are already getting a buff in the next version (b23)
