### ISSUE TITLE
Crash with Silverwood Planks

### ISSUE THREAD

**Issue by SrUca** [Azanor/thaumcraft-beta#1346]
When they appears in my inventory or when i'm looking for them in creative and in Jei (Just enough itens), the game crashed

**Comment by wamc2017** [comment]
Maybe a dupe of #1222

Without any log files, it's hard to say what's crashing. There should be a crash-reports folder, search for the latest crash, post it on gist or pastebin and link the report here...

**Comment by SrUca** [comment]
I solved it

It was the Connected Textures mod

But thank you all

**Comment by yunruiwatts** [comment]
@SrUca I'm glad you were able to solve your problem. Would you mind closing this issue? Besides closing an issue that you open yourself, I think Azanor is the only one who can close issues, so you can save him a minutes or two of having to look at this (already resolved) issue.
