### ISSUE TITLE
[Beta 22] having various Metal clusters w/o having ingots registered

### ISSUE THREAD

**Issue by PokeMaserJ** [Azanor/thaumcraft-beta#1349]
Not sure how long this is been happening, but Thaumcraft adds Copper, Tin, Silver, and Lead Clusters even w/o mods that add those ingots. That causes at least Mekanism, Magic Bees, and Binnie's Bees to have content related to those metals. Mekanism doesn't have a problem with Copper or Tin, since they have their own Copper and Tin Ingots, but Lead and Silver don't have any ingots with these mods.

**Comment by TechnoTadhg** [comment]
So Mekanism tries to use silver and lead even though no mod generates it?

**Comment by PokeMaserJ** [comment]
It's more Thaumcraft adds the clusters w/o any mod that adds ingots.

**Comment by TechnoTadhg** [comment]
Yea but what difference does it make? If they're unobtainable and have no use there's no problem leaving it.

**Comment by PokeMaserJ** [comment]
If I had to guess, these mods see that Thaumcraft has Lead Clusters, so they assume that there is Lead Ingots, so they load their features that use Lead.

**Comment by wamc2017** [comment]
I don't think the clusters are the problem, Thaumcraft also adds nuggets.
MagicBees checks if "nuggetMetalname" is initialized, but not if "blockMetalname" is. TC could maybe add a check to not register the nuggets if the metal is not present, but any other mod which only adds nuggets but no blocks could break MagicBees as well...

**Comment by Azanor** [comment]
There won't be a simple way for me to disable specific nuggets in their current implementation. Not without breaking everyone's saves. 
MagicBees should maybe check more than just nuggets in their code - it isn't too unreasonable to do.

**Comment by PokeMaserJ** [comment]
Ok then, reporting to Magic Bees, thanks Azanor for checking it out
