### ISSUE TITLE
Crash on making first thaumonomicon

### ISSUE THREAD

**Issue by sleurk** [Azanor/thaumcraft-beta#135]
[crash report](https://pastebin.com/hX6b4w9v)
I was messing around in Creative trying to figure out TC6, and when I used salis mundis on a bookshelf it started the visual effects for a second and then crashed.
I'm using a modpack that I just threw together in an hour so it's very possible it's a conflict with another mod.

**Comment by MrNinja93** [comment]
Caused by having [Oops](https://minecraft.curseforge.com/projects/oops) installed, Seems the mod doesn't like the way thaumcraft swaps the bookshelf out for the book.

**Comment by Azanor** [comment]
Not really my fault then - there are many ways to place blocks in the world and it looks like the mod is assuming they will all be players with hands. :3
