### ISSUE TITLE
[Suggestion] Modded Automaton Scanning

### ISSUE THREAD

**Issue by drakray** [Azanor/thaumcraft-beta#1356]
Could there be a config to allow for scanning of modded Automaton, namely from [Extra Golem](https://minecraft.curseforge.com/projects/extra-golems)?

Or maybe a handler to allow mod (hint hint ModTweaker) for specific adding of entities as Automaton?

Thanks for your time :)

**Comment by Glease** [comment]
https://github.com/Azanor/thaumcraft-api/blob/master/research/ScanEntity.java There you go. You just need to call `ScanningManager.addScannableThing(new ScanEntity("f_golem", GolemBase.class, true))` at init stage, which, IIRC, is when MT runs its scripts.

However, there seems to be no MT compatibility layer yet :P

**Comment by Azanor** [comment]
Yeah, if the author of that mod wants to add compatibility they are welcome to by using the api.

**Comment by drakray** [comment]
Thanks, just a quick question: will this ADD a thing to scan to complete research, on top of Vanilla Iron Golem, or will this allow to scan either Vanilla' OR Mod's Golem to complete? Or will it replace Iron Golem completely?

**Comment by Glease** [comment]
Either.
