### ISSUE TITLE
[B23] silverwood sappling breaking unbreakable blocks

### ISSUE THREAD

**Issue by LemADEC** [Azanor/thaumcraft-beta#1361]
As of 1.12.2-6.1.BETA23, players can place silverwood sappling to break into protected blocks and area, notably tombstones or bedrock.
From a quick test with bedrock, sappling growth only check for blocks right above, not on a side or below.

**Comment by TechnoTadhg** [comment]
Yea it's like the Dark Oak bug but much more consistent, due to the lack of shape variants.
