### ISSUE TITLE
[B23]Workbench Charger slowing Focal Manipulator

### ISSUE THREAD

**Issue by Xobra** [Azanor/thaumcraft-beta#1362]
If I put the Workbench Charger above the Focal Manipulator, the rate, at which the Vis is drawn form the Aura, is reduced to 3 Vis per Second, without it, the rate is at 20 Vis per Second.

**Comment by Azanor** [comment]
I cannot duplicate this - in all my tests things work fine, but after taking a look at the code I noticed that if only one or two of the surrounding chunks contain vis then the drain will be a lot less. Maybe that was what you were experiencing?

**Comment by Xobra** [comment]
Looking at the surrounding chunks, most of them are indeed depleted. Only about 3 had Vis in them

**Comment by omegasigma529** [comment]
I had the same issue. The chunk that the Focal Manipulator was in and one other chunk near it were the only ones that had vis in them and seemed to have gotten slower the further along it was in the craft. When it finally hit 0 via left in the craft, it just hung there and wouldn't compete until I removed the charger.
