### ISSUE TITLE
Unable to join server due to Thaum-related error

### ISSUE THREAD

**Issue by DragaoNimhe** [Azanor/thaumcraft-beta#1364]
I will attempt to include as much information as possible, but I'm not entirely sure what the actual error is; so my apologies in advance.

I help run a server that runs a modpack which contains Thaumcraft. One of our players has hit late-game thaum, and suddenly earlier today found himself unable to join the server. When he attempts to join, a massive error message is printed in console. No crash log happens on his end, he simply is unable to join the server. He sent a copy of his chat log and it only had a single, standard line about "connection refused".

In the error messages on console, several lines reference Thaumcraft, as well as a missing net/minecraft/client/particle/Particle. Here are the error messages, in full.

https://pastebin.com/DdNJmKmL

Any insight or assistance you may be able to offer on this issue would be greatly appreciated. Thank you for your continued work on such an amazing mod!

**Comment by wamc2017** [comment]
Which version of Thaumcraft are you running?

**Comment by DragaoNimhe** [comment]
Dangit I knew I was forgetting something. Apologies, I wrote this right before bed haha. We are running Thaumcraft 1.12.2-6.1.BETA21.
