### ISSUE TITLE
Cascading worldgen lag warning

### ISSUE THREAD

**Issue by Eriux** [Azanor/thaumcraft-beta#1365]
I was playing around with a modded server and when I was done and about to stop the server I saw the same message like a 100 times, this was the message:

> [13:17:06] [Server thread/WARN] [FML]: Thaumcraft loaded a new chunk [-47, -39] in dimension 0 (overworld) while populating chunk [-48, -38], causing cascading worldgen lag.
[13:17:06] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Something worth noting is that I was moving around in the world quite a bit.

Normally I wouldn't report this kind of thing but it specifically asked me too so here it is.

[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2321472/latest.log)
[debug.log](https://github.com/Azanor/thaumcraft-beta/files/2321473/debug.log)

**Comment by C0rn3j** [comment]
Also present here. Forge 2758.

**Comment by PulzHF** [comment]
Noticed it a few times, but never reported it. Still seeing it with 2759.

**Comment by SniperHauss89** [comment]
Noticed it on my server as well while trying to track down rubber banding lag. it definitely seems to be contributing in one way or another and from the research I've done it shouldn't happen nor do I remember it happening it the past with previous versions of Thaumcraft. I've used a few different forge versions as well with the latest being 2757.

**Comment by generrosity** [comment]
Using Forge 2760 with beta23.

Doing a fast creative fly across the land, triggering cascade every three seconds or so. Much less often over water. At a guess, could be the pockets of shards spawning at chunk edges? Or the little burrows. 

I know that there is a delay-putting-trees-down-and-back-fill-when-the-next-chunk-loads feature that biomes use to prevent cascades - it might be that that is missing here?

**Comment by PulzHF** [comment]
> Using Forge 2760 with beta23.
> 
> Doing a fast creative fly across the land, triggering cascade every three seconds or so. Much less often over water. At a guess, could be the pockets of shards spawning at chunk edges? Or the little burrows.
> 
> I know that there is a delay-putting-trees-down-and-back-fill-when-the-next-chunk-loads feature that biomes use to prevent cascades - it might be that that is missing here?

You should have seen how many cascades occurred when I used a pregenerator on a 50,000 x 50,000 world 🤣 
I don't believe this will be a huge issue for those of us using borders- as there's only so far outside of the border that can be generated by the player. Still, it would be nice to know exactly what causes this issue and whether a fix can be implemented.

**Comment by Azanor** [comment]
Greatwood trees are big enough that they occasionally generate across chunk borders. This is not a major issue and even though it causes console spam thanks to forge, the actualy worldgen impact should be minimal.

**Comment by Anora** [comment]
i'm getting this on my server and it dose affect tic time severely when new chunks generate
