### ISSUE TITLE
[B19] Break focus research consumes Blood Magic Sentient Sword

### ISSUE THREAD

**Issue by Daenyth** [Azanor/thaumcraft-beta#1366]
I have a sentient sword with mending on it, and completing the break focus research destroyed it.

It also consumed an Illumination Wand from Not Enough Wands

**Comment by lOmicronl** [comment]
It will consume one item with Fortune (any rank) and one item with Silk Touch. If you have multiple items with a qualifying enchant, it will pick one at random.

This is only a bug if one of the two items you named did not have such an enchant.

**Comment by Daenyth** [comment]
The sword had Mending. The wand had nothing.

**Comment by Azanor** [comment]
I see you are using b19. This bug has been fixed in a more recent version. (b21 I think?).
