### ISSUE TITLE
Aspects are overlapping with tooltips

### ISSUE THREAD

**Issue by SirWindfield** [Azanor/thaumcraft-beta#137]
The aspects that show up when I shift + hover over TC6-BETA are overlapping with the tooltips added by other mods. 
I am not sure if TC6 adds the aspect overlay itself (I guess so since that was a feature back in TC4 and TC5 too).  It look slike it only happens with items that have durability.
Here are some screenshot:
![2018-01-27_15 09 33](https://user-images.githubusercontent.com/5113257/35472691-275d3e22-0374-11e8-9790-0891dee7595d.png)
![2018-01-27_15 09 36](https://user-images.githubusercontent.com/5113257/35472692-2779fa08-0374-11e8-8e5b-175e61bf542f.png)
![2018-01-27_15 09 39](https://user-images.githubusercontent.com/5113257/35472693-279795c2-0374-11e8-9934-f57ed5ab0f40.png)
![2018-01-27_15 09 40](https://user-images.githubusercontent.com/5113257/35472694-27b315ae-0374-11e8-80eb-1fb913589129.png)
![2018-01-27_15 09 45](https://user-images.githubusercontent.com/5113257/35472695-27cf9ef4-0374-11e8-8e95-6c84cac3e1ae.png)

**Comment by MrNinja93** [comment]
Can confirm this happens with more than just items with durability, If the tooltip of any item is edited by a mod chances are the aspects will be offset incorrectly.

Currently know it to happen with Waila/Hwyla or ModNameTooltip all adding the mod name to the tooltip of all items (also means JEI is natively affected too as it adds mod names to items it displays) Probably many more that will be affected.
