### ISSUE TITLE
Beta23 metallurgy

### ISSUE THREAD

**Issue by egan566** [Azanor/thaumcraft-beta#1372]
something broken in 23 or is it just with me?

after updating from beta22 to beta23 no longer able to proceed in alchemical metallurgy.

the recipe page for brass ingots remains blank ??

also some of the added sections doesnt seem to complete .. got the btn complete, but only displays "completing...".

​

rig has i7,gtx1070, plenty mem. using twitch, no extra mods.

what i tend to do after new update is start a new world, gather all vanilla stuff, only after collecting all vanilla items i mine crystals and go tru every Thaumonomicon entry.

​

going back to beta22 allows me to proceed in alchemy.

removing modpack and reinstalling didnt resolve either.

**Comment by lOmicronl** [comment]
Cannot reproduce.

Made a new world in a pack with only a few clientside mods next to Thaumcraft 6 Beta 23. Everything worked as it should, and I was able to progress through Alchemical Metallurgy just fine. Recipe for brass ingots showed up normally.

Did you start the affected world in Beta 22 or Beta 23? Perhaps it only affects existing worlds that are upgraded, because new worlds in B23 are definitely fine. Or, something could be wrong on your end - that's possible too.

**Comment by egan566** [comment]
Drat. Tks for response.

Went tru update process twitch again, rushed towards Alchemical Metallurgy.
Same problem, so i can reproduce, on my rig, Will dust off old computer and see if i can reproduce again same account and such. (hope it still boots, will take some time)

![2018-08-28_09 47 30](https://user-images.githubusercontent.com/31178287/44710638-df2a7a80-aaac-11e8-80e0-0b1552ac8150.png)

++Attempting to make brass ingots in b23 similar to b22.
Lava beneath Crucible with water, toss flint, iron ingot, flint, iron ingot, bunch of crystal nuggets … iron ingots are gone, no brass, Inventory does show 5 instrumentum, but no 5 terra.
Normally also the instrumentum is gone also and you get the brass.

Mods conflicting, incomplete install ??

**Comment by wamc2017** [comment]
Which other mods have you installed? Maybe Thaumic Periphery? If so, do you have "Copper Brass Recipe" turned on in the config?

**Comment by egan566** [comment]
interesting ... yes, those mods came with default twitch/modpack update.
Me just a casual player, configuring mods usually i skip.
( where do i find the config ? )
