### ISSUE TITLE
[Beta 23] Blurred Vision Status Effect Does Nothing

### ISSUE THREAD

**Issue by MorzanTLD** [Azanor/thaumcraft-beta#1374]
When the blurred vision effect occurs either artificially or through warp no visual filter is applied.

**Comment by Reassembly** [comment]
Are you using Optifine? I noticed a while ago that "blurred vision" did nothing, but I assumed it was an Optifine incompatiblity.

**Comment by lOmicronl** [comment]
Can confirm, Blurred Vision does nothing for me either. Not running Optifine.

**Comment by SancaVIP** [comment]
Same... No mods, only thaumcraft, and blurred vision does nothing
