### ISSUE TITLE
Void seeds have no recipe in beta23.

### ISSUE THREAD

**Issue by 1naNis** [Azanor/thaumcraft-beta#1375]
When viewed in JEI, there is no recipe available to see. Also no craft for when clicked on in Thaumonomicon. Void Siphon is an alternative, but how could you possibly make void metal without seeds when the siphon requires an entire block of it?

**Comment by Reassembly** [comment]
Collapse a rift.

**Comment by TechnoTadhg** [comment]
There never was a recipe for it, you need to use a causality collapser on a rift, the bigger the rift the more seeds it may drop, it will only take 1-2 rifts if you keep all the void for the siphon.

**Comment by Vercci** [comment]
If you were playing Enigmatica they added a temporary recipe. Wouldn't be surprised if they removed it now that void seeds are reliable to get if you're a loose cannon who doesn't abide by the rules.

**Comment by Hubry** [comment]
The seeds actually had a recipe before - if you cheated in the metallurgy research, the last stage unlocked a recipe for void seeds and void metal. It was removed later, probably when flux rifts started dropping the seeds when they collapse.
