### ISSUE TITLE
cant compleat Focus Medium: projectile

### ISSUE THREAD

**Issue by RocketBoss360** [Azanor/thaumcraft-beta#1379]
I am playing the modpack "A little bit more of everything" and cant compleat Focus Medium: projectile
ive been shotr by an arrow, ive been hit by a blaze and llamas dont exist aparently

**Comment by lOmicronl** [comment]
You can go into creative mode, find a llama spawn egg, and spawn one in front of you. Go back into survival and give it a nice firm slap across the face, and it'll hook you right up.

**Comment by wamc2017** [comment]
If Llamas don't exist in  your modpack, you should talk with the modpack author about this. Normally they spawn in Extreme Hills biomes...
