### ISSUE TITLE
Just an idea about the compatibility

### ISSUE THREAD

**Issue by MCTian-mi** [Azanor/thaumcraft-beta#138]
I've been playing Thaumcraft for a long time，But I've been hard on it that the Goggles of Revealing do not compatible with most of other armors，for example,I can't use it while I'm wearing a diamond armor.So why not change it into a enchanting？
--I think my English is really bad,and most sentences are from Baidu translation.If there are any grammar mistakes,say to me .(〒▽〒）

**Comment by MainFreak** [comment]
I think an Addon Mod called Gadomancy used to make the Fortress Armour "Goggles Addon" be applicable to other armours as well. I agree that this would be a good compatibility addition, especially considering that some mods add armours that surpass Thaumcraft's protection- and feature wise.

**Comment by MCTian-mi** [comment]
Yes, I've heard that mod,but the author seems abandoned pit

**Comment by MrNinja93** [comment]
This is probably why Azanor made the goggles wearable as a bauble or armour, just open up your bauble screen in your inventory and place it in your head bauble slot and you'll be able to wear armour and see things :)

**Comment by MCTian-mi** [comment]
But if I have to wear another bauble?

**Comment by MCTian-mi** [comment]
I've just had another idea:make the Crucible be able to hold other fluid besides water.This is good for players to use Minetweaker to make something.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#160
