### ISSUE TITLE
[Beta23] Looking at Infernal Furnace's recipe crashes game.

### ISSUE THREAD

**Issue by PortalInTime** [Azanor/thaumcraft-beta#1381]
In the Thaumonomicon, simply clicking the Infernal Furnace's recipe in the section "Infernal Furnace" crashes the game. It might be important to note that I also have the mod "Botania" installed.

**Comment by wamc2017** [comment]
There should be a crash-reports folder in yoru minecraft directory, post the latest log on [pastebin](pastebin.com), [gist](https://gist.github.com), [hastebin](https://hastebin.com) or any other text hosting service and link the report here. Without it it's hard to say what's the exact problem...

**Comment by PortalInTime** [comment]
Alright, [here's the crash log.](https://gist.github.com/PortalInTime/56b80dc553f186acc8cd6ac915657264)

**Comment by wamc2017** [comment]
Does the crash happen without optifine?

**Comment by TechnoTadhg** [comment]
If it does happen without optifine try messing with your settings, some optifine settings don't go well with other mods
