### ISSUE TITLE
Mob pathfinding gets stuck on vis crystals

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#1382]
Mob pathfinding apparently sees vis crystals as impassable blocks despite their lack of collision. Mobs will sometimes walk around vis crystals, and if they walk onto a crystal they will spin around on the block for a while until they get unstuck.

**Comment by lOmicronl** [comment]
That might well be a vanilla issue. I often see mobs, particularly two-block long ones (horses, wither cats), get stuck spinning on all sorts of stuff... including simply the edges of normal blocks.

**Comment by TheDeviantCrafter** [comment]
I think the issue is that vis crystals have a colision box that doesn't take up a full block. Mobs get confused when standing on fences or flower pots.
