### ISSUE TITLE
Aspects missing in tooltips (Vivecraft/Optifine)

### ISSUE THREAD

**Issue by ProfessorVR** [Azanor/thaumcraft-beta#1383]
Hi,

I am running Thaumcraft 6.1 BETA 21 using Vivecraft (7-r4).  Vivecraft requires Optifine, so I also have Optifine (1.12.2 HD_U_3) installed.  

In Inventory view, when I bring up tooltips for any item, aspects are not shown-- there is a black box that is appropriately sized for the number of aspects that the item should have, but no aspect icons or numbers.  This is the case for all items in the Survival inventory, and also for all items in the Creative Mode inventory.

Running Minecraft without Vivecraft/Optifine, and with everything else the same (mods etc), the aspects show up fine.  So I suspect Optifine, as I've read a bit about compatibility issues between Thaumcraft and Optifine.  

I've twiddled around with the video settings, but so far haven't found anything that fixes the problems.  I can confirm that AA is off.

Hope there's a fix, as Thaumcraft in VR is wicked, wicked fun.  Thanks!

**Comment by lOmicronl** [comment]
I just launched the game with Optifine_1.12.2_HD_U_E2 enabled, and I can see aspects on items just fine. So it cannot be Optifine alone. Perhaps Vivecraft, too, is changing the rendering in some way to make it VR-compatible, and that doesn't support the way Thaumcraft is putting images into tooltips.

It's unlikely that Azanor can fix this on his end, by the way. Not impossible, but unlikely.

**Comment by Glease** [comment]
I'd believe it's on their side. It seems blending went wrong or something, as no color is shown in your jrbudda/Vivecraft_112#64.

**Comment by ProfessorVR** [comment]
Thanks to you both.  It does seem that the problem is with Vivecraft.  I appreciate the help.
