### ISSUE TITLE
Rift foci doesn't work

### ISSUE THREAD

**Issue by TLOU15** [Azanor/thaumcraft-beta#1386]
I can't seem to get rift foci to open passages. I have made two one with a basic foci and one with an advanced foci. I have tried on single block thick walls and thicker walls and it makes a noise but no opening. 

I am playing with: basic minecraft, Iron backpacks, Iron chests, JEI, Mob grinding Utils, thaumic jei, Xaeros minimap, silkspawners, Evil Notch lib, invantory tweaks, TC6 aspects.

**Comment by lOmicronl** [comment]
There are plenty of ways to create a focus that does nothing. It's not a bug, it's a feature! ;)

For example, "Rift" is a focus effect (square logo), and not a focus medium (hexagonal logo). An effect always attaches to a medium, and requires one to function. By default, if you do not add any medium, adding an effect will attach it to the "self" medium that is the root of all focus plans.

By choosing the "Rift" focus effect and nothing else, you create a focus that attempts to shift _you_ out of the bounds of reality, thereby making a tunnel through _you_. This, however, does not work, as the wise Thaumaturge has designed the focus to not work on organic matter (see the flavor text in the entry in the Thaumonomicon). Also compare the instructions/flavor text for making your very first focus, which specifically warns you that putting the "Fire" effect in without the "Touch" medium will simply result in a focus that sets yourself on fire.

Instead, first choose a medium like "Touch" or "Projectile" or even "Bolt" (they all work), and _then_ attach the "Rift" effect to that medium.

**Comment by TLOU15** [comment]
Ah, I can't remember if I had put one of those in but I rewrote one with touch included (are we supposed to be able to rewrite foci?) and that worked. 
Thanks for clearing that up and I will read the thaumincom a bit closeer
