### ISSUE TITLE
[B23] Golems don't initially render any specialty parts when placed/spawned

### ISSUE THREAD

**Issue by MightyBidoof** [Azanor/thaumcraft-beta#1387]
As the title says, the "Specialization" parts (uni-wheel, claw hands etc.) won't render when they're initially placed/spawned. This bug fixes itself upon restarting but could be slightly confusing for some people.

**Comment by Reassembly** [comment]
Duplicate of #1138

**Comment by Azanor** [comment]
fixed in b24
