### ISSUE TITLE
Arcane Pattern Crafter Not Working in Beta 19

### ISSUE THREAD

**Issue by TDGBullDog** [Azanor/thaumcraft-beta#1388]
Trying to craft flour as shown in the screenshots but it's not working. It will craft fine in my inventory. Running Beta 19 in the latest DW20 pack on a server. Am I doing something wrong?

![1](https://user-images.githubusercontent.com/35701823/44950637-ea6a0700-ae1a-11e8-90c4-e4786fe8b0eb.png)
![2](https://user-images.githubusercontent.com/35701823/44950638-ea6a0700-ae1a-11e8-9719-fba1916d6e98.png)
![3](https://user-images.githubusercontent.com/35701823/44950639-eb029d80-ae1a-11e8-8136-7270e3a8924f.png)

**Comment by Glease** [comment]
AFAIK arcane pattern crafter intentionally works with recipes that use single ingredient, like stone bricks, stone brick slabs, block of coal, etc.

**Comment by TDGBullDog** [comment]
Ah, it does work with single item recipes. Though I think it would be way more useful to be able to craft any recipe. Like for a golem ran pizzeria for example. :)
