### ISSUE TITLE
[B19] Missing Mirror Magic icons

### ISSUE THREAD

**Issue by TDGBullDog** [Azanor/thaumcraft-beta#1389]
Icons aren't appearing for the in the thaumonomicon for some of the mirrors.
![1](https://user-images.githubusercontent.com/35701823/44950738-c2c86e00-ae1d-11e8-85dd-36d5cc4826e7.png)
![2](https://user-images.githubusercontent.com/35701823/44950739-c2c86e00-ae1d-11e8-8670-34a82003e2ab.png)

**Comment by Glease** [comment]
Duplicate of #1088.
