### ISSUE TITLE
Thaumonomicon Localization issues

### ISSUE THREAD

**Issue by MainFreak** [Azanor/thaumcraft-beta#139]
The first research page in the Golemancy tab seems to not be localized properly.
This bug was present in BETA2 already. I tested it with BETA3 again.
![2018-01-27_15 44 07](https://user-images.githubusercontent.com/20734190/35473041-318232b2-037a-11e8-8672-f20a6c68e2e4.png)

In Mirror Magic I also found this one unlocalized
![2018-01-27_15 48 15](https://user-images.githubusercontent.com/20734190/35472997-9693d404-0379-11e8-9dc9-fd3e9e55004a.png)

And another, but minor, issue is that the formatting of this text does not stay over 2 lines
![2018-01-27_15 47 02](https://user-images.githubusercontent.com/20734190/35473045-43de053a-037a-11e8-9c51-34c3c295f466.png)

EDIT:
Also found this one. I think it is voidmetal?
![2018-01-27_16 02 12](https://user-images.githubusercontent.com/20734190/35473119-87167944-037b-11e8-8aaa-4a6a83e6c8d5.png)

I am not sure if any of those are duplicates but I have not seen any yet.

**Comment by Azanor** [comment]
All but the last one are indeed bugs. The last has yet to be implemented.
