### ISSUE TITLE
possible feature but am not shure, cant use any foci in any other dimintion other than the overworld

### ISSUE THREAD

**Issue by RocketBoss360** [Azanor/thaumcraft-beta#1390]
the thaumometer says there is vis there but the foci's effects don't happen

**Comment by VadersFist0501** [comment]
I play on a thaumcraft server (with the (Un)Official Thaumcraft Discord) and we use the heal --> cloud focuses to kill withers in the nether all the time. Point being... foci defiantly work in the nether and the end on the server side

**Comment by Azanor** [comment]
I can't replicate this issue either.
