### ISSUE TITLE
[6.1.BETA23] Control Seal: Provide is broken on dedicated servers

### ISSUE THREAD

**Issue by ilya-pirogov** [Azanor/thaumcraft-beta#1393]
The network doesn't display items or display it incorrect if there're more than 127 items. It looks like overflow of signed byte.
It's reproduced only on dedicated server. Internal server works fine.

There're no any errors in logs. Tried on Forge 14.23.4.2759, 14.23.4.2749 and 14.23.4.2705

**Comment by Minamikaze392** [comment]
Supposing that you mean the item request GUI after shift right-clicking the Golemancer's Bell, yes, that's happening for me too.

**Comment by Azanor** [comment]
a) I assume you mean the stock seal? The provide seal is not supposed to show stack sizes at all.
b) Did beta 24 solve this? I cant replicate it in that version
