### ISSUE TITLE
[SP] Game crashed after Golem set to follow

### ISSUE THREAD

**Issue by Omnimetatron** [Azanor/thaumcraft-beta#1394]
I had a bunch of Golems farming for me, some smart and deft to do the actual harvesting, others just standard Greatwood types to do the collecting and storing. I set one to follow, not sure which as I'd just placed a few of the more advanced ones and they don't render properly, and very soon after the game crashed. Here's a link to the crash report, hope it helps: https://pastebin.com/hrEgQRug

**Comment by F9Alejandro** [comment]
From what i gathered the Golem is unable to find your player entity as it is returned with null. It could be an issue with trying to pass the player entity properly or it could be an issue with trying to get the entity object in the first place. Azanor would have to say what is really going on.

**Comment by Omnimetatron** [comment]
Still an issue in beta 24: https://pastebin.com/1z26grCa

I should add that it doesn't happen every time I have a golem follow me, maybe 1/5th of the time.

**Comment by F9Alejandro** [comment]
By chance is the area chunk loaded that the golem is in? are you flying?

**Comment by Omnimetatron** [comment]
@F9Alejandro The area does happen to be in the spawn chunks, so if that counts then yes. I was not flying either time it has happened, unless double-jumping with the Cloudhopper Ring & Boots of the Traveller counts?

**Comment by Azanor** [comment]
If you place the seal on the ground the golem will repeatedly try and use saplings on that spot - the only thing the seal does is tell a golem to click on the marked blocked with an item. To have the golem only replant the sapling when there isn't one there, first place a sapling, then place the seal on the sapling and set the seal to only click on an empty space.
