### ISSUE TITLE
Can infuse foci without the required 1 XP level

### ISSUE THREAD

**Issue by Minamikaze392** [Azanor/thaumcraft-beta#1395]
Reproduce:
-Ensure that you don't have any XP level.
-Only bring the required vis crystals and start infusing a focus.
-The GUI will look a bit weird, but eventually the infusion will finish properly. The vis crystals are even not consumed.

EDIT: Confirmed in Beta 24

**Comment by Azanor** [comment]
Are you in creative mode?

**Comment by Minamikaze392** [comment]
Nope I'm in survival mode.
