### ISSUE TITLE
[B23]Closing the rift research not unlocking

### ISSUE THREAD

**Issue by lilithwhite** [Azanor/thaumcraft-beta#1400]
Not sure if this is a bug or I'm just doing something wrong. I have been trying to get the rift closing and flux cleaning research for the whole day now.

I filled 3x3 chunk area with flux and had rifts spawn all over the place, scanned one, waited for some of them to collapse and spawn taint stuff, scanned that but nothing. Even stuck a stabilizer next to one rift and stabilized it but nothing, just have the normal rift research.

I have research everything else there is that's available without the eldritch research. This is what my fundamentals tab looks like:
![noresearch](https://user-images.githubusercontent.com/39236392/45104232-4776fd00-b13a-11e8-841e-9c791732ea5d.PNG)

I haven't found anyone on the internet saying whats the trigger for that research to appear is but I have done like everything I can think of that makes sense (and doesn't) to unlock it.

I'm running beta 23 and forge 14.23.4.2757

**Comment by MorzanTLD** [comment]
This is going to sound silly but have you scanned any crystal clusters? If I recall correctly you can't unlock that research without it.

**Comment by lilithwhite** [comment]
Ok wow, that was it... I feel silly. I just gathered up a lifetime supply of vis crystals before I even got the thaumometer so I never did that. Ty for the help!
