### ISSUE TITLE
Crash when I pickup xp orbs and no fall damage which cause thaumcraft errors

### ISSUE THREAD

**Issue by Lloergwaed** [Azanor/thaumcraft-beta#1407]
Just need to figure out what is happening tested with only thaumcraft and baubles and it stil hapen sometimes...
[crash-2018-09-08_14.06.19-server.txt](https://github.com/Azanor/thaumcraft-beta/files/2363589/crash-2018-09-08_14.06.19-server.txt)

**Comment by lOmicronl** [comment]
Please provide a log with only Thaumcraft and its dependencies, then. The one you have upload has an unbelievble amount of mods in it, and that makes troubleshooting very difficult.

**Comment by Lloergwaed** [comment]
i found the faulty mod
it's mobtotem which cause the crash as for why i don'tknow... but i just deleted the mod and everything is working fine so it was not thaumcraft even if the crash report was blaming thaumcraft.
