### ISSUE TITLE
Lose all Thaumonomicon progress on death

### ISSUE THREAD

**Issue by ProfessorVR** [Azanor/thaumcraft-beta#1408]
When I die, on recovering my Thaumonomicon, all research progress is lost, and I'm back to the start.  Observations, theories, branches and items are all gone.  Has happened twice now.  Is this expected behavior or a bug?  Thanks.

**Comment by androshalforc** [comment]
definitely not normal intended behavior, and it doesn't sound like any bug ive heard about possibly a bad mod interaction or some kind of server setting?

**Comment by ProfessorVR** [comment]
thanks for that tip.  It seems to be a conflict with Vivecraft (again).  

Looks like my best option is to cheat the research back in through commands.  I'm now in search of an up-to-date list of research names.  Haven't found one yet.
