### ISSUE TITLE
crashing when opening the creative inventory

### ISSUE THREAD

**Issue by xemnes** [Azanor/thaumcraft-beta#141]
whenever i try to open the creative inventory, i get this crash. https://pastebin.com/U05jmFCW

**Comment by MainFreak** [comment]
@asiekierka Is that your witchery?

**Comment by asiekierka** [comment]
No, this code very closely mirrors vanilla behaviour. Are you sure this happens with FoamFix removed?

**Comment by MainFreak** [comment]
I am not using Foamfix in my current private testing instance and I am not crashing. I can try adding it to see if it really is the issue.

**Comment by xemnes** [comment]
it probably doesnt, i will check. though i dont plan on removing foamfix

**Comment by asiekierka** [comment]
Could be related to BlockPalette, too, whatever that mod is.

**Comment by MainFreak** [comment]
Can confirm that it is not Foamfix. Sorry for mentioning you Asie.

**Comment by xemnes** [comment]
blockpalette is part of conquest reforged, its a ui that tries to pair the current block youre holding with other blocks

**Comment by asiekierka** [comment]
@xemnes Wrong - if you look at the stacktrace, the BlockPalette UI initializes itself the moment you open the inventory GUI and crashes there.

**Comment by xemnes** [comment]
not sure what much of it means really. i will test without blockpalette

**Comment by xemnes** [comment]
yes, removing conuest reforged which removes block palette allows me to open the creative inventory.

**Comment by MainFreak** [comment]
Seems like ConRef does not have a proper Github and their primary place for issues is their Discord. Might report that to their team there. @xemnes

**Comment by xemnes** [comment]
the dev for blockpalette has a git https://github.com/dags-/BlockPalette
i believe blockpalette is a separate mod that they bundle into the conquest reforged jar

**Comment by Azanor** [comment]
Either way, not a TC issue so closing.
