### ISSUE TITLE
[B24] Infernal Furnace incorrect/hidden information

### ISSUE THREAD

**Issue by Ashendale** [Azanor/thaumcraft-beta#1412]
Looking at the Infernal Furnace's Thaumonomicon entry you wouldn't guess it creates flux, yet it does. Is this intended, the entry incorrect, or what am I missing here?

Also, on the subject of flux - must I ruin a chunk or several causing a rift before being able to mitigate/remove flux? The research only shows up just before things go FUBAR.

I would like to use a lot more from the mod, but currently I have to make outposts far far away from home so I can do whatever (essentia, crucible, furnace, etc), or risk seeing all I own tainted/destroyed.

It feels this iteration of TC has no alternate path than that of mayehm and destruction. That, or I'm missing something very obvious...

Still, thanks for the great mod.

**Comment by apmax** [comment]
Taint and rifts are very easy to deal with.
You basically cannot ruin your world with flux unless you try to on purpose, and even then you have to put in a calculated effort to do it.

Part of the progression of TC6 is to let flux get bad, don't live in eternal fear of a taint seed that you'll just kill not even 30 seconds after it spawns.

**Comment by lOmicronl** [comment]
The Infernal Furnace has always produced flux, IIRC (though I have not played TC5). Anyone coming from a past version would just expect it. But you are right, a new player might not. Changing the Thaumonomicon entry to reflect this sounds like a quick and easy enhancement to make.

Don't overestimate the flux produced, though. It's something like 4-8 points for a full stack of items smelted. In the grand scheme of things, it's completely negligible. Now the essentia smelter, _that_ is the thing you have to watch out for. Pretty sure the book entry for it also warns about flux.

**Comment by Ashendale** [comment]
I'm currently experimenting with flux to see what triggers rifts and how to deal with the aftermath.

I keep reading about "stabilizing a rift" but I cannot figure how. The closest thing I found for this was a Stabilizer from the Infusion tab, but I'm not sure that it can be used on rifts.

So what you're saying is that I should take thing slow and away from my base?

**Comment by apmax** [comment]
At the risk of spoilers:
rifts are caused by too much flux
point the stabilizer at the rift
Don't bother moving your entire setup a million miles from your base, flux and flux effects aren't bad enough to warrant that.  Literally one single chunk over will work just fine.
