### ISSUE TITLE
Harvest Seal targets Botania Glimmering Flowers

### ISSUE THREAD

**Issue by ArielFaye** [Azanor/thaumcraft-beta#1413]
I use Glimmering Flowers to light up my areas rather than torches. These buggers keep picking them, lol. - Ariel

**Comment by Azanor** [comment]
That might be something on the botania side. I suspect they are registered as "IGrowable" or extend BlockCrops which makes golems count them as normal crops. Not much I can do about that unfortunately.

**Comment by LumberWizard** [comment]
Maybe add a config option with a blacklist for crops? (or does the Harvest Seal have a blacklist?)
