### ISSUE TITLE
[B22] Dropped Bath Salts Decay Time

### ISSUE THREAD

**Issue by lilolbear** [Azanor/thaumcraft-beta#1414]
Uncertain if this is a feature or a bug but dropped bath salts have a extremely fast decay time compared to other items. It also seems to be random anywhere from 4 to 12 seconds.

**Comment by lOmicronl** [comment]
It specifically says in their Thaumonomicon entry that they decompose quickly, yes. ;)

**Comment by lilolbear** [comment]
Right on. "The salts are quite fragile and will soon dissolve if tossed around haphazardly" lol
