### ISSUE TITLE
Poor little guys just exploded 

### ISSUE THREAD

**Issue by lilolbear** [Azanor/thaumcraft-beta#1419]
After dying, the act of respawning near my great wood golems caused them to give a little cry out and explode into pieces. They were 1 and 2 blocks away from the block I respawned in respectfully. 

I apologize but I haven’t been able to bring myself to repeat the circumstances on more of them. It was quite traumatic. lol

**Comment by Sketaful** [comment]
It's not a bug, it's a feature 🤣😂

**Comment by lilolbear** [comment]
I think that this one can be closed. I have tried so many different ways of dying it is starting to feel like Groundhog Day. I have used water to shove the armor stand around, I have tried catching the golems when they were doing something, all to no avail. I suppose I should be happy. haha

I logged in once to find their parts on the ground but there wasn't anything I could see in the logs to indicate why. I'll report anything new I find but I think the respawn isn't the cause.
