### ISSUE TITLE
[ThC6 Beta] Thaumometer has weird effects on almost everything transparent

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Azanor/thaumcraft-beta#142]
Title says it, here is an example of the Thaumometer making water invisible, and removing SEUS' effects on the surrounding area.
![2018-01-27_16 08 10](https://user-images.githubusercontent.com/13576843/35473170-46f71e26-037c-11e8-9800-1e27774cefb0.png)

**Comment by MrNinja93** [comment]
Probably a similar issue to https://github.com/Azanor/thaumcraft-beta/issues/111 so it might not be fixed in this instance either.

**Comment by Azanor** [comment]
Yup, nothing much can be done about this unfortunately.

**Comment by ProxyPlayerHD** [comment]
the thing is, even without shaders water is still invisible, and so is portal blocks, and quite som,e particles... this is not a shaders only bug.

**Comment by LordPinkerton** [comment]
It would still seem likely to be some other mod or addition that is messing with the rendering, as I haven't seen anyone else with this specific issue. Would you be able to list your mods and anything else running in your Minecraft instance?
