### ISSUE TITLE
[B24] Boots of the Traveller + Cloudstepper Ring position sync error

### ISSUE THREAD

**Issue by Boingboingsplat** [Azanor/thaumcraft-beta#1421]
When both the Boots of the Traveller and the Cloudstepper Ring, double jumping causes a sync error to occur, resulting in a strange, jarring snap in position. Every time this happens the following warning is output to the console:

`[23:10:33] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: BBSplat out of sync, resyncing! error = 0.0
`
This is occurring in survival single player.

Here's a video showing the issue. It doesn't happen if I unequip the boots.
https://streamable.com/k5enf

Forge 14.23.4.2758
Thaumcraft 6.1.BETA24

**Comment by Azanor** [comment]
Unfortunately nothing much I can do about this. However this core mod should solve that:
https://minecraft.curseforge.com/projects/gotta-go-fast?gameCategorySlug=mc-mods&projectID=282064
