### ISSUE TITLE
Infusion Enchantment not completing

### ISSUE THREAD

**Issue by Kalmeira** [Azanor/thaumcraft-beta#1426]
I am playing with b24 and the infusion enchantment (for the destruction property on an unbreaking 3 thaumic pickaxe) will not complete. It will take in the required essentia, consume the TNT, but it will not consume the enchanted book. It keeps knocking it off or destroying it, then requiring more essentia.
I tested this once in survival, then again in creative.

**Comment by apmax** [comment]
Is the enchanted book a vanilla or a modded enchantment?
If it's a modded enchantment, those won't work.

**Comment by Kalmeira** [comment]
I first tried with efficiency 1 (in survival), In creative I tried it with
fortune 3 and maybe others.

**Comment by Azanor** [comment]
I tested this several times and everything works fine with just TC installed. If you have any TC addons try removing them and try again.

**Comment by Kalmeira** [comment]
I do not have any TC addons, which I guess means I need to start removing mods and testing. This may take a while. I only have a couple of mods that add enchantments, so those are the likeliest suspects.  I am a few versions behind on forge, so I can try updating that to see if it helps.

**Comment by Azanor** [comment]
Maybe try updating forge first.
