### ISSUE TITLE
Tainted rock/soil don't drop items when mined

### ISSUE THREAD

**Issue by jBosh0404** [Azanor/thaumcraft-beta#1428]
I don't know if this is working as designed, but tainted rock and soil don't drop their item variants when mined with anything except something enchanted with silk touch. Considering how difficult it already is to get vitium essentia, it seems to me that this would be unintentional, but maybe I'm mistaken. I'm playing B24.

**Comment by jBosh0404** [comment]
To clarify, I'm playing B24.

**Comment by wamc2017** [comment]
Hmm, works fine with Silk Touch on my side, so I guess intended...

**Comment by jBosh0404** [comment]
Yeah, I mentioned it works with silk touch. I've just seen videos of Thaumcraft 6 where this wasn't necessary so I wasn't sure if it was an intentional roadblock or a bug.

**Comment by wamc2017** [comment]
The blocks return item id 0 (air) as a drop since beta22:
![itembyid](https://user-images.githubusercontent.com/33242447/45605511-b9eeb380-ba3d-11e8-88a6-e35d2a90bc57.png)

I think that's a rebalance because the primal crusher can break the tainted blocks quite quick...
