### ISSUE TITLE
Gunpowder Hedge Alchemy is a bit broken

### ISSUE THREAD

**Issue by jBosh0404** [Azanor/thaumcraft-beta#1429]
The gunpowder recipe for Hedge Alchemy is 5 Alkimia, 10 Ignis and 10 Perditio, which matches the vis contents of gunpowder with the exception of 10 points of Exitium. If using gunpowder to provide the essentia to produce gunpowder, it allows for virtually costless collection of Exitium essentia in crystal form, because the 10 points of Exitium remain after duplication. To reproduce this, drop a piece of gunpowder into a crucible and then drop in another. You get both back and 10 points of Exitium remain in the crucible. B24.

**Comment by Glease** [comment]
Exitium? I don't really think this is a vanilla thaumcraft aspect...

**Comment by jBosh0404** [comment]
> Exitium? I don't really think this is a vanilla thaumcraft aspect...

It shows "Thaumcraft" when I hover over it...

**Comment by Glease** [comment]
I checked the game again and indeed there is no exitium. It must be an addon aspect then.

> It shows "Thaumcraft" when I hover over it...

No matter which mod add the aspect the game will tell you it's added by Thaumcraft. Sounds a bit silly, but nobody wished to dedicate their time on these not so important stuff.

**Comment by jBosh0404** [comment]
Ah. A quick google search shows it was added with Thaumic Additions: Reconstructed. Nevermind.
