### ISSUE TITLE
"Warded Jars & Labels" entry displays entirely wrong text

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#143]
This entry's text is an exact copy of the Stage 1 research hint/instructions for unlocking "Essentia Smelting"

**Comment by Ulysses2** [comment]
Sorry for the mess, accidentally hit Enter before I was done writing up the report.

**Comment by MainFreak** [comment]
Also labels are not localized for me. This has nothing to do with this issue but I wanted to say that.
