### ISSUE TITLE
Thaumcraft 6 trees not generating with OTG/Biome Bundle (1.12)

### ISSUE THREAD

**Issue by xAlicatt** [Azanor/thaumcraft-beta#1430]
TCversion: Beta24
OTG version: v6
Biome Bundle version: v6.1

I know this may not be something you can fix, but I thought perhaps OTG could be detected when mods are loading and some extra code activated to be doubly sure that thaumcraft trees generate at the very end of the worldgen stack. 

Oddly enough, though they aren't generating normally, when I have Dynamic Trees enabled with the Thaumcraft compat, I AM getting the DT versions of the TC6 trees generating as normal.

Additionally, the TC6 biome isn't generating in this setup, which isn't the end of the world since it's not needed for TC progression.

**Comment by Azanor** [comment]
Unfortunately not much I can do about this.

**Comment by xAlicatt** [comment]
I don't understand why nothing can be done though? If Dynamic Trees is able to spawn thaumcraft trees (and replace vanilla trees with DTs too) in OTG worlds, it makes no sense that Thaumcraft itself wouldn't be able to do so. Is it just a matter of not wanting to chase a potentially never-ending goalpost of what's generating last in the worldgen stack?

**Comment by Azanor** [comment]
With a few exceptions it is generally not worth it trying to add code to get a mod working nicely with another. There are just too many mods out there for this to be a realistic thing to do.
