### ISSUE TITLE
Suggestion: Golem Finder

### ISSUE THREAD

**Issue by Omnimetatron** [Azanor/thaumcraft-beta#1431]
Partially because of the issues folks have been having with golems occasionally falling into non-full blocks, like stairs grass paths, etc. I thought it might be quite handy to have a feature that would allow us to easily find the location of all nearby golems.

I'm not sure how important this is or even how easy it would be to implement, but I was thinking that some kind of variant Thaumometer that would show golems viewed through it, even through solid blocks (outlined as if they'd been shot with a Spectral Arrow), or wielding a Golemancer's Bell and Essentia Resonator in either hand striking one with the other (shift right-clicking) to achieve a similar effect (Spectral Arrow) to highlight all golems within the local area for a short time.

**Comment by Azanor** [comment]
Not a bad suggestion. I might just include it as the part of the normal function of the bell.

**Comment by Omnimetatron** [comment]
Oh, well that's cool too. Thanks for taking my idea on-board.
