### ISSUE TITLE
Golems take commands from dyed seals, even when they themselves are undyed.

### ISSUE THREAD

**Issue by VadersFist0501** [Azanor/thaumcraft-beta#1433]
I have an automated bloodmagic setup using golems. The seal to take items out of the storage chest and the seal to input items into the blood altar are both dyed "Lime". However, the undyed golem interacts with the chest as though getting commands from the dyed seal.

Also, commanding golems to take items out of a storage drawers results in the golem taking ALL of the items (e.g. 30,000 cobblestone), out of the drawer. Not sure if this is intended or not, but I have used this glitch to great effect, as it is very useful in autocrafting.

**Comment by Omnimetatron** [comment]
This is working as intended as far as I know. Dye the ones that are undyed to a colour that's not being used to prevent them from interacting with Seals set to a specific colour.

As for the other issue, are the golems taking the 30,000 cobblestone (as per your example) as one mega-stack, or are they just continually emptying the storage drawer one stack(64) at a time?

**Comment by Azanor** [comment]
Yup, the first 'issue' is the intended behavior.
