### ISSUE TITLE
umm is this on your end?

### ISSUE THREAD

**Issue by CharCharthemonkey** [Azanor/thaumcraft-beta#1434]
talked with King Lemming from thermal expansion and he says its 100% not on his side so was gonna ask u if its ure end or oresalleasy doing it 
![2018-09-12_21 31 48](https://user-images.githubusercontent.com/30783285/45854174-4c79a600-bd0f-11e8-9127-00345c3e7b6c.png)
![2018-09-12_21 31 54](https://user-images.githubusercontent.com/30783285/45854176-4e436980-bd0f-11e8-955e-39ee93b58839.png)

**Comment by wamc2017** [comment]
Thaumcraft doesn't use dustQuartz or dustNetherQuartz for anything, nor does it add any pulverizer or redstone furnace recipes...
I guess you've Actually Additions installed and the incompatibility is between AA and OresAllEasy...

**Comment by CharCharthemonkey** [comment]
yes i have actually additions installed but was simply asking whos this issue was since  everything either pointed to thaumcraft or oresalleasy so thought id ask and see wat azanor said but im 90% sure its oresalleasy thats doing it but never hurts to be sure before just assuming hehe

**Comment by Azanor** [comment]
Nope, I definitely do not add a smelting recipe for quartz dust. I just add a quartz -> quartz nuggets recipe
