### ISSUE TITLE
[Suggestion] Essentia Splicer

### ISSUE THREAD

**Issue by Tyrion216** [Azanor/thaumcraft-beta#1436]
If essentia can be split, why can it not be mixed? The centrifuge can split essentia into its components but what if a machine could take in two essentias and combine them to make a compound essentia? A couple possible ways of doing it would be simply have a machine with two slots for pipe inputs that run directly from jars and it auto detects which essentias are being input and produces the appropriate compound essentia. A second and my preferred method would be a machine with an interface that acts like the thaumatorium and allows the user to select which type they want to produce, and then the machine produces suction for that specific type. This would allow the use of the emptying aerial device and potentially the filling device as well. 

I know this is the issues board so sue me if you have to but I didn't know where else to post it.

**Comment by wamc2017** [comment]
https://github.com/Azanor/thaumcraft-suggestions/issues/55
