### ISSUE TITLE
Greatwood saplings: Strange growing behaviour?

### ISSUE THREAD

**Issue by Omnimetatron** [Azanor/thaumcraft-beta#1438]
I placed down a square of Greatwood Saplings, hoping to get a bit more efficiency for my newly awesome farm (thanks again), and I discovered that the trees itself is not appearing in place of the saplings, instead it's next to them, meaning only one gets consumed. More efficient than I'd bargained for, but I thought you'd like to know.

https://imgur.com/gallery/hMeDzES

**Comment by Omnimetatron** [comment]
https://imgur.com/a/DxBcLLL

I took a few more images to track what's occurring.

**Comment by Boingboingsplat** [comment]
You only need one sapling to grow a Greatwood Tree anyways.

**Comment by Omnimetatron** [comment]
> You only need one sapling to grow a Greatwood Tree anyways.

Really? I'm surprised by that as it's unlike any other tree.

**Comment by AnrDaemon** [comment]
> Really? I'm surprised by that as it's unlike any other tree.

Been like that forever.

> B25 will require 4 saplings to grow greatwoods

But the report seems to imply that the placement of a newly grown tree is wrong. Was that also amended?

**Comment by Azanor** [comment]
Yes, placement also tended to be unpredictable - it looked for the best fit area like vanilla minecraft did back in the day. That is one of the reasons the multiple sapling thing was added to vanilla I believe. Might as well update mine as well :)
