### ISSUE TITLE
armour displaying incorrectly while flying with wings

### ISSUE THREAD

**Issue by flux1337** [Azanor/thaumcraft-beta#1440]
armour displaying incorrectly while flying with wings from "Wings" mod ( https://minecraft.curseforge.com/projects/wings?gameCategorySlug=mc-mods&projectID=302584 )

**Comment by Azanor** [comment]
Screenshot would be handy.

**Comment by flux1337** [comment]
While flying armour thinks what you are running and shakes arms and legs

**Comment by Azanor** [comment]
I'm guessing the Wings mod obviously uses some kind of custom animation which I can't account for.
