### ISSUE TITLE
[B23]Arcane Levitator does not work reliably when lag is present, especially below 15 tps

### ISSUE THREAD

**Issue by McFrugal** [Azanor/thaumcraft-beta#1441]
I'm not sure why, but the levitation gets all wobbly when there's any lag at all, bouncing you up and down.  The worse the tps is, the less likely you'll be able to even get to the maximum height.  At 12 TPS its range was effectively halved.  It's like it tries to predict how much it needs to push you, and applies that force in a burst, but when there's lag it waits before pushing you, allowing you to fall back down and invalidate the prediction?
This is on a server, I'm not sure if that matters.  Also yeah, it's a modpack.

**Comment by Azanor** [comment]
It applies it's force per tick, so yes, if tps is very low it will not work properly. That is not really something that can be changed.

**Comment by McFrugal** [comment]
Ah, just an update, it turns out the server I was on has huge lag spikes(like, lasting one or two entire seconds), and that's when it stops levitating you.  Definitely nothing to be done to fix it.
