### ISSUE TITLE
[1.12.2] [Request] Dimension blacklist or whitelist for world generation

### ISSUE THREAD

**Issue by NickelHub** [Azanor/thaumcraft-beta#1442]
The Viscrystals are spreaded in all dimensions, espacially the Abyssalcraft ones, where they shouldn't be. It would be useful to control this via the config file.

**Comment by AnrDaemon** [comment]
This is not a bug. If you are making suggestions, [head to the right section](https://github.com/Azanor/thaumcraft-suggestions).
