### ISSUE TITLE
[Suggestion] Essentia Phials compatible with Bibliocraft potion shelves

### ISSUE THREAD

**Issue by NerdimusPrime** [Azanor/thaumcraft-beta#1444]
I don't know if this would be a change in TC or Bibliocraft, but currently (B24) I'm able to place vis crystals in potion shelves, but not phials (either full or empty). At one time [they did work](https://youtu.be/Q6XjvocDmUg?t=1m17s) this way, and it'd be great to have that back. Thanks!

**Comment by wamc2017** [comment]
Add "phial" as an additional keyword to AdditionalPotions in the Bibliocraft config...

**Comment by NerdimusPrime** [comment]
Didn't know I could do that. Thanks!
