### ISSUE TITLE
[Suggestion] - Reintroduce nodes as a far more compact vis battery.

### ISSUE THREAD

**Issue by VadersFist0501** [Azanor/thaumcraft-beta#1447]
Nodes have always an important and interesting part of Thaumcraft, so it seems a shame they do not have any part in TC6. Additionally, the current vis batteries are just... unsatisfying. However, their Thaumonomicon entry in which it is mentioned their capacity cannot be increased opens a great possibility. What if a player could create their own nodes? These nodes would likely be expensive, and require a constant stabilization to neutralize any explosive side-effects. They would probably ensure their balance by accepting a primordial pearl of some sort to be created. However, their use is the important part. They could either be a massive vis battery, or an infinitely dense pile of silverwood leaves. xD
They could basically store... 5-10K(?) vis or create vis at the rate of one-per-second, or something like that. Its just an absolute shame nodes have been removed. I have a thought you are planning *something* with them, but wanted to give some ideas in case they were wanted.

**Comment by apmax** [comment]
I like the environmental and lunar-cycle based vis balance going on so far in TC6, I think a return to nodes in any even remotely similar way to how they were present before would detract from the current system.
As it is now there's more of a focus on vis and flux as an inherent part of the world that you need to be mindful of, rather than as a side effect of aura nodes.  Feels a bit closer to TC2 than before and I'm excited to see how things go further into development with that.

**Comment by VadersFist0501** [comment]
The environment and lunar systems are novel... but they can become obnoxious when you are using large amounts of vis and have to wait for a full/new moon (whichever it is) to get real vis regen. 
The silverwood vis generation is a good concept... but I don't think it is something a late-game thaumaturge would see themselves using (at least with the whole lore of the mod). The system is a little similar to Astral Sorcery... the nodes were an exceptionally unique system. Tbh, the Demon Will Aura in Blood Magic is very similar to thaumcraft's...

**Comment by apmax** [comment]
I don't see how you could feasibly run out of vis in your area and need to wait any large amount of time to start progressing again.  With the workbench charger and both crystal clusters and vis batteries to expand the aura's capacity, you'd be hard-pressed to actually manage to use up all the surrounding vis.

**Comment by VadersFist0501** [comment]
If you are using vis for crafting, yes.
But using vis for foci like like plan -> break, or any focus with a long chain of effects stacks up very quickly. I have to break multiple times during a "big dig" just to the the aura recoup. A node with some sort of effect to alleviate this issue would we welcome. Maybe a node gives a status effect that is essentially the opposite of flux flu, that increases vis efficiency.

**Comment by SlvrKnight96** [comment]
I like the idea of nodes acting as continuous aura generators that regenerate vis at a constant rate (like 1 vis/tick) and will stop once the aura is full. If a primordial pearl is required to craft this, it would become a very rare late-game object, so being a powerful tool to manipulate vis would be welcome. It is kind of annoying that using enough stabilizers to make expensive infusions drains huge amounts of vis that can't be regenerated easily.

**Comment by Xobra** [comment]
We have (unstable) Rifts to the "(Tainted?)Void" that suck Flux. Maybe add a way for a "stable Rift/Node", which are connected to a more magical (pure) place that push Vis to the Aura, replenishing and maybe expanding the Aura, also causing a bit of Flux (like stressing the local Aura, like mirrors). Maybe an inferior or more unstable version, which has greater Flux penalties. (The whole concepts seems like a potential big Expansion of Auromancy?)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#456
