### ISSUE TITLE
golems will not try to remove items from "fake" inventories.

### ISSUE THREAD

**Issue by Frontrider** [Azanor/thaumcraft-beta#1451]
I made a block that displays a fake item, than emits a redstone signal if something tries to take this item(returns an empty stack). The thing is that golems will refuse to take the item after a single try, making it useless.

**Comment by VadersFist0501** [comment]
Golems will not attempt to remove an item from an inventory if that item does not exist, regardless of empty seals.

**Comment by Frontrider** [comment]
The inventory pretends that it has an item, than returns nothing when you extract. It allows the item to show up in screens, and be clickable. (And can be used to trigger automation)
I think the issue is, that the golem task remains uncompleted, and the golem will not try again, until I break and replace the seal.

**Comment by Frontrider** [comment]
OThe golem will not try to remove it until the seal is not replaced , so it's definietly the task system
I'll just make a seal that does what I need.
