### ISSUE TITLE
[B24] - Can not fill bottles from everfull urn

### ISSUE THREAD

**Issue by Tyrion216** [Azanor/thaumcraft-beta#1452]
Buckets seem to work fine. The only problem is bottles as far as I can tell. They just don't fill.

**Comment by VadersFist0501** [comment]
Yes... the (Un)Official Thaumcraft Server using a filled cauldron to teleport players to spawn. We've wanted to use an Everfull Urn to automatically fill the cauldron, but it currently will not work.
