### ISSUE TITLE
Stock Seal doesn't seem to function

### ISSUE THREAD

**Issue by oliveanimone907** [Azanor/thaumcraft-beta#1453]
I have a setup with two chests next to each other.
Chest a contains some items and has a provide seal while chest b is empty and has a stock seal.
The stock seals whitelist contains the items in chest b but still the golems don't transfer the items.
Shift+RightClick with the golemancers bell lets a golem bring the items to me.
Neither seal has special options or prioity/locking. All default.

I'm assuming the stock seal either doesn't find the provide seal or doesn't create a task.

Beta 24

**Comment by Minamikaze392** [comment]
Same here. And I cannot find the option to specify the amount of item to be stocked.

**Comment by VadersFist0501** [comment]
An answer to your question... you need to tinker with left or right clicking (dont remember) on the filter. Basically, you change the icon from an orange "x" to a number: the number of items you want in the tile entity.

**Comment by Minamikaze392** [comment]
> 
> 
> An answer to your question... you need to tinker with left or right clicking (dont remember) on the filter. Basically, you change the icon from an orange "x" to a number: the number of items you want in the tile entity.

Oh thanks for the help. I'll try that later.

**Comment by oliveanimone907** [comment]
Yes, changing the x to a number solved the problem for me.
Thank you!
