### ISSUE TITLE
Particle drastically reduces FPS

### ISSUE THREAD

**Issue by oliveanimone907** [Azanor/thaumcraft-beta#1454]
Sometimes at random flux generates hardly visible white swirly particles that do damage to entities touching it (I would like to upload a screenshot but sadly that doesn't seem to work, so here's a dropbox link: [screenshot](https://www.dropbox.com/s/dnw78pcdoejhj9k/particle_thaumcraft.png?dl=1) ).
For whatever reason this particle absolutely kills my game.
My Laptop isn't the best and I usually only have about 20 FPS but this particle lets them drop to about 4 to 6.
Beta 24.

Edit:
Just noticed that the particles actually are a rift I simply can't see.
So rifts cause my FPS to drastically drop and I can't see rifts ...

**Comment by lOmicronl** [comment]
Remove Optifine and see if it makes a difference. TC6 and Optifine do not always play nice with each other, this is known.

**Comment by Azanor** [comment]
I'm not sure that particle you see is from TC - flux particles are purple clouds and they are purely cosmetic - they do not do damage to entities.

**Comment by Azanor** [comment]
You can also try to disable shaders in the TC config and see if that improves your FPS.
