### ISSUE TITLE
Vis Crystals are like VIRUS.

### ISSUE THREAD

**Issue by Minamikaze392** [Azanor/thaumcraft-beta#1458]
![image](https://user-images.githubusercontent.com/40918110/46251160-114d4480-c47e-11e8-9e0f-f6485e1a2d31.png)
I had the worst nightmare last night.

In the dream, I was going underground for a mining trip. When I hung a torch on the cave wall, The view of the surroundings petrified me. Swarms of vis crystals, _everywhere_!!! It was so upsetting I actually woke myself up shrieking and crying...

... just kidding :D . Anyway, I would be happy if they stop duplicating when there are already many of them.

**Comment by lOmicronl** [comment]
Did you leave this chunkloaded for an IRL month? o_O On my end, they spread so slowly that I've basically stopped bothering with planting crystal clusters entirely. If I play two hours an evening, I see maybe one or two new clusters grow per week.

**Comment by Azanor** [comment]
They have a spread limit and should only be able to spread about 5-6 blocks away from the 'seed' block. That pic seems about right for that.
