### ISSUE TITLE
Asmostpheric Grass Blocks

### ISSUE THREAD

**Issue by netmc** [Azanor/thaumcraft-beta#1459]
I've run into some atmospheric grass blocks in the magical forest biome that seem to have a hard-coded grass color and do not support the greener grass function from quark.  I'm not sure what these grass blocks actually do, but I only noticed them as they are a slightly different shade of green.

**Comment by Azanor** [comment]
They create the particles that float around in magical forests at night. Purely aesthetic. 
Either way they just inherit normal grass blocks, so it means quark probably doesn't account for variant grass blocks like this. Nothing much I can do about it unfortunately.
