### ISSUE TITLE
ore and plants generate in all dimensions

### ISSUE THREAD

**Issue by Hypsellis** [Azanor/thaumcraft-beta#1461]
There is no way to control the Thaumcraft worldgen, which cause ores and plants to generate in dimensions they aren't supposed to generate.

**Comment by NickelHub** [comment]
That is the same as https://github.com/Azanor/thaumcraft-beta/issues/955 and https://github.com/Azanor/thaumcraft-suggestions/issues/440.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#455
