### ISSUE TITLE
Resource Pack breaking GUI

### ISSUE THREAD

**Issue by Yamza** [Azanor/thaumcraft-beta#1462]
How it should look: https://i.imgur.com/bfvDEcc.png
How it looks with a resource pack: https://i.imgur.com/1mt5CwV.png

Minecraft: 1.12.2
Modpack: ATM3 - Remix 0.0.2
Thaumcraft: Thaumcraft-1.12.2-6.1.BETA23
Forge: 14.23.4.2759
Resource Pack: Faithful 32 Modded Edition (http://f32.me/)

**Comment by Hubry** [comment]
Seems like the pack contains textures made for TC4 and not TC6 (downloaded it and I still see things like the old research GUI...) - ask them to update, and for now delete the `thaumcraft` folder in the resource pack. Not a Thaumcraft issue.

**Comment by kellixon** [comment]
**Yamza** maybe just delete the file "gui_researchbook.png" in the folder "assets\thaumcraft\textures\gui" Faithful 32 ME, to use the original interface Thaumcraft, and not from resource pack?
