### ISSUE TITLE
Thaumcraft 6 BETA25 Crash on Load

### ISSUE THREAD

**Issue by type0780** [Azanor/thaumcraft-beta#1468]
https://pastebin.com/2LbAg4hj

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)

**Comment by wamc2017** [comment]
I guess this is some issue with the forge version, try downgrading to 14.23.4.2765

**Comment by kreezxil** [comment]
Confirmed for build 2768 too

6.1beta25 crashes dedicated server Forge 1.12.2 build 2768

Notes:
     on startup

crash report:
http://paste.ubuntu.com/p/Qy4dWZDrvw/

fml server latest:
http://paste.ubuntu.com/p/dshG8T9XXX/

**Comment by Charismara** [comment]
Comfirmed for build 2767 too.

**Comment by wamc2017** [comment]
I guess it has something to do with the changes to the PotionHelper in 2767: https://github.com/MinecraftForge/MinecraftForge/commit/0fb884462394fe604ce19f0b3113be81a4b5d805

**Comment by Charismara** [comment]
`java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate`

I think so too.

**Comment by SanAndreasP** [comment]
[Inspirations](https://github.com/KnightMiner/Inspirations) has the same issue. It seems like Forge doesn't like making that class public for whatever reason and breaks the AccessTransformer of the mod.
The only way to use this class now is via Reflection (or having Forge change the class and its field to ```public``` itself)
You can look at my PR on how I fixed it with Reflection, if needed: KnightMiner/Inspirations#90

**Comment by Pythonic-Rainbow** [comment]
![](https://user-images.githubusercontent.com/25037295/46567281-09504180-c963-11e8-9016-1ee0f9e54824.png)

**Comment by Ioandar** [comment]
AE2 needs at least 2768
Thaumcraft crashes with 2768

**Comment by Pythonic-Rainbow** [comment]
@loandar Just use RV6 Stable 1

**Comment by Pythonic-Rainbow** [comment]
> AE2 needs at least 2768
> Thaumcraft crashes with 2768

Just use RV6 Stable 1

**Comment by soylens** [comment]
> Just use RV6 Stable 1
that won't help

**Comment by Ioandar** [comment]
> that won't help
I also reduced forge to 2766 and now it is working for me with  RV6 Stable 1 and TC

**Comment by barcharcraz** [comment]
The latest version of immersive engineering also requires forge 2768.

**Comment by raziel23x** [comment]
Can confirm also breaks on 2769 as well

**Comment by Pythonic-Rainbow** [comment]
With https://github.com/fewizz/NotEnoughIDs/commit/61af55d1e2df0390b0b183f55d7d61505cf8905c being the first commit in 2018, is fewizz returning?! :0

**Comment by Akame-Zero** [comment]
> 
> 
> Can confirm also breaks on 2769 as well

Same here.

**Comment by xAlicatt** [comment]
https://paste.dimdev.org/sofurahiku.mccrash

2769 here.

**Comment by Pythonic-Rainbow** [comment]
Guys just roll back Forge to 2766 and wait Thaumcraft to be updated

**Comment by xAlicatt** [comment]
@Pythonic-Rainbow thanks for the help...i don't think any of us could have figured that out on our own xD

Some other very popular mods have already fixed this issue with their mod and require updating to a newer version of forge...so for those of us running those mods, it's not as simple as rolling back Forge...we have to roll back those other mods too.

**Comment by Ribbons0121R121** [comment]
well i guess the devs better recode the thing to fix it then, right?

**Comment by Too-DAMN-Much** [comment]
why is this issue incorrectly marked as closed? downgrading forge version is not possible as i have mods that explicitly require higher than 2766

**Comment by xAlicatt** [comment]
**https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta25?comment=40705**

**Comment by Pythonic-Rainbow** [comment]
@xAlicatt @Too-DAMN-Much as a mudpack dev with 315 mods , I managed to solve the compatibility. So please, don't say that you can't roll back.

**Comment by xAlicatt** [comment]
@Pythonic-Rainbow Congrats, you want a cookie? 🍪 

I didn't say we CAN'T rollback, I said it's not as simple as rolling back Forge...some of the other mods we are running require newer versions of Forge to load, so those mods have to be rolled back too...which may or may not mean rolling back bug fixes and such. 

I'm sure this issue will be fixed soon. Until then, yes...we all rollback Forge and any mods that have to be rolledback to. That's nothing groundbreaking or anything that modpack devs haven't been doing for years.

**Comment by Too-DAMN-Much** [comment]
you can say whatever you want, you're still wrong, mods explicitly stopped the game loading and stated they require a higher forge version.

**Comment by Pythonic-Rainbow** [comment]
ah I see, we all get the point anyways XD :)

**Comment by DemonfangArun** [comment]
Just ran into this myself. Hoping this can be resolved by either end quickly, I would like to use updated mods instead of rolling back and introducing bugs into an already likely unstable modpack.

**Comment by RecklessJames** [comment]
> Guys just roll back Forge to 2766 and wait Thaumcraft to be updated

Yeah come on guys just rollback and make all of your other mods break, I mean come on are you all stupid or something. It's EASY, a no brainer!  :100:

**Comment by Pythonic-Rainbow** [comment]
Then write a patch and shut your mouth up @RecklessJames

**Comment by Pythonic-Rainbow** [comment]
Also I have to repeat once again

> as a modpack dev with 315 mods , I managed to solve the compatibility. So please, don't say that you can't roll back.

**Comment by TimidTanuki** [comment]
If the compatibility issue is with AE2, roll it back to rv5-stable-11 and then roll Forge back to 2760; this seemed to work for me.

**Comment by Pythonic-Rainbow** [comment]
@TimidTanuki Forge 2766 + AE2 RV6 Stable 1

**Comment by TimidTanuki** [comment]
> @TimidTanuki Forge 2766 + AE2 RV6 Stable 1

Ah, yep, that works too.

**Comment by kreezxil** [comment]
Why are you using NEI? Just use JEI.

**Comment by Pythonic-Rainbow** [comment]
anyways now BETA26 is out , problems are solved , all mods can be updated now!
