### ISSUE TITLE
Crucible and Nitor Inconsistent

### ISSUE THREAD

**Issue by captcookie** [Azanor/thaumcraft-beta#147]
I have tried making nitor from 2 torches and 1 coal then glowstone. 
I have tried 10 torches and 1 glowstone.

Nitor was created once...and cannot be repeated. 

Thaumcraft 6 beta 3 version

**Comment by MainFreak** [comment]
I made over a dozen and it worked fine? Try putting on a pair of goggles of revealing and make sure the correct essentia is there and did not dissipate.

**Comment by synonix** [comment]
Im  having the same problem. And i have plenty of essentia in the crucible so it's supposed to work, and its not working at all.

**Comment by captcookie** [comment]
[](https://cdn.discordapp.com/attachments/237339636568031232/406873912899534848/2018-01-27_12.11.08.png)

**Comment by captcookie** [comment]
so i destroyed my lava block and replaced with netherack and used a flint and steel to power the crucible with fire. it worked.

**Comment by captcookie** [comment]
we fig it out. you can only complete by right clicking only. tossing in glowstone does not work and will set you back.

**Comment by Goof245** [comment]
Tossing in worked fine for me, are you sure you're tossing in from the top, and not hitting the side of the crucible?

**Comment by Azanor** [comment]
Works fine for me.

**Comment by rgz0** [comment]
I see the same behaviour. I have tried with the googles of revealing to see the amount of essentia in the crucible. How I am doing it:
1. Dropping coal and then glowstone to get the the amount of ignis, potentia and lux needed.
2. Dropping glowstone the same way as I dropped before (both dropping it individually and as a stack do not work).

However, in a test world, I was seeing the same behaviour until a certain point that it worked and after that it always worked. 

Should I try a different way? Should I put the items for the essentia using right-click and drop just the catalyst? Does the way I do it matter (right-clicking or dropping, or even dropping with Q or dragging out of my inventory)?

**Comment by terribleperson** [comment]
I've seen the same thing as rgz0, usually when doing bulk crucible alchemy. I'll go to use the catalyst and it'll get dissolved into essentia instead, but if I then add something else in (like dirt) and then the catalyst, I'll get the expected result and can keep using catalysts to get out my product until it runs out of the required essentia.

**Comment by rgz0** [comment]
I found out why it didn't work for me now. I had a mod called `Survival Tweaks` that changed the why the player interacts with objects when right-clicking them, and it seems the catalyst has to be added by right-clicking the crucible with it. 
So right now, after removing that mod, the way it works for me is by dropping the items I want dissolved into essentia and right-clicking with the catalyst. 
@Azanor is that the way it is intended to work? I.e., right-clicking with the catalyst?

**Comment by Goof245** [comment]
Can either right click the top or throw items in. The 'sweet spot' for the items to land in is kinda close to the center of the liquid, so it's pretty easy to accidentally throw items straight over the crucible, or have them land on the edge instead of dissolving.

**Comment by rgz0** [comment]
That's not my issue. What happens to me is that all items I throw are dissolved. Even the catalyst. The catalyst just works as a catalyst if I right-click it. That's why I'm asking if that is the intended behavior
