### ISSUE TITLE
[Beta25] Some infusion particles seem to be missing

### ISSUE THREAD

**Issue by lOmicronl** [Azanor/thaumcraft-beta#1470]
I did several infusions today, after updating to Beta25. And I noticed that the particle effects that are supposed to appear when an item on an outer pedestal gets sucked into the central item are not showing up for me anymore, when they were definitely there on Beta24. This happened on every infusion I did. I made no changes to my instance other than updating Thaumcraft, including not touching the particle settings in the graphics menu.

Could someone perhaps do a quick check if it also happens on your end?

**Comment by wamc2017** [comment]
Hmm, none of the particles show up on my side, with only beta 25, baubles and jei installed...

**Comment by Sora-Canstavia** [comment]
I Also noticed this during my testing yesterday, only noticed the particles for items getting pulled from the outer pedestals were missing, all others seemed to still be present.
