### ISSUE TITLE
slim ball duplication  hedge alchemy  

### ISSUE THREAD

**Issue by Praitor** [Azanor/thaumcraft-beta#1472]
Thaumcraft-1.12.2-6.1.BETA23
&
Thaumcraft-1.12.2-6.1.BETA24
when trying to do the hedge recipes , i cant duplcate the slim balls , in the inventory it shows diffferent to the book crucible to make it and seems to confuse it , i tryied to make it the way the book shows and it wont work the green slime is the reverse of the book , i tryied by dropping in 2 slim balls and it wont work ? blue slim which is slightly different to book.
![slim ball making](https://user-images.githubusercontent.com/43869344/46513745-f1d56380-c851-11e8-8fce-ce75300b3548.png)
![green slim](https://user-images.githubusercontent.com/43869344/46514339-56de8880-c855-11e8-94b5-8e6b78333191.png)
![slimball](https://user-images.githubusercontent.com/43869344/46513753-f4d05400-c851-11e8-8109-e34d6ab28318.png)

**Comment by lOmicronl** [comment]
What is the actual result if you drop in two slime balls? The expected result is that the crucible throws two slimeballs right back at you. What happens in your case?

(The order in which aspects are shown in the book doesn't really matter, by the way. What's important is that there is at least that number of each of them.)

**Comment by androshalforc** [comment]
Looks like its not recognizing the tinkers construct version. Can you get the vanilla versions with your mod pack

**Comment by Praitor** [comment]
tried with both green and blue slim balls none work , tried with using the bottled versions of each didnt work...

**Comment by Praitor** [comment]
well dont know whats going on , removed every mod and put them back one by one  , restoring the saved game i started with every time and now it works ?
