### ISSUE TITLE
[Suggestion] Essentia Visualizer

### ISSUE THREAD

**Issue by CandyKiller2000** [Azanor/thaumcraft-beta#1480]
G'day Azanor,

I was wondering If it was possible to add an Essentia Visualizer. What I have in mind is something that looks similar to an itemframe which displays an Essentia logo. You could place the Visualizer onto Pipes or basically anything that contains Essentia, making it optically more appealing to sorting systems and the like, plus you'd be able to display the current Essentia in a pipe through which multiple Essentia types are able to flow.

I understand if something like this doesn't have priority, for it doesn't add anything to the mod mechanically, but I do believe that neat little visuals would benefit many thaumcrafters.

Cheers,
CandyKiller2000

**Comment by SirMoogle** [comment]
I could see it being useful for pipes, but as far as other containers go, Jar Labels and the Goggles of Revealing already serve that purpose. It sounds like this would only display one essentia at a time?

**Comment by Xobra** [comment]
Something like a Magical Banner, just Itemframe sized?

**Comment by Xobra** [comment]
Actually, "Essentia Item Frames" behaving like Magic Banners feels like a nice Addition, especially for small spaces

**Comment by CandyKiller2000** [comment]
Yes, that's kind of what I have in mind. It would only display one essentia at a time but other than a banner, which you'd have to change manually, it just automatically changes Symbol to the current Essentia type in pipes/containers. The difference to labels is that it doesn't limit any type of essentia to that container, it just displays the contents.
