### ISSUE TITLE
[Suggestion] Alter recipes or allow toggling to select recipe

### ISSUE THREAD

**Issue by SirMoogle** [Azanor/thaumcraft-beta#1490]
Some recipes in the Arcane Workbench are exactly the same with the only difference being they use different vis crystals--two good examples are the Barrier Stone and the Paving Stone of Travel. If I want to craft the recipe that isn't displayed by default I have to remove one of the vis crystal types that would be consumed to force it into my desired recipe. I suggest having one of the recipes altered or adding a button to the interface to toggle the output.

**Comment by apmax** [comment]
What if the button on the interface is actually just the left mouse button while the cursor is over one of the active crystal slots for the current recipe.  If you press that, button, the recipe changes.

**Comment by SirMoogle** [comment]
That's literally what I typed. I'm saying it'd be nice to have another button be available to toggle **without** taking a stack of crystals for the first recipe.

**Comment by apmax** [comment]
Oh, I'm sure it would be trivial to add a small extraneous button to switch recipes,
But don't you think that it would be equally trivial for the player to press the button that's already there on their mouse to accomplish the same task?  It's the same number of mouse clicks from the player in the end, I'm not sure what the point would be.

**Comment by VadersFist0501** [comment]
Directional and Restricted Essentia tube have the same problem.

**Comment by SirMoogle** [comment]
It's two extra mouse clicks: one for depositing the crystals into my inventory, then shift-clicking them back in once I've created what I wanted. Not fun if my inventory's virtually full.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#453
