### ISSUE TITLE
[Suggestion] OreDicting some of the required items for TC Research

### ISSUE THREAD

**Issue by YaibaToKen** [Azanor/thaumcraft-beta#1493]
Allow using any wooden chest for the Hungry Chest research instead of only allowing Oak Chests.

**Comment by Xobra** [comment]
Yeah, especially with mods like Quark etc, it can be annoying if OreDics are forgotten.
Scripts are always a solution if something is not (yet) added.

**Comment by EngineerXL** [comment]
Really need this! Also add UniDict support, please
