### ISSUE TITLE
[Suggestion] Celestial Notes in Research

### ISSUE THREAD

**Issue by Xobra** [Azanor/thaumcraft-beta#1494]
It can be pretty frustrating if you have a good research going, only to either scrap that research, research Alchemy (which you maxed out) or wait 7 in-game days (especially early game) to wait for a moon phase.
Suggesting to add the option to substitute one Moon Phase with another, possible with malus to progress gained, like -10 Progress for each phase difference. (maybe add a minimum, if totally different Phases)
For Example, if Sun + Full Moon gives 40 Progress, Sun + Half Moon give 20, Sun + New Moon gives 5.

Also, as a little Side Suggestion: Extra progress gain or loss, due to accidents or results. For Example, "Result was disappointing",  "Experiment failed", leading to less/ loosing progress. For more progress something like "Discovered new possibilities", "Unexpected, but welcome Results", "Better Compatibility found"

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#452
