### ISSUE TITLE
Getting crashes with numerous versions of Forge

### ISSUE THREAD

**Issue by Lickah** [Azanor/thaumcraft-beta#1495]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Wizardry Plugin (wizardry-0.9.7.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/11/18 8:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.NoSuchFieldError: field_185200_c
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getPotionReagentsRecursive(ThaumcraftCraftingManager.java:338)
	at thaumcraft.common.config.ConfigAspects.getPotionAspects(ConfigAspects.java:692)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:525)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:36)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385868424 bytes (367 MB) / 3405774848 bytes (3248 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2769 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJ  | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJ  | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2769.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                             | 14.23.5.2769             | forge-1.12.2-14.23.5.2769.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | micdoodlecore                     |                          | minecraft.jar                                   | None                                     |
	| UCHIJ  | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar           | None                                     |
	| UCHIJ  | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJ  | astralsorcery                     | 1.9.4                    | astralsorcery-1.12.2-1.9.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJ  | quark                             | r1.5-130                 | Quark-r1.5-130.jar                              | None                                     |
	| UCHIJ  | autoreglib                        | 1.3-20                   | AutoRegLib-1.3-20.jar                           | None                                     |
	| UCHIJ  | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJ  | guideapi                          | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                     | None                                     |
	| UCHIJ  | bloodmagic                        | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                 | None                                     |
	| UCHIJ  | jei                               | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHIEE | thaumcraft                        | 6.1.BETA25               | Thaumcraft-1.12.2-6.1.BETA25.jar                | None                                     |
	| UCHI   | botania                           | r1.10-356                | Botania+r1.10-356.jar                           | None                                     |
	| UCHI   | chameleon                         | 1.12-4.0.1               | Chameleon-1.12-4.0.1.jar                        | None                                     |
	| UCHI   | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
	| UCHI   | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| UCHI   | chiselsandbits                    | 14.24                    | chiselsandbits-14.24.jar                        | None                                     |
	| UCHI   | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | cofhcore                          | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHI   | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | compactmachines3                  | 3.0.12                   | compactmachines3-1.12.2-3.0.12-b215.jar         | None                                     |
	| UCHI   | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHI   | endercore                         | 1.12.2-0.5.39            | EnderCore-1.12.2-0.5.39.jar                     | None                                     |
	| UCHI   | thermalfoundation                 | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermalexpansion                  | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.36-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | enderio                           | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderiointegrationtic             | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | twilightforest                    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
	| UCHI   | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHI   | conarm                            | 1.1.2                    | conarm-1.12.2-1.1.2.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI   | cucumber                          | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                       | None                                     |
	| UCHI   | enderiobase                       | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderioconduits                   | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderioconduitsappliedenergistics | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderioconduitsopencomputers      | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderioconduitsrefinedstorage     | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderiointegrationforestry        | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderiointegrationticlate         | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderiomachines                   | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | enderiopowertools                 | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                       | None                                     |
	| UCHI   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.3.jar                      | None                                     |
	| UCHI   | forgelin                          | 1.7.4                    | Forgelin-1.7.4.jar                              | None                                     |
	| UCHI   | galacticraftcore                  | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar           | None                                     |
	| UCHI   | galacticraftplanets               | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar       | None                                     |
	| UCHI   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHI   | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHI   | librarianlib                      | 4.15                     | librarianlib-1.12.2-4.15.jar                    | None                                     |
	| UCHI   | minecolonies                      | 1.12.2-0.9.4-RELEASE     | minecolonies-1.12.2-0.9.4-RELEASE-universal.jar | None                                     |
	| UCHI   | harvestcraft                      | 1.12.2z                  | Pam's+HarvestCraft+1.12.2z.jar                  | None                                     |
	| UCHI   | projecte                          | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                       | None                                     |
	| UCHI   | thermaldynamics                   | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | simplyjetpacks                    | 2.2.9.58                 | SimplyJetpacks2-1.12.2-2.2.9.58.jar             | None                                     |
	| UCHI   | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
	| UCHI   | thermalcultivation                | 0.3.1                    | ThermalCultivation-1.12.2-0.3.1.8-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermalinnovation                 | 0.3.1                    | ThermalInnovation-1.12.2-0.3.1.8-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
	| UCHI   | wizardry                          | 0.9.7                    | wizardry-0.9.7.jar                              | None                                     |
	| UCHI   | immersiveengineering              | 0.12-85                  | ImmersiveEngineering-0.12-85.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI   | llibrary                          | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHI   | jurassicraft                      | 2.1.17                   | JurassiCraft-1.12.2-2.1.17.jar                  | None                                     |
	| UCHI   | librarianliblate                  | 4.15                     | librarianlib-1.12.2-4.15.jar                    | None                                     |

	Loaded coremods (and transformers): 
Wizardry Plugin (wizardry-0.9.7.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.59' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF

**Comment by xAlicatt** [comment]
1. Crash reports need to be pasted somewhere like pastebin or hastebin and then linked here

2. This has already been reported multiple times and is being worked on.

**Comment by Zarepheth** [comment]
The main issue for this problem appears to be [#1468]( https://github.com/Azanor/thaumcraft-beta/issues/1468)
