### ISSUE TITLE
[Suggestion] - *Really* need an advanced version of the `BREAK` Seal

### ISSUE THREAD

**Issue by VadersFist0501** [Azanor/thaumcraft-beta#1499]
The break seal is great... I love it, but it needs to have a variant allowing for more whitelistable items. Currently, only allowing 1 item means I need 3 different seals for the particular task I need them to do at the moment, and finding an anchor point for the seals is getting difficult.

**Comment by LumberWizard** [comment]
Suggestions go in https://github.com/Azanor/thaumcraft-suggestions.

**Comment by VadersFist0501** [comment]
When did that become a thing? Cool.
