### ISSUE TITLE
basic thaumaturgy

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#15]
basic thaumaturgy research doesnt progress beyond the point where you craft the first fire focus. when you craft the focus the research page doesnt give you the option to complete the stage. I noticed that the tooltip on the focus in the research page is for a fire focus with 0 vis cost, could this be the source of the problem?

**Comment by fingersome** [comment]
I had this problem too. It asks you to "craft" a focus, (but the focus shown has a casting cost of 0 vis? I don't know if that's relevant or not...?) and yet after creating one in the focal manipulator it doesn't seem to register the task as completable in the thaumonomicon, so I can't access the other thaumonomicon entries in the thaumaturgy tab.

**Comment by Azanor** [comment]
Yeah, it will be fixed in the next release. I expanded the NBT data in the foci a bit, but never updated the required item in the research with the new tags.
