### ISSUE TITLE
[B03] Eldritch Research

### ISSUE THREAD

**Issue by MainFreak** [Azanor/thaumcraft-beta#150]
After scanning some cultists and their equipment I unlocked the "Delving into the Eldritch" research, however it is completely empty. Is this just the unfinished part or is this an issue?
![2018-01-27_23 01 39](https://user-images.githubusercontent.com/20734190/35476776-0db6c2e4-03b6-11e8-9ac7-246b6ff6cc08.png)

**Comment by LordPinkerton** [comment]
According to the release notes/change log: "Currently the Eldritch tier of research is still heavily WIP. There is some things I need to sort out and balance before I can implement it. Since everything else is done I will move on to beta anyway."

**Comment by MainFreak** [comment]
Yeah I was aware of that much but if the research can not be viewed or does not exist at all it should not be shown in the visible part of the Thaumonomicon for now.

**Comment by LordPinkerton** [comment]
Being a work in progress, why not? It's a placeholder.

**Comment by nnystyxx** [comment]
What's more eldritch than an unexpected, totally blank page?

**Comment by Azanor** [comment]
Hehe

**Comment by Yadokingu** [comment]
Is this still tbd? Just asking since this issue is from feburary and I'm still getting the research.BASEELDRITCH.stage.1 text. 
If it still needs to be done could you maybe replace it with an error message in the meantime? It's a bit hard to puzzle out what is a bug and what just isn't done yet.
