### ISSUE TITLE
Thaumcraft-6.1.BETA crashes Forge Server

### ISSUE THREAD

**Issue by Airrocket** [Azanor/thaumcraft-beta#1501]
I'm trying to set up a modded server with Thaumcraft and it continues to crash the Forge server. I'm using version 1.12.2-14.23.5.2769 of Forge and I've tried 6.1.BETA10 to 6.1.BETA25 of Thaumcraft on Ubuntu Server 18.04.1 with Java version 8 update 181.

The crash reports are as follows: 
https://pastebin.com/NHJR0Hxt - Thaumcraft BETA25 and Baubles 1.5.2
https://pastebin.com/RP1Pa9bx - Thaumcraft BETA25 and 51 mods

Here is my mod list:
https://pastebin.com/s81Zkc5p

Sorry if an issue report like this has already been created, I didn't see one anywhere.

**Comment by Agrax** [comment]
You ppl can't use a search module? -.- #1473 dupe. You can close it now. Azanor have already fixed that in dev, but there's some other minor issues he has to deal with before releasing beta26. Just wait

**Comment by Xobra** [comment]
The problem with dupe problems is probably that most can't "read" Crash Logs.

**Comment by Airrocket** [comment]
Xobra, you're right, I can't.
