### ISSUE TITLE
Brass Block oredict has an incorrect item in it

### ISSUE THREAD

**Issue by terrapin47** [Azanor/thaumcraft-beta#1503]
The oredict `blockBrass` has the correct thaumcraft brass block in it, but also contains an item with incorrect metadata `thaumcraft:metal_brass:4`.  This item shows up first in the oredict, and causes issues with processes that use the first item in the oredict, causing it to output a missing texture block.

**Comment by Azanor** [comment]
Yeah, that must be in an older version.
