### ISSUE TITLE
Server crash on Beta 26

### ISSUE THREAD

**Issue by kencinder** [Azanor/thaumcraft-beta#1505]
Appears to be an Infusion Altar responsible?

https://gist.github.com/kencinder/7adbbbc1c7f8c7d60ab48e11487f988a

Ran world from production server on a test Forge server to reproduce with only Thaumcraft(And JEI present cause I was going to build an altar if I couldn't locate the problem one)

**Comment by kencinder** [comment]
This was happening with a pre-existing altar on our server, as soon as the chunk was loaded it is in, no user interaction necessary(Even crashed with no users online if loaded by a chunkloader), but I will have the user dismantle it and then try upgrading.

**Comment by ShedX80** [comment]
Yeah Immma wait for an update that fixes this because I cant make the infusion altar until its fixed sadly, there is no point updating versions tbh because you cant use the altar at all, good thing I have backups of every day I opened the server ^^

**Comment by JeremyCooper** [comment]
I am getting this crash too. Crashes as soon as I open an rftools dialing device's UI. I assume this is because it has to behind the scenes load the teleportation points and I have an altar at one of those points.

**Comment by NerdimusPrime** [comment]
Same issue. The instant I place a pedestal in the server I get disconnected and we have to roll back to a save before the pedestal placement.

**Comment by Azanor** [comment]
Whoops

**Comment by ShedX80** [comment]
Azanor I love you! ♡♡♡ you're amazing!!! Glad you seen this post I did my best to explain the problem and I'm pretty sure it has something to do with the pedestal

**Comment by Azanor** [comment]
I've uploaded a hotfix for b26 that should fix the particle crash on servers. Version remains the same, you just need to download the newer version of the file.

**Comment by NerdimusPrime** [comment]
Thank you!

**Comment by kencinder** [comment]
Thanks Azanor, this is fixed so I'll close.
