### ISSUE TITLE
[Suggestion] allow cultivation of vishrooms for praecantatio essence

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#151]
With netherwarts now giving alkimia the previous common source of praecantatio is gone. Sure you can centrifuge it from it, but i'd much rather have vishrooms spreading like a mushroom, maybe even give them a "big mushroom" variant :]

**Comment by LordPinkerton** [comment]
This would be interesting. I do know that Praecantatio is significantly more scarce in TC6, which I like. Once you've progressed midgame, honestly, just use junk essentia like Herba and others to make crystals to mass produce Salis Mundus. It's cheap and provides a decent amount.

**Comment by MalkContent** [comment]
I mean i guess i don't have trouble producing Salis Mundus. It's just that there is no natural occuring thing anymore that has Praecantatio on it, enchanted items aside. But dammit man, shh, i just want mah mushrooms :D

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#159
