### ISSUE TITLE
Incompatibility with metal chests

### ISSUE THREAD

**Issue by TimGoll** [Azanor/thaumcraft-beta#1510]
I have a compatibility problem with another mod and he says it is on your side: https://github.com/T145/metalchests/issues/43

**Comment by wamc2017** [comment]
Have you updated Thaumcraft to beta 26 and forge to 14.23.5.2768? The MixPredicate error was definitely fixed in b26, can you provide a newer crashlog?

**Comment by TimGoll** [comment]
Yes. And the dev of the mod has changed his mind and fixed it!
-------- Ursprüngliche Nachricht --------Von: wamc2017 <notifications@github.com> Datum: 18.10.18  20:39  (GMT+01:00) An: Azanor/thaumcraft-beta <thaumcraft-beta@noreply.github.com> Cc: Tim Goll <tim@timgoll.de>, Author <author@noreply.github.com> Betreff: Re: [Azanor/thaumcraft-beta] Incompatibility with metal chests (#1510) 
Have you updated Thaumcraft to beta 26 and forge to 14.23.5.2768? The MixPredicate error was definitely fixed in b26, can you provide a newer crashlog?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azanor/thaumcraft-beta","title":"Azanor/thaumcraft-beta","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Azanor/thaumcraft-beta"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wamc2017 in #1510: Have you updated Thaumcraft to beta 26 and forge to 14.23.5.2768? The MixPredicate error was definitely fixed in b26, can you provide a newer crashlog?"}],"action":{"name":"View Issue","url":"https://github.com/Azanor/thaumcraft-beta/issues/1510#issuecomment-431116935"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Azanor/thaumcraft-beta/issues/1510#issuecomment-431116935",
"url": "https://github.com/Azanor/thaumcraft-beta/issues/1510#issuecomment-431116935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Azanor/thaumcraft-beta] Incompatibility with metal chests (#1510)",
"sections": [
{
"text": "",
"activityTitle": "**wamc2017**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wamc2017",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Azanor/thaumcraft-beta\",\n\"issueId\": 1510,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Azanor/thaumcraft-beta\",\n\"issueId\": 1510\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Azanor/thaumcraft-beta/issues/1510#issuecomment-431116935"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 397912832\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by liach** [comment]
@timgoll you should close this issue then

**Comment by liach** [comment]
on top right you should be able to choose close from a list of options, i mean.

**Comment by TimGoll** [comment]
I haven't seen it. Maybe I'm using an other app than you. I'm using `FastHub`

**Comment by liach** [comment]
it's in the edit dropdown list, in fact.
