### ISSUE TITLE
[TC6 Beta 3] Zombie Brains not giving warp

### ISSUE THREAD

**Issue by ZiaAvenicia** [Azanor/thaumcraft-beta#152]
Sorry if this ends up wasting your time, but in previous versions of TC, Zombie Brains used to give warp when eaten, and currently, in TC6, the brains don't give warp. I'm not sure if this feature was removed, or just hasn't been implemented yet, but I thought I would put this here just in case there was a mistake or something like that that caused them to no longer give warp.

**Comment by Azanor** [comment]
They are adding warp, they were just not giving the normal feedback to the player. Fixed for the next release.

**Comment by ZiaAvenicia** [comment]
Ah, good to know that they still give warp. I'll always be sure to keep a stack or two of them on hand just in case I need a boost in warp for whatever reason.
