### ISSUE TITLE
Crash when powering a stabilizer pointed at a flux rift

### ISSUE THREAD

**Issue by PrincessNothing** [Azanor/thaumcraft-beta#1525]
After reading the entry on the stabilizer I decided to attempt to run it while pointing towards a flux rift. I placed the stabilizer facing the rift with no problem but the moment I placed down a vis generator next to it the server crashed and will no longer come back up without disabling thaumcraft. I tried to replicate this in single-player but could not get the game to crash again.

Crash report is as follows

https://pastebin.com/mS3ytX8D

**Comment by wamc2017** [comment]
You're using beta 16, which is kinda old, update to beta 26...

**Comment by PrincessNothing** [comment]
Whoops. I've been using this version since I made the server so I kinda forgot new versions were still comin out. This fixed the problem, though! Sorry for the obvious solution.
