### ISSUE TITLE
Thaumium Fortress Armor does not unlock

### ISSUE THREAD

**Issue by MainFreak** [Azanor/thaumcraft-beta#153]
I have finished almost all researches that were available to me and scanned almost all pre-netherstar/pre-enderdragon level items, including Crimsons and all Tainted stuff. all tools, armours, ingots, gears and plates etc. were scanned but I still have not been able to unlock elemental tools and the Fortress Armor. After forcefully (via command) unlocking the tools for some reason the armour did unlock as well.

If I did something wrong please tell me.

**Comment by LordPinkerton** [comment]
Right now, as far as I know, the stage 4 of metallury is gated because the Eldrich research is still WIP. That is what's needed to progress into Elemental Tools and Thaumium Fortress Armor research that can't be progressed in without /tc commands. If you force research metallurgy, you should be fine.

**Comment by Goof245** [comment]
Elemental tools shouldn't be gated behind eldrich stuff... To me this looks like two issues (eldrich content unfinished + elemental tools gated incorrectly).

**Comment by LordPinkerton** [comment]
This has actually been reported before and I'm sure it's still on his list of things to do. For now, just console command past metallurgy with /tc research (playername) METALLURGY. Loose ends like this are going to be popping up time to time.

**Comment by Azanor** [comment]
Yup, it is supposed to be gated behind thaumium, but it is set to the wrong stage of the metallurgy research.
