### ISSUE TITLE
Can't disable crystal generation in dimension 0

### ISSUE THREAD

**Issue by HarrisFauntleroy** [Azanor/thaumcraft-beta#1533]
I set my overworld dimension as 7 so all thaumcraft stuff would happen in the Twilight but I still get crystals in the overworld. 

Mainly a problem as I can't hide your crystals with game stages.

https://github.com/Darkhax-Minecraft/Ore-Stages/issues/33#event-1927969373

**Comment by KelleyEngineering** [comment]
Personally I'd love the option to pick and choose what dimensions the crystals spawn in. 

Going to the Twilight forest, Betweenlands or some other dimension and seeing crystals everywhere ruins the feel of those places

**Comment by Tulepeeker** [comment]
Is there a way to blacklist crystals from some dimensions with another mod?
