### ISSUE TITLE
Smelting items too large for essentia smeltery

### ISSUE THREAD

**Issue by minakitty** [Azanor/thaumcraft-beta#1534]
Not necessarily a bug, but since documentation is slim on TC6, not sure where to look.

The issue I have is the tank size for the essentia smeltery.  By design, if the tank doesn't have enough room, the next item won't be smelted.  I'm not sure the size of the tank, but Cyclic mod's 'Automatic Torch' has a total of 411 essentia assigned to it (201 Potentia, 201 Ignis and 11 Metallum), which is presumably well over what the tank can hold (I'd guess maybe 200 or so)

Is there an alternative to smelting this down so I can get something useful from it?  Or is it just trash for me?
![2018-10-27_05 05 07](https://user-images.githubusercontent.com/5273418/47603877-ca803b00-d9a6-11e8-8d23-8660168a01ce.png)

**Comment by apmax** [comment]
You could make a huge batch of something in the crucible.
Just make sure to math out all the ingredients and have a bunch of quartz slivers on hand.

**Comment by Gammaboy45** [comment]
Modded items factor in essentia based on their ingredients unless they have been defined by Thaumcraft. That's probably where the ridiculous amount of essentia points is coming from (I assume it's crafted with a lot of coal? Maybe more than just a lot?). I'd say avoid it if it's too much. If its essentia is derived from the recipe, then you should be able to just use what you used to craft it to obtain what you need. You *could* use it to intentionally make flux in crucibles, though- if you want to get primordial pearls from rifts and whatnot or learn how to craft some flux controlling devices.

**Comment by Azanor** [comment]
Yeah unfortunately you won't be able to smelt down items with that much essentia. The limit in the smeltery exists for a reason.
