### ISSUE TITLE
New translation into Portuguese

### ISSUE THREAD

**Issue by MBaltz** [Azanor/thaumcraft-beta#1538]
Hello, I can do the translation into Portuguese (Brazilian).
I wonder if you would accept it.

**Comment by VadersFist0501** [comment]
He probably would... he is known to accept community materials. I know a guy who retextured the infusion matrix to match the new arcane stone, and Az accepted the change.

**Comment by MBaltz** [comment]
> He probably would... he is known to accept community materials. I know a guy who retextured the infusion matrix to match the new arcane stone, and Az accepted the change.

Thank you for your return!!
