### ISSUE TITLE
FYI crash

### ISSUE THREAD

**Issue by Majestyc2k1** [Azanor/thaumcraft-beta#154]
I got the following crash when clicking on the Golem Press tab in the Thauminomicon. Removing Optifine fixed it.

[Link](https://pastebin.com/TGY7DXE1)

**Comment by LordPinkerton** [comment]
There are still issues I've run into with Optifine as well. For beta mods, it's best not to use it. Also, try and title your issue better. Provide the version, like Beta 3 or B3 and the actual issue briefly. So, something like "Beta 3; Golem Press crash with Optifine".

**Comment by Azanor** [comment]
Not a TC issue it seems.
