### ISSUE TITLE
Iron Golem not craftable

### ISSUE THREAD

**Issue by Kenshij** [Azanor/thaumcraft-beta#1551]
Modpack, Enigmatica 2 Expert

Iron Golem not craftable with other mod iron plates. Ore dict problem.

**Comment by wamc2017** [comment]
It works fine with Immersive Engineerings, Embers, IC2 and Thermal Expansions plates on my side on beta 26. So I think this is a pack specific issue and has something todo with their unification process...

**Comment by Kenshij** [comment]
> It works fine with Immersive Engineerings, Embers, IC2 and Thermal Expansions plates on my side on beta 26. So I think this is a pack specific issue and has something todo with their unification process...

Ok good to know the recipe is ore dict compatible.

Then my next guess is, the Thaumcraft iron ore plates are removed in the pack and not showing in NEI, don't know if this is interfering with the coding.

**Comment by wamc2017** [comment]
Can confirm that, if I remove the plate from plateIron with crafttweaker, only TCs plates can be used...

**Comment by NillerMedDild** [comment]
And that is also the case in Enigmatica.

It would be nice if the recipe just used `ore:plateIron`, no matter the state of the TC Iron Plate, but I guess that's a design choice :)

**Comment by ChaonicTheDeathKitten** [comment]
Sounds like this problem is resolved. But just saying, if you named the mods in the first place, many people here could have told you, that the mods are, in fact compatible.
