### ISSUE TITLE
Lattice not replaceable as stated in Thaumonomicon

### ISSUE THREAD

**Issue by remclave** [Azanor/thaumcraft-beta#1559]
As stated in the Thaumonomicon: "the filter can be replaced by clicking on the clogged lattice piece with a fresh one."

I've tried right click, left click, shift and ctrl of same and none of them allow me to achieve what is stated in the book. Only by breaking it can I replace it.

Watching older versions of streams and youtube let's plays show that this issue has been around awhile yet I found no issues previously opened regarding this.

**Comment by androshalforc** [comment]
The filter can be replaced by clicking on the lattice

These are two different items

**Comment by remclave** [comment]
Even so, it still didn't work even to clean the in-place clogged filter. So not sure what to do next.

**Comment by ChaonicTheDeathKitten** [comment]
Are you trying to place a lattice on the clogged lattice, or are you right clicking the clogged lattice with a filter?

**Comment by remclave** [comment]
with a fresh lattice filter in-hand, I tried all combinations I could think of including right-click (placed and attached to clogged filter instead of RE-placing).

The only workaround to keep the structure from collapsing when breaking out the clogged filter involved adding filters to loop around the clogged one and then replacing it by breaking it out and replacing it.

**Comment by androshalforc** [comment]
> with a fresh lattice filter in-hand,

again we are talking about an "essentia filter" not a lattice

**Comment by Azanor** [comment]
Yup, you need to click on it with the filter

**Comment by Gammaboy45** [comment]
that makes sense... no wonder it wasn't working >.>

**Comment by Minamikaze392** [comment]
I think the sentence in Thaumonomicon would be better changed to something like "the filter can be replaced by clicking on the clogged lattice piece with a fresh **Essentia filter**.", with the "Essentia filter" colored to indicate the item name. [Many players](https://www.reddit.com/r/feedthebeast/comments/8z66qw/in_thaumcraft_is_there_a_way_to_clean_flux/) were interpreting the current sentence as clicking with a fresh lattice, including myself.

**Comment by androshalforc** [comment]
As did i at first after attempting to replace a clogged lattice with a fresh lattice ( and being rather upset at the cost) i reread the entry and realized that i needed a filter instead and was much happier

**Comment by remclave** [comment]
Wow! Okay. I, again, have failed in reading 101. I will certainly take another stab at it, this time with the correct resource. In the meantime I am of the same frame of mind as Minamikaze392 in that the wording is misleading in its' current form.

**Comment by wrightleft** [comment]
I too made the same mistake at first. The wording needs to be much clearer.

**Comment by Traask1970** [comment]
Same here - the wording is ambiguous enough to make you think that you're meant to click on the clogged element with an unclogged element. If the wording were more like:

"To clean, use an *Essentia Filter* and right-click on the *Clogged Flux Condenser Lattice*" (Highlighting or recipe linking the two items would be much clearer.

**Comment by remclave** [comment]
With Thaumcraft out of commission, this issue is closed.

**Comment by Serifina** [comment]
It's not out of commission. A team, lead by KingLemming, will be taking care of Thaumcraft in association (and with continued creative direction) of Azanor.

**Comment by remclave** [comment]
I was misinformed. Thank you for the update.
