### ISSUE TITLE
Put the JEI Salis Mundis info page on the uses for Vis Crystals

### ISSUE THREAD

**Issue by aaronhowser1** [Azanor/thaumcraft-beta#1580]
![image](https://user-images.githubusercontent.com/15698722/49842511-70361080-fd81-11e8-882a-1ad763af24f6.png)
This one, so that it shows when looking at recipes that use Vis Crystals.

**Comment by Hallowizer** [comment]
This is not under azanor's control, because this note is from ThaumicJEI, not Thaumcraft. Please post this issue on ThaumicJEI.
