### ISSUE TITLE
[Bug] Crystal textures not showing , Pink box texture

### ISSUE THREAD

**Issue by GlitchOG** [Azanor/thaumcraft-beta#1592]
Any of the crystals are not showing the texture, instead they show as a pink box.

https://imgur.com/a/vVJa8bO

**Comment by wamc2017** [comment]
I guess you got the crystals from an environmental tech void ore miner, in the following issue, you can find a solution how you can configure the metadata correctly:
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/133#issuecomment-434158923

**Comment by GlitchOG** [comment]
i see , i will close the issue and wait for the fix from env tech , until then ill add the id myself. thanks
