### ISSUE TITLE
Odd idea for arcane workbench

### ISSUE THREAD

**Issue by vdrake77** [Azanor/thaumcraft-beta#16]
Pretty much everything has NEI/JEI compatibility... but why not give the arcane workbench thaumonomicon  interaction?  As in, as you determine recipes, anytime you open the arcane table, there's a recipe-list on the side?   Maybe a rolo-thauminomicodex where you can add on non-Thaumcraft recipes to allow for quick crafting.

It'd just be an ease of use thing as opposed to opening worktable, forgetting what you need, closing worktable, opening thaumonomicon, finding the item, closing thaumonomicon, opening worktable again.  Doesn't happen too horribly often but when you're crafting stuff with multiple steps, it can be a bother.

**Comment by gabeernie** [comment]
Maybe a little scroll off to the side you can click to show a list of all crafting recipes

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#174
