### ISSUE TITLE
About touch focus

### ISSUE THREAD

**Issue by NatsuArashi** [Azanor/thaumcraft-beta#162]
Can't "TOUCH" on an entity. 
I want to light up animals without destroying my house.

**Comment by MainFreak** [comment]
Works for me.

**Comment by XoviaHarmile** [comment]
Have to hit them, if you hit the ground it makes a fire block, hitting the entity makes it light on fire without a fire block.

**Comment by NatsuArashi** [comment]
Oh, it works now. 
I must knock it before casting the fire?
That's strange.

**Comment by MainFreak** [comment]
No you have to cast it on the mob, not on the floor. Also make sure you aim at their hitbox properly, apparently 1.10+ has something wonky going on with those.

**Comment by Azanor** [comment]
The range and effective area of the touch medium is a bit low so I will increase it for the next version.
