### ISSUE TITLE
Release Thaumcraft 6 open-source?

### ISSUE THREAD

**Issue by ireece1** [Azanor/thaumcraft-beta#1624]
Since you’ve announced that you’re retiring from Minecraft modding (https://www.patreon.com/posts/sad-farewell-23967282,) do you think that you could release Thaumcraft 6’s source code so that the community can continue development, fix bugs and potentially port it to newer versions of Minecraft?

 You’ve captured lightning in a bottle with this mod, and we are sad to see you go. Long live Azanor, long live Thaumcraft.

**Comment by ulyssedu45** [comment]
it would be a shame to lose mods in the future

**Comment by Serifina** [comment]
It's been announced, and repeatedly noted, that KingLemming (of TeamCoFH), with Azanor's input and continued creative control, will be updating Thaumcraft into future versions.
