### ISSUE TITLE
I can't trade with pech

### ISSUE THREAD

**Issue by mujmajnkraft** [Azanor/thaumcraft-beta#164]
I spawned a pech in my world and fed it with gold blocks. After a while, it stopped picking them up and green particles appeared, so it looked like I befriended it. However, I couldn't trade with it (no GUI opened upon right clicking). I repeated it many times with various rare items, but always with the same result. It picked them up, it looked like it became friendly, but it refused to trade. It worked in previous versions of thaumcraft (4 and 5). Did you change how peches work in this version or is it a bug?

**Comment by captcookie** [comment]
same

**Comment by XoviaHarmile** [comment]
Still can't, though I'd accidentally hit them with the elemental swords chain effect, did you two both attack them beforehand? Because that could be it

**Comment by McFrugal** [comment]
I didn't attack mine.  Couldn't trade with it.  This is with BETA6.

**Comment by Phantom329** [comment]
Same issue on Beta 7
