### ISSUE TITLE
Crafting Issue

### ISSUE THREAD

**Issue by kreezxil** [Azanor/thaumcraft-beta#1641]
The following was reported on my pack [World of Dragons](https://minecraft.curseforge.com/projects/world-of-dragons) at https://github.com/kreezxil/World-of-Dragons/issues/66

---
**Describe the bug**
When throwing an iron ingot in the crucible while 5 Instrumentum are present in the crucible it doesn't get turned into an Alchemical Brass Ingot.

**To Reproduce**

1. Throw e.g. stone shovel in a crucible.
2. Throw an Iron Ingot in the crucible.
3. The Metallum from the Iron Ingot is now in the crucible instead of an Alchemical Brass Ingot coming out of it.

**Versions:**

* Minecraft: 1.12.2
* Forge: 14.23.5.2814
* Mod Pack: World of Dragons-14.21.153.zip
* Mod Name: Thaumcraft
* Mod Version: 6.1.BETA26

**Comment by androshalforc** [comment]
First make sure that the player has completed the research to get alchemical brass. 

If they have not completed the research you wil not get anything. 

Second a number of modpacks have been having a similar issue most notebly stoneblock2 where you need to right-click the catalyst into the crucible

Im fairly certain this is a modpack issue and not a thaumcraft issue

**Comment by Vintschente** [comment]
Right-clicking with the catalyst worked. I was so used to dropping it in too that I didn't even try it out. Thank you very much.

**Comment by kreezxil** [comment]
I am thinking that because this is a popular mod from the 1.7.10 era and many players are return after 4 years of college to find the mechanic of their mod of choice has changed. I'm going to close this but want to suggest bringing back the drop in mechanic too. That way you are covering the old player but also the new player.

**Comment by androshalforc** [comment]
the dropping method works fine in thaumcraft 

Without knowing more about how mods interact i can only assume that some other mod is making a change to the settings to make it only work on right click.
