### ISSUE TITLE
Grappler stuck

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-beta#1653]
Hello! So, I just crafted the Arcane Grappler and charged it, but when I use it, the grappler doesn't reset and it gets stuck on the block I grapple to. If I try to move it pulls be back to the hook. The only way to move is to keep grappling. I've tried to break the block it grapples to and the surrounding blocks, but it just stands there floating in mid-air. It only fixes itself when I restart the game.

https://ibb.co/zrGZpXQ

I'm running the latest version of FTB Revelation, launching via the Twitch app.
It says in the Twitch launcher that it's running Thaumcraft-1.8.9-5.2.4.jar, but when I try to open an issue on this version's page it redirects me here. I hope this is the correct place.

**Comment by androshalforc** [comment]
while im not familiar with 1.89 in the recent version the grappler 'disconnects' when pressing shift (sneaking)

try that or read its entry in the thauminomicon that should tell you the default key for 'disconnecting' it

**Comment by ghost** [comment]
That was indeed the problem. Well don't I feel dumb.
