### ISSUE TITLE
Thaumcraft 6 - Closely examine a climbing creature

### ISSUE THREAD

**Issue by pashkanorm** [Azanor/thaumcraft-beta#1677]
In the Golemancy there is a thing called "Golem Mobility: climbing". I couldn't find any information about the "climbing creature" elsewhere and I've also scanned a lot of creatures.  What should I scan for this upgrade?

**Comment by pashkanorm** [comment]
For some reason regular spiders didn't work out but the spiders in Twilight Forest did the thing.

**Comment by sst3ly** [comment]
It's just a cave spider. Or at least it worked for me.
