### ISSUE TITLE
[BETA3] Aspects tooltips aren't show when any JEI recipe is open

### ISSUE THREAD

**Issue by Buuz135** [Azanor/thaumcraft-beta#169]
Without JEI in any gui it shows:
![](https://i.imgur.com/2D5Muip.png)
Any JEI crafting recipe open:
![](https://i.imgur.com/eeCdGX2.png)

**Comment by Azanor** [comment]
Not something I can fix I believe. JEI uses some sort of voodoo to bypass the events I use to display the tooltips.

**Comment by CaptJSparrow** [comment]
Im useing NEI with JEI and no aspects show for any of the items in just my regular inv. please help i have no idea what items have what aspects

**Comment by Buuz135** [comment]
Yeah @Azanor is using `ItemTooltipEvent` that it seems to trigger only in container GUI. `RenderTooltipEvent` is the way to go

**Comment by CaptJSparrow** [comment]
how would i do that?

**Comment by Buuz135** [comment]
Oh, you don't have to do anything 😛 , just Azanor can

**Comment by CaptJSparrow** [comment]
so the mod is unplayable until the update?
because i cant get it to show at all. im using JEI with NEI

**Comment by mezz** [comment]
Remove NEI
