### ISSUE TITLE
[05:39:55] [Thread-10/INFO] [THAUMCRAFT]: Stopping aura thread for dim 1

### ISSUE THREAD

**Issue by Xoulious** [Azanor/thaumcraft-beta#1703]
There's a closed thread explaining nearly the exact issue I'm experiencing;  The only mods I have installed on my server are B26 Thaumcraft & Baubles 1.5.2, and I've been completely unable to find any information on this server breaking issue outside of the closed thread #1230 which explains the issue pretty clearly.

(Note that before when I had other mods installed it always broke on the last dimension, regardless of how many there were)

**Comment by Mabedin00** [comment]
Did you find a solution?
