### ISSUE TITLE
'Infusion enchantment' doesn't accept sharpness 1 book

### ISSUE THREAD

**Issue by XoviaHarmile** [Azanor/thaumcraft-beta#173]
![screen shot 2018-01-29 at 6 54 06 pm](https://user-images.githubusercontent.com/35862073/35499283-ceaf8948-0525-11e8-946a-8d8adf761b59.png)

**Comment by Ulysses2** [comment]
There's a typo in the json entry for this research. The NBT tag on the book the research calls for is {StoredEnchantments:[{id:16,lvl:1}]}, but the NBT for obtainable Sharpness books is {StoredEnchantments:[{id:16**s**,lvl:1}]}. The research for Runic Shielding has a similar typo, but the one for the Break focus effect uses the correct format.

**Comment by Ulysses2** [comment]
Welp. I made a typo too. The correct NBT tag was supposed to be {StoredEnchantments:[{id:16s,lvl:1s}]}. I hope I didn't throw off your bugfixing efforts.
