### ISSUE TITLE
Tainted snowman can't attack

### ISSUE THREAD

**Issue by XoviaHarmile** [Azanor/thaumcraft-beta#174]
![screen shot 2018-01-29 at 8 20 04 pm](https://user-images.githubusercontent.com/35862073/35502682-dbd2b1fc-0531-11e8-8496-05e8b1763d1f.png)
My snowman that I made to start golemancy somehow became tainted, it follows me but does no damage.

**Comment by mujmajnkraft** [comment]
It's probably work of CIA

**Comment by XoviaHarmile** [comment]
Also, is it normal that the texture of taint keeps moving?

**Comment by Ulysses2** [comment]
Tainted mobs seem heavily WIP at the moment, I'm sure they'll get sorted out before the release version.
