### ISSUE TITLE
B3: Thaumonomicon not accepting Fortune II book for break focus

### ISSUE THREAD

**Issue by Goof245** [Azanor/thaumcraft-beta#175]
Spent hours making a Fortune II book, only to find it won't actually work to unlock this research. My book is yellow, apparently it wants a blue one?

![2018-01-29_23 49 01](https://user-images.githubusercontent.com/3851003/35513639-80af8ce6-054f-11e8-99bb-99b9f14dcf87.png)

![2018-01-29_23 48 50](https://user-images.githubusercontent.com/3851003/35513638-7fb45358-054f-11e8-92d2-e42bacdad0f5.png)

**Comment by MainFreak** [comment]
it does not work for me at all. When I spawn in a book with Fortune it is the yellow variant, if I enchant it normally I get a blue one but it has multiple enchantments and is not accepted by the book.

**Comment by LordPinkerton** [comment]
You can get the single enchant blue books from villager trades.

**Comment by Goof245** [comment]
Villagers are still giving me yellow books. Even if the books I enchant have multiple enchants on them, the name of the book is _still_ yellow...
