### ISSUE TITLE
Golems are not working with the seal harvest on the server

### ISSUE THREAD

**Issue by EternalVitae** [Azanor/thaumcraft-beta#1755]
I know English very poorly, so I have to use a translator, sorry (((

Having installed thaumcraft on server 1.12.2, I encountered a problem that golems do not interact with harvest seal, this problem is not observed when exporting a world in a single player game, what could be the reason, how can I fix it?

**Comment by D4ll4S2** [comment]
Same here

**Comment by EternalVitae** [comment]
> Same here

I deleted the taumiс restoration from the mod server and the problem disappeared, golems began to respond to the bell faster, problems with the golem press disappeared

Please answer if this method helps you
