### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by glingy** [Azanor/thaumcraft-beta#1771]
I notice this repository has not been updated in the past two years. Is Thaumcraft dead? If so, is there a way I can access the source code to fix a bug myself and use locally?

**Comment by Serifina** [comment]
Azanor is no longer modding Minecraft. KingLemming (and a team he assembles) will be porting and updating Thaumcraft, but that is on hold while KL gets Thermal Expansion updated. The mod is closed-source and there is no way to access to the source code.

**Comment by glingy** [comment]
I'm unfamiliar with mod authors, but if KingLemming was one of the authors of Thermal Expansion, I'm excited to see how this turns out. Thanks for the update!
