### ISSUE TITLE
[B26] Arcane Workbench says 0 vis available, even though both thaumometer and thaumic dioptra say otherwise

### ISSUE THREAD

**Issue by Chris-The-Lion** [Azanor/thaumcraft-beta#1776]
basically the title says it all, no matter where i go, be it magical forest with 3 silverwood trees near my location, or my base with slightly less vis in it, the thaumometer shows a large ambient vis level, along with a (cheated in since i cant craft it) thaumic dioptra that shows tons of vis in every chunk in and around me, yet the table cant see it for some reason so i cannot progress in the mod at all. There seem to be similar issues from earlier versions but i didn't see anything helpful in those fixes... I'm wondering if it is because of the addons i have for Thaumcraft, maybe someone knows of an addon problem that just hasn't been brought up yet. my current mod list is as follows

- ae2stuff-0.7.0.4-mc1.12.2.jar         - AE2WTLib-1.12.2-1.0.34.jar          - AkashicTome-1.2-12.jar
- Animus-1.12-2.1.5.jar                    - infinity-1.10.jar                             - Apotheosis-1.12.2-1.12.0.jar
- AppleCore-mc1.12.2-3.2.0.jar         - AppleSkin-mc1.12-1.0.9.jar          - appliedenergistics2-rv6-stable-7.jar
- armoryexpansion-1.3.1.jar          - Aroma1997Core-1.12.2-2.0.0.2.jar   - Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar
- AromaBackup-1.12.2-2.1.1.4.jar     - astralsorcery-1.12.2-1.10.19.jar    - AttributeFix-1.12.2-1.0.4.jar
- AutoRegLib-1.3-32.jar                    - Baubles-1.12-1.5.2.jar                  - bdlib-1.14.3.12-mc1.12.2.jar
- BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar                              - BetterFps-1.4.8.jar
- BiblioCraft[v2.4.5][MC1.12.2].jar      - binnie-mods-1.12.2-2.5.1.188.jar  - BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
- BloodArsenal-1.12.2-2.2.0-28.jar     - BloodMagic-1.12.2-2.4.1-103.jar   - bonsaitrees-1.1.3-b156.jar
- Bookshelf-1.12.2-2.3.585.jar            - Botania r1.10-361.jar                   - BotanicAdditions-1.12.2-4r.jar
- ChanceCubes-1.12.2-4.0.0.271.jar   - Chisel-MC1.12.2-0.2.1.35.jar         - chiselsandbits-14.33.jar
- Chunk Pregenerator V1.12-2.1.jar    - Clumps-3.1.2.jar                          - CodeChickenLib-1.12.2-3.2.2.353-universal.jar
- CTM-MC1.12.2-0.3.3.22.jar             - conarm-1.12.2-1.2.4.jar                - CookingForBlockheads_1.12.2-6.4.71.jar
- CraftingTweaks_1.12.2-8.1.9.jar        - Cucumber-1.12.2-1.1.3.jar           - Cyclic-1.12.2-1.19.13.jar
- CyclopsCore-1.12.2-1.4.0.jar            - Decocraft-2.6.2_1.12.2.jar             - defiledlands-1.12.2-1.4.2.jar
- DimensionalDoors-3.0.9-287.jar      - DoomlikeDungeons-1.12.10-MC1.12.2.jar
- DummyCoreUnofficial-2.4.112.5.jar  - DynamicSurroundings-1.12.2-3.5.4.3.jar
**_- enchantingwiththaumcraft-1.2.jar_**                                                  - EnchantmentDescriptions-1.12.2-1.1.15.jar
- EnderStorage-1.12.2-2.4.5.135-universal.jar                                           - engineers_doors-1.12.2-0.8.0.jar
- EvilCraft-1.12.2-0.10.76.jar               - ExtraBitManipulation-1.12.2-3.4.1.jar
- ExtraCells-1.12.2-2.6.2a.jar               - fairylights-2.1.9-1.12.2.jar             - FarmingForBlockheads_1.12.2-3.1.28.jar
- FastLeafDecay-v14.jar                       - foamfix-0.10.5-1.12.2.jar               - forestry_1.12.2-5.8.2.387.jar
- gravestone-1.10.1.jar                        - Growable Cells-1.12.2-3.1.0.jar     - Guide-API-1.12-2.1.8-63.jar
- HammerCore-1.12.2-2.0.5.5.jar         - Hats-1.12.2-7.0.2.jar                     - fortunate-1.12.2-2.12.jar
- HuntingDimension-1.12.2-1.0.39.jar  - Hwyla-1.8.26-B41_1.12.2.jar        - iChunUtil-1.12.2-7.2.1.jar
- ImmersiveEngineering-0.12-89.jar     - ImmersiveEngineering-0.12-89.jar  - immersivetech-1.12-1.3.10.jar
- instantunify-1.12.2-1.1.2.jar               - inventorypets-1.12-2.0.1.jar         - InventoryTweaks-1.63.jar
- IronBackpacks-1.12.2-3.0.8-12.jar     - ironchest-1.12.2-7.0.72.847.jar      - jeibees-0.9.0.5-mc1.12.2.jar
- journeymap-1.12.2-5.5.4.jar               - JustEnoughEnergistics-1.12.2-1.0.7.jar
- jehc-1.12.2-1.6.4.jar                           - jei_1.12.2-4.15.0.268.jar                - JustEnoughResources-1.12.2-0.9.2.60.jar
- LootBags-1.12.2-2.5.8.5.jar                - LucraftCore-1.12.2-2.4.5.jar          - MagicBees-1.12.2-3.1.10.jar 
- malisiscore-1.12.2-6.5.1.jar                - malisisdoors-1.12.2-7.3.0.jar          - Mantle-1.12-1.3.3.55.jar
- mcjtylib-1.12-3.5.3.jar                        - MikesModsLib-1.0.2.jar                 - moartinkers-0.6.0.jar
- ModFix-1.12.2-1.0.0.1.jar                   - moreoverlays-1.15.1-mc1.12.2.jar  - Morph-1.12.2-7.1.3.jar
- MouseTweaks-2.10-mc1.12.2.jar        - mystagradcompat-1.2.jar               - MysticalAgradditions-1.12.2-1.3.2.jar
- MysticalAgriculture-1.12.2-1.7.5.jar    - natura-1.12.2-4.3.2.69.jar              - NoFog-1.12.2b3.jar
- notenoughwands-1.12-1.8.1.jar         - NotEnoughIDs-1.5.4.4.jar               - obfuscate-0.2.6-1.12.2.jar
- OreLib-1.12.2-3.5.2.2.jar                    - overloadedarmorbar-1.0.4g.jar       - p455w0rdslib-1.12.2-2.3.161.jar
- pamscookables-1.1.jar                        - Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar
- phosphor-1.12.2-0.2.6+build50-universal.jar                                              - Placebo-1.12.2-1.6.0.jar
- ProjectE-1.12.2-PE1.4.1.jar                  - Psi-r1.1-77.jar                                - PTRLib-1.0.4.jar
- QuantumStorage-1.12-4.7.0.jar          - railcraft-12.0.0.jar                           - randomloot 1.5.jar
- RebornCore-1.12.2-3.16.4.478-universal.jar                                                 - RebornStorage-1.12.2-3.3.4.1.jar
- refinedstorage-1.6.16.jar                     - refinedstorageaddons-0.4.5.jar       - Reliquary-1.12.2-1.3.4.796.jar
- Forgelin-1.8.3.jar                                 - simplylight-0.7.0.jar                        - SlashBlade-mc1.12-r33.jar
- SolarFluxReborn_1.12.2-4.35r.jar         - spatialservermod-1.3.jar                 - Surge-1.12.2-2.0.77.jar
- Tails-1.12-1.10.0.jar                             - **_Thaumcraft-1.12.2-6.1.BETA26.jar_**  
- **_tc6aspects4jei-0.0.2a.jar_**             - _**ThaumicAugmentation-1.12.2-2.0.9.jar**_
- **_thaumicbrewing-1.0.2.jar_**            - **_thaumicenergistics-2.2.4.jar_**   - **_ThaumicEquivalence-1.12.2-1.0.5.jar_**
- **_Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar_**                                           -  **_ThaumicGrid-1.0.12.jar_**
- **_ThaumicInventoryScanning_1.12.2-2.0.10.jar_**                                       - **_ThaumicJEI-1.12.2-1.6.0-27.jar_**
- **_Thaumickatana_V1.0.8_MC1.12.2.jar_**                                                    - **_thaumicperiphery-0.3.1.jar_**
- **_thaumicspeedup-1.4.jar_**             - **_ThaumicTerminal-1.0.12.jar_**      - **_thaumictinkerer-1.12.2-5.0-620a0c5.jar_**
- **_thaumicwands-1.2.6.jar_**             - twilightforest-1.12.2-3.8.689-universal.jar 
- weirdinggadget-1.12.2-2.1.16-universal.jar                                                    - tinkersjei-1.2.jar
- bloodtinker-1.0.5.jar                           - TConstruct-1.12.2-2.12.0.157.jar       - tinkersdefense-1.4.2.28.jar
- TinkersComplement-1.12.2-0.4.2.jar   - TinkerToolLeveling-1.12.2-1.1.0.jar    - tinyprogressions-1.12.2-3.3.34-Release.jar
- ToolBelt-1.12.2-1.9.13.jar                   - totaltinkers-0.2.0.jar                          - Totemic-1.12.2-0.11.6.jar
- travellersboots-1.12.2-1.0.3.jar           - Trinkets and Baubles-1.12.2-0.27.jar  - UniDict-1.12.2-2.9.2.jar
- VanillaFix-1.0.10-99.jar                       - veining-1.3.2-1.12.x.jar                       - WailaHarvestability-mc1.12-1.1.12.jar
- WanionLib-1.12.2-2.2.jar                    - Wawla-1.12.2-2.5.273.jar                    - Waystones_1.12.2-4.0.72.jar
- WirelessCraftingTerminal-1.12.2-3.12.97.jar

(didn't realize i had _that_ many addons for Thaumcraft till making this list...) for ease of reading i highlighted the Thaumcraft related addons, any help would be appreciated

here are some screenshots to assist with the issue, as you can see the dioptra shows tons of vis everywhere but the table says nothing. 
![2020-11-03_19 29 02](https://user-images.githubusercontent.com/39244177/98058327-69e82c00-1e12-11eb-8065-ea14362f5a09.png)
![2020-11-03_19 29 15](https://user-images.githubusercontent.com/39244177/98058347-78364800-1e12-11eb-9a2c-cb7e1e73b7cb.png)

**Comment by caspaas** [comment]
thaumicwands-1.2.6.jar 
check the mod description of this addon please.

**Comment by caspaas** [comment]
This can be closed!

**Comment by Chris-The-Lion** [comment]
will do

Edit: yep that would definitely explain my issue... now how to actually *use* it...
