### ISSUE TITLE
Infusion and Thaumic JEI

### ISSUE THREAD

**Issue by Danymaddox** [Azanor/thaumcraft-beta#178]
Hi! If you have Thaumic JEI instaled the Infusion altar does not work.

**Comment by MainFreak** [comment]
Belongs over [here](https://github.com/Buuz135/Thaumic-JEI/issues)

Also Thaumic JEI shows recipes regardless of your research progress. Make sure you have unlocked everything it shows you in your Thaumonomicon.

**Comment by Danymaddox** [comment]
Yeah, I was in creative mode with everyting unlocked. I removed Thaumic JEI and works, I put Thaumic JEI and does not work, so there's an incompatibility

**Comment by MainFreak** [comment]
that's still most likely an issue of Thaumic JEI and not Thaumcraft.

**Comment by Danymaddox** [comment]
Oh, sorry then. I assumed that as Thaumcraft is the one that does not work was his problem. I'll report it to the Author

**Comment by Buuz135** [comment]
Thaumic JEI is a client side mod, it doesn't interact with server side stuff like recipes, and it does work https://imgur.com/o2OnkfS.gifv

**Comment by Danymaddox** [comment]
Well, is not working for me: https://www.youtube.com/watch?v=JRnGv72udpA&feature=youtu.be

If i remove Thaumic JEI it works

**Comment by Buuz135** [comment]
First of all, you said any recipe, and that's not true, just armor upgrading ones, it would have been more helpful if you were more specific about stuff, sorry!

**Comment by Danymaddox** [comment]
I tried several recipes... and now I realise that all was for armor :S Sorry dude, I didnt try every recipe

**Comment by Buuz135** [comment]
I have it fixed, this issue can be closed

**Comment by Danymaddox** [comment]
Thanks!
