### ISSUE TITLE
Thaumcraft 6 BETA 3: Thaumatorium multiblock does not form

### ISSUE THREAD

**Issue by welch3694** [Azanor/thaumcraft-beta#180]
Tested with a fresh install and only Thaumcraft on 1.10.2. Placing a crucible and stacking 2 alchemical constructs on top of it does not cause the Thaumatorium to form. Granting myself all research and breaking/re-placing does not cause Thaumatorium to form. Right-clicking with caster's gauntlet does nothing.

![image](https://user-images.githubusercontent.com/1097586/35538074-9e490c58-051a-11e8-90a4-14ce31243a33.png)

**Comment by VocableWAZZAM** [comment]
Have you tried using Salis Mundus on it?

**Comment by LordPinkerton** [comment]
Correct, even the Thaumonomicon says to use Salis Mundus, at least for the Infusion Altar, Crucible, and Infernal Furnace. It is missing from the Alchemical Automation entries, but it can be mostly inferred.

**Comment by welch3694** [comment]
Gotcha, no I did not try Salis, but as noted the pages don't say that you have to, so for those like me that are too dumb to think of it, please update the text!

**Comment by Azanor** [comment]
I will update the research entry to make things a bit more clear.
