### ISSUE TITLE
No versions above 1.12.2

### ISSUE THREAD

**Issue by BraveCaperCat2** [Azanor/thaumcraft-beta#1805]
Where is the version(s) for 1.16, 1.19 and all versions in between (please update your mod to the latest version)

**Comment by badgeminer** [comment]
@Azanor  has stoped developing mods as of november 2018, but COHF is developing a new version for modern minecraft, I would recomend joining [https://discord.gg/teamcofh](https://discord.gg/teamcofh) for updates on thaumcraft 7

**Comment by BraveCaperCat2** [comment]
I do not use discord.
