### ISSUE TITLE
(Concept Idea) Witches's Broom

### ISSUE THREAD

**Issue by SimulatorSia** [Azanor/thaumcraft-beta#183]
Late game fast witches's broom that has purple lightning around it as to signify thaumcraft theme but it doesn't go up fast and maybe even stalls like a plane of you go straight up and it mustn't require any fuel/essentia to keep going.

No magic mods updated past 1.10 carry a witches broom, I mean a witches's broom is one of the core ideas when it comes to magic. Maybe it's really hard to obtain or you have to carry the latest game wand or even craft it with a jar containing the most powerful node you could make. Reason it shouldn't require fuel is because if it does it'll be obsolete/never used compared to any Extra Utilities 2 Wing Rings or Botania's Flügel Tiara because players are typical when it comes to anything slightly tedious to maintain.

(Just suggestion is all)

**Comment by LordPinkerton** [comment]
Eh, not a witch's broom, just bring back the Thaumostatic Harness with some upgrade options.

**Comment by nnystyxx** [comment]
I have an idea: powering a Thaumostatic Harness with other Essentia than Potentia, or in combination with it, should produce varying forms of locomotion.

Fire: Jetpack, faster upward momentum
Motus: Nearly no upward momentum, greatly increases walk/sprint speed
Aqua: High mobility in water
Alienis: Turns into a jump drive that warps through objects/ceilings/floors when triggered

And so on.

**Comment by MainFreak** [comment]
Would actually be fun, maybe Volatus for normal acceleration but slower descend and faster ascend.

**Comment by SimulatorSia** [comment]
I like idea of there's too ^
:>

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#158
