### ISSUE TITLE
Unable to progress Golemancy due to GUI bug

### ISSUE THREAD

**Issue by Janner3D** [Azanor/thaumcraft-beta#186]
![image](https://user-images.githubusercontent.com/35965176/35573629-8c25f5f8-05cf-11e8-861f-753a1bceb21b.png)

This seems to be halting my progress. Apparently it's solvable by an admin command I hear, If so, what's the command to enable it?

**Comment by LordPinkerton** [comment]
Just the text is missing, but that shouldn't be stopping you from progressing to Clockwork Minds. The unlock requirements are the Essentia Smeltery and Hedge Alchemy. Make sure you've completed those two first in the Alchemy tab.
