### ISSUE TITLE
Beta 3: Issue: Use seal and Click empty air

### ISSUE THREAD

**Issue by LordPinkerton** [Azanor/thaumcraft-beta#188]
In my current situation, I am trying to get a golem that is Smart and Deft to put a single Oak Sapling in the spot with the Use seal. I have set the filter to Whitelist and marked it with the Oak Sapling. After being told to use the Click Empty Air under the Options for the seal to stop him from repeatedly trying to use the sapling on the occupied stop, I set this option to true. However, after doing so, even when the space is vacant, the golem no longer responds to the Use seal. This has been tested both with and without the addition of a Provision seal and the options that go along with it. Perhaps I am doing something wrong. The seal itself is lying flat on the ground where I want the sapling to be placed and the only options marked true are the default Use Metadata and Use NBT Data and additionally the Click Empty Air now.

**Comment by Azanor** [comment]
Could you post a screenshot?

**Comment by LordPinkerton** [comment]
Here ya go. It's just one Use seal and one Collect seal. The collect seal has all default settings to allow the golem to pick up the sapling for testing. Not using an provisioning.

![2018-01-31_00 37 50](https://user-images.githubusercontent.com/11956610/35610590-1d8f21d2-061f-11e8-98f1-ae28699e53ba.png)
![2018-01-31_00 32 16](https://user-images.githubusercontent.com/11956610/35610595-21303538-061f-11e8-886e-c9915c0d3e6b.png)
![2018-01-31_00 32 08](https://user-images.githubusercontent.com/11956610/35610598-214a2682-061f-11e8-870b-210b77c03ba6.png)
![2018-01-31_00 32 13](https://user-images.githubusercontent.com/11956610/35610599-215bf5b0-061f-11e8-9959-9974d85582f7.png)

**Comment by Azanor** [comment]
The use seal needs to be placed on an air block - simply place it on a block where you want the sapling to be and then remove the block. The use seal causes stuff to be used on the block it is placed on, not in the empty space it is located in.
