### ISSUE TITLE
BETA3: Research table crash

### ISSUE THREAD

**Issue by McFrugal** [Azanor/thaumcraft-beta#189]
Same crash as in BETA2, clicking to bring up a new research choice can cause the game to become unresponsive.  Or perhaps the game is unresponsive due to an event immediately prior.
This may be related to the "Reject Fundamentals" choice.  I just had this happen to me after picking that then getting Rethink a few times to build myself back up to 5 inspiration.  When the bug happened I was at 20% Fundamentals and no other progress listed.

**Comment by MrCinnamonCookies** [comment]
I have the same issue but in beta 3.
