### ISSUE TITLE
Spelling & grammar corrections

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#19]
Maybe this would be a good place to put the localization files eventually so that people can look through them for spelling errors etc...? I wouldn't mind proofreading the Thaumonomicon files to make certain sentences flow better, fix punctuation and duplicated or missing phrases etc; also if people want to report any mistakes they could list them here instead of creating a new thread?

I already stumbled upon at least one in the purple console text that pops up when you get research related events, but I can't remember for which event. I've also encountered a few others in various Thaumonomicon entries. I'll list the first few here:

- **"First Steps"** stage 1, page 2, line 1

> is quite delicate  

should be  

> are quite delicate

- **"First Steps"** completed, page 1, line 1  

> is being revealed to me

should be

> are being revealed to me  

- **"Discovering Alchemy"** stage 3, page 1, line 9  

> to ready by

should be

> to read by

- **"Discovering Alchemy"** stage 3, page 2, line 17  

> place anyway

should be

> placed wherever I choose

- **"Discovering Alchemy"** stage 3, page 2, line 21  

> (shift-click while hovering)

should be

> (pressing shift whilst hovering)  
  
There's bound to be loads more, so it might be quicker to be able to fork/pull the localization edits rather than exhaustively list them for you to update~

**Comment by Azanor** [comment]
Not a bad idea.
