### ISSUE TITLE
Suggestion: Sounding enchant applied to weapon detects mobs instead of ores

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#190]
I was thinking it would be useful for finding caves and spawners if you could apply Sounding to a sword or axe. It would work just like it does on a pickaxe only it'd show you mobs instead. It'd work on passive mobs too, but not non-mob entities like minecarts.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#156
