### ISSUE TITLE
BETA3: Crash when golem activates 'Use' seal.

### ISSUE THREAD

**Issue by Linc-42** [Azanor/thaumcraft-beta#191]
So trying to get my golem to plant a sapling with the 'Use' seal has caused the server I'm testing on to crash. I'm not sure if its a problem with FTB utils or not, but I can consistently get a crash by having a golem 'Use' a sapling. I have created a pastebin with the crash log [https://pastebin.com/bAEf3AE3](https://pastebin.com/bAEf3AE3)

**Comment by Azanor** [comment]
Could you paste the crash report again? It seems to lead nowhere

**Comment by Linc-42** [comment]
fixed, formatting error when posted, was late. Thanks for all the work Azanor!

**Comment by Azanor** [comment]
Hmmm, I'm not sure there is anything I can do on my side. You might want to report this to the FTB guys. They will be able to determine who needs to do the fixing.

**Comment by LatvianModder** [comment]
What's the code you use to create your FakePlayer?
