### ISSUE TITLE
[BETA3] Change the aspect in the tooltip render to use RenderTooltipEvent

### ISSUE THREAD

**Issue by Buuz135** [Azanor/thaumcraft-beta#192]
Having the `ItemTooltipEvent` to render the aspect only works in container GUI, if the current GUI is not a container the `ItemTooltipEvent` will get ignored.

**Comment by Azanor** [comment]
Unless I am missing something the text list in RenderTooltipEvent  cannot be modified and I need to insert 2 lines of blank text in there.

**Comment by Azanor** [comment]
Also, the actual rendering takes place in RenderTooltipEvent.PostText
