### ISSUE TITLE
Golemancy research page missing.

### ISSUE THREAD

**Issue by Adn12** [Azanor/thaumcraft-beta#194]
Thaumcraft version 1.10.2-6.0.BETA3

Pack: All The Mods

maybe related mod : Thaumic JEI

issue: Golemancy research page missing, https://i.imgur.com/XGxfvWX.png

**Comment by EPIICTHUNDERCAT** [comment]
You scanned an iron golem possibly

**Comment by Adn12** [comment]
I did, is that what caused it?

**Comment by EPIICTHUNDERCAT** [comment]
not its not broken, scanning a golem is what gets you that research, Azanor is still working on the mod as its incomplete :P so some stuff is still missing.
