### ISSUE TITLE
[Beta 3] Eldrich obelisks dont generate in the world

### ISSUE THREAD

**Issue by Juarrin** [Azanor/thaumcraft-beta#195]
I walked through many biomes where Eldrich obelisks generate before, but I didnt se any of them. Just a bug or are they not in the game anymore?

**Comment by LordPinkerton** [comment]
Not implemented yet, I believe, as well as any of the other Eldritch stuff.

**Comment by EPIICTHUNDERCAT** [comment]
yep eldrich has not yet been implemented and theres no way to unlock the research yet unless you cheat
