### ISSUE TITLE
[Beta 3] Silk Touching Amber Allows Near-Infinite Preserved Curiosity

### ISSUE THREAD

**Issue by magerooster** [Azanor/thaumcraft-beta#196]
To reproduce:
Get silk touch pick.
Silk touch an amber block. (This has a chance to get the curiosity)
Place amber block and mine again. (Again, with a chance to get the curiosity)
It does consume durability but it probably shouldn't drop the curiosities when silk touched up?

**Comment by EPIICTHUNDERCAT** [comment]
Wow, definitely a bug
