### ISSUE TITLE
[Suggestion]?[Beta 3] It's not possible to make fences out of Thaumcraft wood

### ISSUE THREAD

**Issue by alfa38** [Azanor/thaumcraft-beta#197]
Well - recipe simply don't exists, altought recipe for making doors is present.
I don't talk about making greatwood/silverwood fences variant, thought it will be good addition.

**Comment by EPIICTHUNDERCAT** [comment]
Change your title and add [Suggestion], makes it easier to read and for azanor to run through the reports. I don't think this is an issue right? just suggesting he adds variants?

**Comment by alfa38** [comment]
it's kind of suggestion :/ just in TC4 u were able to craft fences of thaumcraft wood due to existence of only one type of fence. Don't remember how it was in TC5 sadly.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#191
