### ISSUE TITLE
[BETA 3]Thaumonicon pages grafical glitch and some misplaced text

### ISSUE THREAD

**Issue by alfa38** [Azanor/thaumcraft-beta#198]
![2018-02-01_14 50 17](https://user-images.githubusercontent.com/15610545/35677442-9fc62cd0-0760-11e8-90b1-5ef48af88ad0.png)

so far saw it only on "Types of Knowledge" page.

PS. Optifine disabled

**Comment by alfa38** [comment]
also this minor text bug in "Alchemical Metallurgy stage 3"
![2018-02-01_19 30 03](https://user-images.githubusercontent.com/15610545/35690394-c82248dc-0786-11e8-8fc7-4072bae4e0cb.png)

**Comment by alfa38** [comment]
![2018-02-01_21 20 41](https://user-images.githubusercontent.com/15610545/35695969-0f109806-0797-11e8-8d08-58e0dd0fb90d.png)

wrong description on Warded Jar Research.

**Comment by EPIICTHUNDERCAT** [comment]
VoidStuff is Eldrich research which isnt implemented yet. only way to get that is with an admin command.

**Comment by alfa38** [comment]
Thaumatorium "Video Guide" played "Backwards"

**Comment by MainFreak** [comment]
@EPIICTHUNDERCAT I think you replied on the wrong issue.

**Comment by EPIICTHUNDERCAT** [comment]
he deleted the message about voidstuff @MainFreak it now says "del"

**Comment by alfa38** [comment]
"Arcane Paving Stones" stage.1 have  "thaumic dioptra" text assigned to it.
