### ISSUE TITLE
Tainted Stone and Tainted Rock not properly breakable

### ISSUE THREAD

**Issue by terribleperson** [Azanor/thaumcraft-beta#199]
I'm not sure if this is intentional, but Tainted Soil and Tainted Rock are breakable by hand, but don't seem to be associated with pickaxes or shovels. Consequently, even the best tools don't let you clear out taint any faster. Clearing even a small area of taint is a painfully slow process. Taintwood is at least recognized as wood by Tinkers' Construct Lumber Axes, but I'm not sure there's nothing wrong with it. 

Tainted Soil and Tainted Rock also seem to be immune to explosives, at least TNT and EFLNs.

**Comment by EPIICTHUNDERCAT** [comment]
I believe its intended, I think taint is supposed to be a difficult material to get rid of. We had a taint outbreak at one point and we had to move. but normally taint is meant to be a difficult thing to get rid of. 

(Infernal Furnace = BAAD)

**Comment by terribleperson** [comment]
I totally think it should be difficult to get rid of. I'm a fan of taint as a serious and virulent threat and think it would be totally neat to play on a server where the edges of tainted areas are chunk loaded so it can keep spreading. 

That said, it's pretty close to impossible to fight at the moment. With the way it spreads and as deep as it can go, it's important to be able to effectively clear the blocks out once you've got the active threat under control. Without an appropriate tool, it's tedious at best.

I also can't imagine explosive immunity being intentional. Shifting from a normal fight to a "total war" approach is exactly the kind of response the Taint should evoke. Indiscriminate use of explosives is the perfect example of that.

**Comment by EPIICTHUNDERCAT** [comment]
trust me lol I would know, i dont think there is a proper method to get rid of it, we even tried using the flux sponge but it would come back.

**Comment by Ulysses2** [comment]
If you want to destroy tainted material, use a casting focus with Break effect.

**Comment by Azanor** [comment]
It is intended that they are hard to break.
