### ISSUE TITLE
Focus suggestions, retooled

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#20]
With the advent of the new focus system, I feel some new focus suggestions are in order! (Because let's be honest, spamming the suggestions folder is my reason for existing. I'm a shotgun, not a rifle.)
Most of these are obvious, but anyway here goes:

**Effects:**  

- **Vector Manipulation**  
*Redirects entity's direction of movement*
- **Shrink / Enlarge**  
*Changes the target entity's size*
- **Temporal Shift (Fast / Slow)**   
*Changes the tickrate for entities / tileentities affected*
- **Conjure Block**  
*Summons the targeted block*
- **Conjure Item**  
*Summons the targeted item*
- **Conjure Entity**  
*Summons the targeted entity*
- **Apply Status Effect**  
*Applies the specified potion effect to the target  
(Could even include effects from other mods e.g. Potion Core / Additional Alchemy)*
- **Glamour**  
*Change target entity's appearance (perhaps through a 'glamour' status effect)*
- **Illusion**  
*Create 'Illusion' blocks. Can be disguised as other blocks. Goggles reveal illusions.*
- **Dispel**  
*Removes status effects from target entities*

**Mediums:**  
- **Rune**  
*Places a rune, empowered with the spell's effect on the ground.*  

- **Trigger: _______**  
*Dictates what action triggers the rune in question. Examples would be "block break" or "entity collide" or stuff like that*

I've always liked the idea of Psi, but i've never played with it because thematically I found it a bit of a turn-off. I'm excited to see how deep the focus crafting mechanic in Thaumcraft 6 will be.

**Comment by nnystyxx** [comment]
If you don't mind, I've got a few effect ideas of my own that I'd like to chip in here. Pardon me if my terminology is inconsistent (or incredibly melodramatic), I'm adapting to the 'foci-as-effects' part of the new system.

**More Effects:**

- **Wind**
_Does comparatively little damage on its own, but violently repels creatures hit by the magic's emanations. With modification, it could potentially pull them towards the caster instead._
- **Sonic**
_Creates nigh-invisible blasts of intense sound that can damage and disorient enemies, vibrate and unsettle loose materials, and-- with some tuning-- be used as a remote trigger for the Arcane Ear._
- **Blades**
_Manifests various bladed, scything hunks of metal in different forms, from small cluster shots of needles/shrapnel to a heavy guillotine force that has a chance to behead one's enemies. Can potentially inflict a lingering bleeding effect._
- **Mental**
_Infests the brains of foes to make them run in fear, wildly attack nearby enemies, or become your personal bodyguard. Other effects might be possible._
- **Acid**
_Weaponizes the corroding effects of the mysterious 'liquid death' to melt enemies in their tracks with bursts of disintegrating energy. Modified, it can replicate the effects of Liquid Death and drop essentia crystals, or even have its chemical effects altered into a caustic substance that will, humorously, cause enemies to drop magical tallow out of their fat._
- **Healing**
_Draws from either the sheer aura, or the life essence of nearby plants, animals, and mobs to restore the caster's physical vitality._
- **Gravity**
_Harnesses the mysterious energies of the Shulker to influence the gravity of living things, from reversing or removing it and sending them into the air, to massively amplifying it and making any form of upward locomotion near impossible or even incredibly dangerous._
- **Spectrum**
_Colors things pretty colors. That's about it, actually._

**Comment by fingersome** [comment]
@nnystyxx cool suggestions. The "wind" effect is kind of what I was going for with my suggestion for the "vector manipulation" effect. You could maybe change the "blades" effect so instead of metal it manifests scything winds that cut your opponent to ribbons instead or something. I like the idea of being able to get mob heads that way =3=

**Comment by nnystyxx** [comment]
The idea is that the 'blades' effect creates temporary constructs kinda slapped together from vis that disintegrate moments later, like how the ice melts. So they're sort of blades, sort of really sharp bits of energy. One could describe it as wind too, though.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#173
