### ISSUE TITLE
Suggestion: Make Fibrous Taint flammable

### ISSUE THREAD

**Issue by terribleperson** [Azanor/thaumcraft-beta#200]
It would be both thematically appropriate and generally nice if Fibrous Taint was flammable.

Fire as a cleansing tool (particularly for any sort of growing organic threat) is pretty ingrained in fiction and pop culture. Allowing fire to burn Fibrous Taint lets us have armored thaumaturges clearing fibrous taint from an area with a fire focus or a flamethrower from a mod (like the Immersive Engineering Chemthrower). It's a pretty satisfying and powerful image.

If you think think it should be immune to normal fire or normal fire at least shouldn't spread on it, the addition of some sort of alchemical fire would also be nice.

**Comment by MainFreak** [comment]
Fire itself naturally only cleans the surface while soiling the air. If that gets implemented it should cause Flux Output into the air as soon as the taint burns down.

**Comment by terribleperson** [comment]
You can break fibrous taint without consequences, and generally speaking the byproducts of fire are less reactive than the fire. Probably bad for your breathing, but I don't feel like it should release flux into the aura. If it does, it should be minimal, since fibrous taint doesn't seem to be very substantial stuff.

**Comment by MainFreak** [comment]
Well if you want to make it burnable I assume you also want to make it affected by fire spread. Therefore you could clean up a massive area with just one tick of a flint and steel. For me that is a big advantage over manual breaking.

**Comment by terribleperson** [comment]
Fibrous taint is just the stuff at the edges, that's spread by crawlers and also seemingly forms over time. I don't want the actual tainted blocks burnable, but it would be nice to be able to prune the edges of the tainted area and fight the continued spread with fire.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#157
