### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by TimeConqueror** [Azanor/thaumcraft-beta#201]
Hello!
Translating Thaumonomicon I faced some problems. At the articles you use pronoun "I", but literally in the same paragraph you also use pronoun "You", so you often switches between first and second person. What pronoun should I use to translate these articles?

**Comment by XoviaHarmile** [comment]
Probably I, because the book (in most cases) is written as if you are the author.

**Comment by Azanor** [comment]
It is supposed to be written in the first person, but I made loads of errors and left over some text I copied from previous versions. I have been fixing things as I encounter them.
