### ISSUE TITLE
Killed Taint Seeds replaced almost instantly

### ISSUE THREAD

**Issue by terribleperson** [Azanor/thaumcraft-beta#202]
I've been trying to clear an area of taint. It's large enough there are two taint seeds. When I kill one, another seed immediately spawns, sometimes in what looks like exactly the same spot. Coupled with the fact that the taintacles spawned by the seed spread the taint and can spawn on untainted ground, and trying to fight the taint by killing the taint seeds is actually making the taint grow.

It makes sense that beyond a certain size a tainted area is going to be unmanageable by a single person on foot, growing and repairing faster than you can kill, but this should be only be an issue with trying to clear out a whole area. Even within a large heavily tainted zone, a killed seed should not be instantly replaced unless something is actively and continuously dumping flux into the aura. If something IS actively and continuously dumping flux into the aura of an already tainted area, there should probably be a second stage of tainted growth for such heavily tainted areas, and larger and more numerous threats rather than just instantly-respawning seeds.

**Comment by XoviaHarmile** [comment]
Making it easier to clear taint would work against what taint is, a repercussion for carelessly dumping flux into into the aura. If taint needed to have something constantly dumping flux it wouldn't make sense, taint is something that grew in the aura and is now spreading into the world, it's no longer connected to the aura.

You should try digging a moat and fill it with water around the tainted area and slowly replace the tainted blocks with water until you can break the seeds without them spreading. Though if this is your base I think you should just move, maybe find a nice magical forest.

**Comment by terribleperson** [comment]
I don't want taint to be easy or safe, but given the description in the Thaumonomicon it seems like it's a bug that a Taint Seed is instantly replaced when I kill it.

**Comment by Azanor** [comment]
It is possible for a seed to respawn in the same spot, but I am adding a small flux cost whenever seeds spawn so they will eventually run out of flux to spawn.

**Comment by terribleperson** [comment]
That's pretty much exactly what I was hoping for.
