### ISSUE TITLE
[1.10.2 6.0.BETA3] Lamp of Growth/Warded Jar interaction errors

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#205]
TESTING: When using a Lamp of Growth (LoG) with any piping with or without herba it functions as it should - working with the herba and not when without. When placing a LoG on top of a jar of herba it will use the herba as expected. Placing a LoG on an empty jar will work as expected - not at all.

ISSUE: When placing a LoG on top of an empty jar nothing happens, I click to fill the jar with herba with phials of herba and it fills and starts being used by the LoG *but* the lamp - while looking like it's working -
 actually does nothing but use up the herba.

ISSUE#2: Stacking 2 LoG on top of each other will light them up like they are on but not work.

**Comment by Azanor** [comment]
Did several tests and everything seems to work for me - you could have been getting bad RNG - the lamp will try to growrandom blocks near it.
