### ISSUE TITLE
[BETA3] Flux and max vis in chunks increasing for no apparent reason

### ISSUE THREAD

**Issue by RainyDayTea** [Azanor/thaumcraft-beta#207]
Can't tell if this is a genuine bug or a consequence of game mechanics due to the way we played, but on a playthrough of the mod, our group had issues where flux started to build up in a chunk without any reason. After everyone logged out and logged back in a few minutes later, the flux stopped building, but just lingered there instead of gradually decreasing.

Another similar issue we had shortly after was that the max vis in a chunk started increasing without explanation as well. As far as we could tell, we didn't have any device running that could displace it.

**Comment by Goof245** [comment]
Working as intended, apparently: https://github.com/Azanor/thaumcraft-beta/issues/136

Supposedly having to isolate your thaumcraft lab well away from one's base to avoid the inevitable flux buildup is the intended progression right now.....
