### ISSUE TITLE
[Suggestion]Option for Golem to right click while using Harvest 

### ISSUE THREAD

**Issue by kdjacobs** [Azanor/thaumcraft-beta#208]
Option to right click when Golems harvest, so it will work with other mods.  Or a place in the config file to add seeds from other mods so it can plant those.

Trying to get it so the golems play nice with other mods like Mystical Agriculture or Pam's Harvest Craft

**Comment by Azanor** [comment]
That is already implemented. Other mods can register their seeds/plants with mine and specify if they should be broken or clicked.
