### ISSUE TITLE
Void metal research

### ISSUE THREAD

**Issue by CaptJSparrow** [Azanor/thaumcraft-beta#209]
in my thaumonomicon, i need to research the next item which i assume is void metal. im at stage 3/5. i hover over the chest which is the thing that needs to be discovered and the text says: "research.c_voidstuff.text" please explain?

**Comment by Goof245** [comment]
Still to be implemented: https://github.com/Azanor/thaumcraft-beta/issues/55, https://github.com/Azanor/thaumcraft-beta/issues/150
