### ISSUE TITLE
[BETA3] Flux in chunk increasing for no reason

### ISSUE THREAD

**Issue by SjetCraft** [Azanor/thaumcraft-beta#215]
Similar issue to #207 where flux builds in a chunk for no reason.

This chunk is located around 3 chunks away from where _very_ limited alchemy was being performed.
Left unchecked this chunk spawned Taint Seeds and took over a 6-7 chunk area before I had to revert to a backup.

I have inspected the chunk in spectator mode and did not find anything in or near the chunk that would be contributing to the flux increase.

Logging out and back in did not solve the flux build up.

**Comment by XoviaHarmile** [comment]
Maybe that *little* alchemy isn't so little after all? How much have you been letting extra essentia go into the aura, and how much have you been emptying jars?

**Comment by Goof245** [comment]
For reference, this is what will happen if you try to ignore this:
![2018-02-06_17 07 50](https://user-images.githubusercontent.com/3851003/35851184-efbe9018-0b72-11e8-9845-1a268199817e.png)

World was a freshly generated one just to test this. Placed a jar, half filled it with ignis and accidentally-on-purpose dumped it. Something that's not at all hard to do, when you consider that you remove a jar label the same way.

Once this happens, 7-8 worlds out of 10 it's all over. Taint seeds that constantly spawn as fast as you can kill them, even while scrubbing the aura clean and cheating all the fibrous taint and tainted rock / soil away with commands.

Note this has happened to me 4 times now in survival playthroughs. Semi-regular triple bellowed furnace use, as well as enough vented smeltery use to get through the mod and make a few toys, suddenly the aura is at 30-40 flux and it's a matter of time before infinite taint seeds show up and screw the area. In my experience so far.

**Comment by Azanor** [comment]
People love throwing out the "for no reason part", but anytime vis levels drop low enough it generates flux. Not a lot, but constant vis usage with the aura constantly being under 10% of its normal max will do it.

Saying that, I actually did find a bug that will be fixed in the next release that was causing taint tendrils to spread even if there is no flux in a chunk.  It is supposed to be able to happen, but at .0001 the normal growth rate. In the current version it is using the full growth rate.

**Comment by SjetCraft** [comment]
@XoviaHarmile No alchemy or any crafting has been performed in that chunk ever. 

Azanor, the vis levels were above 150 and as previously mentioned no crafting or infusing or alchemy was performed in that chunk. Are there other reasons why flux would build in a chunk?

**Comment by SjetCraft** [comment]
Issue resolved in latest betas. Vis levels no longer increase for no apparent/obvious reason.
