### ISSUE TITLE
[BETA 3] Crash involving smelter vent facing

### ISSUE THREAD

**Issue by NerdimusPrime** [Azanor/thaumcraft-beta#217]
I was making a platform of stone bricks to place an infernal furnace. The nearby essentia smelter (with vents) was above me. When I looked up at the smelter the game crashed, with the following log:

https://pastebin.com/gcqJ0a3q

**Comment by Azanor** [comment]
This is actually a crash with portablejim.bbw.core.WandWorker which is part of a mod which I am unfamiliar with.

**Comment by NerdimusPrime** [comment]
That must be Better Builder's Wands. I can report it to portablejim.
