### ISSUE TITLE
[BETA3] Bugs with infusion

### ISSUE THREAD

**Issue by RainyDayTea** [Azanor/thaumcraft-beta#219]
1) Had a rare issue where the infusion would get stuck while absorbing the last unit of essentia despite there still being plenty of it left in the jar.

2) Can't tell if a bug, but sometimes an instability effect would cause an item to disappear completely instead of knocking it off the pedestal as intended.

**Comment by EPIICTHUNDERCAT** [comment]
had this happen to me as well, i think it may be intended. because it would like poof away in purple smoke

**Comment by Azanor** [comment]
Yes, if the instability is high enough an item could simply disappear instead of just getting knocked off.

**Comment by EPIICTHUNDERCAT** [comment]
cool, I thought so, however, this was also happening with smaller, not unstable infusions. so it may be a bug (I see possible bug)

**Comment by terribleperson** [comment]
In the process of making 3 to 4 of each crystal, I had one item 'poof' out of existence, I think. The rest simply fell off a pedestal. This is a pretty low rate, but I didn't expect it to happen with such a minor infusion.
