### ISSUE TITLE
Improve travelling trunk grammar

### ISSUE THREAD

**Issue by Vexatos** [Azanor/thaumcraft-beta#22]
`entity.trunk.guiname` right now is just being appended to the username. It would be nice if it was changed to `%s's Trunk` for `String.format` so translators are able to move the username around in the lang entry.

**Comment by 3TUSK** [comment]
`I18n.format(String key, Object... params)`?

**Comment by Azanor** [comment]
Technically the trunk hasn't existed since TC4 - that is just leftover text. However your suggestion makes sense so I'll change it in case I add it again.
