### ISSUE TITLE
Crafting Table won't be magicy

### ISSUE THREAD

**Issue by BlazeKin** [Azanor/thaumcraft-beta#221]
So i'm sitting here smacking my crafting table with salis mundus but nothing happens. So like anything else that doesn't work I try to go around it by spawning the Arcane workbench but it won't activate progression (can't even throw it on the ground and pick it up) in the thaumonomicon so I can't progress or really start doing anything at all. Best part is I have no idea what could cause it. The really odd thing is I could make the nomicon and the research table just fine.

**Comment by EPIICTHUNDERCAT** [comment]
is the crafting table a modded crafting table or regular? has to be minecraft crafting table. and did you follow progression correctly? because this works for me and everyone else playing :P

**Comment by BlazeKin** [comment]
Yep regular as one can get.

**Comment by LordPinkerton** [comment]
If you're right clicking, you shouldn't be "smacking" the crafting table. Please list what mods you are using along with Thaumcraft please.

**Comment by BlazeKin** [comment]
Here you go I think the most probable ones are Tinker's Construct minecolonies and Surge
 I would test all that now but it is really late where I am so ya.
Better Combat 1.3.5
Animania 1.2.1
Baubles 1.3.13
BedBugs 1.1.6
BetterFPS 1.3.2
Botania r1.9-341
CookingForBlockheads 4.2.45
coroutil 1.1.13
DoggyTalents v1.11.2a
DrZhark's Mo'Creatures Mod 10.0.6
ElecCore 1.7.431
Farseek 2.2
FastLeafDecay-v11
forestry 5.2.17.389
GeographiCraft 0.8.9
iceandfire-1.0.1
ImmersiveEngineering-0.10-61
infinitylib-0.11.0
InventoryTweaks-1.61-58
IronBackpacks 2.2.33
jei 3.14.7.420
journeymap 5.2.4
llibrary 1.10.2
MagicBees Beta 3.0.4
Mantle 1.0.0
Minecraft comes alive 5.2.2
MCMultiPart 1.4.0
minecolonies 0.8.4908
OptiFine_1.10.2_HD_U_C3
Pam's+HarvestCraft+1.10.2j
RadixCore 2.1.3
RealisticItemDrops 1.0.7
refinedstorage 1.2.26
Realistic Terrain Generation 4.1.2.4
Streams 0.4
Surge 1.1.0.70
Tinker's Construct 2.5.2
Thaumcraft 6.0.BETA3
VisibleArmorSlots 2.0
Wawla 2.3.0.197
Weather, Storms & Tornadoes 2.4.10
worldedit 6.1.4

**Comment by LordPinkerton** [comment]
I tried to recreate your pack with the mod versions you listed, but I keep getting a crash on startup. If you can do me a favor and export your modpack profile and attach it.

**Comment by BlazeKin** [comment]
Will do, but it'll take like 8ish hours cuz sleep and stuff you know? 
But in all seriousness I really appreciate the swift response and I'll get the files up when I can.

**Comment by BlazeKin** [comment]
So what files exactly do you want? I'm not using a modpack I just added mods to the game or is that what passes for a modpack now a days?

**Comment by LordPinkerton** [comment]
Assuming that you're using the Twitch/Curse launcher, go into your modpack profile and click the ... button on the upper right, then to Export Profile. The default options, exporting config and mods folder should be sufficient. Then, come back here and drag and drop the zip file it creates into a response comment.

![untitled](https://user-images.githubusercontent.com/11956610/35782415-d6c72a8a-09b4-11e8-89e7-cf3e39ffbee2.png)

**Comment by BlazeKin** [comment]
Oh darn I'm not using that which would be easier? Finding a different way export the profile or should I just get the curse launcher and put all my stuff in there?

**Comment by LordPinkerton** [comment]
You could do that too. Create a new profile in the launcher for 1.10.2 and then open the folder and just drag and drop your modpack folders into there. The launcher should update the modpack profile with it's own referenced mods.

**Comment by BlazeKin** [comment]
Here you go.
[ThePlace-1.0.zip](https://github.com/Azanor/thaumcraft-beta/files/1693356/ThePlace-1.0.zip)

**Comment by LordPinkerton** [comment]
Easy fix. It's that Visible Armor Slots mod that's your culprit. Not sure why, but you should just be able to disabled that one mod and you should be fine, at least for now.

**Comment by BlazeKin** [comment]
wow really? never would have guessed. Thanks mate!

**Comment by Azanor** [comment]
Thanks for the help @LordPinkerton . 
Problem solved then?
