### ISSUE TITLE
[Beta 3] Soft crash with Minecolonies

### ISSUE THREAD

**Issue by thephoenixlodge** [Azanor/thaumcraft-beta#222]
#https://github.com/Minecolonies/minecolonies/issues/2143

More details at the linked issue, but essentially the instance will hang in errored server state if trying to update a world to the more recent versions of Minecolonies with TC6b3 installed, producing the following crashlog: https://pastebin.com/gXrRci3D
Minecolonies dev thinks it's on the TC end to fix, hence the cross-report.

Versions:
Minecolonies: 1.10.2 version 0.9.XXXX (any newer than 0.8.5086)
Forge 12.18.3.2511
Thaumcraft 6.0 Beta3

(also, might want to update the issues link on curseforge to point to this tracker rather than the TC5 one)

**Comment by Azanor** [comment]
This problems seems to be with FoamFix, not TC. It is attempting to assign invalid values to the crystal metadata.
