### ISSUE TITLE
[Question] How to grow cristal shards.

### ISSUE THREAD

**Issue by alfa38** [Azanor/thaumcraft-beta#225]
I discovered research, placed some cristals in my base, and just wait for them to grow... which is never happen.

In TC5 i remember placing them near the nodes of appropriate type and that was working well, and in TC6 i guess i need to UP vis levels in the area.

so, can someone explain to me rules for their growth in TC6?

**Comment by XoviaHarmile** [comment]
I think they removed the ways to get vis up, I think you should just find a magical forest or a local aura hotspot, they'll grow, just be patient.

**Comment by terribleperson** [comment]
I think I saw mine grow before my base was swallowed by taint. It wasn't even a particularly high-vis area. It did take quite a while for the growth, though. I would appreciate it if the Thaumonomicon gave a better idea of what to expect from them.
