### ISSUE TITLE
Runic Shielding not accepting protection I book

### ISSUE THREAD

**Issue by FantomF600** [Azanor/thaumcraft-beta#227]
I enchanted a protection I book for the runic shielding research tab and it doesn't accept it, also seeing similar issues under infusion enchantment and block break.

**Comment by raphydaphy** [comment]
same here

**Comment by LordPinkerton** [comment]
Please do a cursory search before creating a new issue. The issue with the enchantment book requirement has already been posted. While they do not deal with the SPECIFIC book or research topic you're mentioning, it's still part of the same problem. #140 #175
