### ISSUE TITLE
[Beta4]: Combine bolt with chaining in F. Manipulator crash.

### ISSUE THREAD

**Issue by Goof245** [Azanor/thaumcraft-beta#228]
Tested with only Baubles and TC6b4.

Insert a blank focus into the Manipulator. Drag Bolt into the centre. Try to drag Chaining onto the manipulator and the client crashes.

[crash-2018-02-08_22.05.34-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1706941/crash-2018-02-08_22.05.34-client.txt)

**Comment by Cenotaffio** [comment]
Same thing, but with all the possible combinations, if i drag a medium in the center, and try to add others gems, like effects, it crashes.
This happen even if i first put all the  effects and modifications, and then the medium.
[crash-2018-02-08_15.27.50-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1707410/crash-2018-02-08_15.27.50-client.txt)

**Comment by Dayyer1** [comment]
I opened another issue that was similar to this, exept my game didn't crash. (I didn't see this issue, I guess. Oops.)
