### ISSUE TITLE
[Beta4]: Searching JEI for "Focus" throws NPE and crashes client.

### ISSUE THREAD

**Issue by Goof245** [Azanor/thaumcraft-beta#229]
Modlist is as shown in the crashreport. Attempting to search for "Focus" causes a NullPointerException and crashes the client.

[crash-2018-02-08_22.01.12-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1706947/crash-2018-02-08_22.01.12-client.txt)

**Comment by PhillZitt** [comment]
This also occurs when attempting to search "@thaumcraft" - I get to "@th" and then the game crashes.

[Uploading crash-2018-02-08_13.23.54-client.txt…]()

**Comment by Goof245** [comment]
Looks like you clicked "comment" before the crash report had finished uploading; there's nothing there...

If the top of the stacktrace is
```
java.lang.NullPointerException: Rendering ingredient
	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)```

then it's the same issue. Seems it's not actually the _search_ that's the issue, it's the rendering of the focus that causes the NPE.

**Comment by PhillZitt** [comment]
aw, dang. Apologies.

Yes, that is the top line of my stacktrace as well. Cheers!
