### ISSUE TITLE
Legacy issue: Salis Mundus

### ISSUE THREAD

**Issue by 3TUSK** [Azanor/thaumcraft-beta#23]
After some searching, I noticed that "Salis Mundus" actually means "World [of Salt](https://en.wiktionary.org/wiki/salis#Latin)" rather than "Salt [of the World](https://en.wiktionary.org/wiki/mundi#Latin)". 
Should this be corrected (i.e. changed to "Sal Mundi")? The problem is that "salis mundus" is somehow in rhyme whereas "sal mundi" is not.

**Comment by 3TUSK** [comment]
Also... if "mundus" here means "clean" (as an adjective), then the genitive "salis" should be changed to the nominative "sal".

**Comment by Vexatos** [comment]
Thaumcraft has always been full of wrong Latin. I gave up on trying to correct it.

**Comment by 3TUSK** [comment]
*I might want to give a shot on this during spring break...*

**Comment by xenxero1** [comment]
Perhaps Salis Mundus makes sense. Due to the world of salt it is trying to make it early game.

**Comment by Azanor** [comment]
Google Translate Latin is the best Latin  :p

**Comment by Vexatos** [comment]
As a person knowing Latin, it is still mildly upsetting to see wrong Latin in a mod, but if you want it to stay, there's nothing to do about that.

**Comment by xenxero1** [comment]
In world explanation: The first Eldritch to cross the threshold pioneered the roots of our language (Latin), Humans either misinterpreted it, or the proper grammar was fudged over the years, similar to how Latin descended into many other languages.

Thaumcraft is all about discovering the hidden truths to nature, how it works, and figuring out the REAL inner workings of the universe (imo). It would be somewhat funny to have that relevation that we had the answers. They've just gotten so effed over the years that they're scrambled to high hell. It could also explain why the Eldritch writings are incomprehensible, but almost make sense. It was the origin of language, but without guidance we _Warped_ it into our own sense of logic and reasoning.

Idk man, long in-world explanations are my thing. I apologize for the lengthy and rattly post.

**Comment by UnixRonin** [comment]
I actually prefer 'Sal Mundi', upon some reflection.  But then, I'm the kind of guy who takes pains to get grammatically correct Japanese or Old Norse (or, OK, Dovahzul) names for in-game named weapons...

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#172
