### ISSUE TITLE
[1.10.2 - TC6 6.0.BETA3] Arcane Ear (Toggle) not craftable

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#230]
I can make the Arcane Ear but the Toggle version (Arcane Ear + Lever) does not show up when trying to craft it. JEI doesn't recognize it as an existing recipe as well. I can post a screen shot but I don't think it'll show anything that wasn't said just now.

**Comment by Azanor** [comment]
Its fixed in beta 4
