### ISSUE TITLE
[Beta 4]Strange aspects position

### ISSUE THREAD

**Issue by Cenotaffio** [Azanor/thaumcraft-beta#233]
if i try to look the aspects of a item, their position is over the name, and strange simbols apperars were they were supposed to be.

![2018-02-08_15 34 36](https://user-images.githubusercontent.com/35802493/35978398-dd529e28-0ce5-11e8-93be-01f3a584493e.png)

**Comment by alfa38** [comment]
+

**Comment by benjaminkimball** [comment]
This has been resolved in the latests beta...and it's so nice to see! Thanks, @Azanor!
