### ISSUE TITLE
Help using direwolf 1.12.1

### ISSUE THREAD

**Issue by xdrushxd** [Azanor/thaumcraft-beta#235]
Can i install this mod in my server that runs direwolf 1.12.1 ?

**Comment by MainFreak** [comment]
1. Thaumcraft needs to be installed on both the client and server to work. Else people will get kicked constantly.
2. Thaumcraft does not work nor exist for Minecraft version 1.11 or 1.12 yet.

**Comment by xdrushxd** [comment]
allright thanks i just installed on my server and got the error not same version so yeah will wait till they make one thanks
