### ISSUE TITLE
Focus crafting crash [Beta4]

### ISSUE THREAD

**Issue by PyroManiac999** [Azanor/thaumcraft-beta#237]
Heya, long time fan of thaumcraft!
I got a bug for you to squash involving foci. I had the blank focus in the focal manipulator and I very  rapidly clicked first fire and then touch into place and it just crashed to the launcher:

This was what the launcher spat out:
The game crashed whilst rendering screen
Error: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

[crash-2018-02-08_23.43.19-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1709098/crash-2018-02-08_23.43.19-client.txt)

Hope you can find it.

**Comment by PyroManiac999** [comment]
Just loaded the save again, am standing infront of the focal manipulator, as soon as I drag the touch focus over, poof. same error.

**Comment by Danymaddox** [comment]
Yeah, same problem here

**Comment by Azanor** [comment]
Arg, I hate Eclipse sometimes. It occasionally decides to use the wrong import.

**Comment by PyroManiac999** [comment]
Maybe you need a different IDE? I'm a big fan of jetbrains' PyCharm, I've also heard good things about their Java IDE: https://www.jetbrains.com/idea/

**Comment by nnystyxx** [comment]
I hope there's an "emergency" patch released, since I really enjoy the focus system.

**Comment by Stellian** [comment]
Same problem(
Error: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

**Comment by Capten-Zaro** [comment]
Well kinda glad I'm not the only one to see this problem, hope its a quick fix.
 I can put "touch" in the manipulator or I can put "fire" in, try to put in both though and the game dies.
[crash-2018-02-10_09.25.58-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1713264/crash-2018-02-10_09.25.58-client.txt)

**Comment by Dayyer1** [comment]
oof

**Comment by twothe** [comment]
Same issue. Looks like no focus in Beta4 :/

Btw: if you use Eclipse you are making Java programming much more painful than it has to be. I strongly recommend to either use Netbeans or IntelliJ.
