### ISSUE TITLE
[Beta 4] Thaumonomicon text misplaced

### ISSUE THREAD

**Issue by Cenotaffio** [Azanor/thaumcraft-beta#240]
![2018-02-09_11 04 35](https://user-images.githubusercontent.com/35802493/36022399-47a67936-0d89-11e8-885b-629419b8cf75.png)
![2018-02-09_11 04 41](https://user-images.githubusercontent.com/35802493/36022401-49ccbfe0-0d89-11e8-93dd-ac5cc3cafe31.png)

lol

**Comment by Azanor** [comment]
Doh
