### ISSUE TITLE
[TC6BETA4] Focus crafting crashes game.

### ISSUE THREAD

**Issue by PierceSG** [Azanor/thaumcraft-beta#246]
Specifically, the Plan and Exchange focus.

When you try to combine the two of them, the game will crash,

Edit: After further testing, I think Focus crafting is borked. I can't drag two options into the sockets without the game crashing on me. I'll do the test again, but with only TC6.
Edit2: With only Thaumcraft-1.10.2-6.0.BETA4 and Baubles-1.10.2-1.3.13, it still crashes when you try to put more than one focus options into the focus crafting grid. Running Forge 12.18.3.2511, and Minecraft 1.10.2

**Comment by kd8lvt** [comment]
I'm having an error with even crafting the initial touch-flame focus.
[crash report](https://gist.github.com/kd8lvt/dc94e8863e0f7a53ad85012d998f9160)

**Comment by PyroManiac999** [comment]
Duplicate of this one I think: https://github.com/Azanor/thaumcraft-beta/issues/237

**Comment by flippyforever** [comment]
I am running into this issue as well

**Comment by toonslayerking** [comment]
same this is a big issue

**Comment by thenextelement** [comment]
having the same problem, definitely a  fatal bug
