### ISSUE TITLE
[beta4] focus texture/naming suggestion

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#247]
The current textures of the caster foci feel very awkward and busy. The symbols are meant to show what the focus does, but they're difficult to decipher to the point where it would just be better to have a general focus texture for each damage type/spell effect. 

....either that or maybe the foci could take on a unique hue based on the vision crystals used to craft them, similar to armor dyeing. 

I also think it would be useful to allow players to name the foci they craft in the focal manipulator, instead of having to rename it in an anvil. Unless you have plans to procedurally generate names based on the chosen components?

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#192
