### ISSUE TITLE
[BETA4] visual thaumonomicon hover bug

### ISSUE THREAD

**Issue by PyroManiac999** [Azanor/thaumcraft-beta#250]
This research when hovered over (the treasure chest) says:  
"research.c_voidstuff.text" 
Which I'm guessing is not the name that's supposed to be showing
![bug_pic](https://user-images.githubusercontent.com/24716393/36052009-4c5068bc-0dec-11e8-9ce2-6388b4cd0937.png)

**Comment by MainFreak** [comment]
Known issue, this is work in progress stuff that has not been implemented yet (just like everything else related to the Eldritch Tab, Voidmetal etc.). Was mentioned in #55

**Comment by PyroManiac999** [comment]
Okay, thanks for letting me know
