### ISSUE TITLE
Game crashes while trying to use Focal Manipulator?

### ISSUE THREAD

**Issue by LokiWiz** [Azanor/thaumcraft-beta#251]
When trying to move the medium glyph over the box, the game crashes. This has happened every time, at the exact same time.

**Comment by PyroManiac999** [comment]
duplicate of #237 I guess

**Comment by Cenotaffio** [comment]
this was already reported in other 2 posts

**Comment by darklex55** [comment]
No, this is not like the other posts. I'm trying to make the first focus the Thaumonomicon instructs you to, but every time I try to place the second modifier the game crashes. I tried both adding the "fire" after the "Touch" and the other way around but nothing works.
[crash-2018-02-10_20.29.39-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1713671/crash-2018-02-10_20.29.39-client.txt)

**Comment by Goof245** [comment]
Read the stacktrace dude, this is the same crash. Basically the code that tries to check for gem connectivity is broken right now.
