### ISSUE TITLE
[Beta 4] Scrapping and restarting research presents same options

### ISSUE THREAD

**Issue by apmax** [Azanor/thaumcraft-beta#252]
Using the scrap theory button immediately after revealing the first two pages does not actually scrap your theory.
It closes out of those pages, but trying to start a new theory will present you with the same two pages again and you cannot start from scratch without breaking and replacing the table.

Edit: I've discovered a continuation of this; once you have scrapped your theory and created a new one, only to be presented with the same options, you cannot choose either of the pages and need to break and replace the table to be able to research again.

**Comment by Ulysses2** [comment]
The Scrap Theory button works, it just doesn't update the GUI properly. So if you press it and close the GUI, it'll be fixed when you open it again.
