### ISSUE TITLE
Synthesis Theorycrafting Cards are currently misleading

### ISSUE THREAD

**Issue by taggedjc** [Azanor/thaumcraft-beta#254]
Currently, the Theorycraft Card titled "Synthesis" is misleading.

It says:

> When essentia combines to form more complex forms a number of interesting and intricate reactions take place. You will learn much by combining **Aspect** essentia with **Aspect** essentia and then studying the resulting combination. Gain 30 Alchemy.

However, essentia currently *does not combine*, and there's no way to actually *do* that combining.  While the card itself might be describing what you do while fiddling with the ingredients of the card, it's a bit misleading to talk about combining essentia when that's something that's otherwise impossible to do.  Plus, the card implies you would only require the two listed Aspects, but you actually also need a Vis Crystal of the resulting Aspect *as well*.  So, right now, you have to:

1. Use the Thaumonomicon's Aspects of Essentia to find out what Aspect is made out of the two Aspects mentioned on the Theorycraft Card

2. Find some item that *already* contains the goal Aspect

3. Throw that item into a Crucible (or Essentia Smeltery -> Thaumatorium) and use Quartz Sliver to create a Vis Crystal of the goal Aspect

4. Also find some items that contain the two component Aspects and do the same thing to them, so that you can complete the Synthesis card

I think a better solution would be a way to actually combine essences, so that the card as-written would not be misleading.   As it is right now, in-lore you have absolutely no way of *knowing* that Motus is actually Ordo + Aer, up until you actually get an Alchemical Centrifuge set up and find out that Motus *breaks down* into Ordo or Aer, which is pretty far in to alchemy for something so important as far as aspects are concerned!

My suggestion:

Make it so that we can turn Amber into Amber Slivers (which will be similar to Quartz Slivers, except orange!) and if an Amber Sliver is thrown into a Crucible containing 5 each of a compound Aspect's components, it would make a Vis Crystal of that compound essence. Then you *could* combine them.

This would have three benefits:

1. The Synthesis Theorycrafting card would make more sense (although it still wouldn't be perfect - it would be ideal if it actually required you to combine the essentia rather than just supplying the Vis Crystal, but having alternate ways to create the Vis Crystal is probably fine, since the card itself explains how you're going to tinker around with the three essentia anyway)

2. Unlocking the Essentia Smelter would be a lot less tedious since you could synthesize the compound Vis Crystals you need to unlock it, instead of having to travel 1000+ blocks in search of Snow for a Gelum Vis Crystal, for example.  This is handy because the Essentia Smelter is required for Infusion and Golemancy, which are a large part of the mod!

3. It would be an easier way to get some of the difficult aspects such as Praecantatio (easiest way to get it right now typically involves crafting Salis Mundus, which has a lot of extra aspects that you would then have to soak up with Quartz Slivers).  Being able to make it yourself with Aer (from Aer Vis Crystals) and Potentia (from Redstone) without waste would be really beneficial, and would be a good way to reward people for learning the essentia compounding system.

**Comment by nnystyxx** [comment]
I like this idea wholly. Giving more uses to Amber is a nice feeling, and I think it honestly works thematically. It used to be much harder to get individual vis crystals, but it's easier, so compounds might be nice if done in this way. 

I always did think this card made no sense.

**Comment by taggedjc** [comment]
Yeah, I thought adding more to Amber (and making it thematically paired with Quartz) would be a good thing.  Amber is really useful for making Arcane Lamps and also for enchanting your things with shielding, but other than that...

**Comment by twothe** [comment]
This is why I couldn't figure out how combining aspects is done... 

I very much support the idea of having real combining in the game, even if it is just for fluff and research cards. I think it fits the mod well if I can actually do some "experimenting" even if the results are nothing that will bring me immediate advantages (aka large-scale production).

However instead of using Amber slivers as direct replacement for quartz slivers, I would implement it the following way:

1. Put the base materials in the cauldron.
2. Put a sliver of amber into the cauldron as catalyst.
3. The cauldron will now attempt (once) to combine all ingredients to form aspects of the next higher tier.
4. Put a sliver of quartz into the cauldron to pull the vis out.

It is basically the same, except that the amber now reacts as catalyst, which I think is more fitting and easier to implement.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#244
