### ISSUE TITLE
[Suggestion] Scrap requirement for enchanted books (Infusion enchant, Break/Exchange foci)

### ISSUE THREAD

**Issue by Goof245** [Azanor/thaumcraft-beta#257]
It took me a full double chest and a diamond chest to finally create a Fortune II book, using the optimum lvl 15 - 16 enchants and combining two Fortune 1 books. To work through an otherwise really well flowing research system only to be smacked with this RNG crap is a bit of a kick in the balls, even once Az fixes the bug and it works properly.

Some alternatives:
- instead of Fortune II, take a Pickaxe of the Core bearing any enchantment, plus a jar or two of Desiderium
- instead of Sharpness I (although this is easier to get in my experience), take an enchanted Sword of the Zephyr + a jar or two of Aversio
- instead of silk touch, an enchanted Earthmover shovel + a jar or two of Permutatio

For reference, this is what a diamond chest holds:
![2018-02-11_15 08 27](https://user-images.githubusercontent.com/3851003/36070185-62801e9c-0f41-11e8-8e5a-a9f7b2aade15.png)
Not pictured: all the lapis and leather used, plus the offensive level of XP needed to keep rolling at lvl 16 consistently.....

**Comment by Zero-ui9** [comment]
I just used the EnderIO enchanter to cut out the RNG. I realize you may not have that installed, but since both mods are on 1.10.2 its a valid option until the research is changed(if it is, which it should be)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#187
