### ISSUE TITLE
[suggestion] Better support for cooperative groups

### ISSUE THREAD

**Issue by painquin** [Azanor/thaumcraft-beta#264]
Right now if you're playing with five people working together, everyone has to craft several expensive items (alchemical smelter, etc) to progress. A config option to allow players to scan these items instead of crafting their own would go a long way to making the mod more friendly to groups of players. Right now we have an iron shortage but four alchemical smelters and three crucibles sitting in a chest.
Some things make sense for everyone to make their own - thaumonomicon, thaumometer, casting gauntlet. Some things are trivial to repeat - alchemical duplication, for example. This would only make sense for the expensive items.

Maybe require the player doing the scanning to have the research otherwise available.

A separate option to share all observations and theories between the players on a server would be good for very small groups.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#186
