### ISSUE TITLE
Vis discounts don't seem to apply to arcane workbench or focal manipulator

### ISSUE THREAD

**Issue by hacatu** [Azanor/thaumcraft-beta#265]
Wearing armor or baubles that provide a vis discount does not make the vis cost for the arcane workbench or focal manipulator cheaper.  This might be intentional but seems counterintuitive and probably means the infusion cost and infusion speed stones are not currently craftable considering their vis cost is what I assume is the absolute theoretical maximum for a chunk based on the thaumometer (500).

**Comment by taggedjc** [comment]
You can get far over 500 vis available for crafting using the Arcane Workbench Charger.  It draws vis from adjacent chunks and distributes the cost between them all, so you can get nearly 1000 vis available for crafting pretty easily, at least for the Arcane Workbench.

Focal Manipulator is a bit trickier (I feel as though the Workbench Charger should work on it, as well, personally) but at least it draws the vis cost over time so it will just slow down after the current chunk is depleted and then just work at the rate vis regenerates after that.

**Comment by Azanor** [comment]
I actually already made the charger placeable on the focal manipulator for the next release. :)
