### ISSUE TITLE
chash when trying to make foci

### ISSUE THREAD

**Issue by toonslayerking** [Azanor/thaumcraft-beta#266]
The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

**Comment by chrislafeken** [comment]
I'm getting the same crash when trying to make the very first wand foci that the book requests.
[crash-2018-02-12_22.03.04-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1718835/crash-2018-02-12_22.03.04-client.txt)
Attached is a crash report for full details
