### ISSUE TITLE
Bauble Ideas - Retooled for TC6

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#27]
- **Band of Sanity**  
*Allows you to see your sanity wihtout holding a sanity meter.*

- **Band of Aura**  
*Allows you to see the aura levels without holding a thaumometer.*

- **Voidseer's Pearl**  
*Grants vis discount based on Permanent warp  
Increases likelihood and severity of warp events when worn
Has Warping II  
"You peer into the inky blackness... you could swear you saw something staring back..."*  

- **Voidwalker's Sash**  
*Dampens the damage taken from using portals based on permanent warp*

- **Charm of Curiosity**  
*Absorbs experience orbs with a chance to convert them into research resources.*

- **Charm of Draining**  
*Chance for slain mobs to drop their essentia as crystals.*

- **Cleansing Charm**  
*Converts Sticky and Temporary Warp to flux in the aura, slowly.
"May cause indigestion, vomiting, intense sobriety, etc."*

- **Festering Sash**  
*Prevents Tainted poison when in tainted biome/standing on taint.  
Tainted mobs ignore you.  
Has Warping I.*

- **Taintacle Necklace**  
*Taintacles will become friendly, and attack your enemies.
Has warping I.
"You find this amulet's vice-like grip on your neck reassuring, somehow..."*

- **Beads of Mending**  
*Repairs equipped armor & items in inventory.
Uses vis instead of experience*

- **Orderly Sash**  
*Sorts inventory for you
Allows you to set items to ignore on the ground.*

- **Safekeeper's Ring**  
*Keeps your baubles and armor when you die.
Effect stacks with 2 rings, allowing you to keep your hotbar as well.*

- **Flagellant's Choker**  
*Increases vis discount based on health.  
<2 hearts = 20%  
<4 hearts = 10%  
<6 hearts = 5%*  

- **Deatheater's Girdle**  
*Allows you to ignore the hunger debuf from rotten flesh  
Also gain a weak regeneration buff from eating zombie brains.*     

- **Ring of Bone**  
*Undead will ignore you, unless provoked.*  

- **Bloodthirsty Ring**  
*Heal player for a portion of melee damage dealt.  
Effect stacks with 2 rings.  
Must deal damage to opponent, doesn't proc if opponent has shielding*

- **Fierce Locket**  
*Doubles potency of foci.*  

- **Searing Sash**  
*Blazes & Firebats ignore you, unless provoked.*  

- **Charm of Ash**  
*2x exp from mobs killed, but no drops.*  

- **Incendiary Amulet**  
*Causes a large explosion that sets fire to nearby blocks when the player dies.  
Creepers ignore you.  
"You have to resist the urge to hiss softly in peoples ears when you sneak up behind them."*

- **Molten Band**  
*Increased chance to mine native clusters.  
Effect stacks with 2 rings.*

- **Charm of Gills** 	
*Grants Waterbreathing*

- **Lunar Amulet**  
*Slowly fills with vis.  
Speed depends on the phase of the moon.  
Holds half as much vis as the amulet of vis storage.*  

- **Soothing Talisman**  
*Prevents any status effect from being applied to the player.*

- **Thrifty Locket**  
*Doubles Frugality of foci*  

- **Prismatic Circlet**  
*Ancient Guardians will ignore you.*

- **Fleeting Pendant**  
*Increases player speed / jump.*  

- **Charm of Gusts**  
*Repels projectiles.*  

- **Angelic Wings**  
*Elytra, but also allows a double jump*

- **Nimbus Ring** 	
*Double jump with a little puff of mist.  
Effect stacks with 2 rings, allowing 2 extra jumps.  
Combined with Angelic wings, allows for 3 consecutive jumps.  
(Shamelessly stolen / inspired by the cloud in a bottle from terraria)*

- **Stoic Circlet**  
*Doubles your runic shielding.*  

- **Steadfast Charm**  
*Doubles your runic shielding's recharge rate.*

- **Sturdy Bandolier**  
*Negates knockback, Doubles the knockback of your own attacks.*

- **Burrower's Ring** 	
*Mine faster, the lower down in the world you are.  
Effect stacks with 2 rings.*  

- **Geomancer's Ring** 	
*Chance to mine primal essentia crystals when mining stone, diorite, andesite or granite.  
Chance to gain bonus crystals when breaking or right-clicking clusters.  
Effect stacks with 2x rings, increasing chance.*

- **Sash of Spiderclimb**
*Allows you to climb walls like a spider. Also allows you to pass through web blocks unhindered and stand on top of them.*

**Comment by xenxero1** [comment]
A few of these seem a little over powered without durability or some other resource gate, but overall this list is awesome!

**Comment by fingersome** [comment]
@xenxero1 considering they all need vis to function, and have to be crafted (presumably by infusion in most cases) I feel they're mostly fair. Plus, "overpowered" is relative in minecraft imo.

**Comment by fingersome** [comment]
Perhaps the beads ARE a bit op as is - also slightly redundant given that void tools repair themselves anyway.

**Comment by nnystyxx** [comment]
I do definitely think a greater expansion of Baubles' presence in TC6 would be nice. There's a lot of potentially not-too-difficult visual modifications to be made to the existing rings, amulets, et cetera to distinguish them from each other, and all of these functions seem cool. I love that some of them encourage different play styles, like the taint-based ones, or the Charm of Ash for when you really want XP but not drops. Balance may be an issue, and the Beads are perhaps a little extraneous, but overall these are great ideas in my opinion.

If you have any ideas for how they'd look, I can make really quick, hacky sprite edits of the existing items/baubles for funsies.

**Comment by Azanor** [comment]
Some good suggestions here btw. I sort of skimmed this post when it was originally posted, but now that I'm in the 'adding content' phase of the alpha I'm looking over all the old suggestions.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#171
