### ISSUE TITLE
Holding shift shows two lines of symbols on tooltip of any item with aspects

### ISSUE THREAD

**Issue by Ulysses2** [Azanor/thaumcraft-beta#273]
![2018-02-13_22 08 28](https://user-images.githubusercontent.com/9127495/36186047-7fdab3ec-110a-11e8-9d26-a882775c8740.png)

**Comment by Goof245** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/233

**Comment by Ulysses2** [comment]
Oh, sorry, nvm.
