### ISSUE TITLE
Thamometer works incorreclty on north/south chunk border

### ISSUE THREAD

**Issue by mujmajnkraft** [Azanor/thaumcraft-beta#277]
When you are standing on the north side of north/south chunk border, thaumometer is actually showing vis level of the chunk on the south side. On east/west border no such thing occurs.

![2018-02-14_11 03 26](https://user-images.githubusercontent.com/15549341/36199666-8860736a-117a-11e8-82a7-086c3ed672a5.png)

I am currently in completely drained chunk and thaumometer is showing no vis.

![2018-02-14_11 03 34](https://user-images.githubusercontent.com/15549341/36199676-904e1c26-117a-11e8-86f6-1756b4b7bcfe.png)

When I get closer to a chunk border, it starts showing vis level of adjacent chunk despite I haven't crossed the border yet.

**Comment by Azanor** [comment]
Try using F3 and looking at the chunk coords given there. According to that everthing is fine. vOv
