### ISSUE TITLE
Cannot unlock infusion enchantment [BETA 4]

### ISSUE THREAD

**Issue by Hunt3rM4d** [Azanor/thaumcraft-beta#280]
Having a enchanted book with Sharpness 1 and the required "research" for unlocking the entry, the "complete" button simply doesn't show up to unlock the Infusion Enchantment. Is it broken? Do we need any other kind of enchantment to unlock that entry? I did the research during BETA 3, perhaps that's the problem.

**Comment by VallenFrostweaver** [comment]
Same exact situation for me as well.

**Comment by Goof245** [comment]
Duplicate issue xlots, also fixed in Beta 5.
