### ISSUE TITLE
[1.10.2 - Beta4] Smart head / Armored Smart head has no difference

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#281]
Besides the Armored Smart head costing more there is no difference between it and the Smart head (unless it's an asthetic change only) so it has no benefit. Armor rating stays the same. Health stays the same. Functionality stays the same. No differences in traits (ie Fragile, etc). Same seal accesses.

**Comment by Ulysses2** [comment]
You probably have another golem part that adds the Fragile property. Fine manipulators, dart launchers, and levitation modules all give it that property.

**Comment by Azanor** [comment]
Yup, it is simply a smart head without the fragile trait, so if your golem still has fragile then it is getting it from something else.
