### ISSUE TITLE
[1.10.2 Beta 4] Golem seals render is off when sneaking

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#282]
See image attached. 
![seal](https://user-images.githubusercontent.com/13642054/36202398-92c5ad92-117b-11e8-9c6a-b1079ee32b2c.png)

**Comment by Azanor** [comment]
That was actually already changed for beta 5 - sneaking renders it through blocks which caused the strangeness above. When sneaking now the seal will lose its 'thickness', but at least it doesn't look like that.
