### ISSUE TITLE
[B5] Fire Focus is not recognized as crafted for entry completion

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#284]
Since I can now craft the fire Focus without the game crashing I did so, but the Thaumonomicon entry did not recognize the completion of the task. I took the focus manipulator apart, placed it again, put all the reagents inside, crafted another one and it is still not recognized. Which means I am stuck now on Auramancy.

**Comment by MrScopi** [comment]
I have the same issue, and did similar steps.  Also tried each of the six positions for the fire tile, but that didn't seem to affect anything.

**Comment by fingersome** [comment]
I stumbled upon this same issue just now in Beta 5.

**Comment by PyroManiac999** [comment]
Same here.

**Comment by Luicuelo** [comment]
Thaumonomicon doesn't see Caster focus (Touch, Fire) BETA7.
I think the  Thaumonomicon ask for a 4.4 damage focus and i got a 5 damage focus.

**Comment by Orangekun6** [comment]
I'm having the same problem. :(
