### ISSUE TITLE
Break focus effect persists and stacks for a given space, even if the block is broken and replaced

### ISSUE THREAD

**Issue by Jaitsu** [Azanor/thaumcraft-beta#293]
(Note: tested in Creative mode.)

If one uses a Break effect on a block that's slow to break, ex. a low-Potency Break projectile on a block of obsidian, it's possible to break the block and replace it with something else. The breaking visual effect immediately reappears on the new block, and the process continues until the block is broken. This also affects liquids like water (the water block will disappear as if 'broken') and likely others.

This also stacks with multiple casts on the same block - spam a focus on the block, and it'll break whatever block is in the space whenever one of the 'break timers' would have ended, even several times after the initial block is broken. (After doing this, there seems to be a persistent effect on the space that will put cracks on the block, but never break it.)

**Comment by hacatu** [comment]
I'm still getting this problem in beta 21.  When I use a max sized break in an ocean monument random blocks of water keep getting broken and re-filling perpetually after all of the solid blocks have been broken.
