### ISSUE TITLE
Thaumonomicon doesn't see Caster focus (Touch, Fire) BETA5

### ISSUE THREAD

**Issue by alexperegar** [Azanor/thaumcraft-beta#295]
![2018-02-15_16 11 30](https://user-images.githubusercontent.com/36506410/36258226-043a9ff6-126b-11e8-8977-556d72f3e05f.png)
![2018-02-15_16 11 41](https://user-images.githubusercontent.com/36506410/36258227-047c6238-126b-11e8-863f-40ebbf5b8c23.png)

**Comment by twothe** [comment]
#284 
Which is already done.

**Comment by alexperegar** [comment]
i made it, but can't continue research this tree because i can't accept this "quest"
