### ISSUE TITLE
Alpha 7? (Question)

### ISSUE THREAD

**Issue by joelou1** [Azanor/thaumcraft-beta#3]
I do not want to push or anything, but I was wondering if any bugfixes update was about to unfold. There is only so much we, Backer/Tester, can report with a build that you have cleared all bugs already.

I am sure you are doing your best to provide us, the players, the best content possible.

I have another question. People in the discord Community started to think that Thaum 6 may end up being for the 1.11 branch. I would be glad if you could enlighten us on which version of minecraft it will happen.

Thank you for the developpement and reading me.

**Comment by Azanor** [comment]
I'm redoing the wand system atm which will take a bit of time unfortunately - this being the busy time of year for me at my real work is also not helping.

I am currently coding for MC 1.10.2. MC 1.11 requires a massive overhaul of how itemstacks are handled and I would rather avoid that for now.

**Comment by joelou1** [comment]
Thank you for the enlightenment!

~~WANDS!!!!~
