### ISSUE TITLE
[Beta5] Creating Crucible Crashes

### ISSUE THREAD

**Issue by kd8lvt** [Azanor/thaumcraft-beta#300]
Right clicking Cauldron with Salis Mundus (Creating the Crucible) causes a crash. Loading back into the world, the Cauldron remains unchanging, and the Salis Mundus is still available to be used. This does not effect the Arcane Workbench, though I can not say if it effects anything else, as I'm not that far into the mod ;P

Cheating in a Crucible seems to work fine.

[Crash Report](https://gist.github.com/kd8lvt/57c546882a6621354720f7b5bc8ef3d1)

**Comment by Dayyer1** [comment]
Fixed in Beta 6, bud.

**Comment by kd8lvt** [comment]
@Dayyer1 I posted this when B5 had just come out, but thanks for letting me know B6 was a thing ^-^
