### ISSUE TITLE
Thaumcraft 6 Beta 6 crash with Railcraft 10.3.1

### ISSUE THREAD

**Issue by ryu777mtg** [Azanor/thaumcraft-beta#304]
This is my mod list for the test environment:

    UCHIJ   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar)
    UCHIJ   Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar)
    UCHIJ   Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar)
    UCHIJ   railcraft{10.3.1} [Railcraft] (Railcraft_1.10.2-10.3.1.jar)
    UCHIE   thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar)

[Here is the latest.log before closing the minecraft client.](https://pastebin.com/0jd5RfxK)

**Comment by xXTheBigBearXx** [comment]
It appears to be the Potion aspects attempting to apply aspects to railcraft's creosote potion, me and some friends have had this issue also

**Comment by Acillius** [comment]
I can confirm I am currently using it is ALL THE MODS for 1.10.2 for testing purposes and Beta 6 crashes on load up. The issue seems to stem from the potion aspects like TheBigBear and Ryu have mentioned and shown.

**Comment by serialtasted** [comment]
I'm also having this issue. Not on the client but my server won't start. Probably the client won't too didn't had the time to test.
Here's my crash-report if it helps: https://pastebin.com/vsJcK3k6

**Comment by MidnightsFX** [comment]
I am also seeing this issue, with PSI potions and the potion aspect calculations.

[Pastebin of crashlog](https://pastebin.com/qUwgrzaz)

**Comment by touhouzun** [comment]
Oh my me too,I'm a Chinese player and I also experienced it.*sign*
[crash-2018-02-16_11.12.45-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1730469/crash-2018-02-16_11.12.45-client.txt)
We should be together and help azanor to make a hotfix.(Tried to type an emoji of smiling.)
But I have no knowledge of coding._(:з)∠)_

**Comment by dariumz** [comment]
Similar issue, crash on start due to potion part I expect.

[2018-02-16-2.log](https://github.com/Azanor/thaumcraft-beta/files/1731284/2018-02-16-2.log)
