### ISSUE TITLE
[BETA6] Logistics menu doesn't like more than 127 of an item

### ISSUE THREAD

**Issue by Goof245** [Azanor/thaumcraft-beta#309]
Using one byte for stacksize doesn't really play nice with this... If you have more than 127 of an item in your little golem logistic system the item count overflows, then wraps around to -128.

![2018-02-16_13 53 09](https://user-images.githubusercontent.com/3851003/36293013-e339a808-1321-11e8-82b2-1cc52e4d7697.png)
![2018-02-16_13 53 00](https://user-images.githubusercontent.com/3851003/36293019-e4508cd4-1321-11e8-99ba-d5786208342e.png)

**Comment by twothe** [comment]
In Java all numerical base types are signed. To cast from unsigned byte to int, you need to do
`int size = byteSize & 0xFF;`

**Comment by Azanor** [comment]
This is strange - I am not storing the amount in stacksize, but in a separate int. I tested it with huge stacksizes (1000+) to make sure stuff like this doesn't happen. Hmmm.

**Comment by Azanor** [comment]
What other mods are you using? I just tested it again and everything is working fine on my side. Tested with JEI as well incase that was the cause (I assume it is JEI you are using in the screenshot).
