### ISSUE TITLE
How about a focus for defence?

### ISSUE THREAD

**Issue by NatsuArashi** [Azanor/thaumcraft-beta#31]
We can't use sword for blocking anymore. And shields were not cool.
 I found a tank-job in a onlineRPG , they use gauntlets summoning metal to attack or defence.
Take a look.
https://www.youtube.com/watch?v=k4nOoADmf8k

**Comment by fingersome** [comment]
Ok, how about a spell effect like **"Reflect"** or something of that nature.
If you use the "touch" spell medium, your spell gauntlet acts like a shield, with the added bonus that it blocks attacks and projectiles (and spells!) from any angle, not just the direction you're looking...?

**Comment by NextdoorPsycho** [comment]
Maybe even like a ward- that you can cast and it drains vis from the aura-thread over time (like all spells) but the longer you have it out- the more it costs

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#170
