### ISSUE TITLE
[BETA6] Game crashing when using Plan + Exchange Focus

### ISSUE THREAD

**Issue by Danymaddox** [Azanor/thaumcraft-beta#310]
My game crash every time I try to equip a focus made with "Plan" + "Exchange" to a Caster's Gaunlet.

Here you have the crashlog:

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/16/18 4:57 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at thaumcraft.common.items.casters.ItemCaster.getPickedBlock(ItemCaster.java:549)
	at thaumcraft.client.lib.events.HudHandler.renderCastingWandHud(HudHandler.java:596)
	at thaumcraft.client.lib.events.HudHandler.renderHuds(HudHandler.java:84)
	at thaumcraft.client.lib.events.RenderEventHandler.renderTick(RenderEventHandler.java:313)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_RenderEventHandler_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1078)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.common.items.casters.ItemCaster.getPickedBlock(ItemCaster.java:549)
	at thaumcraft.client.lib.events.HudHandler.renderCastingWandHud(HudHandler.java:596)
	at thaumcraft.client.lib.events.HudHandler.renderHuds(HudHandler.java:84)
	at thaumcraft.client.lib.events.RenderEventHandler.renderTick(RenderEventHandler.java:313)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_RenderEventHandler_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Danymaddox'/48938, l='MpServer', x=863.38, y=66.12, z=1330.62]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24936 game time, 24936 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 66 total; [EntityItem['item.item.arrow'/49920, l='MpServer', x=885.43, y=69.00, z=1329.01], EntityItem['item.item.bone'/49921, l='MpServer', x=884.91, y=69.00, z=1328.77], EntityItem['item.item.rottenFlesh'/49794, l='MpServer', x=910.71, y=64.00, z=1306.24], EntityItem['item.item.arrow'/50050, l='MpServer', x=881.01, y=70.00, z=1327.95], EntityItem['item.item.bone'/50051, l='MpServer', x=881.54, y=69.00, z=1328.22], EntitySheep['Sheep'/49030, l='MpServer', x=840.46, y=64.00, z=1305.78], EntitySheep['Sheep'/49031, l='MpServer', x=841.73, y=65.00, z=1296.50], EntityItem['item.item.rottenFlesh'/49032, l='MpServer', x=845.82, y=64.00, z=1306.96], EntitySquid['Squid'/49034, l='MpServer', x=837.84, y=62.40, z=1328.13], EntityItem['item.item.rottenFlesh'/49546, l='MpServer', x=818.59, y=64.00, z=1270.13], EntitySquid['Squid'/49035, l='MpServer', x=828.40, y=58.39, z=1318.22], EntityItem['item.item.bone'/50443, l='MpServer', x=866.80, y=64.00, z=1313.52], EntityCreeper['Creeper'/49044, l='MpServer', x=854.50, y=15.00, z=1268.50], EntityItem['item.item.rottenFlesh'/49941, l='MpServer', x=833.47, y=68.00, z=1388.58], EntityChicken['Chicken'/49046, l='MpServer', x=860.50, y=66.00, z=1251.50], EntitySheep['Sheep'/49053, l='MpServer', x=847.18, y=64.00, z=1303.43], EntityCreeper['Creeper'/49055, l='MpServer', x=872.17, y=65.00, z=1324.46], EntitySheep['Sheep'/49060, l='MpServer', x=880.28, y=56.81, z=1332.47], EntityZombie['Zombie'/49061, l='MpServer', x=878.42, y=56.00, z=1332.20], EntitySkeleton['Skeleton'/49062, l='MpServer', x=873.31, y=64.00, z=1330.49], EntityPlayerSP['Danymaddox'/48938, l='MpServer', x=863.38, y=66.12, z=1330.62], EntityCow['Cow'/49079, l='MpServer', x=890.56, y=64.00, z=1254.36], EntitySkeleton['Skeleton'/49081, l='MpServer', x=897.50, y=35.00, z=1282.50], EntityZombie['Zombie'/49082, l='MpServer', x=910.50, y=37.00, z=1291.50], EntityCreeper['Creeper'/49083, l='MpServer', x=910.50, y=37.00, z=1291.50], EntityCreeper['Creeper'/49084, l='MpServer', x=909.50, y=37.00, z=1292.50], EntitySkeleton['Skeleton'/49085, l='MpServer', x=931.50, y=51.00, z=1260.50], EntityCreeper['Creeper'/49088, l='MpServer', x=930.50, y=19.00, z=1276.50], EntityItem['item.item.arrow'/49728, l='MpServer', x=814.97, y=64.00, z=1274.68], EntityZombie['entity.Zombie.name'/49089, l='MpServer', x=935.57, y=16.00, z=1271.72], EntityCreeper['Creeper'/49090, l='MpServer', x=934.19, y=17.00, z=1272.70], EntityBat['Bat'/49096, l='MpServer', x=920.75, y=30.92, z=1306.75], EntityBat['Bat'/49107, l='MpServer', x=875.48, y=45.74, z=1385.00], EntityCow['Cow'/49108, l='MpServer', x=907.63, y=66.00, z=1368.19], EntityCow['Cow'/49109, l='MpServer', x=910.15, y=66.00, z=1365.11], EntityPig['Pig'/49110, l='MpServer', x=909.80, y=64.00, z=1375.94], EntityPig['Pig'/49111, l='MpServer', x=910.68, y=64.00, z=1372.56], EntityCow['Cow'/49112, l='MpServer', x=911.82, y=65.00, z=1370.45], EntityZombie['Zombie'/49114, l='MpServer', x=905.50, y=48.00, z=1326.50], EntityItem['item.item.bone'/49882, l='MpServer', x=879.69, y=70.00, z=1331.51], EntityCreeper['Creeper'/49117, l='MpServer', x=933.50, y=20.00, z=1292.50], EntityCow['Cow'/48992, l='MpServer', x=812.50, y=63.00, z=1296.50], EntityBat['Bat'/49120, l='MpServer', x=914.45, y=35.92, z=1298.32], EntityZombie['Zombie'/49123, l='MpServer', x=904.50, y=40.00, z=1337.50], EntityCow['Cow'/49125, l='MpServer', x=918.39, y=64.00, z=1392.14], EntityZombie['Zombie'/48998, l='MpServer', x=785.50, y=45.00, z=1410.50], EntityCow['Cow'/49126, l='MpServer', x=933.50, y=63.00, z=1382.98], EntityCreeper['Creeper'/48999, l='MpServer', x=820.50, y=13.00, z=1335.50], EntityCow['Cow'/49127, l='MpServer', x=934.50, y=63.00, z=1382.50], EntityCreeper['Creeper'/49000, l='MpServer', x=820.50, y=13.00, z=1335.50], EntityCow['Cow'/49128, l='MpServer', x=935.50, y=63.00, z=1381.50], EntityCow['Cow'/49129, l='MpServer', x=924.82, y=63.00, z=1385.50], EntityCreeper['Creeper'/49002, l='MpServer', x=821.50, y=13.00, z=1338.50], EntityCow['Cow'/49133, l='MpServer', x=913.81, y=66.00, z=1363.54], EntityCow['Cow'/49134, l='MpServer', x=914.76, y=65.00, z=1368.82], EntityItem['item.item.rottenFlesh'/50158, l='MpServer', x=887.76, y=66.00, z=1336.45], EntityPig['Pig'/49135, l='MpServer', x=916.30, y=64.00, z=1370.71], EntityCow['Cow'/49136, l='MpServer', x=915.32, y=65.00, z=1364.86], EntityPig['Pig'/49137, l='MpServer', x=914.26, y=64.00, z=1372.34], EntityChicken['Chicken'/49142, l='MpServer', x=869.50, y=64.00, z=1408.50], EntityCow['Cow'/49144, l='MpServer', x=911.57, y=64.00, z=1392.22], EntityBat['Bat'/49145, l='MpServer', x=915.33, y=14.72, z=1389.08], EntityCow['Cow'/49147, l='MpServer', x=918.01, y=64.00, z=1382.67], EntityCow['Cow'/49148, l='MpServer', x=914.78, y=64.00, z=1381.60], EntityCow['Cow'/49149, l='MpServer', x=916.50, y=64.00, z=1378.50], EntityCow['Cow'/49150, l='MpServer', x=915.50, y=64.00, z=1377.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:529)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332488080 bytes (317 MB) / 2567438336 bytes (2448 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 102
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_E7 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAAAAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAAAAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAAAAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
	UCHIJAAAAAAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAAAAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAAAAAAA	thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar) 
	UCHIJAAAAAAAAA	ThaumicJEI{1.1.1} [ThaumicJEI] (ThaumicJEI-1.1.1.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJAAAAAAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAAAAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	Launched Version: forge-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by twothe** [comment]
Good thing I didn't try that... Plan + Dig however works great.
