### ISSUE TITLE
"Bolt" focus causes a lingering ghostly particle effect in Multiplayer 

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#312]
Potentially also causes this in singleplayer, haven't tested this though.
The focus In question is a magic damage energy bolt focus with potency and frugal modifers.

![2018-02-16_13 01 40](https://user-images.githubusercontent.com/9419312/36308761-e248463c-1319-11e8-8231-9dc6e1560dfc.png)

As you can see, it creates the normal effect but rather than dissipating almost immediately, it hangs around for about 10 seconds.

**Comment by Ulysses2** [comment]
Can confirm that Wisps do this in singleplayer as well.

**Comment by Leppan** [comment]
And it's singleplayer too.
