### ISSUE TITLE
Beta 6:  Sapling drop rate too low?

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#317]
So I had a try to farm myself some silverwood in my new world.

First three trees I felled dropped 0 saplings.
The fourth dropped one.  Fifth dropped 0.  Sixth dropped three.  Now I had four saplings.

I planted those four.  The next three trees dropped 0 again.  The last one dropped 2.

So far that's ten trees to get 6 saplings.  0.6 saplings per tree.  Now I had 2 saplings.

Planted those two.  Very shortly I had 0 saplings.

At this rate, silverwoods would go extinct.  Isn't this drop rate a bit low?

**Comment by Ulysses2** [comment]
Fortune seems to have an effect, but I was only able to notice it with a cheated-in Fortune X tool. I wouldn't mind if it was made more effective so you had to probress a bit before being able to farm silverwoods. But just increasing the drop rate in general would be fine.

**Comment by UnixRonin** [comment]
I got one sapling total from the next two trees I cut.  I think the average seems to be tending more towards 0.5 saplings per tree.  So far I'm at 7 saplings from 14 trees.

I haven't tested the effect of a Fortune axe yet.

**Comment by twothe** [comment]
I recently cut down a silverwood tree with my fortune II gauntlet and it dropped 3 saplings. Either I got lucky, or fortune plays a big role in getting the saplings.

**Comment by Azanor** [comment]
That is about the expected drop rate. They are supposed to be super rare - it is even listed in their thaumonomicon entry.
