### ISSUE TITLE
[Question]:  What triggers Epiphanies? B6

### ISSUE THREAD

**Issue by Ratione** [Azanor/thaumcraft-beta#318]
I'm currently stuck in my world because i cannot trigger Epiphany in order to progress in either artifice or Auromancy. I have all the other requirements, but Ive been playing for a long time, and no Epiphanies have occurred. I have tones of research, but nothing i do helps. What am i doing wrong?

**Comment by dariumz** [comment]
What worked for me was going into the alchemy tree and start researching the things in there, when I did the automated alchemy one (I believe) I got an epiphany. :)

**Comment by Ratione** [comment]
I ended up getting a couple through research in other branches, but the Book contains no mention that you should have to do other research. I was loading up a new game, and had no interest in doing alchemy beyond the mandatory first section. I was trying to get to the gauntlet so i could play with the foci, since B5/6 fixed the crash. If its required, why not make that more clear? Or better yet, if its research that's mandatory, why have the Epiphany system at all, why not tell the player its gated behind specific research, which it looks like its doing *Anyway*?

**Comment by apmax** [comment]
It seems like you get epiphanies from researching various things, which makes sense as you're developing a more complete understanding of magical stuff and things.  You can't start learning something far off if you don't know enough general knowledge.

**Comment by Dayyer1** [comment]
In case you didn't know:
While holding a Thaumometer (spelling?) and shift-clicking on a chest, you will be able to scan every item in the chest.
Sometimes, you'll get research points. (I forgot what they're called now, but you'll get rewards for scanning certain items.)
The scanning works with pretty much any inventory, as far as I know, including iron chests, which makes scanning lots of things very easy.
Hope this helps. :)

**Comment by twothe** [comment]
You can... scan the whole inventory at once?? O.o

**Comment by kd8lvt** [comment]
In fact, you can scan colossal chests, meaning you can scan billions of items at a time (given you have iron chests). You just scan the core or an interface.

**Comment by Azanor** [comment]
You can a small bit of epiphany progress when scanning things, but you usually get a full point by completing certain key researches like Essentia Smelting.

**Comment by Ratione** [comment]
Could we maybe get a more clear explanation in the book? I don't mean anything 4th wall breaking, or anything, just something that gives at least some direction as to how they work or when they happen? Maybe we could get epiphanies or unlock tech trees when scanning items found in them? Like, if i scanned a Thaumium Golem, i would auto unlock the Golemancy Tree, because as a Magic Scientist or whatever, we have the ability to reverse engineer stuff. The book kindof already suggests we do this in several places.

**Comment by Bizuex** [comment]
I noticed you can also SHIFT+Scan the ME drives entirely.
