### ISSUE TITLE
[Improvement] Cocoa beans are too rare for a recipe

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#320]
With the terrain generation changes since 1.7 jungle biomes are now pretty rare. In most worlds you need to travel for hours to find one, which means that cocoa beans should only be used in very rare and precious recipes. Currently they are used in the harvest seal, which makes that seal excessively difficult to obtain.

**Comment by NerdimusPrime** [comment]
Maybe a crucible recipe to create cocoa beans from seeds or something?

**Comment by twothe** [comment]
That would be a good idea.
