### ISSUE TITLE
[Improvement] Chain spells should ignore pets of the caster

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#325]
Currently the chain spell is somewhat limited in use, as it hops to pets of the caster. If you have a horse, or pet wolves, or pet golems, the chain spell is going to kill them, which makes it rather useless. I also think (haven't tested it) that the spell would chain to other players, which would be a problem if playing with a friend.

I suggest the following changes:
- Chain spells should always ignore pets if the owner is the caster.
- If the gauntlet is shift-right-clicked, it will change mode between PvP (hit all players) to PvE (ignore all players).

**Comment by XoviaHarmile** [comment]
Same thing with the elemental sword, hits pets. I also think Pech shouldn't be hit by this unless agro'ed.

**Comment by Ulysses2** [comment]
Horses and pigs being ridden by a player are already immune to bolts and projectiles.Touch foci don't directly deal damage, but they still inflict secondary effects such as fore and slowness, which is probably a bug.

If you don't want players attacking each other on accident, disable PVP or put them on the same team with friendly fire disabled.

I think something to make foci more selective, like an effect modifier that makes the focus only target hostile mobs, is not a bad idea, but it belongs on thaumcraft-suggestions, not here.

**Comment by twothe** [comment]
2 days ago in B6 I killed my horse because the chain spell jumps to them and even aims at them, so I don't think they are immune. 

The switch for PvP is in regard to public servers that have PvP enabled in general, but then you might still want to play with a friend without killing him or her all the time. This is a very common setup for public Minecraft servers, so I think it is a relevant feature.

Thanks for the hint about the suggestion tracker, I wasn't aware it exists.
