### ISSUE TITLE
[B6] TC casts other mods potions to the wrong class

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#327]
See #314 (that report was prematurely closed)

`registerPotionTypeConversion` in the Forge API allows to register potions as `com.google.common.base.Predicate` however Thaumcraft later casts that class to `PotionHelper.ItemPredicateInstance` which then can cause a crash.

**Comment by A47C** [comment]
Yeah, having the same problem...

**Comment by jambonmcyeah** [comment]
I have the same issue
