### ISSUE TITLE
Conflict with the iron-nugget in some mod

### ISSUE THREAD

**Issue by Tollainmear** [Azanor/thaumcraft-beta#328]
This simply issues make a “fatally missing blocks and items” problem when client connect to server. this situation will block anyplayer to join server.
So plz try to make compatible with other mods such as taiga's(a dependency of tconstruct mod) iron-nugget, may add a configurable node in config to use other mod's item with same ore-dictionary id could solve this problem(I am not sure~)

**Comment by Azanor** [comment]
Could you post the logs you are getting? My iron nuggets are in the ore dictionary and should not be causing any errors like this.

**Comment by Tollainmear** [comment]
![pic](http://p1ptfdlcg.bkt.clouddn.com/QQ截图20180221022606.png)
[fml-server-latest.log](https://github.com/Azanor/thaumcraft-beta/files/1741345/fml-server-latest.log)
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/1741346/latest.log)

**Comment by Tollainmear** [comment]
the log files was generated by server, and I could not found any useful information :P

**Comment by Tollainmear** [comment]
Hi @Azanor ？

**Comment by MainFreak** [comment]
Uh those logs didn't have the right information I think. The only thing I saw in the logs was someone logging in either without or with a wrong version of Thaumcraft.

**Comment by Azanor** [comment]
Are you sure it is a TC issue? The mods you mention work fine with TC normally.

**Comment by Tollainmear** [comment]
nop, In fact, I don't know which mod cause the problem, the reason I post issue here, is because the server has been running for two months before thaumcraft 6 was released, then I setup thaumcraft 6 to server(which with multi mods loaded), and the client appeared this problem, client could not connect to server if setup thaumcraft6 to the server whose worlds was created with other mods.
