### ISSUE TITLE
Coremod ThaumcraftLoader: Unable to class load

### ISSUE THREAD

**Issue by MidnightsFX** [Azanor/thaumcraft-beta#33]
I keep getting this coremod complaint when loading Thaumcraft with other mods, Agricraft and WTF Expedition seems to trigger it, something to do dynamically generated textures, but I have not been able to pin down why.

Here is the coremod error: https://pastebin.com/PeWwkFfK

The crash which is listed as the cause is a seemly random failure to generate an atlas texture. 

When I see another crash I will provide it. The crash has been rather sporadic but becomes blocking (game won't load) once it occurs, changing mods being loaded eventually fixes it (then it will load with the same mods as was crashing before...).

**Comment by MidnightsFX** [comment]
This is caused by turning clothing off.
` # Enable Tech-Visor, Camo Pants, and other Clothing Items [default: true] B:ENABLED=false`

**Comment by Azanor** [comment]
The coremod class is currently not enabled which is why the error is occuring, but it should not be gamebreaking - MC just ignores it and goes on. 
It will be the first error you see in the log, but should not be the cause of the issues. Could you see if anything else is listed in the log?

**Comment by MidnightsFX** [comment]
Yeah that makes sense since it doesn't seem to be directly related to whatever is causing the model & texture stitching issues.

Looking back in my logs, the only guess I have as to why this was happening was Surge and FoamFix having issues implementing and copying the model loader.

I don't see any crash reports that list thaumcraft as the first error- besides optifine- which doesn't count.

I'll close this, thanks for clearing up that the coremod error should not be a blocking issue!
