### ISSUE TITLE
Thaumcraft crashing Modpack on load

### ISSUE THREAD

**Issue by SoulShark** [Azanor/thaumcraft-beta#333]
Minecraft version: 1.10.2
Thaumcraft version: Thaumcraft-1.10.2-6.0.BETA6.jar

[crash-2018-02-20_10.51.48-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1740758/crash-2018-02-20_10.51.48-client.txt)

**Comment by A47C** [comment]
This problem has been already mentioned in #327

**Comment by SoulShark** [comment]
Sorry! I read through some of the issues and I guess I missed it...
