### ISSUE TITLE
Casters gauntlet offhand glitch

### ISSUE THREAD

**Issue by HorstRadish** [Azanor/thaumcraft-beta#334]
I found when I put the casters gauntlet in my offhand slot the game Instantly crashes and when I tried to get back into the world the game crashes again and again. Eventually I had to go into MCedit to remove the casters gauntlet from my inventory.

**Comment by Ulysses2** [comment]
We can't really do much without a crash report. You can find them in the crash-reports folder inside your minecraft instance.

**Comment by Azanor** [comment]
Yup, I need a crashlog please.
