### ISSUE TITLE
B6:  Self-disassembling infernal furnace

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#335]
Possible bug with the Infernal Furnace.  Having just built an infernal furnace in the Nether, I went to try it out by smelting some of the oddly locally abundant netherrack to nether bricks.  Used to right-clicking to place items in the nearby crucible, I right-clicked with netherrack, and inadvertently placed netherrrack in the furnace's top opening instead of dropping it in.

**POOF!**  Suddenly I didn't have an infernal furnace any more.

This probably shouldn't happen.  Accidentally placing a block in the opening of an already-crafted infernal furnace shouldn't destroy it.  If I want to unmake my furnace, I should have to actively **break** it.

**Comment by Leppan** [comment]
You're not supposed to right-click, you're supposed to drop.

Though yes, that shouldn't happen.

**Comment by Azanor** [comment]
That is wierd.

**Comment by Azanor** [comment]
Yeah, I can't duplicate this at all. However placing a solid block in the top space will cause a odd rendering bug. Was that what you saw?
The furnace was designed with the idea you can place blocks in there like a hopper.

**Comment by UnixRonin** [comment]
No, it wasn't just a rendering bug.  Accidentally placing a block of netherrack in the opening caused the furnace to revert to the nether brick and obsidian structure.  I had to re-apply the sal mundi.

I will retest and see if I can reproduce it in B7.

**Comment by UnixRonin** [comment]
OK, I just re-tested in B7 and could not reproduce the problem.  Intentionally placing a block of netherrack in the opening was ... completely uneventful.  It just sat there.
