### ISSUE TITLE
 (B6) Server just force crashing every 2 min. Seeing thaumcraft highlighted as the error. 

### ISSUE THREAD

**Issue by Keveyy** [Azanor/thaumcraft-beta#337]
I am not sure if its Bioms O plenty Is conflicting with it.
(Update) - I Took bioms O plenty off the server that seemed to fix the issue found out I'm using the most updated version of bioms o plenty but its in Alpha so yea. I will try the stable build and find out how that goes. 

21.02 06:22:18 [Server] Server thread/ERROR Encountered an unexpected exception
21.02 06:22:18 [Server] INFO net.minecraft.util.ReportedException: Exception ticking world
21.02 06:22:18 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
21.02 06:22:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
21.02 06:22:18 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class thaumcraft.common.entities.monster.EntityPech
21.02 06:22:18 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_152]
21.02 06:22:18 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_152]
21.02 06:22:18 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_152]
21.02 06:22:18 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_152]
21.02 06:22:18 [Server] INFO at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:656) ~[aiq$c.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:140) ~[aik.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198) ~[ls.class:?]
21.02 06:22:18 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
21.02 06:22:18 [Server] INFO ... 4 more
21.02 06:22:18 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2018-02-21_06.22.18-server.txt
21.02 06:22:18 [Server] Server thread/INFO Stopping server
21.02 06:22:18 [Server] Server thread/INFO Saving players
21.02 06:22:18 [Server] Server thread/INFO Saving worlds
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/Overworld
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/Nether
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/The End
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/Moon
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/Deep Dark
21.02 06:22:18 [Server] Server thread/INFO Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world 0
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world -1
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world 1
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world -28
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world -11325
21.02 06:22:18 [Server] Server thread/INFO [THAUMCRAFT]: Removing aura cache for world -9999
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension 0
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension -1
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension 1
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension -28
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension -11325
21.02 06:22:18 [Server] Server thread/INFO [FML]: Unloading dimension -9999
21.02 06:22:19 [Server] Server thread/INFO [FML]: Applying holder lookups
21.02 06:22:19 [Server] Server thread/INFO [FML]: Holder lookups applied
21.02 06:22:19 [Server] Server thread/INFO [Galacticraft]: Unregistered Dimension: -28
21.02 06:22:19 [Server] Server thread/INFO [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
21.02 06:22:19 [Server] Server Shutdown Thread/INFO Stopping server
21.02 06:22:19 [Server] Server Shutdown Thread/INFO Saving players
21.02 06:22:19 [Multicraft] Server shut down (running)
21.02 06:22:19 [Multicraft] Not restarting crashed server.
21.02 06:22:19 [Multicraft] Server stopped

**Comment by Goof245** [comment]
What's in that crash report it saved? This looks a bit like something that was supposed to be fixed back in beta4-5ish.

**Comment by Azanor** [comment]
That is a very strange error. It claims Pech are not defined.  O.o

**Comment by JurjenVreugdenhil** [comment]
I have this exact same issue. It crashes the server and when the person joins that triggerd it, the server crashes again. I just teleport them to spawn the moment they join and tell them not to go there for now.

**Comment by jensz12** [comment]
I have the same issues with Pechs on B7

**Comment by jensz12** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class thaumcraft.common.entities.monster.EntityPech
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:656)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:140)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)
```
