### ISSUE TITLE
[B6] Automated Alchemy

### ISSUE THREAD

**Issue by NikolaDare** [Azanor/thaumcraft-beta#338]
i unlocked automated alchemy, made the device and now it doesn't take essentia from jars. the first time this happened it was on my private server so i tested it in creative and still doesn't work. 
i tried placing jars and pipes in every exit of the device. didn't work

**Comment by NerdimusPrime** [comment]
I don't have the game in front of me to check, but by "device", do you mean the thaumatorium?

**Comment by NikolaDare** [comment]
yes

**Comment by NerdimusPrime** [comment]
It works fine for me, so let's do a walk through.
Break any pipes connected to the thaumatorium.
Right click the thaumatorium and open the gui.
Place an iron ingot in the input slot. You should get a recipe output option on the right, probably thaumium.
Click the output so it gets a blue circle around it. The bottom row should show the essence required.
Attach jars and pipes with the correct essence to the thaumatorium inputs on the sides.
Anything happen?

**Comment by NerdimusPrime** [comment]
Also, do you have a heat source under the thaumatorium (nitor, lava, or flaming netherrack)?

**Comment by NikolaDare** [comment]
oh i found the problem i used the magma block for heating the crucible. i just put nitor and it works. thank you for help.

**Comment by NerdimusPrime** [comment]
No problem. :-)

**Comment by NerdimusPrime** [comment]
@Azanor, can you make this an enhancement request to add magma blocks as valid heat sources?

**Comment by NerdimusPrime** [comment]
Will the magma block work if you set it on fire first, like netherrack?

**Comment by NikolaDare** [comment]
it works when set on fire

**Comment by twothe** [comment]
It might be a good idea to have a kind of error message in the GUI that tells people that the heating is missing, as this seems to be a rather common mistake.

**Comment by jesmores** [comment]
Maybe Magma Block should be added as a heat source for the crucible. Magma needs more love <3

**Comment by TheFitzZZ** [comment]
If I may highjack this: does it work for you with recipes that use two or more types? For me, only the ones with only one work, the rest never gets pulled. I tried using one and two emptying transfusers. Thanks!

**Comment by NerdimusPrime** [comment]
Works fine for me, @TheFitzZZ. I just made a thaumium ingot using one emptying transfuser. Is your emptying transfuser connected directly to the thaumatorium, or is there any pipe in between?

I found that if you use pipe, 1 point of essentia stays in each section of pipe after the first essentia type gets pulled in, which blocks any other essentia type from entering the system.

**Comment by TheFitzZZ** [comment]
Thanks for your quick answer @NerdimusPrime! My first try was indeed using one transfuser with one pipe, then added another pipe and transfuser with no success. I then moved the structure to the jars and added the two transfuser left and right... and it still only would work with single essentia recipes... 

Was there any change here between B5 and B6? My server dude just told me we're still on 5 - apologies that I didn't get this information earlier.

**Comment by NerdimusPrime** [comment]
There were quite a few fixes between 5 and 6, but the problem I described with essentia residue in the pipes I discovered in 6, so presumably it's in 5 as well.

**Comment by Azanor** [comment]
I did add magma as a heat source for the crucible, but never updated the thaumatorium. Derp.
