### ISSUE TITLE
Thaumaturgy research requirements 

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#34]
This is just a suggestion, but I feel that the requirements for unlocking thaumaturgy are much more difficult and excessive than the requisites for alchemy and artifice. I'm pretty unlucky when it comes to world gen, and I usually have to resort to teleporting myself randomly around the world until I land in a desert, ocean, or extreme hills. For unlucky players like myself, or for anyone using mods that replace vanilla world gen/boimes, unlocking thaumaturgy can be a disaster. 
I would suggest either having a config option that lets you discover thaumaturgy by some other means, or by lessening the difficulty of the research entirely  (maybe only make us search for a magic forest biome?)

**Comment by Azanor** [comment]
I do agree that there is a disparity in the difficulty there and I was planning on balancing it out a bit more.

**Comment by UnixRonin** [comment]
Aside:  In my last 1.7.10 world, I **finally** found a magical forest biome something like 12,000 blocks from (0,0).

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#169
