### ISSUE TITLE
Runic Shielding infusion isn't working

### ISSUE THREAD

**Issue by LokiWiz** [Azanor/thaumcraft-beta#340]
I've got everything I need, but when I try to start the infusion process, nothing happens.

**Comment by Ulysses2** [comment]
It's working fine for me. What does your infusion setup look like?

**Comment by VallenFrostweaver** [comment]
I'm finding that you can create a ring with Runic Shielding +1 but you can't increase it beyond that. I have 10 times the amount of essence and the ingredients on the infusion set-up but the infusion altar won't activate.

**Comment by Ulysses2** [comment]
You have the right recipe? It's 1 salis mudus plus 2 amber - the amount of amber needed goes up by 1 for each level of shielding your item already has.

**Comment by Azanor** [comment]
Has this been solved or is it still an issue?
