### ISSUE TITLE
Golemancy research bug

### ISSUE THREAD

**Issue by thenextelement** [Azanor/thaumcraft-beta#354]
In the research table, when i click on a "scripting" card for golemancy research it completes the card without me having paper and scribing tools in my inventory.(beta 6)

**Comment by MainFreak** [comment]
By "inventory", do you include the inventory of the research table? Or just your player inventory?
It uses a bit of ink and paper from the table iirc but I am not sure either.

**Comment by thenextelement** [comment]
The "scripting" card consumes a piece of paper and a full set of scribing tools from the players inventory.

**Comment by Azanor** [comment]
Nope, it is consumed from the table.
