### ISSUE TITLE
Can't put multiple of same item.

### ISSUE THREAD

**Issue by jobensingh** [Azanor/thaumcraft-beta#356]
Im not sure if this is supposed to be the case or not, but I can't put 2 gunpowder into a cauldron or similar items as it just crafts another one of itself.

**Comment by ChaonicTheDeathKitten** [comment]
I would suggest to not use gunpowder as a base material then. If you want to go with renewable resources, give charcoal, cobblestone and any potion a go.

**Comment by jobensingh** [comment]
Yah I figured, just kinda makes gunpowder almost useless as a material then

**Comment by Azanor** [comment]
You can always melt it down in an essentia furnace and use filled phials in the crucible instead
