### ISSUE TITLE
a couple of broken labels, and how do i progress past them?

### ISSUE THREAD

**Issue by lolwutskis** [Azanor/thaumcraft-beta#36]
![2017-06-21_15 59 38](https://user-images.githubusercontent.com/28024805/27413043-00981564-56c7-11e7-8280-f9e28bd41f7b.png)
![2017-06-21_15 59 54](https://user-images.githubusercontent.com/28024805/27413058-07b5d7e6-56c7-11e7-8ef8-f8761728610f.png)

**Comment by Azanor** [comment]
Those still need to be added in.

**Comment by LordPinkerton** [comment]
Does this also include the Aurum aspect?
![aurum](https://user-images.githubusercontent.com/11956610/33010463-d1889d5a-cd97-11e7-8a9d-674777f9e5d2.png)

Is there any way to force past the requirement, or is this simply unfinished? Thank you.

**Comment by Azanor** [comment]
Oops, spelling mistake :p  
its supposed to be auram
