### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by KamiSami** [Azanor/thaumcraft-beta#360]
Okay! I am fan of this mod, therefore you might understand why i am asking these (i hope so at least..)

So, do you have any estimated time in mind when TC6 release will be for 1.12.2 Minecraft? (My top 1 question)

And another one, i really love focus magics (all magic to be honest, but especially those i can cast).. So, The question, will there be even more focus magics in future?

And another question, kind of related to first question, when is Eldritch tab going to be released? (approx. guess)

And which Minecraft version will you focus on the most?

And last question i come up with (had more but i forgot them for now, might ask later) Is there any way to raise vis in local aura? Like planting silverwood maybe?

(Edit) Oh! Also there is slight problem with golems replanting crops, i have them set to try replant crops as they harvest, but, for some reason they dont do that at least most of the time, could this be possible bug? It happens with potatoes

**Comment by jesmores** [comment]
> And last question i come up with (had more but i forgot them for now, might ask later) Is there any way to raise vis in local aura? Like planting silverwood maybe?

I'm curious about this too. However, if you're having problems getting enough vis in your current chunk for crafting with the worktable, there is an upgrade for it that allows it to draw vis from the surrounding chunks as well - I believe it is further down the auromancy research tree, or possibly artifice.

**Comment by Dayyer1** [comment]
I think it's called the Workbench Charger. It's in Auromancy. SO HELPFUL.

**Comment by Azanor** [comment]
This git is for bug reporting so I'm going to close this.

I will answer some of the questions however: 
I don't know when the conversion to 1.12 / eldritch tab / etc. will be done. I am currently in bug hunting mode so once most of those are squashed I will start working on that.

Currently there is no way to artificially increase the aura.

Golems are very derpy atm. Very derpy. I am well aware and I am looking for solutions.
