### ISSUE TITLE
Bug at start up may cause issues

### ISSUE THREAD

**Issue by Shadow-of-Christ** [Azanor/thaumcraft-beta#361]
There is something that may cause issues tho this matters only right now for 1.10.2 and wont matter in the future it may be worth taking a look at.

whenever you start up and scroll through the log it says something to the effect of "error upper casing is not supported in this version of Minecraft it will be supported in 1.11"

this can theoretically be fixed by making the .jar file lowercase as well as any supporting mods it seems to speed up load times as well.

**Comment by Azanor** [comment]
This will cause some logistical issues, so I am going to make this a problem we can live with till I update to 1.12 :p
