### ISSUE TITLE
B7:  Progression glitches

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#364]
1.  Auromancy, Basic Thaumaturgy, phase 3/3.
1a.  Should that now be "Basic Auromancy" ...?
1b.  I've crafted my first touch fire focus, but the thaumonomicon won't give me credit for it and let me complete the research.

2.  Celestial Observation
I can observe the starry sky, but seem unable to make celestial observations of the moon.  Is this implemented in such a way that it might possibly only work with vanilla textures?

**Comment by Dayyer1** [comment]
I could scan lunar ones just fine, I have no mods or anything changing the moon. Did you point your thaumometer directly at the moon?

**Comment by UnixRonin** [comment]
I aimed as directly at the center of the moon's visible face as I could.  Repeatedly.  If I were shooting at it, it'd have a nice group right between the eyes.

**Comment by Azanor** [comment]
What mods are you using that could possibly make changes to the night sky?

**Comment by Serifina** [comment]
Chances are, the conflicting mod is Astral Sorcery, which makes changes to the night sky. Astral Sorcery has a compatibility option in config - change weak render to true, and see if that helps.

**Comment by Azanor** [comment]
That only adds stars though? I would think it would try and keep the moon in the same place.

**Comment by UnixRonin** [comment]
**MODS**, none.  But I'm using a 128-bit resource pack with a photorealistic moon.

Yes, overworld.

**Comment by UnixRonin** [comment]
The fire focus problem appears to be that the first fire focus you make does **5 damage** per use, but the Basic Thaumaturgy (or Basic Auromancy?) progression requires a fire focus with **4.4 damage** which apparently can't be made.

**Comment by Saphrym** [comment]
I'm getting quadrant and sun, but no lunar pages. I'm using the Simply Thaumic modpack I made. Tried turning off resource packs.... no help.

**Comment by Azanor** [comment]
The sun and moon are exactly opposite from each other in MC. The fact that you can scan one and not the other is very strange.

**Comment by A47C** [comment]
@UnixRonin yep, it seems it's the case, I'm having the same problem with fire focus with 5 damage instead of 4.4

**Comment by UnixRonin** [comment]
I haven't tried scanning the sun, didn't know I could.   I'll try that as well.

**Comment by UnixRonin** [comment]
Oh, so, yeah, my findings match @Saphrym's, I can scan the sun but not the moon.

**Comment by ScottRadish** [comment]
Came here to report the same issue with the fire focus. I can craft it, but it deals 5 damage. The one in the book says it should deal 4.4, and won't give me credit for crafting.

**Comment by Azanor** [comment]
I am actually removing the fire focus craft as a requirement in the next version. It seems like there is some goofyness in the nbt values that makes it work for some and not for others. For me it works fine when I test.

**Comment by KomacloS** [comment]
I have the same issue with the focus fire- if it is no way to complete it, maybe a command ./tc research can deal with it?
 I only need the name of the research. Basic_Thaumaturgy and any combinations I tested isnt working..

**Comment by MatalMoore** [comment]
Try BASEAUROMANCY.

**Comment by KomacloS** [comment]
oh, thank you, that helped!

**Comment by UnixRonin** [comment]
Heh.  Used /tc to unlock BASEAUROMANCY, and had enough Auromancy theories built up to go straight to 82% complete...

**Comment by AbortRetryFail** [comment]
Just chiming in on this with the sun/moon issue. 
Running BETA7 with only Baubles and Thaumcraft on a SMP server. I'm able to scan all 4 quadrants of the sky and the sun, but not the moon at any phase. It just doesn't produce the notes.

**Comment by LemADEC** [comment]
Scanning the moon in multiplayer with sponge forge will raise an exception:
```
[14:54:11] [Server thread/FATAL]: Error executing task
/*****************************************************************************************************************/
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
/*                                          Completing incorrect phase                                           */
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
...
/* Minecraft : 1.10.2                                                                                            */
/* SpongeAPI : 5.2.0-SNAPSHOT-c675e80                                                                            */
/* SpongeForge : 1.10.2-2477-5.2.0-BETA-2793                                                                     */
/* Minecraft Forge : 12.18.3.2511                                                                                */
...
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2477-5.2.0-BETA-2793]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3948) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
>       at thaumcraft.common.lib.research.ScanSky.onSuccess(ScanSky.java:80) ~[ScanSky.class:?]
>       at thaumcraft.api.research.ScanningManager.scanTheThing(ScanningManager.java:48) ~[ScanningManager.class:?]
>       at thaumcraft.common.items.tools.ItemThaumometer.doScan(ItemThaumometer.java:137) ~[ItemThaumometer.class:?]
>       at thaumcraft.common.items.tools.ItemThaumometer.func_77659_a(ItemThaumometer.java:53) ~[ItemThaumometer.class:?]
>       at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163) ~[adz.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
>       at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2477-5.2.0-BETA-2793]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) ~[CauseTracker.class:1.10.2-2477-5.2.0-BETA-2793]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) ~[PacketUtil.class:1.10.2-2477-5.2.0-BETA-2793]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) ~[fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 7 more
```

Sounds like TC Beta7 is using a client method to get the moon position.

Players are able to get sun and the 4 stellar quadrants, it's only an issue with trying to scan the moon.

**Comment by Saphrym** [comment]
Yep. The moon scanning issue is confirmed as a server problem only on my end also.

**Comment by UnixRonin** [comment]
The really odd part is being able to scan the sun but not the moon.

**Comment by Beetrootmonkey** [comment]
I second not being able to get notes from scanning the moon while I'm able to scan both stars and sun without any issues.

**Comment by yoshiweegee** [comment]
I can confirm that there is an error regarding scanning the moon with a Thaumometer while connected to a server. This is the error message generated when attempting to do so:
`[21:06:12] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at thaumcraft.common.lib.research.ScanSky.onSuccess(ScanSky.java:80) ~[ScanSky.class:?]
	at thaumcraft.api.research.ScanningManager.scanTheThing(ScanningManager.java:48) ~[ScanningManager.class:?]
	at thaumcraft.common.items.tools.ItemThaumometer.doScan(ItemThaumometer.java:137) ~[ItemThaumometer.class:?]
	at thaumcraft.common.items.tools.ItemThaumometer.func_77659_a(ItemThaumometer.java:53) ~[ItemThaumometer.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more`

I hope this helps!
