### ISSUE TITLE
[Beta 7] Can't unlock void metal essentia smelter.

### ISSUE THREAD

**Issue by jobensingh** [Azanor/thaumcraft-beta#365]
I Can't unlock void metal essentia smelter as i am only 3/5 in alchemical metallurgy because under things that need to be discovered is "research.c_voidstuff.text". I'm hoping this gives me an epiphany because as of beta 7 I needed to use an extra epiphany for arcane infusion which leaves me missing one for golems.

**Comment by UnixRonin** [comment]
I'm presuming void metal is part of the eldritch tree, which isn't done yet.

**Comment by jobensingh** [comment]
So what should I do about the extra Ephiphany I need now

**Comment by Azanor** [comment]
I am actually considering removing epiphanies. They are a pointless hurdle atm.

**Comment by jobensingh** [comment]
I liked the idea, and them being a hurdle, just wish you got them in a different way such as having to go on quest for it or something
