### ISSUE TITLE
Crafting a void jar with a full warded jar deletes label and essentia

### ISSUE THREAD

**Issue by gerbilfat** [Azanor/thaumcraft-beta#367]
I had crafted a void jar from a full normal warded jar with a label. The game let me craft it, but the resulting void jar was empty w/ no label. The essentia in the jar and the label seemed to be deleted by the crafting process, and no flux was generated.

TC6 and Baubles, no other mods installed, SMP. Thank you!

**Comment by jesmores** [comment]
Happened to me in Beta6 too

**Comment by Azanor** [comment]
Not really a bug since nowhere is it claimed that you will retain the contents of the jar. 

I might at some point alter the recipe so the contents and labels remain.

**Comment by jesmores** [comment]
FWIW it did force me to learn how the essentia pipe suction system worked when I decided to use them to manually transfer contents to a void jar.

**Comment by gerbilfat** [comment]
I wasn't sure if the recipe would even work and tried it just to see what would happen. We **are** beta testing after all ;) Normally there's some kind of penalty for dumping essentia. Having the essentia be deleted from the game without repercussions goes against the world building setup by the rest of the mod content where you'll mess up the environment if you're a Bad Wizard.
