### ISSUE TITLE
[Beta 7] Strange Potion Sprayer texture

### ISSUE THREAD

**Issue by groting** [Azanor/thaumcraft-beta#371]
Click on Potion Sprayer with MMB in creative.

![2018-02-27_21 00 54](https://user-images.githubusercontent.com/5873866/36797629-7861df9a-1cb9-11e8-9df0-3b8654ac3b56.png)

**Comment by Broam** [comment]
The "Potion Sprayer as an Item" texture seems to be undefined. Dropping the block as an item also yields this.
