### ISSUE TITLE
[Beta 7] Odd golem behavior regarding Arcane Pattern Crafters and inventories

### ISSUE THREAD

**Issue by ZiaAvenicia** [Azanor/thaumcraft-beta#372]
Arcane pattern crafters don't seem to give an update to inventories when putting items into them, which makes it so that inventories with empty seals on them that have pattern crafters putting crafted items into them unable to have their inventories emptied by golems.

**Comment by Azanor** [comment]
I am unable to duplicate this issue. What containers did you have under the pattern crafter?

**Comment by ZiaAvenicia** [comment]
I'll record a video on it soon so I can show the issue.

**Comment by ZiaAvenicia** [comment]
https://www.youtube.com/watch?v=cCfbbEFRVJA& Here's the video. The bug is at 3:25, while the rest of the video is showing how everything else is working except what I have at 3:25.
