### ISSUE TITLE
B7:  Jar/phial issue

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#373]
OK, first of all, my understanding of jar/phial interactions is this:

1.  Right-clicking an **empty** phial on a warded jar containing at least 10 essentia fills the phial from the jar.
2.  Right-clicking a **filled** phial on a warded jar with room for at least 10 of the type of essentia in the phial empties the phial into the jar.
3.  Right-clicking an **unlabelled** warded jar with a label that is **not incompatible with the jar's contents** labels the jar.
4.  Right-clicking a **labelled** warded jar **on the label** with an empty hand removes the label **without emptying the jar.**
5.  Right-clicking a warded jar containing essentia **on any unlabelled face** with an **empty hand** empties the jar.
6.  **No other action** should empty the jar.

Do I have this all correct?

In practice, what I have observed is that #2 above, right-clicking a filled phial onto a warded jar that can accept the essentia contained in the phial, does **not** empty the phial into the jar; instead, **it empties both the phial and the jar.**  I just dumped half a jar of Terra this way.

(I've come to realize, upon seeing it happen again, that this is how I accidentally dumped a full jar of Perditio in my last playthrough in B4 or so, triggering the taint eruption that totally destroyed my base.)

**Comment by Azanor** [comment]
I am assuming this happens when you sneak-click? That is when I have been able to reproduce it - normally it does not occur. Still a bug though :p

**Comment by UnixRonin** [comment]
Uhhhh......    you know, now that you mention it, I'm not certain if I was sneaking or not.  I don't **THINK** so, but so many other mods do use that mechanic it's possible I could have been doing it from force of habit without realizing.
