### ISSUE TITLE
[Beta 7] Burst effect renders Break foci useless

### ISSUE THREAD

**Issue by Jaitsu** [Azanor/thaumcraft-beta#374]
Been doing some experimenting with different focus effects, and just discovered that trying to combine Burst and any Break focus makes it completely ineffective. Tested with Bolt, Projectile and Touch, even with Potency. It casts as normal and consumes vis, but blocks are completely unaffected. (I'd been expecting it to affect blocks in a small radius/bubble.)

**Comment by Azanor** [comment]
Focus system changed in beta 8 onwards so this no longer applies. Burst will be re-added in beta 9+ and it will effect blocks then.
