### ISSUE TITLE
Essentia mirror not recognized

### ISSUE THREAD

**Issue by Shadow-of-Christ** [Azanor/thaumcraft-beta#376]
So I always set up a giant kind of alchemy lab to work with and test and stuff and I've recently notice that essentia mirrors are not recognized by the filler essentia tubes the empty version seems to work fine but no matter what I try it seems that even if I isolate the filler and mirror somewhere it won't work it will only take it from the jar directly I don't know if this is the way it was designed or if its a bug but any time try using an empty or filler to get to a mirror the mirrors aren't recognized as part of the pipe network as they have been in previous builds.

**Comment by Azanor** [comment]
Fillers and mirrors do not interact. Mirrors are solely useful for the infusion altar. Honestly, the whole system is a bit wack and needs a rework.
