### ISSUE TITLE
[Beta 7] Cannot seem to actually change research difficulty to -1 (aka using experience to buy research)

### ISSUE THREAD

**Issue by treblotmail** [Azanor/thaumcraft-beta#380]
After updating to Beta 7, "Discovering Infusion" and "Discovering Golemancy" were locked again. After determining it was impossible to research them without cheats, I tried to change the "research difficulty" to -1 to buy the research with experience so I could progress in the game again. However, after changing the config file, I was never able to "buy" the research when I had 30 or so levels; I couldn't even do it in creative.   Is this a bug or am I doing something wrong?

**Comment by mujmajnkraft** [comment]
It looks like Azanor didn't update config file. There is a bunch of options left from previous versions that do nothing right now (like node rarity, since nodes don't exist at all in this version). Possibilit to buy research for experience no longer exists due to changes in research system.
