### ISSUE TITLE
B7 - Vis discount applies to cost but doesn't apply to enable crafting

### ISSUE THREAD

**Issue by LemADEC** [Azanor/thaumcraft-beta#383]
As of Beta7, while making an Arcane workbench recipe, the Vis discount doesn't apply towards enabling the craft.

For example, Auxiliary Venting Port requires 150 vis. With 2 googles and a full Thaumaturge set, I will get 18% discount, which is 123 vis.
* While available vis is below 123 vis, recipe output shows dimmed and can't be picked up.

* While available vis is below 150 vis, and above 123 vis, recipe output is missing (like it's an invalid recipe) and can't be picked up.
![image](https://user-images.githubusercontent.com/4776032/36928594-6b0eccc0-1e87-11e8-97c4-752d73fdb385.png)

* Above 150 vis, the recipe output is shown and can be picked up.

* After crafting, the available vis is decreased by 123 vis, hence applying discount properly.

This was observed on a dedicated server. Single player wasn't tested.

**Comment by McFrugal** [comment]
Can confirm this happens in single player as well.
