### ISSUE TITLE
B7: Problem with Research

### ISSUE THREAD

**Issue by Praetor238** [Azanor/thaumcraft-beta#387]
This isn't so much a problem with how a research is done, but upon switching between B6 and B7, I had partially completed the research for artifice/infusion.  With those researches being split up in B7, I have found that I cannot complete the artifice research and the goggles of revealing are uncraftable/the recipe isn't available.

**Comment by Azanor** [comment]
Unfortunately that is not really fixable. You might want to spawn yourself a cheat thaumonomicon.
