### ISSUE TITLE
[B7] The 'Control Seal: Butcher' Infusion craft can not start.

### ISSUE THREAD

**Issue by nekotan9** [Azanor/thaumcraft-beta#388]
I will report what I noticed on the Infusion craft.
Attempting to place 'Control Seal: Guard' on the center pedestal to craft 'Control Seal: Butcher' will cause Seal to stick to the center pedestal. Regardless of whether sneaks are present, it will occur.

![2018-03-04_12 27 36](https://user-images.githubusercontent.com/12724117/36942338-f8db8e04-1fb2-11e8-9814-cea521892252.png)

**Comment by PyroManiac999** [comment]
I used a hopper to get it in, but it's something Azanor could maybe take a look at?

**Comment by Z1xt** [comment]
Same issue when trying to put a seal in the crucible by right-clicking instead of throwing. The easiest solution probably will be to make seals place-able only on shift+right-click?
