### ISSUE TITLE
Dupe with focus: silktoch 

### ISSUE THREAD

**Issue by evernife** [Azanor/thaumcraft-beta#390]
When using the focus of Sliktouch, if you break a machine from EnderIO, you drop the machine with all internal items, but the items stay inside it.

So, you get an infinite dupe, just keep breaking your machines! :D

> Thaumcraft-1.10.2-6.0.BETA7.jar
> and
> spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar

**Comment by evernife** [comment]
Seems to work with other mods like FluxNetworks as well

**Comment by Azanor** [comment]
This the same thing happen with a vanilla silk touch pickaxe?

**Comment by evernife** [comment]
Nop, just with the Focus.

I Tried with modded pickaxes too (DraconicEvolution, ThermalExpansion, TinkersConstruct, etc) they work well.
