### ISSUE TITLE
Possible Suggestion- Thaumic Horizons (And A Little More)

### ISSUE THREAD

**Issue by CTH999** [Azanor/thaumcraft-beta#394]
The Best [Thaumcraft Addon](https://ftbwiki.org/Thaumic_Horizons), Thaumic Horizons.

There are some features in it that would be nice, I just don't know what you think.

1. [Mob-Infusion](https://ftbwiki.org/Mob_Infusion), and it's offshoot, [Self-Infusion](https://ftbwiki.org/Self-Infusion)
2. [Reincarnation](https://ftbwiki.org/Reincarnation), and the [Mirred-Amulet](https://ftbwiki.org/Mirrored_Amulet)
3. [Essentia-Potions](https://ftbwiki.org/Seroconverter)
4. [Silverwood and Greatwood](https://ftbwiki.org/Greatwood_Boat), [Thaumium](https://ftbwiki.org/Thaumium_Boat), and maybe void metal boats
5. Wand Effects: [Liquifaction](https://ftbwiki.org/Wand_Focus:_Liquefaction), [Illumination](https://ftbwiki.org/Wand_Focus:_Illumination_(Thaumic_Horizons)), [Disintegration](https://ftbwiki.org/Wand_Focus:_Disintegration), And, [Animation](https://ftbwiki.org/Wand_Focus:_Animation) And, Maybe A Slow One
I See Slow making it more powerful, but take longer. (I.E. It would take a while before a _Slow_, _Plan_, _Break_ Starts breaking. This could be used tactically. and as a potency that uses less VIS!

However, these are just ideas. It's your mod, so you decide what to do :)

Thanks!

**Comment by WindBlades** [comment]
I'm just developing an addon for some time that will bring back old mechanical abandoned addon like thaumic horizon ^ ^ (of course it will be rework and slightly change)

**Comment by CTH999** [comment]
OK, Can't wait :)
I do hope some things will be implemented, but, well, an addon will be nice too!

thanks!

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#217

**Comment by CTH999** [comment]
Ok! Thanks!
