### ISSUE TITLE
[B7] Auromancy (Basic Thaumaturgy)

### ISSUE THREAD

**Issue by Otisnfur** [Azanor/thaumcraft-beta#396]
It appears as though the third and final step of the first "Quest" for Auromancy is impossible to complete. I have crafted the "Touch Fire" Focus, however when I craft it, it comes out with 5 damage whereas the Thaumunomicom want's it to have 4.4 Damage and thus does not complete the quest.
![image 1](https://i.imgur.com/Jgzko8Y.png)
![image 2](https://i.imgur.com/L0iGEt3.png)

**Comment by darklex55** [comment]
I have the same problem on a server. One player can do it, another one can't. Even tried to do it myself by login in with his account but can't do it either

**Comment by Otisnfur** [comment]
@darklex55 I actually found another issue with the same problem. Apparently it's going to be fixed in the near future. https://github.com/Azanor/thaumcraft-beta/issues/364

**Comment by Otisnfur** [comment]
@Lightone Harvest Festival. Pack is Renaissance

**Comment by Phantom329** [comment]
I'm having this same issue, how do you name the research so that I can use the command to force it?
