### ISSUE TITLE
No word on the mod for almost a month.

### ISSUE THREAD

**Issue by CyprinusCarpio** [Azanor/thaumcraft-beta#4]
Not to sound like whining ungrateful one, but the ones who do not donate to you on Patreon, did not get a word on the devolopment of the mod for almost a month. Thaumcraft for 1.10.2 is the most anticipated mod as of ever, even more than Aether for 1.7.10. I understand that you got real life problems, which may take a lot of time. I am not the only one to be dying of curiosity. With the relase of Bibliocraft and Project Red, Thaumcraft is the only mod left. No Minecraft modded experience is full for me without Thaumcraft, as it is for hundreds of thousands of people. I think, it would be an safe assumption, that most of those people would agree with me on that we dont want relase just now, we demand information. And, just a suggestion. Thaumcraft was never an open source mod. Maybe its time to change that? I understand the pros and cons of this idea. From my (as for now past) example, i can assure you, that relasing the mod in not compiled form is enough to protect it from thousand of people using unstable and not done versions, then whining at you cuz their world crashes every time they load it. Plus, the ones who CAN compile it, and even make slight fixes if they notice something (count me in) would with all the pleasure report bugs and request commits. This way, mod devolopment would be at least a little faster. Not to mention, that a look of others into the code might offer solutions that one couldn't even think of (ask the Bibliocraft author about it).
You might say that this will remove your 'leverage' on the patreons to pay. But, i think it is untrue, as there  are a lot of people who are paying the 1$ monthly. My other idea, is that you should add more donation options. Because i think 1$ is too low for your work, and on the other hand i cant just stick 25$ into someones wallet. A few new donation options like 5$, 10$, 15$ would surely make more people donate.
To end this essay, i will say that this is not by any means whining for you to relase the mod as fast as you can.
Cheers

**Comment by CuteyCang** [comment]
Agree.
Thaumcraft is my favorite mod. I check MinecraftForum,Github and Twitter everyday, but no news about the mod. I feel depressed.
I think all CyprinusCarpio's ideas are very great.
And Thanks you for your perfect work. ❤
:)

**Comment by diamondsaplenty** [comment]
much agreed
and if we get more beta testers maybe development will go faster because more bugs will be reported (maybe i honestly dont know)

**Comment by joelou1** [comment]
Dont worry about it too much, we donators dont recieve much info either. Last thing I know is that he was re-working on the wand system.

**Comment by CyprinusCarpio** [comment]
Unfortunately Azanor has been ill for some time, hence no updates.
Fortunately,
http://i.imgur.com/OTzUw2m.png

**Comment by CyprinusCarpio** [comment]
So, how is the Alpha build 7 going? If i may know?

**Comment by Azanor** [comment]
Already out and I'm working on 8

**Comment by CyprinusCarpio** [comment]
How do you see the ideas i have wrote down in my 'essay'?

**Comment by groting** [comment]
Mr. CyprinusCarpio please be patient. Do not distract the developer to work on the mod. Azanor puts messages on the forum if necessary. And this section is created for feedback from beta testers.
