### ISSUE TITLE
Harvest Seal

### ISSUE THREAD

**Issue by Otisnfur** [Azanor/thaumcraft-beta#403]
The Harvest Seal doesn't seem to be working.

I have placed the Harvest Seal down, and my Golem goes around and attempts to farm to his hearts content, however he never really "harvest" the crops, and doesn't deposit them in a chest despite there being a store seal.

https://youtu.be/NpioEmxgm2U

This was attempted on a server with the following Modpack: 
Renaissance

**Comment by Azanor** [comment]
This is obviously a mod interaction of some kind. You might want to report this to the modpack owners.

**Comment by LemADEC** [comment]
try in the wild instead of inside a protected area, golem might be acting under a non-trusted fake player
