### ISSUE TITLE
B7:  Golemancy progress blocked

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#405]
Golem flight:  "Closely examine a flying creature."

I've tried scanning chickens, hellbats, ghasts, blazes ...   several Mo'Creatures flying mobs, but I wasn't expecting them to work and they didn't.  I'd scan a bat if I could find one.  Thinking perhaps I'm not examining them closely enough, I tried killing a chicken, cooking it, and eating it.  It was tasty, but failed to yield new insight.  Maybe if I added a Bearnaise sauce...?  Or lemon pepper.  Lemon pepper is good.

And then there's the Use seal, and the other things that depend on Biothaumic Minds.  I'm blocked on an epiphany again and cannot figure out what should give me that epiphany.

**Comment by ZiaAvenicia** [comment]
Did you ever scan a vanilla bat?

**Comment by UnixRonin** [comment]
As I said, "I'd scan a bat if I could find one."  They aren't always easy to find.

**Comment by UnixRonin** [comment]
I eventually gave up and spawned in a bat...  The problem is most likely the high mob spawn rate of Mo'Creatures,  It's supposed to be able to be adjustable in Custom Mob Spawner, but CMS is the very devil to configure, and BiomeTweaker interacts with spawning as well, and....

Should any flying creature suffice?  If it is intended to specifically need a bat, perhaps the hint needs to be a little more specific too.

**Comment by Broam** [comment]
A possible fix would be that Firebats would also count.

**Comment by UnixRonin** [comment]
Yup, when the chicken didn't work I thought "Firebats for sure."  I was wrong.

Though given that the description of golem flight isn't so much flight as levitation, I almost wonder whether Blazes wouldn't be a better thaumaturgical fit.  They levitate, after all.  And hey!  What thaumaturge doesn't need the challenge of getting close enough to a Blaze to scan it?  :)

**Comment by Azanor** [comment]
I'll expand the list of flying critters that count towards that unlock.

**Comment by pashkanorm** [comment]
What about the "Climbing creature"?

**Comment by Broam** [comment]
Have you tried spiders?

**Comment by comfuzzled** [comment]
I actually summoned a a wither to attempt to solve the problem. Bats suck to find and apparently the wither doesn't work either. I haven't tried yet, but I assume the ender dragon and the vex also don't work. These should probably be added to the list that work for a later update.
