### ISSUE TITLE
[B7] Basic Thaumaturgy research will not proceed

### ISSUE THREAD

**Issue by nekotan9** [Azanor/thaumcraft-beta#406]
I will report events that seem to be faulty.
In the third phase of Basic Thaumaturgy's research, despite creating the specified item, the research is not completed.Although it is unknown whether it is a direct cause, there seems to be a case in the item display of the commentary and the item created.Please check the screenshot.

![2018-03-14_22 17 17](https://user-images.githubusercontent.com/12724117/37404860-6762c416-27d6-11e8-8cb6-892f836205e6.png)
![2018-03-14_22 17 05](https://user-images.githubusercontent.com/12724117/37404862-691806a4-27d6-11e8-89e9-b9e54cdf2b6c.png)

**Comment by Otisnfur** [comment]
@nekotan9 
https://github.com/Azanor/thaumcraft-beta/issues/396
https://github.com/Azanor/thaumcraft-beta/issues/364

This is already documented and a fix is in progress

**Comment by nekotan9** [comment]
oh, sorry. tx Otisnfur
