### ISSUE TITLE
Golem Use Seal crashes game

### ISSUE THREAD

**Issue by chukklehed** [Azanor/thaumcraft-beta#409]
I don't know if this is an issue with the seal or just how it interacts with Tinker's Construct, but I set up a golem to use a casting basin and once the basin was full, the server I was running crashed. Any attempt to launch the server afterward crashed it again, and I eventually had to load from backup. Attached is the error log. It should be noted the error happened durring Beta 6, but persisted into Beta 7.

[fml-server-1.log](https://github.com/Azanor/thaumcraft-beta/files/1821430/fml-server-1.log)

**Comment by Azanor** [comment]
The bug isn't 100% on my side, but I will try and catch the exception.
