### ISSUE TITLE
Erroneous biome registration

### ISSUE THREAD

**Issue by srs-bsns** [Azanor/thaumcraft-beta#410]
Currently, the old (1.7.10) method employed to register Thaumcraft's biomes, using the vanilla registration method,
has the biomes being registered in the `minecraft` domain, instead of the `thaumcraft` domain. This is due to passing
only the biome registration name to the method without Thaumcraft's mod ID prepended, so during the creation of the
`ResourceLocation`, `minecraft` is assumed.

There are a few different ways to remedy this. The easiest way would be to simply prepend the Thaumcraft Mod ID to the
biome registration name ("thaumcraft:biome_name") in the call to `Biome#register`, but there are other, more desirable ways.

The best way would be to register your biomes directly to the Forge registry, using the registration event. This will not
only solve this issue, but also has the added advantage of not having to worry about manually assigning biome IDs as they
will be assigned automatically, and therefore will not conflict with other biomes added by other mods.

Here is an example class to handle registration of your biomes with the `RegistryEvent.Register<T>` event:
```java
@EventBusSubscriber // This class will be subscribed to the MinecraftForge.EVENT_BUS during mod construction.
public final class Registrar
{
    @SubscribeEvent
    public static void registerBiomes(final RegistryEvent.Register<Biome> event) // An event for biome registration
    {
        // This is where you register all of your biomes..

        Biome myBiome = new MyBiome(/*<BiomeProperties>*/); // Create an instance of a biome
        // #setRegistryName (one of 3 methods) does not have to be called here. It can be called from the constructor
        // of your biome class, but this must be done before passing the object to #register below.
        myBiome.setRegistryName("thaumcraft", "my_biome_registry_name"); // see: IForgeRegistryEntry#setRegistryName
        event.getRegistry().register(myBiome);
        // After registration you can add BiomeDictionary tags for your biome (biome needs to be registered first).
        BiomeDictionary.addTypes(myBiome, BiomeDictionary.Type.SPOOKY, BiomeDictionary.Type.MAGICAL/*, etc...*/);

        // Note: You will still have to use the BiomeManager to add other properties for the biome, such as adding
        // it to OverWorld generation with a call to: BiomeManager#addBiome (Magical Forest only, in this case),
        // or to allow village/stronghold generation, etc..
    }
}
```

Classes used, for reference:
`net.minecraftforge.fml.common.Mod.EventBusSubscriber`
`net.minecraftforge.fml.common.eventhandler.SubscribeEvent`
`net.minecraftforge.event.RegistryEvent`
`net.minecraftforge.common.BiomeDictionary`
`net.minecraftforge.common.BiomeManager`

More methods can be added to the above example class to register all of your other objects with their appropriate Forge registry.
See Docs here: https://mcforge.readthedocs.io/en/latest/concepts/registries/

**Comment by Azanor** [comment]
Thanks, I have been meaning to do this for a while now, but keep forgetting :p

**Comment by Azanor** [comment]
Hmmm, I keep running into this error:

[10:32:36] [Client thread/WARN] [FML]: ****************************************
[10:32:36] [Client thread/WARN] [FML]: * Dangerous alternative prefix `thaumcraft` for name `magical_forest`, expected `minecraft` invalid registry invocation/invalid name?
[10:32:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:32:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:91)
[10:32:36] [Client thread/WARN] [FML]: *  at thaumcraft.common.world.biomes.BiomeGenMagicalForest.<init>(BiomeGenMagicalForest.java:43)
[10:32:36] [Client thread/WARN] [FML]: *  at thaumcraft.Registrar.registerBiomes(Registrar.java:18)
[10:32:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_Registrar_registerBiomes_Register.invoke(.dynamic)
[10:32:36] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)...
[10:32:36] [Client thread/WARN] [FML]: ****************************************

**Comment by srs-bsns** [comment]
For some reason, when you are setting the registry name, Forge thinks that `minecraft` is the active mod container, so it is warning that your intended domain 'thaumcraft' doesn't match the name of that mod container. 

See: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/registry/IForgeRegistryEntry.java#L75-L84

I'm not exactly sure why this is happening in your case. Is your biome class being instantiated at a time that is outside of the mod initialization lifecycle?
