### ISSUE TITLE
B7 About the Arcane Spa ...

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#411]
The Thaumonomicon says the Arcane Spa can be filled using automation.  However, I have yet to find any kind of pipe that will connect both to the Arcane Spa and to a water source (for example, an Ender Tank from Ender Storage, or an Aqueous Accumulator from Thermal Expansion).  Thermal Expansion fluiducts, Mekanism mechanical pipes, no joy.  Both worked in 1.7.10.  Neither will it draw from a pool of water below it, though the Thaumonomicon says it will pump fluids.  An Everflowing Urn won't fill it either.  I've yet to find any way to fill it except by hand with buckets.

**Comment by Azanor** [comment]
Works fine for me - it will only fill if in mix mode if there is ingredients inside, otherwise it will need to be set to 'Just use fluid' mode. It also depends what sort of liquid you are using.

**Comment by UnixRonin** [comment]
I can get it to pump water (mixed or otherwise) out of itself to fill a pool/bath above it, yes.  What I can't get it to do is fill **itself** from any water source, nor get any fluid-carrying pipe to attach to it in order to pipe water in.  It's buckets by hand, and that's it.

**Comment by Broam** [comment]
Try using the Jar of Endless Water. That worked for me.

**Comment by AnrDaemon** [comment]
I've successfully fed it from the bottom using 2x2 EnderIO Reservoir.
What I can't get is salts automation. EnderIO conduits do not connect to Arcane Spa.

Do you still use IInventory? It has been deprecated for two years.

**Comment by UnixRonin** [comment]
I just retested in B11, and Thermal Expansion fluiducts connect to the spa now.
Not sure how I'd automate salts as well; seems that'd require connecting ducts on two different faces.  Which I suppose is actually feasible if I use a microblock cover over the side connection.  I'll have to see whether itemducts connect to it too.

**Comment by AnrDaemon** [comment]
Itemduct does. Don't Thermal Expansion have covers?

**Comment by UnixRonin** [comment]
...You're right, Thermal Expansion has its **own** covers.  I forgot that.

**Comment by UnixRonin** [comment]
Confirmed:  Arcane spa now fills via Fluiducts.  Other fluid pipes will presumably also work.

**Comment by Geethebluesky** [comment]
Would there be a way to get the Everful Urn to fill it somehow though?

I'm not using any pipe or device-adding mods, would be nice to have the Urn work with the Spa somehow since they're both in the same mod, feels kind of logical.

**Comment by UnixRonin** [comment]
I haven't retested with the Urn.  But yeah, it would be good for that to work.

**Comment by Geethebluesky** [comment]
I have an Everful Urn 2 blocks above an Arcane Spa in my bath (Spa, above it: 1 layer of water, above it: Urn). It's currently not refilling the Spa, which is set to "just use fluid". I would expect it to, since the Urn's description says it'll fill anything in a 2-block radius that accepts water from the top.

(There's also no particle effects coming from the Urn but I don't know if that's because of my shaders and such, need to check in my testing profile later...)
