### ISSUE TITLE
B7: Cant fill crucible with water

### ISSUE THREAD

**Issue by kealor** [Azanor/thaumcraft-beta#415]
Right clicking a crucible with a bucket filled with water has no effect. Using it on a regulare vanilla cauldron fills is as per normal.

I do have other mods installed so it may be a compatibility issue, so i will continue to investigate, i just thought id put this up early in case anybody had heard of this before.

Edit: The water sigil from blood magic fills the crucible, but nothing else seems to (in my head-cannon ill just pretend the crucible needs magic water or some shit lol)

**Comment by Otisnfur** [comment]
Definitely sounds like a compatibility issue. I've been able to put water in the crucible just fine. What other mods are you running? (Will be useful for people attempting to look for conflicts)

**Comment by kealor** [comment]
After further use it seems i also cant do any crucible operations, even when filled with the water sigil. I chuck in the components for say nitor (checked with goggles), but when i throw in glowstone it just dissolves like the rest instead of completing as nitor.

Also here is a png of my mods folder with everything (easier than writing it all down)
![39](https://user-images.githubusercontent.com/32090057/37859983-9c297bca-2f6c-11e8-838f-a9e57e415538.png)

**Comment by Alaell** [comment]
It’s the Aether mod you have installed. Same thing happened to me. x
