### ISSUE TITLE
Feature Request: Convenient Plate Crafting

### ISSUE THREAD

**Issue by weds4** [Azanor/thaumcraft-beta#417]
Could the recipes for Brass, Iron, Thaumium and Void Metal Plates be modified so that they can be crafted using plates and ingots i.e. you need two more plates and have one, so you craft 1 plate and 2 ingots to yield 3 plates? This would not break balance, and could reduce some early game hassle (before Alchemical Automation) and limit waste of more expensive materials like void metal.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#216
