### ISSUE TITLE
B7: Verdant Heart Charm

### ISSUE THREAD

**Issue by Phantom329** [Azanor/thaumcraft-beta#418]
When I have the charm in my baubles slot, the icon on the left for its charge keeps disappearing and sliding back on screen. The frequency is about every second and it also shows up on my friend's screen who doesn't even use Thaumcraft.

**Comment by Phantom329** [comment]
If I move my amulet of vis and the heart charm around it sometimes stops. Also I have a constant saturation buff from the RFTools Environmental Controller.

**Comment by Otisnfur** [comment]
I have the same issue, am not using an RFTools Environmental Controller

**Comment by varvolgyibeni** [comment]
this is a bug that has been around since TC5 where is was doing literally the same with the Thaumostatic Harness and the verdant heart band, and also other stuff.
