### ISSUE TITLE
B7: Preliminary focus feedback

### ISSUE THREAD

**Issue by Phantom329** [Azanor/thaumcraft-beta#422]
I like the new focus crafting system a lot, it adds a cool testing phase where you can try out different combinations of patterns. From playing in survival I have some feedback and suggestions for the foci.

I'm sure you have some planned patterns but here is I've thought of.
- Medium
  - Self - effect yourself
  - Atmos - effect the weather and time (might be OP idk)
  - Earth - effect crops
- Effect
  - Life - healing aspect; take from your own life?
  - Wind - push the target
  - Lux - Light, make stuff glow
  - Spectral - the new MC spectral effect (combined with Lux?)
  - Taint - creates even more taint
  - Crimson - strong but gain temporary warp each cast
- Modifier
  - Charm - changes an effect into a weaker status effect that draws vis until you deselect your caster or cast another spell. The balance would be that you cannot do much while you use a charm modifier. Self+Wind+Charm+Potency=Flight 👀 
  - Inverse - reverses an effect; Lux->blindness, Life->life steal, Break->build, Wind->suck (items and mobs)
  - Trap - makes a trap or utility; leaves residual magic that can be faintly seen with goggles of revealing, or +Spectral for anyone to see
  - Time - makes effects last longer; Self+Time=speed

Changes
* Frost - put out fires; create ice when it hits water, not the sea floor; slippery floor
* Fire - don't create flames on blocks from range without lasting effect modifier

Other stuff
* Some focus effects and modifiers could be 'too powerful' for the basic caster, requiring the upgraded ones in dev; don't tell the player, let the caster blow up in their hand first
* Needs better personal vis storage, I always feel like I run out of vis really quickly
* Advanced focal manipulator; larger crafting and multiple of the same effect and modifier
* Eldritch effects that can only be found on notes and put into the manipulator, unpredictable sometimes?

Let me know what you think of these, the only reason I started playing MC again is because of this mod :)

**Comment by Azanor** [comment]
I've actually completely revamped how foci worked for the beta 8 release (coming soon).

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#215
