### ISSUE TITLE
B8 focus problems 

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#423]
-projectiles are very slow and have a very short range. The combination of the two make them incredibly difficult to aim.
-bolt foci don't seem to do any damage, although I didn't test with every damage type.
-the cloud medium is very cool, but it's ape range seems rather small. Perhaps add an aoe size modifier similar to the power/ duration sliders for other effects.

**Comment by Azanor** [comment]
You do know you can set stuff like the projectile speed and cloud area? Select the node in the UI and check the bottom right of the screen.

**Comment by Azanor** [comment]
What effect did you combine with the bolt?

**Comment by gabeernie** [comment]
It was the warp/flux damage effect. And my apologies for posting without looking more carefully!

**Comment by Alcamore** [comment]
I tested the earth effect with the bolt medium and can confirm that it's not doing any damage.

**Comment by McFrugal** [comment]
I made a touch/break focus and it worked just fine.  I set it to strength 2.

A side issue: foci don't get renamed when you make them.  They're still called blank, but in italics?

**Comment by Alcamore** [comment]
I'll have to try it again then. Fingers crossed.

Did you change the name at the top of the GUI when you make the focus? You can type a custom name.

**Comment by McFrugal** [comment]
Oh.  No.  I just noticed that actually.  I feel like it should create a more interesting default name anyway, but that can probably wait until the foci system is set in stone.

**Comment by Alcamore** [comment]
Yeah, I agree with that. Another thing I noticed while testing is that if you close the GUI for the focal manipulator with the close inventory key (E), it saves what's inside. However, if you close it with Esc, it doesn't save what elements you've added, or the name.

This is particularly frustrating when I wanted to grab a missing crystal and closed it with Esc, just to have to re-enter the medium, the effects, and all the parameters again.
