### ISSUE TITLE
[BETA7] Basic Thaumaturgy research bug

### ISSUE THREAD

**Issue by zahkruin** [Azanor/thaumcraft-beta#424]
when i'm trying to finish the 3rd step of basic thaumaturgy it requires a basic focus with Touch and Fire with 4,4 damage's points but when I create it it haves 5 damage's points and I can't complete the research because they aren't the same or the system doesn't detect them like the same. regards

**Comment by wamc2017** [comment]
#364 
#396 
#406 

Don't know if this fixed in beta8 ( don't have access to it...) but for now the only option is /thaumcraft research playername BASEAUROMANCY ... ;)

**Comment by zahkruin** [comment]
Thanks for the info. i hope this will solved in beta8. it's a problem because you can continue with this part of the mod if you not complete that research

**Comment by Azanor** [comment]
This is solved in beta 8
