### ISSUE TITLE
Focus Suggestions

### ISSUE THREAD

**Issue by CJL48** [Azanor/thaumcraft-beta#426]
Some suggestions for possible improvements to the mod:
1. Chaining and Burst modifiers do not currently work with the Break effect. This may or may not be a bug, but it would be cool if they could.
2. A continuous beam shape, like the dig focus in previous iterations of thaumcraft.
3. Spark/shock focus effect, to go with bolts.
4. Effects that move mobs around (knockback, pull, etc).

Also, maybe a way to store vis for the gauntlet, for areas where flux is clogging the aura?

**Comment by Alcamore** [comment]
Suggestions should be created in [thaumcraft-suggestions](https://github.com/Azanor/thaumcraft-suggestions/issues)

The issues on this repo are for bug reports, despite the confusing description.

**Comment by CJL48** [comment]
My apologies.
