### ISSUE TITLE
[Question] Am I supposed to see those buttons?

### ISSUE THREAD

**Issue by MainFreak** [Azanor/thaumcraft-beta#427]
Uh... I just wanted to ask if I am supposed to be able to see and click those?
![firefox_2018-03-29_21-24-29](https://user-images.githubusercontent.com/20734190/38109277-ec3043e0-3397-11e8-8162-4986c12b1f1a.png)

**Comment by jesmores** [comment]
Just tried it. What it actually does is fork Azanor's repo into your own account and create the file there, so there's no danger of someone messing with the official repo because of these buttons :P - probably a new feature being rolled out by Github.

**Comment by MainFreak** [comment]
Ah, very interesting. Thank you!
