### ISSUE TITLE
B8: Focus Projectile and Bolt stuck at stage 2/2 but uncompleted

### ISSUE THREAD

**Issue by McFrugal** [Azanor/thaumcraft-beta#428]
I had already researched most of auromancy in B7.  With the update, Bolt and Projectile are stuck flashing yet also reading 2/2 and no complete button visible when clicked on.
I went into the playerdata via nbte and set them both to stage 1, but it doesn't appear to have worked.
Going back and looking at the playerdata it appears to have reverted to stage 2.

**Comment by McFrugal** [comment]
To be clear, this is a problem because some new research requires these nodes, and they count as uncompleted in this state so I can't get to the new research.

**Comment by Luicuelo** [comment]
Same issue, I used command research

/tc research playername FOCUSPROJECTILE

**Comment by Azanor** [comment]
/tc research playername <whatever> should complete it.
