### ISSUE TITLE
B8: Can't make alumentum 

### ISSUE THREAD

**Issue by scorp1onSlayer** [Azanor/thaumcraft-beta#429]
pretty self explanatory issue but i used one sand and two coal in the crucible and no alumentum

**Comment by varvolgyibeni** [comment]
i can confirm this also. used the same recipe. using charcoal also doesn't work, it does seem like the recipe is either missing, or the the first stage of the research won't unlock the ability to craft it.

**Comment by Alcamore** [comment]
I third this, can't craft it either.

**Comment by fingersome** [comment]
ditto

**Comment by Santtinen** [comment]
Yup doesn't work even with Automated Alchemy

**Comment by Shadyfox0402** [comment]
Can not create alumentum. The crucible does not recognize the coal/charcoal as an ingredient instead of essentia. I have tried using triple the essentia needed but it still will not work.

**Comment by Luiscon95** [comment]
does any one know how t give the research with commands ?

**Comment by varvolgyibeni** [comment]
if i remember correctly it's something like /thaumcraft research *player's name* ALUMENTUM

**Comment by Luiscon95** [comment]
yea it is THx!
