### ISSUE TITLE
B8: crash game

### ISSUE THREAD

**Issue by nailfor** [Azanor/thaumcraft-beta#430]
https://pastebin.com/yjCpTtVw

The crash constantly in the same place

**Comment by Aathoss** [comment]
I want to clarify for myself that I currently have the same problem
The problem comes back constantly in the deserts

Minecraft version 1.10.2 --> https://pastebin.com/bMphmDBp

**Comment by Azanor** [comment]
Looks like a connected texture mod is somehow managing to get the crystal renderer into an invalid state. I will try and capture the error.
