### ISSUE TITLE
[B8] Flux dissipates very quickly

### ISSUE THREAD

**Issue by McFrugal** [Azanor/thaumcraft-beta#431]
I needed to discover Vitium so I went somewhere secluded and dumped 5 or 6 stacks of cobble in a crucible.  As expected, flux skyrocketed, I got the entry level flux research, and some taint-related things started happening.

After observing for a while I swapped back to my thaumometer and noticed I was reading no flux, despite the meter being completely maxed out before.  I went back to base and got my Dioptra, and... yep.  No flux anywhere.  The taint is still there (including the seed) but no flux at all.  This explains why my base read as completely clean despite having definitely created some flux earlier on.
As a side note, when the flux was still showing up on the thaumometer it didn't seem to be spreading into nearby chunks.  It was only in one chunk.

Should tainted pigs not give new scan results?

**Comment by Alcamore** [comment]
I noticed this as well. I wanted to test the effects of serious taint in the environment, so I filled the crucible to the brim and emptied it twice, then held out my thaumometer. Of course, some extreme taint popped up pretty quickly, but I never even saw the flux before or after. Maybe the flux clears out of the environment after overflowing?

**Comment by McFrugal** [comment]
After further experimentation it's almost as if the taint eats the flux as it grows.  Could just be correlation though.
I did manage to get some flux readings from adjacent chunks but only after repeated dumpings of cobble, which seemed to stick around.  Maybe taint *does* eat flux?  It seems to eat too much of it in that case though.
The dioptra's flux setting showed the slightest of bumps near the area where I dumped flux.  I think it needs to be more sensitive for it to be useful.

**Comment by Alcamore** [comment]
Oh, from the Thauminomicon:
"If Flux builds high enough it seem to cause a tear in the very fabric of magic itself. The flux escapes through this tear(...)"

**Comment by Azanor** [comment]
Taint does indeed 'eat' flux to grow, but at the same time it creates just enough flux to be able to continue growing. This results in there being an initial big burst of taint growth once it happens and then just slow and steady growth as long as no further flux is added to the system.

**Comment by Azanor** [comment]
Also flux levels need to be fairly high before it starts spreading to nearby chunks. If you think of the aura as liquid then Vis flows like water while flux flows like thick jam.
