### ISSUE TITLE
[B8] Control Seals are popping off when there is no full block

### ISSUE THREAD

**Issue by amefeu** [Azanor/thaumcraft-beta#435]
I was doing some testing with Golemancy with the new update installed. When I went to break the block that I placed the seal on the seal popped off. Non-fullblocks also seem to cause them to pop off. (In my case a Lamp of Growth).

**Comment by Azanor** [comment]
Which seals were you using? Seals that require an inventory is supposed to pop off, but since you mentioned a lamp I assume it was something else?

**Comment by amefeu** [comment]
I was using Block Breaker and Harvest as I was working with melons at the time. (Herba without anything else) I ended up placing the seals on the ground as a work around.

**Comment by Azanor** [comment]
Ok correction - most seals can be placed on any non-air block and will pop off if there is no block attached - same goes with the harvest seal so what happened is correct - if you break the block the seal will go away.

A few seals are more strict, while others like the use seal can remain in place even if the block they are attached to is removed.

In short: not a bug

**Comment by amefeu** [comment]
If it's not already in the book pages on control seals probably a good idea to note which are which in some way so that players know ahead of time.
