### ISSUE TITLE
[B8] Infusion stability, crystal clusters don't count while the thaumonomicon claims they do.

### ISSUE THREAD

**Issue by LlamaTea** [Azanor/thaumcraft-beta#436]
According to the thaumonomicon you're supposed to be able to use crystal clusters to lessen instability, It doesn't however. If I remember correctly it was possible in previous versions so maybe you forgot to add those in this time? Or did you decide not to use crystal clusters this time around and just forgot to edit them out in the thaumonomicon?

**Comment by Azanor** [comment]
That is actually correct - they no longer help stability so I must have missed the entry in the thaumonomicon

**Comment by LlamaTea** [comment]
Aw that's a shame! Guess I'll have to rebuild my infusion setup then!
