### ISSUE TITLE
B8: Reusing Foci

### ISSUE THREAD

**Issue by Phantom329** [Azanor/thaumcraft-beta#438]
I tried to reuse a focus and the manipulator let me make a new plan but when I hit 'Start Crafting' it got stuck forever.

**Comment by Phantom329** [comment]
Ok, not I can't make any foci... it just spins around on top with the crystals forever. It looks like it should be completed from the GUI because it says vis=0.

**Comment by Alcamore** [comment]
I was doing some testing for another issue earlier and was able to do that just fine on my end. What components are you using for the focus?

**Comment by Phantom329** [comment]
I think lag could've been involved but I was doing simple touch + fire.
