### ISSUE TITLE
B8: Stucked in basic auromancy

### ISSUE THREAD

**Issue by ayhexinf** [Azanor/thaumcraft-beta#439]
I started this mod since Beta 7 and updated it to Beta 8 recently. I didn't finish the basic auromancy research in beta 7 because I didn't make a focus, and the mod requires a focus to unlock other researches. But in Beta 8, you don't need a focus to unlock further researches. Which means I should already done with the basic auromancy, but none of the researches have been unlocked. Please help me fix this problem.
<img width="960" alt="problem" src="https://user-images.githubusercontent.com/35821526/38291596-40495a42-3795-11e8-8cc0-79bbeec08791.png">

**Comment by Alcamore** [comment]
Did you craft the new 'Blank Lesser Focus' item? Stage 3 requires crafting one to complete if I remember correctly.

**Comment by ayhexinf** [comment]
yeah, I did craft one, yet i wasn't able to unlock other researches

**Comment by ayhexinf** [comment]
Alright, It's solved. I opened to LAN and allowed cheat. I hate using command but I guess I don't have a choice

**Comment by Alcamore** [comment]
Yeah, beta is beta. 👍
