### ISSUE TITLE
Initial mod compatibility testing, A14

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#46]
Haven't done much yet except to walk around looking at everything available with a thaumometer to see what comes up with discoverable research from the mods in my modpack.  It goes without saying vanilla blocks and items are generally as expected.

Blocks that work so far:  All Mineralogy and BaseMetals blocks I have tried, BaseMetals mining hammers, Bibliocraft furniture, all BaseMetals ores, EnderStorage blocks and Translocators (pretty much anything of Chickenbones'), Roxa Tall Doors, vanilla doors animated by Malisis Doors, all Router Reborn blocks and conduits, Mekanism armors and weapons (including Mekanism-specific materials such as osmium and refined obsidian), Thermal Expansion ducts, machines, blocks and ores of Thermal Expansion metals known to Thaumcraft (but not some of the metals unique to Thermal Expansion such as signalum), Slashblade soul shards, many Project Red simple machines, Project Red ores and gemstone blocks, some Project Red lamps, Biomes o'Plenty trees/woods (but not leaves), Forestry trees/woods, single-block Forestry machines

Things that DON'T have attributes:  Forge Microblocks (unsurprising), apparently all Mekanism blocks and machines including metal blocks and ores, all ArchitectureCraft blocks, Forestry hives, Slashblade weapons (also unsurprising), most Project Red wires and cables, complex Project Red machines, Biomes o'Plenty crops and plants, vanilla stained glass (or is it just all considered glass?)

Things that appear to have attributes but nevertheless cannot be scanned:  Project Red ICs, many Project Red lamps, most Project Red item pipes, vanilla water

Slightly odd things:  Only some colors of vanilla carpet seem to have attributes, though all colors of wool do.  But that might have been user error.

**Comment by Azanor** [comment]
I can only calculate essentia values for items with 'normal' recipes. Anything that uses their own recipe handlers or uses the vanilla handlers in a non standard way won't work.

**Comment by UnixRonin** [comment]
Oh, absolutely.  This is just reporting what mods I found to already work with the thaumometer and what didn't, since I'm probably running a different set of mods with it than you are.  Observations and notes, not even an enhancement request.  (Is there an "Information only" tag?)

Several of these didn't surprise me at all, in particular Slashblade (which is totally separate from vanilla weapon implementations), and Architecturecraft (GregT rolls as GregT rolls).  Stained glass, I guess is all just considered glass, so you scan *one* vanilla glass, stained or otherwise, and you're done.  I didn't actually expect anything from Project Red except for the lamps to have attributes.  I was pleasantly surprised how much Thermal Expansion stuff scanned.

On 1.7.10, I have a mod, I think it's called Thaumcraft Attributes, that allows assigning essentia values to things that don't already have them (Mo'Creatures mobs, for example).  I can't imagine it taking too long for that to get updated once TC6 releases.

Water, I think, has always been a problem for scanning.
