### ISSUE TITLE
Sky readings do not reset "today" at 0 time.

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#461]
When the sun rise, the new day starts, but if you try to scan the sky in the evening, it says "you did scan this "today" already".

**Comment by androshalforc** [comment]
ive been having similar problems with scanning the stars i assumed that the day reset at midnight so if you scanned the stars anytime in the early morning it would count for "today" so scanning early evening would fail.

**Comment by Azanor** [comment]
The minecraft day starts at sunrise, not at midnight, but I should maybe consider fiddling with things so it makes more real-world sense.

**Comment by AnrDaemon** [comment]
Not need. You scan sky at night, so scanning two times at one night make little gameplay sense, makes calculations harder, and the code - more obscure and harder to maintain.

**Comment by Azanor** [comment]
Yup, I came to the same conclusion earlier.
