### ISSUE TITLE
[B9] Magic Forest biome never generates

### ISSUE THREAD

**Issue by Alcamore** [Azanor/thaumcraft-beta#467]
A friend and I were trying out the new Thaumcraft beta on a private server, and decided to live in a magic forest biome. 

After searching for a couple hours, a decent portion of which was flying in creative, I changed `I:biomeMagicalForestWeight` to 100. I flew around with the new generation for about 15 minutes before trying to set `I:dimensionOuterId` to 0. I flew around again afterwards without finding anything. Attempted again in SSP with both configuration states.

Is the biome generating for anyone else?

Forge version: 14.23.3.2655
Mod list:
- Baubles-1.12-1.5.2
- Thaumcraft-1.12.2-6.1.BETA9

**Comment by Azanor** [comment]
Nope, magic forest generation was actually broken.
