### ISSUE TITLE
[B9] Cant make Thaumonomicon

### ISSUE THREAD

**Issue by Mii1128** [Azanor/thaumcraft-beta#471]
I did the dream stuff, but when i used Salis Mundus on the Bookcase, It played the animation but the the bookcase just poofed out of existence and i get neither the book nor the research.

**Comment by UnixRonin** [comment]
I just ran into this myself.

**Comment by kurtawirth** [comment]
I have yet to find a solution to this. This is still happening for me.

https://github.com/Azanor/thaumcraft-beta/issues/1257

**Comment by Murrlin** [comment]
I have a similar problem but MC crashes right after the sparkles begin. 1.10.2 forge 2239 then 2511; I also have Thaumic JEI and TC Inv Scanning, and wonder if it's a TC bug or an addon bug?
