### ISSUE TITLE
[B10] "Click for recipe" crashes game

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#474]
Hi,

whenever I click "Click for recipe" inside the Thaumonomicon the game crashes:
https://pastebin.com/Rnqk0CD4

Mods used to test this issue:
Baubles-1.12-1.5.2
jei_1.12.2-4.9.1.168
Thaumcraft-1.12.2-6.1.BETA10

Forge version: 14.23.3.2673
Minecraft version: 1.12.2

Thanks for looking into it. :)

Best regards
wamc

**Comment by Azanor** [comment]
Does it happen with ALL recipes, or only specific ones?

**Comment by wamc2017** [comment]
Looks like it happens for ALL recipes.
