### ISSUE TITLE
[1.12.2] Crash When Clicking On Items In The Books

### ISSUE THREAD

**Issue by EmosewaPixel** [Azanor/thaumcraft-beta#479]
So I was quickly going through the thaumonomicon to see if everything is working correctly. I got to the Thaomometer and clicked on the item in the bottom left corner, where the tasks are displayed (once I had crafted it and it had a check mark on it) and I got this crash: https://pastebin.com/yRd3TZkw

**Comment by wamc2017** [comment]
#474

**Comment by EmosewaPixel** [comment]
Oh, sorry, missed that.
