### ISSUE TITLE
Native Cluster Smelting is being registered too late.

### ISSUE THREAD

**Issue by KingLemming** [Azanor/thaumcraft-beta#481]
Basically as title.

Your smelting recipes for your Native Clusters need to be registered prior to PostInit. I believe what's happening is that you're checking for the ingots in PostInit and then doing the registration.

While this works for the vanilla furnace, it's basically incompatible with all mods which have to do reads of the smelting list in PostInit.

You can safely move your cross-compat to Initialization, as ALL oredictionary stacks should be registered prior to Initialization.

**Comment by Azanor** [comment]
Cool, will do.

**Comment by KingLemming** [comment]
BTW, welcome back. :)
