### ISSUE TITLE
[B10] Arcane workbench not accepting vanilla crafting recipes

### ISSUE THREAD

**Issue by Mii1128** [Azanor/thaumcraft-beta#485]
![2018-04-24_22 29 04](https://user-images.githubusercontent.com/4788644/39212767-f810e048-480f-11e8-9b38-676006fc97cd.png)

**Comment by Mike-U5** [comment]
Just tested, and I have the same issue.

**Comment by Azanor** [comment]
Argh! Azanor smash! I spent half a day last week making sure this all works fine, but it looks like something broke between then and now. Gah. Oddly enough some vanilla recipes do work.
