### ISSUE TITLE
[B10] Scanning the sky with the thaumometer does nothing

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-beta#487]
https://www.youtube.com/watch?v=CvOXKw78hyg

It doesn't show in the video but I do have scribing tools and paper in the inventory. Unless it has to be in the hotbar? I asked in discord and people seemed to agree that it's a bug.

Minecraft: 1.12.2
Forge: 2673
Mods: [list.txt](https://github.com/Azanor/thaumcraft-beta/files/1944584/list.txt)

**Comment by Xiaminou** [comment]
Yep, did turns out you need them in the hotbar, wish someone would have told me.

**Comment by AnrDaemon** [comment]
Azanor/thaumcraft-beta#494 for reference.
