### ISSUE TITLE
A15:  Recipe conflict (informative/heads-up, author of problem mod notified)

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#49]
I have found a recipe conflict:  Thaumcraft's recipe for its iron plate (required for the vis resonator for the Caster's Gauntlet), three iron bars in a horizontal row, conflicts with Malisis' Doors recipe for its rusty iron ladder.
I've suggested to Ordinastie that **he** change his recipe to three iron bars in a **vertical** line, which makes more sense for an iron ladder anyway, especially since investigating further I discovered that Base Metals uses the same iron plate recipe Thaumcraft 6 does.  Since Base Metals uses the same three-bars-horizontally recipe, I'm treating Malisis Doors as being in the wrong here by majority usage.

**Comment by UnixRonin** [comment]
Ordinastie has changed his rusty iron ladder recipe to emulate the regular wooden ladder recipe.  There is no longer a conflict.

**Comment by Azanor** [comment]
:)
