### ISSUE TITLE
[B10]  Cannot stury curio in inventory, only in hotbar

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#494]
I just drew a "Study Curio" card calling for a Preserved Curiosity.  I have 26 of them in my inventory right now, but still cannot activate the card.

**Comment by UnixRonin** [comment]
Update:  I could activate the card **only** once I moved the stack of Curiosities to my hotbar.

**Comment by Azanor** [comment]
Hmmm, I can't duplicate this at all - items work both in the hotbar and in the normal inventory for me.

**Comment by Azanor** [comment]
Actually there was an unrelated bug I fixed earlier that might have indirectly solved this one. Let me know if this persists in the Beta11+ updates.
