### ISSUE TITLE
[B10-1.12.2] Nitor recipe crash

### ISSUE THREAD

**Issue by DevTimur** [Azanor/thaumcraft-beta#496]
CRASHLOG: https://pastebin.com/VFahiZ98
VERSION: Thaumcraft-1.12.2-6.1.BETA10

Steps to reproduce:
1) Start learning untill reach Alchemy and Nitor crafting
2) Open recipe for nitor in Thaumonomicon (Top right icon, because if you press bottom left you instacrash)
3) Hover mouse over recipe and ingridients, seems working, but...
4) After 10-15 seconds you will crash

**Comment by hanleybrand** [comment]
This is still happening for me with beta 11 #514

**Comment by EnderofGames** [comment]
Make sure you are using a different save. 

This fixed the problem for several of the reports, but you may be able to just replace your Thaumonomicon, too, if you want to give that a try.
