### ISSUE TITLE
Crash when clicking on Thaumometer Recipe in book

### ISSUE THREAD

**Issue by EmergentCapulin** [Azanor/thaumcraft-beta#497]
The Recipe under the introductory page where the Thaumometer first appears seems to crash the game when clicked on.  The tab that appears on the right appears to function just fine.  

It has happened to me 3 times.

Now, I have not tried this without JEI Thaumcraft installed, nor with JUST Thaumcraft installed by itself.  If needed, I can try to attempt this at some point tomorrow.

**Comment by AnrDaemon** [comment]
All of the progression recipe links cause crash. The "bookmark" links at the right do not.
