### ISSUE TITLE
[1.12-B10] Oak trees not generating in SMP magic forests?

### ISSUE THREAD

**Issue by xAlicatt** [Azanor/thaumcraft-beta#498]
I'm not even sure if this is something you can fix, but all of the Magical Forests on our SMP worlds are generating without oak trees. It does not work this way in singleplayer.

Server-side mods not included in the pack we are using:

-Aromacore and backup
-Fast Leaf Decay
-Recurrent Complex and ivtoolkit
-Morpheus
-No Mobs Spawning on Trees
-Worldborder

**Comment by xAlicatt** [comment]
Hmmmmm I'm going to close this because I think it's the Dynamic Trees mod not knowing what to do with the Magical Forest that's causing this...even though I have the worldgen on that mod turned off. Sorry for the pointless report!

**Comment by xAlicatt** [comment]
Ok. I'm reopening this because it isn't related to Dynamic Trees or the pregeneration like I thought. It only seems to be happening on our SMP world for some reason. Client-side seems to work the way it's supposed to. It's not a huge deal, since it's less a functional issue than it is a cosmetic one, but I thought I would share anyhow.

**Comment by AnrDaemon** [comment]
So was your MF pregenerated by tools or normally though player exploration?

**Comment by xAlicatt** [comment]
Both ways is causing this. Using the Chunk Pregenerator mod and manual exploration.

**Comment by UnixRonin** [comment]
They're generating fine in my SMP magical forests.  So apparently it's not a Thaumcraft issue.  I'm also using No Mob Spawning on Trees, so it's not that.  I can't imagine that Morpheus would have anything to do with it either.

**Comment by xAlicatt** [comment]
Yeah it's a really curious issue. I tried removing Fast Leaf Decay...no dice. @UnixRonin do you use Recurrent Complex?

**Comment by UnixRonin** [comment]
Nope, I've never used it, sorry.

You did just remind me to reinstall Morpheus though.

**Comment by xAlicatt** [comment]
K i'm closing this again....we are missing oak trees on our entire map, except the pam's ones.
