### ISSUE TITLE
Got the info for Discovering Thaumaturgy, but it didn't offer a 'complete'

### ISSUE THREAD

**Issue by vdrake77** [Azanor/thaumcraft-beta#5]
'Visit the endless blue seas' and the 2 observations and an epiphany are checked, but I don't get an offer to complete it.

Alpha 7

**Comment by Azanor** [comment]
Hmmm, can you post a screenshot?

**Comment by Azanor** [comment]
Hmmm, just went to chech the research. Is the other 3 requirements checked as well? "Visit the lowest depths of the world", "Visit the highest peaks you can find", and "Visit dry and barren wastes".
