### ISSUE TITLE
Research Crash- repeatable 

### ISSUE THREAD

**Issue by NextdoorPsycho** [Azanor/thaumcraft-beta#50]
**Bug- crashes client/test server**

If you want to freeze the test server/client; while you research stuff in the table, and you go at a hasty rate (fast clicks) he client freezes and the sever stalls up (this has happened 3 times, so i know its not a single problem.)

**Comment by Firenzeo** [comment]
Another possible cause, or could be separate, but related
[https://github.com/Azanor/thaumcraft-beta/issues/53](url)

**Comment by Azanor** [comment]
Could you please post the crash report?

**Comment by MainFreak** [comment]
I think it is a stall and not a crash. The game just stops responding to anything you do ingame and freezes when yo pu try to exit the world or wait for long enough. The fml-latest.log may be of more use here. Please correct me if that is a different issue.

**Comment by Azanor** [comment]
see https://github.com/Azanor/thaumcraft-beta/issues/97
