### ISSUE TITLE
Grapples works strange

### ISSUE THREAD

**Issue by NatsuArashi** [Azanor/thaumcraft-beta#500]
The grapple head stuck on my foot for a while before shooting out.

**Comment by NatsuArashi** [comment]
And this, the effect coverd other entities?

![19](https://user-images.githubusercontent.com/7349001/39245969-cd7f0554-48c7-11e8-87c4-7d8b544f5bdb.png)

**Comment by Gammaboy45** [comment]
Yeah, I find this really annoying as well. Most of the time, the grapple hits the block beneath me or in front of me instead of flying forward. It makes it feel slow and makes the grapple somewhat difficult to use.

**Comment by Azanor** [comment]
I cannot replicate this at all - is this in single player or on a server?

**Comment by Azanor** [comment]
NM, I managed to duplicate it.

**Comment by NatsuArashi** [comment]
It's in single player.
