### ISSUE TITLE
[Suggestion] Remove Visual Obstruction of Theory Category Progress

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-beta#501]
![2018-04-25_14 22 43](https://user-images.githubusercontent.com/8670392/39245586-7b95b162-4894-11e8-914b-bec1e85db929.png)

As you can see in this screenshot the progress of my Theory is obstructed by both JEI and a theory.
For reference, my GUI scale is Large.

**Comment by UnixRonin** [comment]
You know you can turn off the JEI display with a hotkey, right...?

**Comment by Xiaminou** [comment]
You know mods can make JEI's UI go around elements like that, right...?

**Comment by AnrDaemon** [comment]
>You know you can turn off the JEI display with a hotkey, right...?

Unfortunately broken in current JEI.

**Comment by Mike-U5** [comment]
Perhaps an option to display category progress on the left instead of right could work?  
  
Also, I too did have a few instances where a Theory page obscured the progress, even without JEI.

**Comment by AnrDaemon** [comment]
And may be "zoom out" the cards down to the table, when cursor moves up/down from the table area?

**Comment by Toksyuryel** [comment]
> > You know you can turn off the JEI display with a hotkey, right...?
>
> Unfortunately broken in current --JEI--NEI.

So this obviously isn't an ideal solution but a workaround for this right now is to go into the NEI settings and change the item panel to NEI, which will cause the hotkey to work. Once you're done hiding it you can go back to the NEI settings and change the item panel back to JEI.

**Comment by laserlemons** [comment]
It'd be nice if it automatically hid JEI in the research table GUI.

**Comment by AnrDaemon** [comment]
> It'd be nice if it automatically hid JEI in the research table GUI.

Not at all. How would I cheat in the crystals and other objects required to complete the theory?

**Comment by Szasdragon** [comment]
I just limited the JEI display columns to 7.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#392
