### ISSUE TITLE
[B10 - 1.12.2] Crafting result with empty arcane workbench

### ISSUE THREAD

**Issue by Eydamos** [Azanor/thaumcraft-beta#503]
The user phantom_kasper has opened an issue in my backpacks mod.
When the arcane workbench is empty a medium tier backpack is shown in the crafting result slot.

After a little debugging I figured out that the problem is a wrong size of InventoryArcaneWorkbench.
According to the debugger it has an inventory width of 5 when it actually only has 3 slots per row.
This messes up the recipe matching logic of my mod.

I will also add some code to address issues with wrongly sized crafting inventories.

**Comment by Toksyuryel** [comment]
The workbench actually has more slots than just the crafting slots in the middle, each of those colored circles around it is a slot where vis crystals need to go. That is most likely why the width is configured the way it is.

**Comment by Eydamos** [comment]
Still the logic has to be fixed. As it is a crafting table it will iterate over all recipes and try to find the correct one. Even if the slots around are for additional crafting materials like crystals the actual crafting grid is only 3x3 and the code has to correspond to that.

Currently as an example if you take some oak wood planks ant put on in the top left corner and one in the right slot of the middle row you are able to craft sticks. The result of the method craftingGridInventory.getStackInRowAndColumn(row, column) will not return the items like they are placed in the visual crafting grid.

**Comment by Mii1128** [comment]
Possibly related to #485

**Comment by Eydamos** [comment]
Indeed this is related.

**Comment by Azanor** [comment]
Yup, this should be fixed in the next release.
