### ISSUE TITLE
[B10] [Suggestion] Displaying messages

### ISSUE THREAD

**Issue by TimeConqueror** [Azanor/thaumcraft-beta#505]
There are some suggestions...
1) When I picked up vis crystals (at first time, before creating Thaumonomicon), the message appeared. But it dissapeared very quickly, and I think it's difficult for players to read such messages quickly. It appears suddenly and player can't concentrate on it. When the player realizes, it will be too late, the message will dissapear.
So I think, that such messages should be visibile a little more time. Or alternatively you can make it so that the message will disappear when the player presses, for example, the Enter button.

2) Also there are some problems with translated messages. For example Russian words are much longer than English words. This causes the problem that some amount of symbols/words are not visible, they are beyond the screen. Is it possible to make the text going to a new line when it reaches edge of the screen?
![image](https://user-images.githubusercontent.com/25156941/39268229-e9e961ac-48d7-11e8-9889-ac3423899d0d.png)

**Comment by Lukas45** [comment]
Very much agreed, the first message disappears way too quickly. It only stays out for like 2 seconds, and you spend at least a second noticing it (if you notice it at all)
