### ISSUE TITLE
[B10 - 1.12.2] Golem Press Crash

### ISSUE THREAD

**Issue by codygizmo** [Azanor/thaumcraft-beta#506]
I saw something like this was mentioned back in December, but I didn't see a solution for it? Game is crashing whenever i click on anything while in the Golem Press. Whether that be the buttons in the UI or the items in my inventory.

Giving me the error:
The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: Stack can not be invalid!

**Comment by Boolyman** [comment]
The same is happening to me... here is a crash log.  https://pastebin.com/J2Ree1Sf
