### ISSUE TITLE
Can't complete alchemy "Essentia Smelting" research 

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#51]
Unable to craft smelter block for some reason? Prior research remains incomplete (metallurgy) due to not having completed the forbidden research. Is this the cause or have I missed something?

![2017-12-19_14 09 40](https://user-images.githubusercontent.com/9419312/34160932-cf74ecd0-e4c6-11e7-91a8-1db41bb18c96.png)
![2017-12-19_14 09 43](https://user-images.githubusercontent.com/9419312/34160933-cf8947b6-e4c6-11e7-80e5-8330288e7481.png)
![2017-12-19_14 09 47](https://user-images.githubusercontent.com/9419312/34160934-cf9c2926-e4c6-11e7-91e2-2eae822514b3.png)

**Comment by LordPinkerton** [comment]
You CAN actually craft the smeltery at this point, even though it tells you otherwise.
Recipe is:
Brass Plate, Crucible, Brass Plate
Cobble, Furnace, Cobble
Cobble, Cobble, Cobble

**Comment by Azanor** [comment]
BTW, I just want to throw it out there that I am very appreciative of proper beta testing like this. Most people just seem to use the beta access for a way of previewing TC6  :p
