### ISSUE TITLE
[B11] Essentia Smelter research cannot be completed

### ISSUE THREAD

**Issue by codewarrior0** [Azanor/thaumcraft-beta#511]
The Essentia Smelter research wants to consume one of each primal Vis Crystal, but the icons below the research show colorless crystals and it will not consume any crystals I have. 

This is because the JSON for each crystal's NBT has a spurious `0:` before the element of a list. Editing the JSON research files resolves the issue. In other words, 

`{Aspects:[0:{amount:1,key:'aer'}]}`

should be

`{Aspects:[{amount:1,key:'aer'}]}`

**Comment by codewarrior0** [comment]
A search suggests this issue also affects researches `BELLOWS` and `CRYSTALFARMER`

**Comment by AnrDaemon** [comment]
the correct name for the research is "Essentia Smelting"

**Comment by AnrDaemon** [comment]
> because the JSON for each crystal's NBT

That's not JSON, that's, actually, NBT.
If it were JSON, any JSON parser would scream error outright on the construction, for multiple reasons.

**Comment by AnrDaemon** [comment]
Had to replace the research JSON's directly in the JAR. Despite being in `assets/` subdirectory, they are not read from the resource pack.

**Comment by Dragnier** [comment]
I am having this issue currently. I tried dropping one of each primal in the crucible, lighting them on fire in the world, blowing them up with TNT... basically all of the possible "destructive" tests I could think of.

**Comment by AnrDaemon** [comment]
No, I may not rehost the JAR, but I [published the changed JSON's](http://project.rootdir.org/minecraft/Thaumcraft/6.1/FixedThaumcraft-beta-11.zip). [Check the forum thread.](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta11?comment=39825)

**Comment by Dragnier** [comment]
The solution posted by AnrDaemon did not work completely for me. It fixed the display in the book, but did not let me complete the 1/4 research on the primal crystals.

**Comment by Sumguy62** [comment]
I tried using AnRDaemon's fix, but get a crash every time I try to load the game now.

**Comment by flamingram** [comment]
just cheat in the that area otherwise you cant progress easy fix

**Comment by AnrDaemon** [comment]
> I tried using AnRDaemon's fix, but get a crash every time I try to load the game now.

Then you did something wrong.

**Comment by UnixRonin** [comment]
I did it manually.  I just opened up the .jar file, opened all the research JSON files in an editor, and did a global replace of 'Aspects:[0:{' with 'Aspects:[{', then saved.  And it worked perfectly.  It's not a difficult fix to apply.

**Comment by EightOneFive** [comment]
Not sure if this is a dumb question or not, but if playing on a server does the admin have to modify any of files as well? I've modified my json files using WinRAR and everything seems to be fine. I can see the proper color/type of crystals when I open the Thaumonomicon and can hit complete on the Essential Smelting, but it just seems to be stuck on 'Completing...' and can't advance. Have reloaded the game a couple times now just in case.

**Comment by AnrDaemon** [comment]
The server should have corrected JAR, client may or may not have it, the check for successful completion of the research is done on the server side.
