### ISSUE TITLE
[B11] Cant craft with the Thaumatorium

### ISSUE THREAD

**Issue by LightniX** [Azanor/thaumcraft-beta#513]
It doesnt matters which catalysator I use or how many types of essentia I connect. I cant use it

**Comment by Santtinen** [comment]
Yup. I have the same problem.

**Comment by ZoeZoePixel** [comment]
metoo

**Comment by ZoeZoePixel** [comment]
i  noticed tht this video [https://www.youtube.com/watch?v=yGwsc42_tU8](url) showed the alchemy automation working...... why is tht?

**Comment by wamc2017** [comment]
Because the video was made for the 1.10 version, where the Thaumatorium worked fine...
