### ISSUE TITLE
[B11] Can't complete Elemental Tools

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#515]
Hi,

I started a new world in beta 11 today and I'm stuck at the Elemental Tools page:

![2018-04-26_17 52 22](https://user-images.githubusercontent.com/33242447/39317010-e1c1f630-497a-11e8-9fb7-64d51a26d5af.png)

I crafted the axe and the sword like I crafted the other tools (2 times, because I thought maybe the first craft didn't count...) but they are not recognized by the book.

Thanks for looking into it. :)

Best regards
wamc

**Comment by Azanor** [comment]
I can't duplicate this bug - it recognizes the items when I craft them. Did you craft the axe and sword before you opened this research, or did you craft all of the items together? It shouldn't make a difference, but it could be related.

**Comment by wamc2017** [comment]
I crafted them all at the same time. But tried three or four times to craft them again, with not result. Will check it again in a new world (don't got the old one anymore) if I find some time... :)

**Comment by wamc2017** [comment]
Tried it and it worked without problems this time, I'm closing it for now.
