### ISSUE TITLE
[B11] Crimson Rites book doesn't use up

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#516]
Hi,

during my studys a lesser portal opened and after some hard fight I got two Crimson Rites books. When I use them they stay inside my inventory and I get unlimited research points (which isn't bad for me, but I think that's not intended... :grinning: )
I'm in survival mode, not in creative...

Thanks for looking into it.

Best regards
wamc2017

**Comment by AnrDaemon** [comment]
It got used up later, when I did some more research in the book and tried to study the Rites again.
