### ISSUE TITLE
[B11] Mouseover on an item on tab recipes in the Thaumonomicon cause crash

### ISSUE THREAD

**Issue by Kyozan** [Azanor/thaumcraft-beta#519]
I'm finding consistent ArrayIndexOutOfBoundsExceptions (with a 1 index) when mousing over some items in the tab recipes for researches in the Thaumonomicon. I thought I had seen a issue open for this in B10, but I can't seem to find it so I'm re-posting just to keep it here.
It seems to happen to the same items on the entire research page, and on any tab-page within it. For example for the Theorycrafting research, hovering over any ink sac will crash. It also seems to happen with all kinds of recipes, from normal crafting to crucible to arcane crafting (maybe more but I haven't gotten that far yet). I also found that I didn't crash for all the items of some researches, so it doesn't seem to happen all the time. I put a list below for the items I found for different researches that cause the crash, though it isn't exhaustive by any means. I also added the crash logs for each of the different types, though the only difference between any of them is which `thaumcraft.client.gui.GuiResearchPage.draw<CRAFTING TYPE HERE>Page` they come from.

### Known research & items:

- First Steps &rarr; nothing so far?
- Theorycrafting &rarr; ink sac
- Discovering Alchemy &rarr; glowstone
- Discovering Infusion &rarr; string
- Discovering Auromancy &rarr; nothing so far?
- Warp &rarr; mirror
- Basic Alchemy &rarr; glowstone _and_ clay?
- Alumentum &rarr; nothing so far?
- Hedge Alchemy &rarr; string (again)

Note that for Hedge Alchemy the crash only happened for string when completing the gunpowder + slimeball part, and afterwards string was fine. And all the while glowstone, clay and ink sacs now worked, as compared to other researches having them broken.

### Crash logs:
[crash-2018-04-26_09.55.26-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1952212/crash-2018-04-26_09.55.26-client.txt)
[crash-2018-04-26_09.56.03-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1952213/crash-2018-04-26_09.56.03-client.txt)
[crash-2018-04-26_09.57.57-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1952214/crash-2018-04-26_09.57.57-client.txt)

**Comment by Kyozan** [comment]
Ok this is weird, after completing the Hedge Alchemy step, when I go back to almost any of those known issues, they all seem to work again? The only exception I found was that the Warp entry with the mirror still being broken.
From what I can see the only diff between the two steps was that the items causing issues before could be crafted/duplicated through Thaumcraft, but didn't have a tab made for them in the Thaumonomicon yet. Now that they do have a tab made though, they seem to work fine on mouseover anywhere. Since I haven't discovered the mirror research yet this would still explain the issue with Warp.

**Comment by hanleybrand** [comment]
Seems like the same core issue with #514 although this one has more items that cause the crash.

**Comment by drakray** [comment]
got this too when looking at Enchanting Fabric recipe on the right tab https://pastebin.com/EN7DWZcN
b11 too, though I got it on b10 before

**Comment by AnrDaemon** [comment]
#474

**Comment by alfuken** [comment]
@Azanor why would you mark it as solved, if it's still present in current release?
