### ISSUE TITLE
[B11] Basic auromancy shows wrong event

### ISSUE THREAD

**Issue by Mii1128** [Azanor/thaumcraft-beta#522]
it tells about a projectile while the on fire one is needed

**Comment by wamc2017** [comment]
Yeah I think f_onfire should be f_arrow in this line:
https://github.com/Azanor/thaumcraft-beta/blob/master/en_US.lang#L1582

**Comment by AnrDaemon** [comment]
It says you to "study effects more closely".
Which, literally, means:
1. f_arrow - being shot by an arrow.
2. f_fireball - being hit by Ghast fireball.
3. f_spit - …you guess it.

**Comment by Dragnier** [comment]
This is not super clear. It honestly makes one think you need to _craft_ something, not get hit by things. Perhaps changing the line to mention "experiencing the effects of being hit by projectiles of various kinds" might be better?

**Comment by AnrDaemon** [comment]
Unfortunately…
Plus there's no way to actually track progress, since it is not printed to the chat, but briefly flashing on screen. Where it is easily missed in the middle of fight.

**Comment by Mike-U5** [comment]
I scanned an arrow/bow and assumed it was a bug when it didn't. If this is intentional then it's pretty vague.
