### ISSUE TITLE
server crash with 1.12.2-6.1.BETA11

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [Azanor/thaumcraft-beta#524]
Server crash while flying around.
Exception ticking world
java.lang.NoClassDefFoundError: Could not initialize class thaumcraft.common.entities.monster.EntityPech
more see here: [crashlog](https://gist.github.com/5t0rmr1d3r/461d7752a8d8b9ed37c019a80756101b)

**Comment by Kyozan** [comment]
Seems likely to be same issue as in #416 and maybe #337

**Comment by icray1** [comment]
Disable them in the config this is the same problem as #486
