### ISSUE TITLE
Unable to control directional tubes.

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#525]
To change directional tube state, you have to hit its center. Which is near impossible in cramped setups due to both tiny size of the tube center's hitbox and disabled tube extensions' extents being always present in the world.
I suggest to take the example from the best and only present extents when the extension is actually present.
If extension is disabled, hit the central block's face to "pull it off" into the world.
Increase hitbox of the tube core to 6x6x6 or even 8x8x8.
Unify all tubing controls. Click with the wand… ok, gauntlet, to turn connection on/off. Crouch-click to alter the configuration of the connection without altering its state. For directional tubes, that means setting(toggling) preferred direction directly. (pun intended)

**Comment by AnrDaemon** [comment]
Crouch-click on the tube core to take tube away… yes I'm too used to "BC compatible wrench"…

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#390
