### ISSUE TITLE
Clicking Crafting Recipes from the Thaumonomicon From one to Another Causes Crashes.

### ISSUE THREAD

**Issue by jdude360** [Azanor/thaumcraft-beta#526]
Basically, If you open the Thaumonomicon, and Click to view a Recipe, then Click another The Server Shuts itself down from some kind of Rendering Error. Don't Know if its your Mod or something i'm missing.
[crash-2018-04-26_17.49.44-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1953266/crash-2018-04-26_17.49.44-client.txt)

**Comment by AnrDaemon** [comment]
Duplicate #474

**Comment by UnixRonin** [comment]
I'm not seeing a server crash from opening recipes.  What I **AM** seeing is a **client-side** crash when **mousing over** crafting recipes in the Thaumonomicon.

**Comment by talonos2** [comment]
@UnixRonin I saw that too. I opened an issue for it at #614
