### ISSUE TITLE
[B8] Repeated bursts of lag when in the Nether

### ISSUE THREAD

**Issue by FN343** [Azanor/thaumcraft-beta#527]
Hello, so every time I'm in the Nether, every couple of seconds, my game freezes due to Thaumcraft lagging in the background somehow. I look at the output log and it keeps spamming it...

This is what it looks like...

[https://pastebin.com/vr7Zkp0v](url)

**Comment by FN343** [comment]
For some reason the link is broken so here...

https://pastebin.com/vr7Zkp0v

**Comment by AnrDaemon** [comment]
Just in case you did not notice: We're in B11 now.

**Comment by FN343** [comment]
Lol, it's only two weeks off...

**Comment by AnrDaemon** [comment]
Unless you can reproduce it with Beta 11, nobody's going to care.

**Comment by FN343** [comment]
...I still have yet to do that...

**Comment by Azanor** [comment]
This is a perfectly valid bug report. Sure it is for an out of date version, but nothing like this was reported previously and since I haven't fiddled with the aura's between now and then it might still occur in b11.

**Comment by FN343** [comment]
@Azanor Aww, thank you for such a respectful reply, you're the best, and yeah, I guess I should update, huh... It's just been too long since I've played and I haven't gotten a chance to properly make a 1.12.2 pack... I'm still on 1.10.2 (slightly more mods, of course) and 1.11.2 but I really should just move on... Sorry for the outdated bug...
