### ISSUE TITLE
Research requires unobtainable items.

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#530]
I.e. vanilla Ender Chest is often disabled, when Ender Storage is installed.
Please check if items you require are at all obtainable.

**Comment by Toksyuryel** [comment]
This is a modpack issue, the configs should be changed to enable the vanilla ender chest if TC6 will be part of the pack.

**Comment by FoxMcloud5655** [comment]
Developers do not have to integrate their mods with others.  They only choose to do so if they want to.  They make mods in their free time, for absolutely nothing.  If you truly have a complaint to file, file it with the modpack developer for not checking if everything works properly before publishing it for full release.  If you happen to just be including Thaumcraft 6 for your own use, then that's an issue that you should be able to resolve by going through your configs.

**Comment by EnderofGames** [comment]
This is clearly something for the developer of Thaumcraft to see. The expectancy of the player to research every item should be adjusted for items that are not available. If there is no realistic way for Azanor to do so, he can say so himself. If he expects modpacks to fix it themselves, he can say so himself. No need to inform everyone else on a decision you made if you are not the developer.

**Comment by Azanor** [comment]
Its most definitely NOT my job to make sure my mod happens to work with every other mod or modpack out there. Most mod devs check vs. the major mods, but there is simply not enough hours in the day to do that for everything. 90% of mods are balanced vs. vanilla minecraft. Mine definitely is.
