### ISSUE TITLE
[1.12.2-beta 11] Mining blocks under vis crystals makes them disappear

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#531]
As the title says. I'm not sure if this behavior was the same or different in previous versions, but it doesn't feel right either way. They don't drop as items on the ground, they just poof out of existence.

Let me know if you need more info.

**Comment by AnrDaemon** [comment]
Place block back and crystals will reappear. They are still hanging to the other nearby blocks.

**Comment by Azanor** [comment]
Yup
