### ISSUE TITLE
BETA10-11 Cant craft any Focus spell (TICKING BLOCK ENTITY)

### ISSUE THREAD

**Issue by Allev01** [Azanor/thaumcraft-beta#535]
everytime i tried to craft a spell in the focal manipulator the game crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  Wizardry Plugin (wizardry-0.7.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/27/18 12:15 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.traverseChildren(TileFocalManipulator.java:213)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.generateFocus(TileFocalManipulator.java:198)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.endCraft(TileFocalManipulator.java:232)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.func_73660_a(TileFocalManipulator.java:148)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.traverseChildren(TileFocalManipulator.java:213)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.generateFocus(TileFocalManipulator.java:198)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.endCraft(TileFocalManipulator.java:232)
	at thaumcraft.common.tiles.crafting.TileFocalManipulator.func_73660_a(TileFocalManipulator.java:148)

-- Block entity being ticked --
Details:
	Name: thaumcraft:tilefocalmanipulator // thaumcraft.common.tiles.crafting.TileFocalManipulator
	Block type: ID #2940 (tile.wand_workbench // thaumcraft.common.blocks.crafting.BlockFocalManipulator)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (960,91,-51), Chunk: (at 0,5,13 in 60,-4; contains blocks 960,0,-64 to 975,255,-49), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #2940 (tile.wand_workbench // thaumcraft.common.blocks.crafting.BlockFocalManipulator)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Mundo nuevo
	All players: 1 total; [GCEntityPlayerMP['rojo5521'/18598, l='Mundo nuevo', x=964.34, y=90.00, z=-51.06]]
	Chunk stats: ServerChunkCache: 578 Drop: 0
	Level seed: 3419265106864328829
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (240,64,252), Chunk: (at 0,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1063980 game time, 5936 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2091826976 bytes (1994 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 2, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.42 Powered by Forge 14.23.3.2659 Optifine OptiFine_1.12.2_HD_U_D1 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version                  | Source                                           | Signature                                |
	|:--------- |:-------------------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42                     | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.3.2659.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.3.2659             | forge-1.12.2-14.23.3.2659.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore                                |                          | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | aether_legacy                                | 1.12.2-v2.0              | aether_legacy-1.12.2-v2.0.jar                    | None                                     |
	| UCHIJAAAA | astralsorcery                                | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                   | None                                     |
	| UCHIJAAAA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | biomesoplenty                                | 7.0.1.2337               | BiomesOPlenty-1.12.2-7.0.1.2337-universal.jar    | None                                     |
	| UCHIJAAAA | thaumcraft                                   | 6.1.BETA11               | Thaumcraft-1.12.2-6.1.BETA11.jar                 | None                                     |
	| UCHIJAAAA | botania                                      | r1.10-354                | Botania r1.10-354.jar                            | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                                 | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore                                 | 2.4.0                    | BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCHIJAAAA | buildcraftlib                                | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftcore                               | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftbuilders                           | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftenergy                             | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftfactory                            | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftrobotics                           | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcraftsilicon                            | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | buildcrafttransport                          | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCHIJAAAA | coralreef                                    | 2.0                      | CoralReef-2.4-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | customspawner                                | 3.11.4                   | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| UCHIJAAAA | customnpcs                                   | 1.12                     | CustomNPCs_1.12.2(20jan18).jar                   | None                                     |
	| UCHIJAAAA | cyclopscore                                  | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                  | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar              | None                                     |
	| UCHIJAAAA | ptrmodellib                                  | 1.0.0                    | Decocraft-2.5.4_1.12.2.jar                       | None                                     |
	| UCHIJAAAA | props                                        | 2.5.4                    | Decocraft-2.5.4_1.12.2.jar                       | None                                     |
	| UCHIJAAAA | draconicevolution                            | 2.3.10                   | Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCHIJAAAA | mocreatures                                  | 12.0.4                   | DrZharks MoCreatures Mod-12.0.4.jar              | None                                     |
	| UCHIJAAAA | ebwizardry                                   | 4.1.0                    | Electroblob's+Wizardry+-+4.1.0+-+MC+1.12.2.jar   | None                                     |
	| UCHIJAAAA | erebus                                       | 1.0.22                   | Erebus-1.0.22.jar                                | None                                     |
	| UCHIJAAAA | evilcraft                                    | 0.10.53                  | EvilCraft-1.12.2-0.10.53.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | jei                                          | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                         | None                                     |
	| UCHIJAAAA | forestry                                     | 5.8.0.264                | forestry_1.12.2-5.8.0.264.jar                    | None                                     |
	| UCHIJAAAA | evilcraftcompat                              | 1.0.0                    | EvilCraft-1.12.2-0.10.53.jar                     | None                                     |
	| UCHIJAAAA | galacticraftcore                             | 4.0.1.174                | GalacticraftCore-1.12.2-4.0.1.174.jar            | None                                     |
	| UCHIJAAAA | galacticraftplanets                          | 4.0.1.174                | Galacticraft-Planets-1.12.2-4.0.1.174.jar        | None                                     |
	| UCHIJAAAA | mjrlegendslib                                | 1.12.2-1.1.3             | MJRLegendsLib-1.12.2-1.1.3.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extraplanets                                 | 1.12.2-0.3.2             | ExtraPlanets-1.12.2-0.3.2.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extrautils2                                  | 1.0                      | extrautils2-1.12-1.7.6.jar                       | None                                     |
	| UCHIJAAAA | forgelin                                     | 1.6.0                    | Forgelin-1.6.0.jar                               | None                                     |
	| UCHIJAAAA | llibrary                                     | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | iceandfire                                   | 1.4.0                    | iceandfire-1.4.0-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJAAAA | wizardry                                     | 0.7.2                    | wizardry-0.7.2.jar                               | None                                     |
	| UCHIJAAAA | librarianlib                                 | 9.4                      | librarianlib-1.12.2-4.9.jar                      | None                                     |
	| UCHIJAAAA | radixcore                                    | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar             | None                                     |
	| UCHIJAAAA | mca                                          | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                   | None                                     |
	| UCHIJAAAA | millenaire                                   | Millénaire 6.2.0-beta.23 | millenaire-6.2.0-beta.23.jar                     | None                                     |
	| UCHIJAAAA | moreplanets                                  | 2.0.14                   | More-Planets-1.12.2-2.0.14-GC156.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJAAAA | nuclearcraft                                 | 2.10f                    | NuclearCraft-2.10f--1.12.2.jar                   | None                                     |
	| UCHIJAAAA | roots                                        | 0.104                    | roots-2-0.104.jar                                | None                                     |
	| UCHIJAAAA | rustic                                       | 1.0.3                    | rustic-1.0.3.jar                                 | None                                     |
	| UCHIJAAAA | thebetweenlands                              | 3.3.7                    | TheBetweenlands-3.3.7-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAA | twilightforest                               | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar      | None                                     |
	| UCHIJAAAA | worldedit                                    | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar            | None                                     |
	| UCHIJAAAA | librarianliblate                             | 9.4                      | librarianlib-1.12.2-4.9.jar                      | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
Wizardry Plugin (wizardry-0.7.2.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['rojo5521'/18598, l='Mundo nuevo', x=964.34, y=90.00, z=-51.06]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.30.14
	OpenGlRenderer: Intel(R) Iris(TM) Plus Graphics 640
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by Xiaminou** [comment]
I managed to craft a few foci but eventually got the same crash.

[crash-2018-04-27_14.23.43-server.txt](https://github.com/Azanor/thaumcraft-beta/files/1955067/crash-2018-04-27_14.23.43-server.txt)

**Comment by Mike-U5** [comment]
Seems like when the brown rune with an eye in it appears at the top of the focal manipulator interface, you're good. 
It wasn't there during my first attempt, which did crash the game.

**Comment by lag42** [comment]
can confirm this still happens

**Comment by Allev01** [comment]
it works now but i have to put the foci and then retreat it and put it back so the rune witht the eye appears
