### ISSUE TITLE
(B11) Vis crystals in Thauminomicon

### ISSUE THREAD

**Issue by Majestyc2k1** [Azanor/thaumcraft-beta#536]
The following sections are missing specific aspects on the vis crystals needed to complete the research. The vis crystals in the book are generic; they do not have any aspect associated on them.

Crystal Farming
Essentia Smelting
Arcane Bellows

Beta 11
Forge 14.23.3.2673

**Comment by AnrDaemon** [comment]
Duplicate #511

**Comment by LightniX** [comment]
You should close this issue.

**Comment by Majestyc2k1** [comment]
Sorry, I found #511 after the fact.
