### ISSUE TITLE
[1.12.2-6.1.BETA11] Golem Press Refuses to draw Machina

### ISSUE THREAD

**Issue by Thaumatarge** [Azanor/thaumcraft-beta#538]
I have no solid idea about why this is happening, but the Golem Press refuses to draw Machina essentia from any jars I put next to it or anywhere else (connected with the pipes), not even when I use different means of getting the essentia in to the machine, not even with the air transport. Clicking the crafting button doesn't do anything other than layering the texture of the Machina aspect on top of itself without proceeding with the process of creating the golem.

Checking the Press with the Essentia Resonator yields "Suction 0 Machina" so I have a feeling the internal tank of the machine is just nil, meaning the machine has no way of buffering Machina essentia for the process to take place, but that is just my idea/hunch.

**Comment by LightniX** [comment]
I wanted to post this issue too but i forgot.
Thank you!

-LightniX

**Comment by ZoeZoePixel** [comment]
i have this problem too

**Comment by AnrDaemon** [comment]
@ZoeZoePixel , if you want notifications of issue updates, click "Subscribe" on the right.
Your "I do have it too" does not add to the issue.

**Comment by ZoeZoePixel** [comment]
k srry
