### ISSUE TITLE
Crash while using thaumonomicon

### ISSUE THREAD

**Issue by Sumguy62** [Azanor/thaumcraft-beta#541]
https://pastebin.com/c8e6dzbb

**Comment by Kyozan** [comment]
#519 #514

**Comment by EnderofGames** [comment]
Update to beta 11 and make sure you are using a different save. 

Fixed the problem for several of the reports. You may be able to just replace your Thaumonomicon, too, but I cannot confirm that.

**Comment by mmillstein** [comment]
I'm definitely still seeing it happen in a fresh B11 world

**Comment by Geethebluesky** [comment]
Happening to me in beta 11, I **just** crafted the Thaumonomicon and was on the Scribing Tools page, clicked on the glass phial cause I didn't remember the recipe, crash above occurred.

**Comment by Imotepchief** [comment]
Just got the same error, running Beta11, I had just opened the Thaumic Dioptra tab when it happened.
