### ISSUE TITLE
[1.12.2] [B11] All Vis Crystals in the Thaumonomicon Look The Same

### ISSUE THREAD

**Issue by EmosewaPixel** [Azanor/thaumcraft-beta#546]
![image](https://user-images.githubusercontent.com/25333164/39380693-bd1c8d32-4a5f-11e8-92ce-4b7f9462d230.png)
I'm guessing the items in the tasks don't respect NBT.

**Comment by wamc2017** [comment]
#511 for reference

**Comment by Tyrion216** [comment]
I can confirm that this happens for me as well. The arcane bellows and essentia smelting both have this issue where I can't see which specific crystals are required. So far these are the only two. Unless one were to happen to know which ones were required, you can't progress past this point.
