### ISSUE TITLE
Vis Resonator Crafting

### ISSUE THREAD

**Issue by JupiterYourHero** [Azanor/thaumcraft-beta#549]
The item won't craft.

**Comment by Dragnier** [comment]
Did you try in an Arcane Workbench with Primal Crystals in their proper places? If you only used a regular crafting bench, they don't craft there because they require Primals and Vis which can only be supplied by the Arcane Workbench.

**Comment by sandalle** [comment]
I had the same "issue" when trying to make the Vis Resonator for the Thaumic Dioptra under Artifice. The "fix" was to complete step #1 of Discovering Auromancy under Fundamentals. :) Afterwards, I was able to craft the Vis Resonator in an Arcane Workbench.
