### ISSUE TITLE
A15 Issue: voidstuff research requirement

### ISSUE THREAD

**Issue by LordPinkerton** [Azanor/thaumcraft-beta#55]
Issue: When progressing through the Alchemy Metallury research, the stage 3 requirement for c_voidstuff seems to be mismatched to the text reference. Also, there does not seem to be an event that triggers the research requirement for this stage and cannot be progressed past.

**Comment by LordPinkerton** [comment]
On a related issue, checking to see if the Thaumium Smeltery is supposed to be gated at Metallurgy stage 3 instead of 4.

**Comment by Azanor** [comment]
The first one is a known issue. I am still working on the whole eldritch tree.
The second part is indeed an issue.

**Comment by Geethebluesky** [comment]
Hey Azanor, this is now closed but I'm still seeing the voidstuff reference in Beta 13. Since closed I'm assuming it's no longer supposed to show that way?

[Pic](https://i.imgur.com/uWtschv.png)
