### ISSUE TITLE
[B11] Server stuck on "Stopping aura thread for dim 0" after I tried to shut it down

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-beta#551]
My server froze up with the last message being `[03:57:51] [Thread-26/INFO] [THAUMCRAFT]: Stopping aura thread for dim 0`, when I tried to shut it down via the quit command in the server console.
I can't say for sure that this is a Thaumcraft issue, but I played a lot of Thaumcraft today so it's hard to believe it would be a coincidence.

Here is the log: [debug.log](https://github.com/Azanor/thaumcraft-beta/files/1957167/debug.log)

Minecraft: 1.12.2
Forge: 2669
Thaumcraft: B11
Mods: [list.txt](https://github.com/Azanor/thaumcraft-beta/files/1957168/list.txt)

**Comment by nickmuenster** [comment]
How do you solve it??
