### ISSUE TITLE
[1.12.2] Thaumonomicon recipe viewing crash

### ISSUE THREAD

**Issue by Yhuxz** [Azanor/thaumcraft-beta#554]
Just started and trying to view the recipe for Thaumometer in Thaumonomicon crashes the game.

[crash-2018-04-28_12.36.37-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1957289/crash-2018-04-28_12.36.37-client.txt)

**Comment by mmillstein** [comment]
I've also been having this happen in the B11 build
