### ISSUE TITLE
pech STILL crashes you

### ISSUE THREAD

**Issue by redgoblin88** [Azanor/thaumcraft-beta#556]
i first encountered this bug in minecraft 1.10 which thaumcraft6 first released for. 
every update since initial release this bug has persisted and it makes the world implayable because the game tries to spawn in a pech but the code is incomplete/broken so it cant spawn crashing the game.

here is the crash report: https://pastebin.com/Zkh4G36K

i am playing with:

thaumcraft: 6.1.BETA11
Forge: 14.23.3.2655

and many more mode but they have nothing todo with mob spawning

**Comment by EnderofGames** [comment]
#528

**Comment by LlamaTea** [comment]
As a way to temporarily solve your issue if you wish to be close to/in a magical forest you can edit the config called thaumcraft world (i think, check the others if not) to disable pechs from spawning.

**Comment by Azanor** [comment]
This bug is so annoying. I can't replicate it at all and there is nothing in the pech code that differentiates it from any of my other mobs at all. Obviously it is a problem as lots of people have reported it thusfar.

**Comment by omegasigma529** [comment]
I don't know if it's the same in this case, but on 1.10.2, the iChun's Hats mod would cause a crash if a Pech spawned with a hat on. We ended up having to disable hats on non-vanilla mobs.

**Comment by Hillage** [comment]
For what it's worth, I went through all of the B11 and B10 crash reports in relation to pech, and anyone that included a crash report has the hats mod. Is there a semi-popular modpack that has both Thaumcraft Beta and the hats mod??

Will try testing pechs in our server shortly without the hats mod.

**Comment by AgentEpsilon** [comment]
I think I've narrowed down the issue here.

As some others have said, it definitely has to do with a conflict in iChun's Hats mod. To work with other mods' mobs, the Hats mod keeps a json file here: https://github.com/iChun/Hats/blob/master/src/main/resources/assets/hats/mod/HatModMobSupport.json

It looks like the Hats mod is attempting to access the mob at `thaumcraft.common.entities.monster.EntityPech`. Is that still where the EntityPech class is located in Thaumcraft 6? If not, I could see this causing issues.

If this is the case, this would definitely be a Hats mod issue. @Azanor, could you confirm?

**Comment by Sketaful** [comment]
It would be awesome if it all have to do with a "simple" thing as the thaumcraft.common.entities.monster.EntityPech being incorrect. If so the right place for the EntityPech class could be sent to iChun and he'll only have to fix that.

**Comment by LandKingdom** [comment]
Pech crashes you with or without Hats mod installed.

**Comment by Sketaful** [comment]
That's strange. Peach works for me. Even works with the hats mod as long as you don't have it activated for mods.

**Comment by Wohlf-craft** [comment]
Was this fixed in beta 18? @Azanor Well im not really sure what pech is but I was told that this was a thaumcraft bug. So https://pastebin.com/zygtMim8

**Comment by LandKingdom** [comment]
It's not a hat. A pech is a mob from thaumcraft, added since Thaumcraft 4.

**Comment by Wohlf-craft** [comment]
Ya, it has been too long since I had played with thuamcraft. I probably need to watch dire's spotlight.
