### ISSUE TITLE
A15 Issue: Theorycraft Fundamentals

### ISSUE THREAD

**Issue by LordPinkerton** [Azanor/thaumcraft-beta#56]
Not a bug, but a possible rebalancing needed from my experience so far. It would seem that coming across Theorycraft pages in Fundamentals is extremely rare, in my playthrough, requiring many stacks of paper to even get a single point.

**Comment by Azanor** [comment]
They are supposed to be harder to get, but it is quite possible that they are TOO hard to get. I will need to take a look.
