### ISSUE TITLE
[B11] Scanning inventories doesn't scan contained items

### ISSUE THREAD

**Issue by apmax** [Azanor/thaumcraft-beta#561]
Using the thaumometer to scan certain inventory blocks, particularly chests from other mods, will not scan each individual item contained within.
I've experienced this most notably with storage crates from actually additions.

**Comment by Sumguy62** [comment]
It works for me with Iron Chests.

**Comment by Dragnier** [comment]
I would guess that the chests in question do not extend/inherit from the vanilla chest; which probably causes the thaumometer to not see them as a chest/inventory.
