### ISSUE TITLE
[B11]  Suggestion:  Goggles enhancement

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#562]
...Just a thought:

Since the Thaumometer shows sparkles on scannable items you haven't scanned yet, and the Goggles of Revealing are made from thaumometers, it would make sense if the Goggles of Revealing also revealed unscanned items.  Then you could just dig out your thaumometer whenever you saw something sparkly, instead of walking around the whole time peering through your thaumometer.  You'd still need to actually pull out your thaumometer to scan an object or measure the aura, but the Goggles would tell you **when** you needed to pull out the thaumometer.

**Comment by androshalforc** [comment]
this ive been thinking the same since i was introduced to Thaumcraft back in 3 or 4

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#388
