### ISSUE TITLE
[B11]  REGRESSION:  Crafting Sal Mundi on the arcane workbench consumes the flint and bowl

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#563]
Not much more to say.  On a regular crafting table or, say, a Bibliocraft fancy crafting table, you get the bowl and flint back just like you always have.  On an arcane workbench, you don't.

This is a regression from B10 and earlier.

**Comment by AnrDaemon** [comment]
Adding to that, I've noticed Arcane Workbench misbehaving in general.
Some recipes from normal crafting tables can't be crafted at all. Presumable those with returns handled by a function.

**Comment by UnixRonin** [comment]
Hmm.  Related perhaps to #567?

**Comment by DustyTheLion** [comment]
Too add to this, the arcane workbench seems to also be consuming buckets from recipes that call for buckets of liquid.  I noticed this while making treated wood in Immersive Engineering.
