### ISSUE TITLE
[B11] Infernal Furnace rejecting or eating multiple stacks of Cobble

### ISSUE THREAD

**Issue by Dragnier** [Azanor/thaumcraft-beta#564]
I don't know if this affects anything else because I haven't tried anything but Cobblestone. I put 4 stacks of Cobble into the Infernal Furnace with 3 bellows on it. When I got around front, two stacks of cobble were sitting there and it was working on a third turning it into Smooth Stone as per usual. However, the fourth stack simply vanished as the furnace finished the first and never gave more stone.

I tried this several times and it always rejects or vanishes some of the stacks while only ever producing one stack total of smooth stone.

**Comment by Dragnier** [comment]
Just tested with meat. Threw in a large stack of raw beef and then followed by a small amount of raw mutton. The mutton disappeared like it just burned up.

**Comment by Azanor** [comment]
I could not replicate this, but I have significantly cleaned up the code related to furnace item handling so hopefully this should be sorted in the next release.
