### ISSUE TITLE
[1.12.2] Crash when loading with Botania

### ISSUE THREAD

**Issue by billyma6** [Azanor/thaumcraft-beta#565]
When I load Thaumcraft 6 BETA11 with Botania, the game crashes on while starting up, stopping when it reaches Initializing Mods. My forge is 1.12.2-14.23.3.2655, -1,12,2-6.1.BETA11, and Botania+r1.10-353.

**Comment by wamc2017** [comment]
#468, #477 and maybe more...

Update Botania to r1.10-354
