### ISSUE TITLE
[B11-B13]  Worldgen issue, chunks generated with 0 aura SOLVED (Forge optional feature is incompatible)

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#567]
So, I've made up a batch of arcane cloth and I'm trying to craft arcane gear.  Wearing boots and goggles, I have a 7% discount.  With that discount, crafting pants requires 93 vis.  At my keep, there's 81 available.  So I take my thaumometer and go searching the area.

185 blocks away, I find a chunk with 211 vis.  I mark the spot, grab my arcane workbench, take it back there, plunk it down, lay out the cloth on the workbench and ...  0 vis available.  Say what?  Five minutes ago there was 211 on that very spot.

This has happened several times.  Each time, the thaumometer says the aura is anywhere from 80 to ... I've seen as high as 295, but the Arcane Workbench says 0 available.

**Comment by UnixRonin** [comment]
Also see #563.  The Arcane Workbench seems to be a little flaky in general right now.

**Comment by AnrDaemon** [comment]
Discount applies to the result. You still have to have full vis level to start crafting.

**Comment by UnixRonin** [comment]
Oh, sure.  But the workbench shouldn't be reporting '0 available' when the thaumometer is reporting 211.

**Comment by AnrDaemon** [comment]
Sure.

**Comment by UnixRonin** [comment]
I just spent an hour running around with an arcane workbench and my thaumometer.  Every time I found a chunk where the thaumometer reported >170 aura, I'd plonk down the workbench, lay out the crystals and ingredients for an infusion matrix, and every time, the workbench would say '0 available'.

**Comment by UnixRonin** [comment]
Oh, also, what seems bit weird ...  my dioptra is reporting two "rift valleys" of chunks near to me where the aura is 0.  Is that even supposed to happen?  Or did something go wrong in worldgen there?  And why wouldn't my thaumometer ALSO show 0 there?

**Comment by Azanor** [comment]
Is this happening in a single player world or in MP?

**Comment by UnixRonin** [comment]
This is an SMP dedicated server.  The dioptra seems to agree with the workbench that there are tracts of blocks along the edge of the first couple of region files that have no aura, which appears to be fairly clearly a worldgen issue possibly triggered by my doing a regen of all but the first couple of regions because a BoP update removed some biomes.  (I'm considering a full world nuke-and-pave.)  The really odd part is that the thaumometer still seems to be showing those chunks' **ORIGINAL** aura levels even though the workbench and dioptra agree that it's now 0.

**Comment by UnixRonin** [comment]
I still don't know why the thaumometer reports different aura values from the workbench or dioptra when a chunk's aura is borked.

**HOWEVER**, I am _reasonably_ sure I have isolated the cause of the dead-aura chunks **themselves** to chunks being forcibly generated or regenerated by/using WorldEdit Forge or Chunk Pregenerator.

**Comment by UnixRonin** [comment]
I just reported this as an issue against Chunk-Pregenerator, BTW.

**Comment by xenxero1** [comment]
I think this would be an issue on thaumcraft's end. Seeing as you can still see the old vis levels in the thaumometer. I'd probably guess it has something to do with how thaumcraft checks it auras. At the very least, any chunk editied and reverted to 0 vis should slowly gain vis from it's surrounding chunks vis-fields. Running a check and heal on server start/restart would probably be a quick and clean way to solve this with minimal performance impact.

**Comment by xenxero1** [comment]
Right, but anything that overwrites a generated chunk shouldn't be able to set the maximum to 0. We're assuming it's an issue with editing software overwriting things it shouldn't, I doubt its overwriting values like Maximum instead of deleting that part of the chunk's code.  You could run a check at startup to change any chunks with maximum = 0 to some random number within a range (maybe calculated by the surrounding chunks). That is, unless we have a legitimate reason for wanting max=0 naturally. 
It might be that these editing tools just erase the data corresponding to the vis fields in general, in which case you can run a check for missing vis field code from chunks on startup, and impose a new one.

Alternatively, it makes sense to me to switch to Astral Sorcery's system of keeping the "energy field" information separate from the world.dat file, but that's also a huge system change.

**Comment by UnixRonin** [comment]
I think the fundamental problem as to why chunks are ending up with 0 aura in this case is that tools that pre-generate chunks without them being visited by a player, such as Chunk Pregenerator, or that forcibly **regenerate** a chunk on demand, such as WorldEdit, are triggering the chunk generation in some not-quite-correct manner that somehow does not reliably cause aura generation to happen.  (Chunk Pregenerator is already documented as not working correctly with RTG for another example.)  I don't think that's Thaumcraft's problem, unless Azanor wants to tackle the problem of figuring out what it is that they're not doing right and working around it.

The Thaumcraft issue here is that when it does happen, somehow the workbench and dioptra are seeing one aura value for the chunk, and the thaumometer is seeing a dramatically different value.  Specifically, it seems the workbench and dioptra see the chunk's aura as 0, while the thaumometer sees whatever it "should" be.  And I'm not quite sure how this could even happen, but apparently it is.

The gripping hand is, it's a corner case that probably **shouldn't** even be able to happen in the first place because there **shouldn't** be overworld chunks generated with 0 aura.

**Comment by UnixRonin** [comment]
Um, OK, I take it back.  Houston, we have a problem.

After the last round of testing, I **completely removed** Chunk Pregenerator from server and client, wiped the world, created a **brand new** B12 world from the same seed, then flew, not teleported, to a number of areas I had previously noted as possible building sites.  I picked one out, set down the collected stuff I've been toting around with me, and oh gee, look, I still have the dioptra I was carrying around for testing.  Let's put this thing down.  **...Uh-oh.**

Take a look.  Out of this entire 13x13 chunk area, more than half of which is magical forest, nine chunks have any aura at all according to the dioptra.  And this was **ENTIRELY NORMAL** generation.

[https://www.caerllewys.net/public/minecraft/2018-05-04_16.36.24.png](url)

**Comment by AnrDaemon** [comment]
> Right, but anything that overwrites a generated chunk shouldn't be able to set the maximum to 0.

How? If it overwrites entire chunk, including all of its metadata?

**Comment by xenxero1** [comment]
It can overwrite the chunk, I'm saying we shouldn't allow it to interfere with thaumcraft's side unexpectedly. I'm not saying that it can't, I'm saying we could potentially plan for that on thaumcraft's end, and prevent it from accidentally overwriting thaumcraft information like vis fields.

**Comment by UnixRonin** [comment]
Here's another one.  To the west, magical forest, aura out the wazoo.  To the right, taiga, and the first five chunks of it is a rift valley of zero aura running dead north-south.  Then the aura returns to normal on the other side of those five chunks.

[Great Aura Rift Valley?](https://www.caerllewys.net/public/minecraft/2018-05-04_17.20.01.png)

**Comment by UnixRonin** [comment]
Oh yeah, forgot to add — still occurring in B13.

**Comment by Geethebluesky** [comment]
@UnixRonin 
> Perhaps if there were some way Thaumcraft could check aura level each time a chunk is loaded, and redo aura generation if it is 0? (I'm assuming here that a chunk's aura may be low, but should never actually be 0.)

That would.... be useful, since I generated the vast, vast majority of my world with a chunk generator which is going to be faster than most other methods... eep.

if not possible I guess I'll just have to extract my base and regen a new world :(

**Comment by UnixRonin** [comment]
@Geethebluesky — could I ask you to flit around a bit with a dioptra and a thaumometer and do some spot checking to determine whether you are encountering the same problem?

**Comment by Geethebluesky** [comment]
Sure thing.

**Comment by Geethebluesky** [comment]
Just checking though, you already went though Chunk Pregenerator with a different TC RegenKey and just set it to regen the aura and nothing else, right?

I had part of the world already-generated when I installed TC so that's the first thing I did (well, I set it to generate everything, so I'm supposing it did.). Not seeing any issues close to me so far...

**Comment by Geethebluesky** [comment]
Went to a few deserts and BoP Wastelands biomes, where the aura there is naturally quite low (as it's supposed to be), but not seeing any 0-aura chunks. I'll update more if I see any but your chunks seem pretty frequent, I'd try regenerating the aura only again...

**Comment by UnixRonin** [comment]
OK, so this was REALLY interesting.

I wiped and recreated the world **again**.  Set god mode, gave myself a dioptra and a pick, measured aura around the spawn.  13x13 all good.
Picked up the dioptra, waled about 4 chunks south, set it down again.  4-chunk band of 0 aura across the south side of the map, static, not changing.
OK.  Teleported to 1000,1000.  Splash, middle of the ocean.  Nowhere to put down the dioptra.
Teleported to 2000, 2000.  Splash.  Land nearby, maybe 30 blocks away.  Hop over to the land, plop down the dioptra, 0-aura patch on the side away from where I 'ported in.
Teleported to 3000,2000.  Arrived on solid ground.  Plunked down the dioptra in time to see 0-aura patches at two corners of the display fill in over a period of about 15 seconds as the chunks loaded.

Repeated this experiment about 3-4 times.  Each time I **teleported** to a new location, the chunks generated with normal aura.

Then on one teleport I forgot to pick up the dioptra..  So I teleported back to the last location to get it ...   and saw this:

[Uh-oh](https://www.caerllewys.net/public/minecraft/2018-05-05_14.18.01.png)
[And from the other side...](https://www.caerllewys.net:public/minecraft/2018-05-05_14.18.20.png)

So the chunks initially _generated_ with correct aura, but when _reloaded_, the aura was missing from about half the total chunks in the area.

There seems to be something badly wrong here.


@Geethebluesky — I just looked at my configs again.  This is initial generation, and every **generation** setting is set to true.  You're saying that you did a **regeneration** using B:regenAura=true?

I wonder if I could pregenerate, then set just B:regenAura=true and set S:regenKey, and see if it will correctly just regenerate the aura as I visit chunks.  I'm going to try this and see what happens.

**Comment by Geethebluesky** [comment]
>  You're saying that you did a regeneration using B:regenAura=true?

What I did when I installed TC for the first time was change the generation key from DEFAULT to something else. I didn't even load the mod before then: just generated default configs via the client, copied to server, set a regen key on the server, loaded the world with TC set to regen everything and ran through all region files with the chunk pregen.

Needing to do that seemed logical at the time, reasoning is that some server ops may not want any TC features at all in old chunks, the only way to ensure that would be for the DEFAULT key to not touch anything already existing when it's added.

Seeing your issue though I wonder if that's supposed to be the desirable default behavior, but in a nutshell, the regen worked for me as it should have as far as I can see now.

**Comment by UnixRonin** [comment]
Chunk boundaries were half the reason I regenerated in the first place.  BoP dropped a couple of biomes in the last update and the entire biome map changed.

**Comment by UnixRonin** [comment]
OK, I just tried the Thaumcraft aura retrogen trick with a 50-chunk radius around origin pregenerated, but I'm still seeing tracts of adjacent chunks with no aura.  I'm trying again with a 100-chunk radius.  I do notice Thaumcraft's chunk aura retrogen is almost instantaneous, and I still wonder whether the real fix for this would be if Thaumcraft automatically did aura retrogen on any chunk that loaded with 0 aura.  This is however predicated on the assumption that a chunk's aura **should never be** 0.

**Comment by UnixRonin** [comment]
Tweak timepertick where?

**Comment by UnixRonin** [comment]
BaseMetals-1.12-2.5.0-beta5.214.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
BiomeTweaker-1.12.2-3.2.345.jar
BiomesOPlenty-1.12.2-7.0.1.2382-universal.jar
CarryOn+MC1.12.2+v1.8.jar
Chameleon-1.12-4.1.3.jar
ChickenASM-1.12-1.0.2.7.jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
Chunk+Pregenerator+V1.12-1.7.1.jar
ClassicCombat-1.12-1.0.0.jar
ClayWorldGen-1.1.0-1.12.0.jar
CoFHCore-1.12.2-4.4.1.12-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
CodeChickenLib-1.12.2-3.1.7.340-universal.jar
CraftTweaker2-1.12-4.1.6.jar
EnderCore-1.12.2-0.5.20.jar
EnderIO-1.12.2-5.0.22.jar
EnderStorage-1.12.2-2.4.2.126-universal.jar
Erebus-1.0.22.jar
ExtraGems+1.12.2++(v.1.2.3).jar
FenceOverhaul-1.3.4.jar
ForgeMultipart-1.12.2-2.4.0.55-universal.jar
Hwyla-1.8.24-B39_1.12.jar
ImmersiveEngineering-0.12-81-core.jar
ImmersiveEngineering-0.12-81.jar
InventoryTweaks-1.63.jar
KleeSlabs_1.12.2-5.4.8.jar
Login_Shield-1.12.2-1-g24c2a5e.jar
Mekanism-1.12.2-9.4.5.340.jar
MekanismGenerators-1.12.2-9.4.5.340.jar
MekanismTools-1.12.2-9.4.5.340.jar
Mineralogy-1.12-3.4.0.22.jar
MobController-1.12.2-1.1.jar
Morpheus-1.12-3.3.2.jar
MyCommands-1.12.2-01.jar
NaturesCompass-1.12.2-1.5.1.jar
NetherMetals-1.12-1.2.0-beta3.52.jar
NetherPortalFix_1.12.1-5.3.13.jar
NoMobSpawningOnTrees-1.2.1-mc1.12.jar
NotEnoughItems-1.12.2-2.4.1.233-universal.jar
OreSpawn-1.12-3.3.0.136.jar
RedstoneArsenal-1.12.2-2.4.2.9-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
SGCraft-1.0-mc1.12.2.jar
SlashBlade-mc1.12-r12.jar
SophisticatedWolves-1.12.2-3.13.2.jar
StorageDrawers-1.12.2-5.3.6.jar
Thaumcraft-1.12.2-6.1.BETA13.jar
ThaumicJEI-1.12.2-1.2.1-4.jar
ThermalDynamics-1.12.2-2.4.1.10-universal.jar
ThermalExpansion-1.12.2-5.4.2.27-universal.jar
ThermalFoundation-1.12.2-2.4.1.15-universal.jar
TickProfiler-1.12-0.0.4.jar
Translocators-1.12.2-2.5.0.70-universal.jar
Wawla-1.12.2-2.5.253.jar
[1.12]TreeCapitator-client-1.43.0.jar
[1.12]bspkrsCore-universal-7.6.0.1.jar
architecturecraft-1.12-2.68.jar
boptools-1.12-0.0.3.0.jar
chunkedgeindicator-1.4.jar
dazzle-1.0.jar
dirt2path-1.7.0.jar
immersivetech-1.12-1.3.7.jar
ironchest-1.12.2-7.0.40.824.jar
jei_1.12.2-4.9.1.169.jar
journeymap-1.12.2-5.5.2.jar
levels-2.0.3.jar
malisisblocks-1.12.2-6.1.0.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
torchmaster_1.12.2-1.6.1.53.jar
twilightforest-1.12.2-3.6.345-universal.jar
underphangables-1.12.0-1.0.0.jar
worldedit-forge-mc1.12-6.1.8-dist.jar


Though I really have not had time to get around to actually delving into EnderIO or Immersive Engineering yet.  I added EnderIO primarily for inventory management, and Immersive Engineering because it looked interesting.  Most of the rest I've been using for years alongside prior versions of Thaumcraft.

**Comment by UnixRonin** [comment]
I think I **MIGHT** have identified the culprit:  BetterFPS.  I'm adding everything **else** back in right now to verify.

**Comment by UnixRonin** [comment]
...Well crap.  I **THOUGHT** I had narrowed it down to BetterFPS.  Apparently I was wrong.

Well, I appear to now have a lengthy list of mods it **isn't**...

**Comment by UnixRonin** [comment]
**FOUND IT FOUND IT FOUND IT**

It was a configuration problem.  Forge has this optional feature that is disabled by default:

```
    # Unloaded chunks can first be kept in a dormant cache for quicker
    # loading times. Specify the size (in chunks) of that cache here
    I:dormantChunkCacheSize=0

```

**DO NOT ENABLE THIS CACHE.**  It screws up Thaumcraft aura generation.

**Comment by AnrDaemon** [comment]
Are you sure it is literally broken?
From the description of feature, it delays chunk unloading while server is running.
Imagine you're running back and forth across your base, edge chunks are constantly loaded/unloaded.
This feature is intended to reduce this constant reload.

**Comment by UnixRonin** [comment]
Yes, I understand quite clearly what it is supposed to do.  Or rather, it does not delay cache unloading, but caches recently unloaded chunks so that they can be quickly reloaded.

However, the evidence of days of testing trying to isolate the problem is unequivocal.  Enabling this feature was solely and definitively the single factor wrecking Thaumcraft aura generation.  It works fine with every other mod I'm aware of **as long as you're not running Thaumcraft**, but somehow it causes Thaumcraft's aura generation to fail on a massive scale.

**Comment by AnrDaemon** [comment]
[I have to do it again…](http://www.stonemakerargument.com/1/1a.jpg)
The fact this feature breaks Thaumcraft aura handling does not necessarily means that the feature itself is broken.
Though, I can see that possible. Aura levels are stored in the chunk attributes. If it does not correctly restore said attributes, they could be lost.

**Comment by UnixRonin** [comment]
I didn't say the feature itself was necessarily broken.  However, it appears to be incompatible with Thaumcraft 6.

**Comment by UnixRonin** [comment]
Oh, wait, I did in my title edit, didn't I?
I plead late-at-night.  I'll amend that.

**Comment by Geethebluesky** [comment]
If you're saying that **a chunk loaded from cache** loses its aura, I have to nix that theory. I've been using the dormantChunkCache (size 64) since I learned about what it does (installing Foamfix on forge 2655 over a month ago) and I don't have the zero-aura problem at all.

**Comment by UnixRonin** [comment]
Well that puts it back to mystery then, because that is the only change that has had any effect on the aura-loss behavior.  With nothing but Thaumcraft, the required Baubles, and the JEI necessary to test in a reasonable time, and the chunk cache **enabled**, the aura bug is present.  **Disable** the chunk cache, making **no other change**, and it does not manifest at all even with the entire modpack.

This is with Forge 2677 and Java 8u172 64-bit.

**Comment by UnixRonin** [comment]
Not even Chunk Pregenerator is needed.  I have not retested Chunk Pregenerator.

It might be worth testing different values of chunkcache.  I tried 500.  Maybe I set it too high, if you've been getting good results with 64.  (I note that the dioptra maps 169 chunks, 13×13, and that Forge by default loads a ...  is it 8 or 10 chunks radius by default?  That's either 256 or 400 chunks.)

My procedure:  generate a new world from the server console, log in, use JEI to give myself a pick and a dioptra, run or fly around in random directions five to ten chunks at a time and plonk down the dioptra to look at the aura in surrounding chunks.

Also, teleport a thousand chunks or so away and then teleport **back**, and upon returning to the original spot, 9 times out of 10 its aura will be hosed.  You should be able to place the dioptra where you teleported **TO** in time to watch the corners of its mapping area fill in as Minecraft loads the furthest-out chunks.

**Comment by Geethebluesky** [comment]
Okay well that did it, I experienced your same issue with 256 after teleporting only 3 times.

Going to try the same steps again with 64.

**Comment by UnixRonin** [comment]
If we can nail down a safe upper bound, that would be worthwhile.

**Comment by UnixRonin** [comment]
I'll give it a try at 64 and see if I run into any problems.

**Comment by Geethebluesky** [comment]
This is weird. Same world seed with a dormant cache of 112, TPed to the same general areas. Instead of seeing the canyon I spotted with the 160 cache size, I see deep spikes instead.

I have no idea why the same map seed with same modlist etc. would behave "a little bit better" with a cache size of 112, it's like there's no sharp cutoff here.

**Comment by UnixRonin** [comment]
yeah, it seems to be a case of "it just gets progressively worse"

You can probably imagine how bad it was at 500.

**Comment by UnixRonin** [comment]
I just saved the seed for my most recent test world actually, because there's a bunch of big Mineralogy slate deposits right near to the spawn.  Great roofing material, y'know, a slate roof can last centuries....

**Comment by Geethebluesky** [comment]
So. I just reloaded the world created with cache size 160 (after resetting the config so it's still 160) and went looking for that aura canyon again.

The canyon is gone.

Want to try going back to your 500-cache world dead zones after restarting the server?

**Comment by UnixRonin** [comment]
That worldgen round is long since gone.  But I did multiple rounds of restarts and aura retrogens at that setting, trying to find anything that would work, and never once saw the aura clean up.

**Comment by UnixRonin** [comment]
OptiFine was one of the variables I tested for.  It made no difference however.  I was able to consistently reproduce the problem with absolutely nothing installed except for Forge, Thaumcraft, Baubles, and JEI.

**Comment by belathus** [comment]
I have this problem, and I have never set that setting to anything above zero.

https://imgur.com/a/mQX0STC

**Comment by Geethebluesky** [comment]
@belathus This is in Beta 16?

**Comment by belathus** [comment]
It is B16. Something to note: it got worse as I left and returned to the dimension. Seems that the more chunks loaded and unloaded, the worse it got.

However, now that I've restarted the server, things seem okay, for now.

https://i.imgur.com/rnpnQFW.png

```
base-1.12.2-3.7.2.jar				Botania\ r1.10-354.jar			CTM-MC1.12-0.3.0.15.jar			 elulib-0.1.12.jar			   Guide-API-1.12-2.1.5-60.jar		    lostcities-1.12-2.0.8.jar			 moreoverlays-1.13-mc1.12.1.jar     RedstoneFlux-1.12-2.0.2.3-universal.jar  TConstruct-1.12.2-2.10.1.84.jar			       VTweaks-1.12.2-2.0.0b.jar
advancedmortars-1.12.2-1.6.20.jar		Baubles-1.12-1.5.2.jar				ChatFlow-1.4-7.jar			CustomMainMenu-MC1.12.2-2.0.8.jar	 EnchantmentDescriptions-1.12.2-1.1.8.jar  Guidebook-1.12.2-2.0.1.jar		    lostsouls-1.12-1.1.4.jar			 Morpheus-1.12-3.3.2.jar	    Reliquary-1.12.2-1.3.4.763.jar	     tellme-1.12.2-0.6.0.jar				       Waystones_1.12.2-4.0.43.jar
AdvancedRocketry-1.12.2-1.4.0-81.jar		BedBugs-1.12-1.0.1.jar				Chisel-MC1.12.2-0.2.0.31.jar		CustomOreGen-1.12-1.8.1.jar		 Enchiridion-1.12.2-3.3.3.jar		   ImmersiveEngineering-0.12-82.jar	    LunatriusCore-1.12.2-1.2.0.42-universal.jar  MTLib-3.0.5.jar		    ResourceLoader-MC1.12.1-1.5.3.jar	     Thaumcraft-1.12.2-6.1.BETA16.jar			       wizardry-0.8.5.jar
AppleCore-mc1.12.2-3.1.1.jar			BetterAdvancements-1.12.2-0.0.7.42.jar		chiselsandbits-14.17.jar		cyberware-1.12.2-0.2.10.12.jar		 EnderCore-1.12.2-0.5.30.jar		   InventoryTweaks-1.64-dev.jar		    MagicBees-1.12.2-3.1.10.jar			 NaturesCompass-1.12.2-1.5.1.jar    ReWIRED-1.0.3.jar			     thaumicperiphery-0.2.3.jar
AppleSkin-mc1.12-1.0.9.jar			BetterBuildersWands-1.12-0.11.1.24569d0d70.jar	ChunkPregeneratorV1.12-1.8.jar		CyclopsCore-1.12.2-0.11.6.jar		 EnderIO-1.12.2-5.0.26.jar		   IvToolkit-1.3.3-1.12.jar		    MagnumOpus-1.12.2-0.0.19.jar		 NetherEx-1.12-2.1.14.15.jar	    rockhounding_chemistry-1.12.2-3.13.jar   TheBetweenlands-3.3.8-universal.jar
appliedenergistics2-rv5-stable-11.jar		BetterFps-1.4.8.jar				CoFHCore-1.12.2-4.5.2.19-universal.jar	deepresonance-1.12-1.7.0-alpha.jar	 EnderZoo-1.12.1-1.4.0.49.jar		   jei_1.12.2-4.9.2.196.jar		    Mantle-1.12-1.3.2.24.jar			 NetherPortalFix_1.12.1-5.3.13.jar  rockhounding_core-1.12.2-3.10.jar	     theoneprobe-1.12-1.4.23-alpha.jar
Aroma1997Core-1.12.2-2.0.0.0.b150.jar		BetterQuesting-3.5.258.jar			CoFHWorld-1.12.2-1.2.0.5-universal.jar	DimensionalDoors-3.0.9-287.jar		 Erebus-1.0.22.jar			   jeibees-0.9.0.5-mc1.12.2.jar		    mcjtylib-1.12-3.0.0-alpha.jar		 NoFov-MC1.12-1.0.1.jar		    rockhounding_oretiers-1.12.2-3.06.jar    TipTheScales-1.12.2-1.0.1.jar
AromaBackup-1.12.2-2.1.1.3.b101.jar		BiblioCraft[v2.4.3][MC1.12.0].jar		ContentTweaker-1.12.2-4.5.0.jar		DrCyanosLootableBodies_1.12-2.4.0.jar	 EvilCraft-1.12.2-0.10.58.jar		   journeymap-1.12.2-5.5.2.jar		    Mekanism-1.12.2-9.4.10.345.jar		 plustic-6.5.2.0.jar		    rockycore-1.12.2-0.4.0.jar		     topaddons-1.12.2-1.7.0.jar
artisanworktables-1.12.2-1.19.0-SNAPSHOT.6.jar	BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar	Controlling-3.0.6.jar			DungeonTactics-1.12.2-0.14.2.jar	 extraalchemy-0.3.8.4-release.jar	   librarianlib-1.12.2-4.9.jar		    MekanismGenerators-1.12.2-9.4.10.345.jar	 PrimalCore-1.12.2-0.6.56.jar	    RoguelikeDungeons-1.12.2-1.8.0.jar	     TrashSlot_1.12.1-8.4.6.jar
astralsorcery-1.12.2-1.8.10.jar			blockcraftery-0.1.3.jar				CosmeticArmorReworked-1.12.2-v1.jar	DynamicSurroundings-1.12.2-3.4.9.13.jar  foamfix-0.9.9.1-1.12.2-anarchy.jar	   LibVulpes-1.12.2-0.2.8-31-universal.jar  memory_repo					 Quark-r1.4-123.jar		    rustic-1.0.5.jar			     twilightforest-1.12.2-3.7.424-universal.jar
athenaeum-1.12.2-1.14.0.jar			BloodMagic-1.12.2-2.2.12-97.jar			CraftingTweaks_1.12.2-8.1.9.jar		ElecCore-1.12.2-1.8.434.jar		 forestry_1.12.2-5.8.0.295.jar		   Login_Shield-1.12.2-3-g7c6e7ac.jar	    MetalChests-v1.2.2.g3d3d54b.jar		 QuickLeafDecay-MC1.12.1-1.2.4.jar  Stackie-1.12.2-1.6.0.48-universal.jar    ValkyrienWarfareRevamped-1.12.2-v0.9_alpha-full\ (1).jar
AutoRegLib-1.3-17.jar				Bookshelf-1.12.2-2.3.549.jar			CraftTweaker2-1.12-4.1.8.jar		ElectroblobsWizardry-4.1.1-MC1.12.2.jar  Forgelin-1.6.0.jar			   LootTweaker-1.12.2-0.0.7.jar		    modtweaker-4.0.12.jar			 RecurrentComplex-1.4.7.jar	    StandardExpansion-3.4.143.jar	     VanillaFix-1.0.5-43.jar
```

**Comment by belathus** [comment]
Yup, I travelled a short way away from my base and came back, and this is what the dioptra shows: https://i.imgur.com/IOAINz8.png

**Comment by Geethebluesky** [comment]
Ok, and in your forgeChunkLoading.cfg, you are 100% certain that

>  I:dormantChunkCacheSize=0

?

Because the default value in new configurations seems to be 400.

**Comment by belathus** [comment]
100% certain. https://github.com/belathus/Wanderlust-Renewed/blob/master/config/forgeChunkLoading.cfg#L32

I regularly sync my configs with Git, and the server automatically downloads those changes (doscarding changes the server may have made).

**Comment by Geethebluesky** [comment]
Okay. Well then, there's 2 possibilities I see and others will add more I'm sure.

1. dormantChunkCacheSize=0 is backfiring because Forge needs something higher than 0 to work properly. I have zero idea of whether or not it could be the case, but I've seen things behave bizzarely when set to extreme values before.

2. One of your mods is interfering with worldgen, chunk loading, etc. According to the discussion above with UnixRonin it seems it's Forge's cache that's the problem--doesn't mean other mods can't also contribute to the issue.

In both cases I suppose I'd load up a chunk generator, load up a very basic set of mods and check from there. I hope someone else comes in with more ideas...
