### ISSUE TITLE
Iron capped wand

### ISSUE THREAD

**Issue by JupiterYourHero** [Azanor/thaumcraft-beta#568]
I'm unable to craft this item

**Comment by EnderofGames** [comment]
There are no wands in Thaumcraft 6. 

Instead collect vis crystals somewhere from the overworld, then sleep. The game has instructions from there.

**Comment by androshalforc** [comment]
the mod download page at  https://minecraft.curseforge.com/projects/thaumcraft 
still lists creating an iron capped wand as part of getting started it should probably be updated
