### ISSUE TITLE
Infusion Crafting Doesnt seem to work

### ISSUE THREAD

**Issue by Wotzinator** [Azanor/thaumcraft-beta#571]
i tried to craft the parts of the thaumium fortress armor but wen i rightclick on the matrix (with the gaunlet) it wont do anything so i tested everthing in creative mode (like altering the shape of the structure) but nothing works so i belive somehow fusion crafting is broken

**Comment by Mike-U5** [comment]
Infusion Enchanting doesn't work either.
Infusion in it's entirety does not appear to work at all.

**Comment by Gammaboy45** [comment]
Same here. The biggest note I have is that I formed the alter with the items already on the pedestals, if that makes any difference.

**Comment by Wotzinator** [comment]
Gammaboy45 i tried it and it doesn't matter when you place the items on the pedestals

**Comment by Dragnier** [comment]
Duplicate of #518
