### ISSUE TITLE
[B11] Thaumcraft made all Vanilla Leaves opaque?

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-beta#572]
I noticed after I installed Thaumcraft that Vanilla Leaves and Spruce Leaves in my world were no longer transparent, I don't know if that's a coincidence, or some mod interaction problem.

![2018-04-29_14 15 19](https://user-images.githubusercontent.com/8670392/39406595-e9b07c1e-4bb8-11e8-9af8-ab30a7d6e99f.png)
![2018-04-29_14 15 15](https://user-images.githubusercontent.com/8670392/39406596-e9c78238-4bb8-11e8-9273-ee4a211be6fc.png)

Minecraft: 1.12.2
Forge: 2673
Thaumcraft: B11
Mods: [list.txt](https://github.com/Azanor/thaumcraft-beta/files/1958702/list.txt)

**Comment by UnixRonin** [comment]
Not seeing this myself, and I'm even using OptiFine as well.  Looks like something else is doing it.

**Comment by Wotzinator** [comment]
could it be because of the texture pack youre using

**Comment by Circine** [comment]
I'm getting this too with only Thaumcraft, Baubles, and Optifine in my mod list, with any custom resourcepack. Removing either TC or Optifine fixes it, or using vanilla textures with both. Getting rid of the leaf blockstates file also works.
