### ISSUE TITLE
essentia smelter reasearch broken

### ISSUE THREAD

**Issue by flamingram** [Azanor/thaumcraft-beta#575]
so when i got the essentia smeltry the vis crystals to unlock it are all blank so cant progress

**Comment by flamingram** [comment]
![2018-04-29_10 36 58](https://user-images.githubusercontent.com/34726796/39409295-4e9bedea-4b99-11e8-9f94-04001fd19c86.png)

**Comment by mmillstein** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/511 has a temporary fix for this
