### ISSUE TITLE
[B11]  Cannot fill glass phials from crucible

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#577]
To get started on infusion, I need a block of stone, a feather, and a phial of Aer.
Sone, check.  Feather, check.  Grab a stack of glass phials and toss two feathers into the crucible.  Crucible how has 10 Aer and 10 Volatus ...  and I can't get them out.  I cannot fill the phials.

**Comment by wamc2017** [comment]
I don't think the crucible is meant for filling essentia into glass phials, that's what the essentia smelting is for...

**Comment by UnixRonin** [comment]
Filling phials from the crucible has always worked before, unless I am totally misremembering.  If that's the case, it would be impossible to get arcane bellows until after essentia smelting.

**Comment by UnixRonin** [comment]
Well, maybe I'm just completely misremembering it then.  I _**thought**_ it used to work...

**Comment by Spearkiller** [comment]
I'm 90% sure you used to have an Arcane Alembic next to the crucible that would hold leftover essentia from the crucible and you'd right click on that -- now we have the essentia smeltery. So maybe that's what you're thinking of?

You can right click with a quartz sliver and you'll get a crystal shard with 1 of whatever aspect, in case you didn't know :)

**Comment by UnixRonin** [comment]
Oh, sure, I know about shards.  And their 50% flux rate.

**Comment by AnrDaemon** [comment]
You're not supposed to fill phials from crucible, no.

**Comment by UnixRonin** [comment]
You try it and tell me.  :)  Sure looks to me like the other point of essentia went to flux...

**Comment by Geethebluesky** [comment]
@Spearkiller where did you discover that in the progression? I'm not sure if I missed it or if it just hasn't been shown yet, but I was also trying to fill phials from the crucible and wondering why it wasn't working. It feels like it should work even though it was never a mechanism before.

Maybe this should be a separate suggestion, where if you try it a msg pops up saying "Hmmm, something about this doesn't feel quite right."

**Comment by wamc2017** [comment]
@Geethebluesky,

should be first stage of Base Alchemy:

Essentia crystals should be fairly easy to craft. All I need to do is break down a quartz crystal into smaller shards to act as a growth medium.
Simply dipping a shard into the crucible should soak up some of the essentia it contains and cause the crystal to grow.
This won't be a particularly efficient way of doing things - it will probably cost at least twice the essentia that the crystal will end up containing and there is the net loss of quartz which is not always the easiest thing to find.

https://github.com/Azanor/thaumcraft-beta/blob/master/en_US.lang#L1318

**Comment by Geethebluesky** [comment]
Well that explains it, I don't have Base Alchemy researched yet. It's kind of strange (to me at least) that some theorycrafting pages require things you just aren't able to craft yet, but they're still shown with no note about it...

**Comment by Azanor** [comment]
Filling phials from the crucible has never been a thing, sorry.
