### ISSUE TITLE
Items stop rendering on Pedestals

### ISSUE THREAD

**Issue by Gammaboy45** [Azanor/thaumcraft-beta#579]
On a LAN server, using Arcane Pedestals made items stop rendering after a while. I did not test this on a singleplayer world and do not know the cause; all I know is that it terrified me at first

**Comment by AnrDaemon** [comment]
Same happens in singleplayer. Items pop in and out of rendering seemingly at random.

**Comment by MalkContent** [comment]
Still happens whenever the chunk is unloaded and you load it again. strangely enough this does not happen when you play singleplayer and the chunk is loaded when you load the world. It's weird.
