### ISSUE TITLE
B11 jei 

### ISSUE THREAD

**Issue by tyler489** [Azanor/thaumcraft-beta#581]
Pretty sure jei is showing internal items https://gyazo.com/bad4d66de49fca561f87d01ef6e0ce1b that are just used for the book. Also fluid.fluxgoo is mising lang it seems

**Comment by Azanor** [comment]
Quite possible, but not really a bug or anything I can do much about

**Comment by Azanor** [comment]
Well, I can fix the lang issue at least :p
