### ISSUE TITLE
[B11] Thaumometer is opaque

### ISSUE THREAD

**Issue by Barwyn** [Azanor/thaumcraft-beta#583]
When using the Thaumometer, it is not see through.

![](https://i.imgur.com/g3eiUqu.jpg)

![](https://i.imgur.com/gNSxXil.jpg)

**Comment by AnrDaemon** [comment]
What's your system specs, what other mods are installed?

**Comment by Thaumatarge** [comment]
I can see shaders, the shaders are most likely causing this, try disabling your shaders.

**Comment by Azanor** [comment]
Yup, nothing I can do about that unfortunately. The shader mod is interfering with the transparency.
