### ISSUE TITLE
mossy stone not working

### ISSUE THREAD

**Issue by flamingram** [Azanor/thaumcraft-beta#584]
so i got some mossy stone but its not working i really need to finish to get everfull urn its tuck on hedge alchemy

**Comment by Alaberti** [comment]
https://minecraft.gamepedia.com/Moss_Stone#Crafting_ingredient

**Comment by flamingram** [comment]
what is teh comman to cheat it in because ive done /tc research username and hedge_alechmy still wotn cheat in

**Comment by wamc2017** [comment]
Dupe of #510 #548.

The research name is HEDGEALCHEMY, you could list the names with /tc research list...

**Comment by AnrDaemon** [comment]
#511 has a temp. fix.
