### ISSUE TITLE
[Suggestion] Make crucial/fun things less exploration luck heavy (minor spoilers)

### ISSUE THREAD

**Issue by Mii1128** [Azanor/thaumcraft-beta#585]
Sorry for rant. I love this mod. but this makes me a bit angry.

Ok here is my point. Many crucial things require specific rare resources to complete (see old Gauntlet recipe with rabbit skin). Main Point for me: Golem Seal Harvest. I searched 3+hours in SSP to find a jungle for cocoa beans. I ofter play MONTHS in a world without finding a single jungle (or melons/pumpkins/carrots/potatoes).

Please make crucial/fun/(or any) things not depend on fiding specific (rare) biomes, blocks, mobs etc.
Ideas:
Bring back boss mobs and add this stuff to the loot bags.
Golemancy can be unlocked with either redstone or a small clay golem you can craft earlier.
Seal: Harvest only needs normal seeds. (or make other seeds craftable (organic alchemy?))
Auromancy Projectile: Should not need llamas.
I'm sure there are more.

**Comment by AnrDaemon** [comment]
Villager golems are rather common, if you don't sit in your hole.
But in general, I agree with an observation.

**Comment by Geethebluesky** [comment]
I would agree for vanilla MC. Regarding cocoa beans specifically (and probably other items, but this one is obvious), Biomes O'Plenty is used, they are common in any tropical biome, which are common with BoP default settings. I know balancing for every mod out there is a monumental task but maybe the community can help.

**Comment by CTH999** [comment]
I think he Is addin in a few boss mobs, I know the eldritch is still a wip... mut, I see your point. It's not really a rand (ok, _technically_ it is) It is a good point!

**Comment by UnixRonin** [comment]
I will note here that the Nature's Compass mod adds an item to reliably point to the nearest instance of any specified biome.

(Of course, that biome may be a Minecraft week's travel away on foot...)

**Comment by CTH999** [comment]
True, true

**Comment by 00jaydon** [comment]
Possibly make this a config option or something like that, as certain people like me completely love the system that's in place right now. Especially the hours I spent trying to figure out what the hell a 'sticky projectile' was, and then trying to find a Llama and get it to spit on me.

**Comment by louisereay** [comment]
I agree that it can be troublesome to find some items.

Golems I don't really agree on though - both Iron and Snow golems are vanilla craftable with easy to obtain components. Finding llamas in my current world was quite troublesome though :)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#387
