### ISSUE TITLE
Server crash when attacking crimson knight with yoyo

### ISSUE THREAD

**Issue by randomlypickedname** [Azanor/thaumcraft-beta#591]
I'm not sure if this would be you or Jozufozu, but here you go: https://gist.github.com/randomlypickedname/176d3e75a19c7714977e8c7d4c51fd36

**Comment by randomlypickedname** [comment]
Occurs with Spiky too: https://gist.github.com/randomlypickedname/9836d7c0f6021bd8a4c0de970c79906b

**Comment by UnixRonin** [comment]
It's not what you attack with that matters.  It's that you kill a Crimson Knight of Cleric and it tries to drop something.  As far as I have been able to determine, if there's no drop, there's no crash.
