### ISSUE TITLE
Unable to craft a Golem.

### ISSUE THREAD

**Issue by XMineReaperX** [Azanor/thaumcraft-beta#594]
![2018-04-30_15 51 39](https://user-images.githubusercontent.com/38868966/39450790-20eaf7fc-4c92-11e8-962c-371f15d517e8.png)

I had all the makings to construct said golem and proper amount of essentia required and it allowed me to press the Craft button, but did not construct said golem once pressed.

**Comment by UnixRonin** [comment]
Most likely a duplicate of #538.
