### ISSUE TITLE
Suggestion: Change the location of the mini pictures in to the left

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#596]
![default](https://user-images.githubusercontent.com/37004902/39455129-53b2eef4-4cf8-11e8-878d-d4734cc24e1f.jpg)

**Comment by Mike-U5** [comment]
Perhaps make it a config option.

**Comment by CurePindal** [comment]
Great idea! Like it!

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#385
