### ISSUE TITLE
Focus Suggestion 

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#6]
I really love the  new focus crafting system, it opens so many doors for customization, and really makes you feel more magical and powerful. One suggestion I would make is to have an upgrade component option that lets you charge the focus in your hand before firing, costing extra vis in exchange for more power once cast. Like if your fire projectile can kill a pig in two shots and each shot costs 1 vis, or you can charge up the blast and kill the pig in one shot for a vis cost of 2.33 or 2.5. 

Maybe let the charge scale for multiple levels and consume increasing amounts of vis. A fireball not charged is weaker but costs 1 vis, And fireball at the third level of charging is much stronger but costs 3-4 vis.

**Comment by Azanor** [comment]
Hmmm, interesting suggestion. Not sure if it is easily doable, but worth looking into.
