### ISSUE TITLE
[B11, modded] Colored nitor recipe displaying inconsistently

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#603]
This is a recipe display issue involving colored nitor, available from the Base Alchemy tab.

I'm playing Thaumcraft with Biomes O'Plenty installed but I'm not sure if it's the problem.

- On the tabbed edge of the Base Alchemy page, the item cycles through all possible colors of nitor. (That tells me the recipe lets you create all colors, not just one.)
- While that's going on, the result item at the top [always displays](https://i.imgur.com/TJ3VVWb.png) "White nitor".
- The top left item cycles between bonemeal and white dye **only**.
- The top center item cycles through [all available](https://i.imgur.com/jUvrhbS.png) colors of nitor.

I'm expecting the top left grid item and result items to cycle through all colors as well but they don't.

If it matters, Biomes O'Plenty happens to add four, "blue dye" to avoid using lapis lazuli, "brown dye" to replace cocoa beans, "black dye" to replace ink, and "white dye" to replace bonemeal. Not sure if this is what's messing up the recipe display since the top left grid item it only cycles between "white dye" and "bonemeal".

**Comment by Azanor** [comment]
There are arrows on the bottom of the recipe page that allows you to cycle through the various different recipes - there is one for each dye type. A dye with any color of nitor will recolor it - that is why the top middle nitor ingredient is cycling through the different colors.
