### ISSUE TITLE
Urn/Crate Loot Tables

### ISSUE THREAD

**Issue by Gammaboy45** [Azanor/thaumcraft-beta#611]
More of a possible oversight than a bug, but I found elytra in an uncommon urn in a mound. Probably shouldn't find them there >.>

**Comment by Gammaboy45** [comment]
Further note, however: after testing with 134 urns in a seperate world, the most I ran into was a dulled Primordial Nodule. I guess my luck was extreme in that one case.

**Comment by Azanor** [comment]
I did not add the elytra to their loot tables, but since the urns and crates tap into the dungeon chest loot tables so I'm guessing elytra is in those - just extremely rare.

**Comment by Azanor** [comment]
Actually, turns out I do add it to the loot tables by hand. Doh.

**Comment by Gammaboy45** [comment]
Must say, when paired with a grapple they make for the greatest form of transportation
