### ISSUE TITLE
[Suggestion] Make all displays affected by B:dialBottom=true, not just caster's gauntlet

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#613]
I like the following configuration because with mods like Lycanite, Harvestcraft etc. and anything that adds a lot of potion/status effects, there's always text in the top left of the screen.

    # Set to true to have the wand dial display in the bottom left instead of the top left.
    B:dialBottom=true

It would be nice to have **all** meters relocated to the bottom left following that option, not just the caster's gauntlet; the Thaumometer also overlaps, same for the Sanity checker, etc.

(I'm also open to _any other_ mods that can move the status effect textboxes to the right a bit, instead, if you guys have suggestions for that. Don't know of any.)

**Comment by xenxero1** [comment]
Alternatively/additionally, Is there any reason we don't see more mods use the Ars Magica system of /am2uicfg ? I love being able to customize my UI, especially when I have a ton of other mods that might have conflicting overlays. Not to mention, this could make modpacks a lot smoother by giving modpack curators the ability to easily adjust their overlays to have a cleaner default setup.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#384
