### ISSUE TITLE
Entity Pech Causing Exception Ticking World Crash

### ISSUE THREAD

**Issue by LordXemnas23** [Azanor/thaumcraft-beta#616]
Whenever I load in a chunk with a Pech, the server crashes.  This is the starting line of the crash report: java.lang.NoClassDefFoundError: Could not initialize class thaumcraft.common.entities.monster.EntityPech

**Comment by LordXemnas23** [comment]
Already turned it off, still new to GitHub.  Thank you for replying though.

**Comment by Azanor** [comment]
Are you using the hats mod?

**Comment by LordXemnas23** [comment]
Yes, I am using the hats mod.

**Comment by stclaus4** [comment]
https://pastebin.com/Aff8THAq
another sighting
