### ISSUE TITLE
[B11] Essentia Buffer doesn't carry suction?

### ISSUE THREAD

**Issue by Lukas45** [Azanor/thaumcraft-beta#619]
This may be intended or not, never fully understood how the suction worked.

Any Jar hooked up to a Essentia Buffer doesn't request Essentia, neither will chains of Essentia Buffers, with normal Pipes from the buffers to the Jars

**Comment by Azanor** [comment]
You can set the sides of the buffer to have or not have suction. It only has a suction of 1 however. Buffers are mostly intended to be connected directly to essentia output blocks like the centrifuge.
