### ISSUE TITLE
Can't swap focuses in pouch when it is equipped as a bauble

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#62]
Just like the title says. Doesn't matter what hand the gauntlet is held in.

**Comment by Azanor** [comment]
It works perfectly fine for me. Are you sure it is equipped in the belt slot and not in the offhand slot next to it?

**Comment by fingersome** [comment]
Oh, now it works fine. Maybe I was just being dumb.

**Comment by Azanor** [comment]
Cool, I'll close this for now, but keep an eye on it and if it happens again please reopen this.
