### ISSUE TITLE
Grappler graphics issues

### ISSUE THREAD

**Issue by Boundarybreaker** [Azanor/thaumcraft-beta#621]
there are two main issues with the arcane grappler at the moment, one that seems like a bug and one that seems like a missing feature.

The bug is that, at some angles, the grapple line won't render. I haven't found a 100% reliable way to reproduce, but it most commonly happens around northeast, northwest, southeast, and southwest. [Here's](https://gfycat.com/DistantScentedBarasingha) a gif of it both working and not working.

The missing feature is that there's no HUD element for the vis charge of the grapple like there is with the casting gauntlet. Is that something the grappler is planned to have?

**Comment by Gammaboy45** [comment]
The Gauntlet charges directly from the atmosphere without use of a vis stone or any other vis recharging system other than itself, which may be why it requires an overlay; it would be nice, however, to view charge on Traveler boots and Grapples without opening the inventory.
