### ISSUE TITLE
[B12] Random crashes during Infusion

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#624]
Hi,

currently testing to infuse some items with runic shielding, everything is fine so far, but sometimes it crashes randomly. (had 4 of these crashes now, so kinda reproducable)

https://gist.github.com/wamc2017/133d17b1ece3fb175d0cc45b47adc1bf

Modlist:
https://gist.github.com/wamc2017/b7b87e8e23e1b3e6ed957182ea16e383

Edit: I think it happens when I'm looking at the infusion matrix with goggles on, because the game crashed again after restarting when looking at the matrix.
Edit2: It also crashes without goggles on...

Thanks for looking into it. :)

Best regards
wamc2017

**Comment by the-realest-stu** [comment]
This seems to be due to the altar setting the inventory of a pedestal to null instead of ItemStack.EMPTY in TileInfusionMatrix line 535. It occurs when an item is removed from that altar due to instability.

**Comment by wamc2017** [comment]
No crashes in beta 13 anymore. Close...
