### ISSUE TITLE
[B12] Thaumatorium cannot craft alt recipes for Vis Crystals

### ISSUE THREAD

**Issue by Chopter** [Azanor/thaumcraft-beta#625]
Whenever i go to attempt to craft one of the other vis shard types that isnt the first vis type shown, for me it shows tenebre at default, it will be unable to craft it, opun opening and closing the gui it will show the tenebre shard again, show its requested that essentia type, and not craft

**Comment by Azanor** [comment]
Is this with the thaumatorium?

**Comment by Chopter** [comment]
Yes, specifically with Thaumatorium
