### ISSUE TITLE
Can't create nitor

### ISSUE THREAD

**Issue by FrankieRozsa1** [Azanor/thaumcraft-beta#626]
I Have tried so many times to make nitor now and with the exact recipe and everything. I use either lava, nettherack and flint and steel, or a magma block to heat the crucible (which I transformed from a cauldron with salis mundus) then I drop exactly 2 torches for 10 lux, 1 coal for 10 ignis and 10 hand thing, and then drop a glowstone, and instead the glowstone just adds it into the cauldron and nothing happens.

I have checked the recipe many times and it says I only need those 3, (its hard as well since every time I click on a recipe from the thaumonomicon my game crashes) possible bug.
what am I doing wrong to make a nitor? I have also discovered torches, coal and glowstone with my thaummometer

**Comment by FrankieRozsa1** [comment]
I guess I could try the update 1 week ago version from 9minecraft, but will it mess up everything if I use the new version?

**Comment by xenxero1** [comment]
That's minecraft version. You need to find the thaumcraft mod file, it should tell you in the name what beta version it is. You can also check in-client if you can view mod lists. I can almost guarantee you that you're using Beta10 because I had the same issue. Don't use 9minecraft, just download it from the official Curseforge page found here; https://minecraft.curseforge.com/projects/thaumcraft

**Comment by CTRiastad** [comment]
Do not download anything 9minecraft, Use the curse download page. Downloading the recent update (from earlier today) -Beta12- should help.

**Comment by FrankieRozsa1** [comment]
omg you absolute legends, Its fixed, thank you for the tip I just kinda downloaded every mod from random websites. you cant believe how long i spent trying to fix it thank you haha

**Comment by xenxero1** [comment]
In the future, I would recommend only using curseforge or the Twitch/Curse launcher to download mods. As I said before, most of these unofficial sites (9minecraft in particular) are full of faulty and malware ridden downloads.
