### ISSUE TITLE
[1.12.2] The Worktable GUI Has To Be Reopened To See The Result

### ISSUE THREAD

**Issue by EmosewaPixel** [Azanor/thaumcraft-beta#627]
You sometimes need to reopen the Worktable's GUI to see the recipe output. It's happened to me on all 1.12.2 versions.
![image](https://user-images.githubusercontent.com/25333164/39637661-fc1cd88e-4fc3-11e8-921c-a30eebea338a.png)
![image](https://user-images.githubusercontent.com/25333164/39637662-ff7be830-4fc3-11e8-80a7-1466b6191c10.png)

**Comment by EmosewaPixel** [comment]
Hmmm... it might be FastWorkbench. I'll have to test it though.

**Comment by Azanor** [comment]
Was that the cause?

**Comment by EmosewaPixel** [comment]
I haven't really gotten the time to test that recently.

**Comment by drinfernoo** [comment]
ItemZoom is showing the enlarged item on the left, and I'm not sure why the white overlay on the output slot, but I have it too (only in the Arcane Workbench).
