### ISSUE TITLE
Thaumcraft Automatic crossbow crashes server sometimes

### ISSUE THREAD

**Issue by FrankieRozsa1** [Azanor/thaumcraft-beta#629]
My minecraft server crashed after the automated crossbow shot 2 zombies twice. here is the crash report:
https://imgur.com/a/d4ApNVT

we tried it again but it didn't crash when it shot me and killed me. but we didnt recreate it more times, so im not sure why it crashed or if it was the fault of another mod.

**Comment by Azanor** [comment]
Thats cool - it did show enough for me to track down the bug.

**Comment by FrankieRozsa1** [comment]
Yeah sorry I could find the best way to send the file in So i just screenshotted the important bits. thanks so much for the help though
