### ISSUE TITLE
[Beta 13] Unable to Complete Essentia Smelting

### ISSUE THREAD

**Issue by TechnoMysterio** [Azanor/thaumcraft-beta#631]
When I try to complete the first part of the "Essentia Smelting", I run into strange behaviour in the way the game tries to detect the six different primal essentia crystals, which ultimately results in me being unable to complete the research.

Using Creative mode (for testing the mod out for bugs and such), I complete the research tree up to the point where I reach Essentia Smelting part 1. I spawn in the six crystals necessary to complete the research, open up the book page, and I find the game doesn't detect some of the crystals in my hotbar:

![2018-05-04_19 37 35](https://user-images.githubusercontent.com/5113920/39646232-a2ef7384-4fd2-11e8-95ef-dd41d2d79f73.png)
Note the crystals in my hotbar.

After this I can try and run through the items in my hotbar, pick them up and move them around, click on the object icons in the book entry, and sometimes, with some luck, the game will detect that the crystals are there:

![2018-05-04_19 39 38](https://user-images.githubusercontent.com/5113920/39646313-e7005e26-4fd2-11e8-8d5f-61b96d219c87.png)

However, after this I click on "Complete Research", and the book gets stuck saying "Completing..." and never actually does so, no matter how many times I click out of the book entry and try again, or if I try to reload the world/game, I can't complete the research.

![2018-05-04_19 40 10](https://user-images.githubusercontent.com/5113920/39646334-f9317f4e-4fd2-11e8-8629-f81d72f37990.png)

This behaviour is very inconsistent. For instance, I can rarely complete the first part, but then I get stuck on the second part, or sometimes the book won't detect the crystals properly no matter what I do.

**Comment by jdude360** [comment]
I am having this issue as well. using B12

**Comment by 5kedone** [comment]
yep had that issue too it happens with a few of the researches , this is what i was talking about with the essentia tubes as well @Azanor

**Comment by Nenacu** [comment]
I've a potential workaround for this issue. At least, it's worked for me 2/2 times so without further testing I really can't say much, but it might work until a fix is implemented. Get all of the vis crystals needed to finish the entry in the book into your inventory, then close out of MC entirely. Reopen, open your world, immediately open your book, and the entry should populate.

**Comment by TechnoMysterio** [comment]
Well, the fact that the book struggles to detect the crystals is only part of the problem, the main issue is that when the book eventually does detect that all the crystals are there, the research doesn't complete itself when I click "Complete Research", instead just getting stuck saying "Completing...". I noticed that problem happening on a few other research pages as well, although I can't remember which ones.

**Comment by TechnoMysterio** [comment]
This is still happening on Beta 13, so I've updated the title, also making sure it better reflects the issue at hand. @Azanor

**Comment by wamc2017** [comment]
Hmm, maybe I'm wrong, but do you guys have AstralSorcery installed and if so tried removing it for a test?

**Comment by TechnoMysterio** [comment]
You're onto something, I took Astral Sorcery out and the research completed with no problems at all. It even worked fine with the second part of the research, with the larger array of different essentia crystals. Perhaps Astral Sorcery is doing something to the essentia crystals so that the game can't read them correctly?

**Comment by 5kedone** [comment]
How did you figure that one out I'm trying that today if it's the case , I to have astral installed lol , who does the issue lay with as in should we report to there team ?

**Comment by wamc2017** [comment]
Hmm, everything was working fine with only Thaumcraft installed, that's why I tried with one of my testmodpacks which got around 70 mods. I splitted the modlist into half, tried it ingame, splitted the modlist again... until only one mod was left, which was in this case Astral Sorcery.

I don't know the root of the issue, it's maybe better to wait for an answer by Azanor, before contacting the AS devs...

**Comment by TechnoMysterio** [comment]
Well the problem is with Thaumcraft's research, so as wamc2017 said it'd be best to wait for Azanor to have a look over this (when he gets the chance) to determine whether the problem is on Thaumcraft's side or Astral Sorcery's.

**Comment by TechnoMysterio** [comment]
Astral Sorcery just got a bugfixing update, so I decided to see if it's buggy interaction with Thaumcraft hadn't resolved itself. From initial testing of both "Essentia Smeltery" and "Essentia Tubes" it seems it has, but it would be good if others could also test Thaumonomicon research on their end and post back here to see if I should close this issue or not.

**Comment by Nenacu** [comment]
Cheers to that Azanor. I've noted it's not just the book that seems to have the issue, but the infusion crafting setup as well. As with the workaround I explained in my last post, if an infusion recipe isn't working for somebody, set up the table and make sure you have your essence values. Quit out of the game, then go back in and immediately tap the matrix. Everything should flow.

**Comment by SteveGodwin** [comment]
I was seeing this problem on Beta 13 and can confirm that removing Astral Sorcery made the problem go away for me. Interestingly ProjectE was seeing a similar problem where duplicate items were appearing in the Transmutation Table. Those problems also went away when I removed Astral Sorcery.

**Comment by SteveGodwin** [comment]
I was seeing this problem but have know been able to complete this stage with Thaumcraft-1.12.2-6.1.BETA13 and AstralSorcery-1.12.2-1.8.10 installed. (Can't guarantee problem has gone away, I may have just been very lucky). If I disable AstralSorcery I can always complete the stage.

Interestingly I have been seeing a similar problem with ProjectE, where duplicate entries have been sometimes appearing in the Transmutation Table (see https://github.com/sinkillerj/ProjectE/issues/1642 ). This feels like ProjectE is not recognising two items as being of the same type. Again if I disable AstralSorcery the problem goes away.

**Comment by marker2000** [comment]
Should i change the map when i renew B11 to B14 @Azanor
