### ISSUE TITLE
[B12] Torches have bestia instead of lux

### ISSUE THREAD

**Issue by Sumguy62** [Azanor/thaumcraft-beta#632]
Instead of one lux, torches have one bestia essence. This seems like a bug.

**Comment by xenxero1** [comment]
In B10, torches have 5 lux instead of bestia. Do you have any other mods installed?

**Comment by Azanor** [comment]
My guess is you have a mod that adds an alternate torch to replace the vanilla one.

**Comment by Sumguy62** [comment]
Could it be forge multipart cbe? I know I can place multiple torches in the same block, which isn't vanilla.
