### ISSUE TITLE
[B12] Eldritch Crab is in 2 places at once and frozen

### ISSUE THREAD

**Issue by Gravityowl** [Azanor/thaumcraft-beta#636]
When an eldritch crab gets on your head it instead freezes in place and continues to deal damage no matter where you are. trying to attack above you does nothing, however you can hit the frozen one. if a projectile or something else travels above you head then it will deal damage to the frozen one despite there being nothing visible above you

**Comment by Geethebluesky** [comment]
Head.... crabs....?

I love this mod even more now and I have not encountered that yet.
