### ISSUE TITLE
[B12] Infusion Pedestal Ghost Items

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-beta#637]
During infusion, whenever an item is either knocked off or destroyed due to infusion instability, the item appears to still be on the pedestal.  A item that is knocked off is still thrown to the ground.  In either case, the pedestal works as normal, but during the removal/replacement process, it appears as though the item remains on the pedestal the entire time.  In another case before infusion, I placed some items on the pedestals, and had a friend come watch the infusion, however I had to replace them because  he couldn't see them, and I found out after the infusion wouldn't start that the items were not actually there, even though they appeared to be.

I'm using the All The Mods 3 modpack, and obviously playing on a locally hosted server, so I'm not sure how that plays into the equation.  These issues aren't critical, but I thought I might point them out.

Also, sometimes the altar takes several seconds to detect aspects before drawing them, but I've sometimes seen that happen once or twice over the years of thaumcraft versions, so I imagine it doesn't happen too often to be important.

**Comment by wamc2017** [comment]
Same thing with only Thaumcraft and JEI installed, quiting the world and relog seems to fix the ghost rendered items on the pedestials.
