### ISSUE TITLE
Node Properties - updated

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#64]
_Aura nodes currently serve no real purpose. But they also just aren't very fun.
I agree that in their current state, they're not really worth the effort to develop when they really add nothing tangible to the mod. My idea is to think of them less like a portal to another place as in previous incarnations and more like a knot of flux. I imagine them as being a hairball forged from loose magic and aspects. When you think of them like that, there's more potential for weird interactions and fun effects they might create in the world. Nodes would spawn naturally in certain biomes or under certain conditions - but they could also perhaps be created by careless buildup of flux_

Aer		- Shocks nearby entities (like a shock focus) Converts blocks to air.
Terra	- Shoves nearby entities away and damages them. Converts blocks to stone.
Ignis	- Ignites nearby entities (like a fire focus). Converts blocks to lava.
Aqua	- Fills empty containers with water. Converts blocks to water. 
Ordo	- Smoothes things out. Cobble becomes stone, nearby ores become quartz.
Perditio	- Breaks things down. Stone becomes gravel, gravel becomes sand, bricks become cracked etc.
Vacuous	- Sucks in all entities and damages them with suffocation, destroys nearby blocks.
Lux		- Gives off more light than usual & spawns glimmers like the arcane lamp
Motus	- Time speeds up around this node. Entities move faster, growth ticks are faster, etc.
Sensus	- Sounds are louder, colours are brighter  / sounds are muted & colours are desaturated.
Gelum	- Slowly converts biome to a cold biome. Spawns snow. (Taiga, frozen plains etc)
Vitreus	- Nearby living entities that die drop essentia crystals.
Metallum	- Drops a random assortment of metallic items (nuggets, bars, native clusters and rare earths).
Victus	- Heals nearby entities with a weak regeneration effect (like the hot spring water from BoP).
Mortus	- Kills nearby living entities. 
Potentia	- Increases the speed and efficiency of nearby infusions.
Alkimia	- Grants a random potion effect to nearby entities.
Vitium	- Produces flux.
Alienis	- Randomly teleports nearby entities around.
Volatus	- Causes entities to fall slowly.
Herba	- Turns dirt to grass, causes grass to sprout into tall grass, places flowers / saplings.
Fabrico	- Crafts items in nearby arcane crafting tables. Draws items from adjacent chests.
Machina	- Increases the efficiency of nearby machines.
Vinculum	- Time slows down around this node. Entities move slower, growth ticks are slower, etc.
Spiritus	- Nearby players that die can walk around as spectators if they stay nearby the node.
Aversio	- Damages nearby entities as if hit with an iron sword. Breaks nearby cobwebs and grass.
Exanimis	- Consumes living creatures, barfs out rotten flesh, brains, bones, and twisted curiosities.
Humanus	- Spawns villagers.
Bestia	- Spawns animals.
Auram	- Slowly removes flux from the aura.
Cognitio	- Proximity gives random observations. Can be used as a research aid.
Permutatio	- Randomly sheds and gains other aspects, including the permutatio aspect.
Praecantatio	- Grants a large vis discount to nearby players.
Instrumentum	- Slolwy repairs tools and armor of nearby players.
Tenebrae		- Darkens the area around it. Places mycelium and mushrooms.
Praemunio	- Grants Absorption to nearby entities.
Desiderium	- Turns nearby metal ore into gold ore. Turns nearby coal into diamonds.

Fading	- Effect is less potent than normal.
Bright	- Effect is more potent than normal.

**Comment by Treya7** [comment]
This is a very interesting idea but how would you move the nodes around the world to get the effects you want where you want them? What would be the radius of these effects? That’s a lot of work to put in right now for a mod that’s being built from scratch.

**Comment by fingersome** [comment]
I'm not suggesting this is high on the priority list - just as food for thought for if nodes do make a comeback.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#167
