### ISSUE TITLE
Automated Alchemy Can Duplicate Glowstone But Not Create Nitor

### ISSUE THREAD

**Issue by EvilOtter** [Azanor/thaumcraft-beta#648]
GUI interface for Thaumcraft-1.12.2-6.1.BETA13 Automated Alchemy will display Nitor but duplicate glowstone dust. Attempting to remove ingredients, scroll through products, or any other methods will continue to duplicate glowstone dust regardless.

**Comment by Azanor** [comment]
I can't duplicate this at all - I can easily switch between the two types of crafting and it produces the right output every time.
