### ISSUE TITLE
[B13] Crash while tessellating block model

### ISSUE THREAD

**Issue by LWnellA** [Azanor/thaumcraft-beta#649]
When I try to play Thaumcraft B13, within 1~2 minuets, the game crashes with a 'game crashed whilst tessellating block model' error
[crash-2018-05-06_13.51.08-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1977346/crash-2018-05-06_13.51.08-client.txt)
[crash-2018-05-06_13.36.33-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1977347/crash-2018-05-06_13.36.33-client.txt)

**Comment by Azanor** [comment]
This doesn't seem to be TC related - the crash is happening while trying to render vanilla dark oak leaves.

**Comment by LWnellA** [comment]
Huh, that is weird. 
I guess I just got really unlucky and only got dark oak in the words I made without thaumcraft then?
