### ISSUE TITLE
Blank Lesser Focus not crafting and blocking research

### ISSUE THREAD

**Issue by Filvandrel** [Azanor/thaumcraft-beta#650]
Hello!

I have a problem with Blank Lesser Focus crafting. I put the required aspects in the crucible (5 auram, 10 praecantatio, 20 vitreus) and when I throw the ordo vis crystal to the Crucible, it does not craft, just adds 1 ordo as another aspect, hence locking the progression in the Auramancy chapter.

**Comment by wamc2017** [comment]
Which version are you using?

**Comment by Filvandrel** [comment]
1.12.2-6.1.BETA13

**Comment by Azanor** [comment]
If you press F3 + H to enable advanced tooltips how many NBT tags are shown to be on the vis crystal?

**Comment by Mystara0001** [comment]
I actually wonder if this was caused because of the dissipation of aspects over time. Meaning if you don't throw the ordo crystal into the crucible fast enough, you may have lost one of the other aspects because it escaped as flux. So when you tossed that crystal in, it just added ordo.

**Comment by Filvandrel** [comment]
No, this was not the cause. I've been playing with Thaumcraft since Thaumcraft 1 on Minecraft 1.2.5, I know about this mechanic. But I've used Goggles of Revealing to monitor that, I did threw them pretty quickly, and I've also used some extra crystals of those 3 aspects to prevent that. But it seems that the crucible didn't want to register the crafting process after dropping the ordo crystal for some reason. And I have no idea why, cause I could not replicate the bug again. Besides, it only happened with the Lesser Focus, every other item crafted with the crucible worked fine.

**Comment by Mijithemidge** [comment]
I can say this is happening to me too! I try to make the focus, but it just adds in Ordo to the crucible. I have been monitoring it. It's really frustrating as the aspects can be a pain to get! The version I have is 1.12.2-6.1.BETA13. Watching the crucible with my goggles shows that all the amounts are in proper numbers, but it won't create the focus, no matter how many ordo crystals I throw in.

**Comment by Mijithemidge** [comment]
I tried entering creative mode and just dumping in the aspect crystals and the ordo crystals, and still nothing was made. Also, when I gave myself a blank focus and then entered survival again, it didn't recognize it.

**Comment by ConnCraft** [comment]
Same bug in 6.1Beta25.

**Comment by Macrophage001** [comment]
Receiving this same bug in 6.1Beta26

**Comment by ObsidianFlight** [comment]
i got same problem

**Comment by Wgairborne** [comment]
same problem

**Comment by Wgairborne** [comment]
this softlocks the whole auromancy tree up, what can you do to fix it?

**Comment by LastNarrator** [comment]
Same bug in the 1.12.2 pack on technic, made 1 lesser focus and then it refused to work thereafter (this is causing me to release a ton of essence as flux)
