### ISSUE TITLE
Unable to alchemy Brass ingots

### ISSUE THREAD

**Issue by Zang518** [Azanor/thaumcraft-beta#651]
TC Ver. TC1.12.2-6.1BETA10
Forge 14.23.3.2673

I know I'm a few versions behind, but when adding 5 instrumentum to a bubbling crucible then throwing in a iron ingot, it adds 15 metallum instead of creating a brass ingot. I have gone into a cheat world, gave all research to myself when I attempted this. Currently unable to craft a brass ingot because the iron is adding metallum and not  alchemy'ing the brass ingot. Is there something I'm doing wrong? 

This is what the recipe shows in the thaumonicon and in JEI
![2018-05-06_06 48 48](https://user-images.githubusercontent.com/6557762/39672523-9692a58e-50f9-11e8-9258-0e6591557860.png)

With 5 Instrumentum
![2018-05-06_06 42 55](https://user-images.githubusercontent.com/6557762/39672487-e9ba42ae-50f8-11e8-9886-9544865a3bcc.png)
and after throwing an iron ingot 
![2018-05-06_06 42 56](https://user-images.githubusercontent.com/6557762/39672492-f47ee442-50f8-11e8-98ef-35f84195968a.png)

**Comment by wamc2017** [comment]
Update to Beta 13.

**Comment by Zang518** [comment]
Thanks. Didn't check the change log. Will do that before posting. Thanks again, now working.
