### ISSUE TITLE
Cloudstepper's Ring prevents Tinkers' Construct slime boots from bouncing on low heights

### ISSUE THREAD

**Issue by Hubry** [Azanor/thaumcraft-beta#653]
Reproduction: Equip slime boots and the cloudstepper's ring. 
Do `/tp @p ~ ~43 ~` and note that the player didnt bounce at all. 
Do `/tp @p ~ ~44 ~` and note that the player bounces only once. 
Unequip the ring, do the first command - player bounces ~6 times.

Modpack is Twilight Forest's official server's pack ([link](https://minecraft.curseforge.com/projects/do-i-am-cake)). 
Relevant mod versions: Forge 14.23.3.2678, TConstruct-1.12.2-2.9.1.65, Thaumcraft-1.12.2-6.1.BETA13.

**Comment by Lukas45** [comment]
That's because the bounce from Slime Boots is based on the fall damage you WOULD take.
Same effect can be seen if you apply Feather Falling to the Slime Boots

**Comment by Hubry** [comment]
I cannot reproduce the effect you speak of - I am getting the same amount of bounces after teleporting up with both Feather Falling 4 and no Feather Falling on my slime boots at all. Also, the ring is very effective at reducing fall damage, to the point where a 1000 block fall deals about half a heart of damage, so it doesn't seem like the boots should work at any height with the ring in your case.

**Comment by Lukas45** [comment]
Feather Fall may not then, I think it was Levels2, that had a 50% reduction in fall damage trait. When I had that, I barely bounced

**Comment by Azanor** [comment]
Yes, the ring negates a lot of fall damage (maybe too much) so if the boots work like I expect they do they you won't get any bounce.

**Comment by Gammaboy45** [comment]
if you can grapple the ground hard enough, perhaps you can glitch a good bounce :3

**Comment by xenxero1** [comment]
It might be a good idea to post this item interaction to the Tinkers Issue Tracker. If they change how the calculations work for bounce, it could probably solve all of these interactions.
