### ISSUE TITLE
Thermal Expansion plates not working for creating Vis Resonator

### ISSUE THREAD

**Issue by ArtOfCombat** [Azanor/thaumcraft-beta#654]
Thermal expansion plates should work in the Vis resonator recipe according to JEI and the thaumonomicon: they do not. The recipe can be assembled without crashing, but nothing appears in the results column and nothing can be removed from it. This is more than a visual glitch.

TC version: 1.12.2-6.1BETA12

**Comment by UnixRonin** [comment]
FYI, if memory serves, both Base Metals and Thermal Expansion brass and iron plates were working for me in Thaumcraft 6 recipes when I last tried it.  (Base Metals uses the same 3 ingots -> 3 plates recipe as Thaumcraft does.)

**Comment by ArtOfCombat** [comment]
It was my mistake: I was following the JEI recipe, not the thaumonomicon, which I misread. In that regard, it would be great if the JEI recipes were updated with a plugin to show the table and crystals needed.

**Comment by UnixRonin** [comment]
Have you by chance looked at ThaumicJEI?
