### ISSUE TITLE
Crafting salis mundus creating stacks of ingredients

### ISSUE THREAD

**Issue by Caopr** [Azanor/thaumcraft-beta#655]
After creating 1 salis mundus It started to multiply the flint redstone and bowl I placed in the table by quite alot. after 10 It overflowed the table and upon breaking it got whats in the picture

Beta 13

![2018-05-06_16 13 43](https://user-images.githubusercontent.com/29389055/39677805-3456f806-514f-11e8-9925-b720dee20584.png)

**Comment by Azanor** [comment]
What crafting table were you using - the normal vanilla one, the arcane workbench or something else?

**Comment by PistaMista** [comment]
I had the same issue as well in the arcane workbench - it doubled the stacks and then took the ingredients I think.
![arcanebenchdupe](https://user-images.githubusercontent.com/16634160/39943280-a2bbe812-5562-11e8-9a50-2153cd127fa0.png)
