### ISSUE TITLE
Minecraf crashes when mousing over stuff in thaumonomicon

### ISSUE THREAD

**Issue by ziba1** [Azanor/thaumcraft-beta#661]
Hey, firstly, thaumcraft Yay ! 
Secondly, as title says, video link to youtube of it happening.
I'm playing it in a pack on twitch/curse called thaumaturgy's rebirth

https://youtu.be/qg-tOFLGbdM

https://www.curseforge.com/minecraft/modpacks/thaumaturgys-rebirth

**Comment by Azanor** [comment]
This should be fixed int he latest version.
