### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by Pollobomba** [Azanor/thaumcraft-beta#662]
I do not know if it's a bug I have not been able to discover it. in "Focus Medium: projectile" I can not advance in the investigation. I do not know how to discover the firey projectile and sticky projectile.

I have made 4 focus of fire and ice of different powers but I can not unblock it.

Regards, and thanks for your work
(excuse my english google is helping me)

**Comment by Azanor** [comment]
This should be fixed int he latest version.

**Comment by Azanor** [comment]
Oops, thought this was something else

**Comment by Azanor** [comment]
You need to looks for projectiles like that in the world - tip: blazes and llamas

**Comment by Pollobomba** [comment]
thanks
