### ISSUE TITLE
Smelting enchanted iron swords in the Essentia Smeltery causes a crash.

### ISSUE THREAD

**Issue by PogoPogoPogo** [Azanor/thaumcraft-beta#667]
Log: https://paste.ee/p/5yxeR
Thanks for all the effort, it doesn't go unnoticed. Keep it up!

**Comment by Azanor** [comment]
This doesn't seem to be a TC error. From the looks of it BloodMoon is breaking something with OpenGL.

**Comment by PogoPogoPogo** [comment]
Well, sorry for that then. Since it happened 3 times in a row I thought that it was related. I'll just remove that thing. It's weird because there wasn't even a bloodmoon out come to think of it. Anyway, keep up the good work, thoroughly enjoying myself.
