### ISSUE TITLE
Higher tier research items

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#67]
Random loot item in chests. 

They would simply fulfil the next required step in a random research when used. So for example, if the next step in researching nitor is to craft nitor, that requirement would instead be met when you use the item and you can skip crafting it. So instead of gaining insight by doing experiments and researching things practically, you read passages of prose and discover old segments of spell runes, old schematics or descriptions of places and creatures in these various pieces of lore that fill the gaps in your knowledge instead.

They would be broken up by research category. So a thaumaturgy manuscript would increment a random thaumaturgy research, a golemancy schematic would increment a random golemancy research etc.

I suppose they're a bit like curiosities... perhaps they would be like a rarer version of curiosities? Perhaps they could even have a chance to grant epiphanies?

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#166
