### ISSUE TITLE
[B13] Arcane workbench recipes bug (crystals highlighted)

### ISSUE THREAD

**Issue by Akxe** [Azanor/thaumcraft-beta#673]
Steps to reproduce:

Place down arcane workbench.
Fill it with all primal vis crystals.
Put in 4 arcane bricks in square recipe. (Paving stone of travel & barrier stone)
Current behaviour:
The barrier stone is displayed to be crafted, but the crystals to be used are shown for the other recipe. After crafting it will use up different crystals, than it displays to use. (by taking the on of highlighted crystal you will alter the game selection, but it will go to initial state if you returns it.)

Expected behaviour:
Used crystals should match with the one used in crafting.

This bug is more generic than this, but this is nice minimal example to show the bug on.

Append:
I am bit biased on a multiple recipes having shame shape and block & differ only in crystals used. It might get a bit confusing. Imagine a player, he looks up a recipes and put it in the bench, where he has all of crystals. He swiftly grabs the item, and soon after he realises he crafted different block... (my case, thought lucky I wanted both, so it didn't messed up much for me...)

**Comment by Geethebluesky** [comment]
Unless I'm mistaken though, the bench isn't meant to be a crystal _storage_ device. So the crystals are part of the recipe, just like the shape of the blocks and the pattern are, people should expect to get different results based on what crystals are available.

What differs from vanilla MC here is that when there are too many items in a crafting table, the recipe requirements are no longer met. Whereas with the Arcane Workbench, no check seems to be made to invalidate the current grid if too many crystals are present.

**Comment by Akxe** [comment]
The bug is as this. Have a look... 
![snimek obrazovky 4](https://user-images.githubusercontent.com/2001798/39772015-5a6a8480-52f4-11e8-9c20-931e38ed5162.png)
![snimek obrazovky 5](https://user-images.githubusercontent.com/2001798/39772016-5a871faa-52f4-11e8-8e43-75bb0cb7f068.png)
![snimek obrazovky 6](https://user-images.githubusercontent.com/2001798/39772017-5aa45840-52f4-11e8-8f19-042895e32064.png)
![snimek obrazovky 7](https://user-images.githubusercontent.com/2001798/39772018-5abe3896-52f4-11e8-9a4e-66e8d40f6cf3.png)
