### ISSUE TITLE
[B13] Arcane workbench not registered as crafting table

### ISSUE THREAD

**Issue by Akxe** [Azanor/thaumcraft-beta#675]
Just a small feature to be asked. Is it possible to give the arcane workbench ability to shift click recipes in?

**Comment by Boomflex** [comment]
You can.

![image](https://user-images.githubusercontent.com/22868795/39789047-66f63768-5325-11e8-938b-1caa6b2edcd5.png)

Look at the bottom right... the + is what you need to press.

**Comment by Akxe** [comment]
This is part of a mod, without it you won't find any Thaumcraft recipes, 
which is fine, but you won't be able to shift click vanilla recipes 
either... (the mod you use might change that) 

---------- Původní zpráva ----------
Od: Boom Flex 
Datum: 9. 5. 2018 v 02:08:44
Předmět: Re: [Azanor/thaumcraft-beta] [B13] Arcane workbench not registered 
as crafting table (#675)


You can.

image 
(https://user-images.githubusercontent.com/22868795/39789047-66f63768-5325-11e8-938b-1caa6b2edcd5.png)

Look at the bottom right... the + is what you need to press.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/Azanor/thaumcraft-beta/issues/675#issuecomment-387580137)
, or mute the thread

**Comment by drinfernoo** [comment]
This feature is something from JEI, not Thaumcraft.
