### ISSUE TITLE
The thaumcraft wand does not exsist in game

### ISSUE THREAD

**Issue by extracterflux** [Azanor/thaumcraft-beta#678]
Me and my friend play on a modpack i made and we have thaumcraft 4 installed. I downloaded the 1.10.2 beta version. When he tried to craft a wand nothing happened and he couldn't even craft the iron caps. I searched for it but it didn't seem to exist in the game at all.

**Comment by reinder-s** [comment]
the wands are gone, there is now a gauntlet

**Comment by Geethebluesky** [comment]
@extracterflux You start the progression by mining vis crystals in the world, then sleeping. The mod takes you from there.

**Comment by laserlemons** [comment]
This is probably the fault of the mod page being outdated. Wands don't exist anymore, to start the mod just mine a crystal and then sleep.

**Comment by UnixRonin** [comment]
Wands be ol' skool, yo.  :)

**Comment by extracterflux** [comment]
ahh ok, thank you very much guys for the answers!
