### ISSUE TITLE
[Enhancement] Cleaned Up Sounds - Demo Video Included

### ISSUE THREAD

**Issue by TechnoMysterio** [Azanor/thaumcraft-beta#679]
I've been working on cleaning up some sounds for Thaumcraft, as many are of a low sample rate and are therefore quite muffled. The sounds I've altered are essentially the same, it's just that I've used higher quality sources for them, so therefore they sound much crisper. Here's a demo video to show the comparison between the original and the altered sounds:

https://www.youtube.com/watch?v=TC68PBHyRkM

It goes over most of what I've changed: Salis Mundis, the crucible, research, the infusion completion sound (wand1-3.ogg, I haven't changed the infusion loop sound), as well as some sounds to do with warp. It's fairly minor, but I feel it makes the mod feel much tidier and more polished.

On an unrelated note, while making the video I noticed a small bug while doing the cloudstepper ring infusion, so I made sure to leave it in to show it off. It happens at 2:05 or so, where the feather falls off the pedestal but also appears to have stayed on at the same time. I imagine that's a visual glitch, as the infusion process got stuck looking for a feather that already seemed to be there, meaning I had to put one on another pedestal to complete the process.

**Comment by AlekseiVoronin** [comment]
Nice sounds is № 2

**Comment by Azanor** [comment]
Sorry I took so long to notice this. They sound great! I downsampled most of the sounds in TC simply to keep their filesize small. How much bigger are these files?

**Comment by TechnoMysterio** [comment]
Hmm, that may be a problem. I've only managed to find cleaner sources of 28 files so far, and the total filesize of them is 1.71MB.

**Comment by TechnoMysterio** [comment]
I should be able to cut down the size a little, by removing any patches of silence or by limiting certain files to a 44100Hz sample rate, so that may help. Did you have any particular filesize limits in mind?

**Comment by TechnoMysterio** [comment]
Well, after a bit of tidying up (cut some unused silence, dropped a couple of files to 44100Hz, changed some to mono) I managed to cut the total filesize down to 1.30MB, so that's certainly... um... a measurable improvement I suppose.

**Comment by Azanor** [comment]
Thanks, but still a bit big. This might be better as an optional resource pack. Not everyone may want to the extra size & memory they will use. Thanks for the effort though

**Comment by TechnoMysterio** [comment]
That's fine, I was planning on releasing these sounds in resource pack at some point, along with some other sound enhancements I was working on for other mods. However, channelling my inner Columbo for a moment: just one more thing @Azanor ... 

Doing these sounds is quite painful, as the process is very tedious. I usually have to guess as to what the original sound effect was called (some of the sounds do have titles embedded in the metadata, but only very rarely) and what site/sound pack it came from (the metadata shows that a lot come from SoundDogs, but didn't wind1-2.ogg come from a free Hollywood Edge library?). The searching alone takes ages, and is unlikely to be successful. I do want to get the soundpack done however, so could you give me a list of the sound sources showing their names and the libraries/sites the came from or something, in txt file perhaps? Maybe not here, as that might clutter the thread somewhat, but I'd seriously appreciate any pointers for redoing these sounds.
