### ISSUE TITLE
Bug or ficha 

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#680]
![gnhbd_-bekc](https://user-images.githubusercontent.com/37004902/39770676-22bbb620-5309-11e8-8804-62b48e3a657b.jpg)

**Comment by AnrDaemon** [comment]
That's called "feature", and no, this is not the one :)
That "+" is an indication of a bonus draw, you can't have it "stacked" in any event possible.

P.S.
May I introduce you to the [SmoothFont](https://minecraft.curseforge.com/projects/smooth-font)?

**Comment by Azanor** [comment]
Actually you can have multiple bonus draws... I just wasn't expecting that many. The fact that you go that many is in fact a bug since most of the time you will use it up in your next draw.
