### ISSUE TITLE
[1.12.2] Sleeping Blocking TC Progress

### ISSUE THREAD

**Issue by MokahTGS** [Azanor/thaumcraft-beta#682]
With the recent changes to TC you start the mod by finding a vis crystal and then sleeping.  This is fine, except what if you can't sleep.  I have a mod pack that we are creating where the player is never in the overworld, and so can't sleep.  They can set their spawn, with a bed but can't ever actually sleep because they aren't in dimension 0.  This is an issue with TC as Salis Mundus requires the player to sleep to unlock it.  Is there any other Overworld REQUIRED bits we need to know about?

Is it possible to add a config for opening this research without sleeping?

**Comment by Geethebluesky** [comment]
Some of the progression also requires taking notes about the sun, moon and sky in the Overworld.

**Comment by MokahTGS** [comment]
hhmmm...any chance that works in any dimension with sun and moon?

**Comment by MokahTGS** [comment]
Can you give specific research or observations with commands?

**Comment by AnrDaemon** [comment]
```
/mt help
/tc help
```

**Comment by xenxero1** [comment]
I've got no idea what else is in your pack, but I'm wondering if this is something JustEnoughDimensions could solve. You can have "overworld" dimensions, and just customize the world generation to mimic whatever world's you wanted to emulate. This should allow you to sleep, and most likely will allow you to collect notes on the sky.

**Comment by MokahTGS** [comment]
I am using JED, just have no idea how to set stuff up.  It's pretty complicated.  I've looked through the Wiki and will need to figure it out.  If you know of a clear guide somewhere, I'd love to know about it.

For now, I'll just have to give the research via commands until we have a better solution.
