### ISSUE TITLE
Sand>Tainted Soil>???

### ISSUE THREAD

**Issue by SethosSch** [Azanor/thaumcraft-beta#683]
Dirt
![image](https://user-images.githubusercontent.com/6932672/39774630-15edecec-5304-11e8-8d3a-d34d3ab5ba8d.png)

**Comment by androshalforc** [comment]
how much flux is in the area?
if you've been doing too much careless alchemy in the area this could easily happen

**Comment by talonos2** [comment]
Duplicate of #607 

Sadly it's not a priority for him.

**Comment by androshalforc** [comment]
Ahh I misunderstood the issue i thought it was about taint spreading not about turning into sand into dirt
