### ISSUE TITLE
[B13] Server Progression Broken?

### ISSUE THREAD

**Issue by OneTrueVex** [Azanor/thaumcraft-beta#687]
"Current Stage 1/3" on First Steps, with Types of Knowledge and Theorycrafting unlocked and I'm unable to progress any further. First Steps won't register that I've crafted the arcane workbench. It works in single player, but not in my server. I've tried a clean server with no mods besides thaumcraft and baubles, a clean client, still nothing. Am I missing something?

**Comment by kurtawirth** [comment]
Having this problem, too.

https://github.com/Azanor/thaumcraft-beta/issues/1257

**Comment by OneTrueVex** [comment]
A fresh server and client with only the latest version of thaum installed yields a successful progression system. After some process of elimination, it seems to be CustomNPCs that's causing the [complete] button to not appear. I'll report this discrepancy.
