### ISSUE TITLE
Crash on creating a focus, Divide by zero when assigning focus colour

### ISSUE THREAD

**Issue by jwrennie** [Azanor/thaumcraft-beta#688]
I've got a Server running the latest Thaumcraft Beta (Thaumcraft-1.12.2-6.1.BETA13) and it was running fine till one of the users tried making a focus. We get a divide by zero error when it tries to render the focus that crashes the client. 

Here is the full crash report. If I understand it correctly, I should be able to work around the problem by deleting the entity referenced and telling the user not to create one till at least the next Beta comes out. Any help in how I might go about doing that to work around the problem would be appreciated. 

[crash-2018-05-09_13.14.18-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1986300/crash-2018-05-09_13.14.18-client.txt)

**Comment by Dayyer1** [comment]
Did it create a black hole?

**Comment by jwrennie** [comment]
Something like that ;)
