### ISSUE TITLE
Greatwood tree generation looks off

### ISSUE THREAD

**Issue by tyra314** [Azanor/thaumcraft-beta#69]
I came across this odd looking Greatwood tree:

![2018-01-15_21 31 54](https://user-images.githubusercontent.com/16997177/34960553-a6609896-fa3b-11e7-82e1-baee1b60fc75.png)

I only have Thaumcraft, Baubles, and JEI installed.

This is my seed: 3253225137211855828, default world generator
Position of the tree: 632 / 71 / 374

**Comment by Azanor** [comment]
While defintely an outlier, it is possibly for goofy things like this to spawn.
