### ISSUE TITLE
[B13] Can't craft Tasty Meat Treats

### ISSUE THREAD

**Issue by emfolkerts** [Azanor/thaumcraft-beta#697]
I can not craft Tasty meat treats. I place my three different nuggets in the crafting grid with a piece of sugar and nothing is produced.
![2018-05-09_11 18 13](https://user-images.githubusercontent.com/36866543/39826635-f08eceea-537a-11e8-94db-0c11baec2d84.png)

**Comment by Geethebluesky** [comment]
Can confirm this is happening to me too.

Same lack of output with the Arcane Workbench.

![Imgur](https://i.imgur.com/U1acWti.png)

**Comment by Geethebluesky** [comment]
This issue still persists in B16.

**Comment by luminousinsect** [comment]
Can confirm this in B16 as well.

**Comment by Reassembly** [comment]
And B17.

**Comment by Reassembly** [comment]
The most similar recipe (i.e. accepts fixed items + a subset of a collection of items) is for Salis Mundus, which works properly.

Structurally, the recipe definitions are very similar. However, the Salis Mundus recipe uses _both_ an "!= null" check _and_ an ".isEmpty()" check when iterating over the crafting grid, to skip over blank spaces. The Triple Meat Treat recipe _only_ has the "!= null" check - which I suspect does not skip over "empty" spaces, but only spaces outside of the crafting grid (i.e. when using a 2x2 grid, but checking 3x3). If this is true, then the Triple Meat Treat recipe is treating empty slots in the crafting grid as invalid ingredients. Adding an ".isEmpty()" check, like how it is used in the Salis Mundus recipe, might fix this issue.
