### ISSUE TITLE
[B13] Arcane Spa isn't refilling via the Everful Urn

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#698]
This was initially a comment under another Spa issue but I figure maybe I'm not the only one with this problem?

Currently: I have an Everful Urn 2 blocks above an Arcane Spa in my bath (Spa, above it: 1 layer of water, above it: Urn). It's currently not refilling the Spa, which is set to "just use fluid". I would expect it to, since the Urn's description says it'll fill any liquid container in a 2-block radius that accepts water from the top.

The Spa's description says it can be filled with automation... well the Urn is an automatic refilling device, right?

I tried replacing the existing water layer with dirt (that was water the Spa produced after filling it manually with buckets). I left the Spa block and Urn where they are. After removing the dirt (leaving the bath empty) and toggling the Spa a couple times, it's still not filling itself up, nevermind the tub. [Setup pic](https://i.imgur.com/wQo9XnB.png)

[Setting](https://i.imgur.com/alBU6eP.png) toggled a couple times

There's also no particle effects coming from the Urn but I don't know if that's because of my shaders and such, need to check in my testing profile later and will edit this.

**Comment by AnrDaemon** [comment]
Can Spa be filled from the top?…

**Comment by Geethebluesky** [comment]
I would have to assume so, since it says it can be automated and the default input on just about every block is the top? Can anyone check? I don't have any automation mods myself.

**Comment by xenxero1** [comment]
Most setups i've seen have the Urn pushing water into the bottom. There's a good chance that the spa just won't take in water from the top, considering that's mainly where it outputs and interacts with the world.

**Comment by Broam** [comment]
I've placed the urn directly under the spa and that worked.

**Comment by Geethebluesky** [comment]
Oh dear, I forgot to actually move the Urn myself. Well thanks for confirming @Broam :)

**Comment by AnrDaemon** [comment]
That could be indication of a **different** bug.

**Comment by Geethebluesky** [comment]
Which would be? The Urn not reaching underneath the Spa block?

**Comment by AnrDaemon** [comment]
Urn filling the wrong side of the block.

**Comment by Azanor** [comment]
The urn only outputs to the top of a block, unless directly underneat it.
