### ISSUE TITLE
Focal Manipulator Gem Colors

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#7]
The hexagonal system for focus creation is really well thought out, however there's some inconsistency with the coloration of the different "gem" components that you drag and drop onto the grid. The gems for the elemental effects are very brightly colored and clearly reflect their purpose (bright red for fire, cool blue for ice) however the other gems (projectile, bolt, frugal, potency, etc.) are very dull in comparison. Perhaps these gems could be colored to match the vis crystals that they add to the recipe (or otherwise brightened a bit.

P.s. the magical purple lightning effects that conjoin the different components it's absolutely beautiful, maybe it could be added to the visuals during crafting as the vis crystals orbit the blank focus.

**Comment by Azanor** [comment]
Those colors and such where just placeholders. I've already updated it for the next release.
