### ISSUE TITLE
Incompatibility with Valkyrien Warfare

### ISSUE THREAD

**Issue by Gammaboy45** [Azanor/thaumcraft-beta#700]
It's a bit of a wierd one, but not too surprising to say the least. The Cloudstepper ring does not function so long as this mod is active. I believe it may be a result of the Ether crystals and the way they function on a player when in their inventory. Whether this can be fixed on the Thaumcraft end of things I am uncertain, but I'll still take it to you to see if there is something you can look into about it.

**Comment by Azanor** [comment]
This might have been fixed with the b17 patch
