### ISSUE TITLE
Cant progress past First Steps in Thaumonomicon [Thaum 6]

### ISSUE THREAD

**Issue by MachewMachew** [Azanor/thaumcraft-beta#702]
The game doesn't register when I create an arcane workbench.

**Comment by Geethebluesky** [comment]
The first steps are actually to mine Vis crystals in the world, then sleep. You've done that?

You've also created Salis Mundus and sprinkled it onto the table? What happens then?

**Comment by OneTrueVex** [comment]
Is your problem the same as mine, MachewMachew? https://github.com/Azanor/thaumcraft-beta/issues/687

**Comment by Azanor** [comment]
I made some changes that should make the crafting completion checks a bit more robust. Let me know if this persists.
