### ISSUE TITLE
[B13] Conflict w/ Crafting EX prevents creation of Arcane Workbench

### ISSUE THREAD

**Issue by hextrace** [Azanor/thaumcraft-beta#703]
Unfortunately, there wasn't any significant errors found in the logs to include in this ticket.

**Mods:**
    Crafting EX 1.12 v1.2.0
    ThaumCraft 1.12.2-6.1BETA13

**Issue:**
    With Crafting EX loaded, using salis mundis on a vanilla crafting table triggers the sparkles but does not complete the transformation.

**Workaround:**
        Disabled Crafting EX and the process works as intended. Additionally, StimmedCow: NoMoreRecipeConflicts does not appear to have this same issue.

Also opened [ticket](https://github.com/kegare/Crafting-EX/issues/2) in Crafting EX's issue tracker.

**Comment by red360** [comment]
Just a work around. If you have tinker's installed just convert the crafting table to a crafting station first then it will work.
