### ISSUE TITLE
[B13] Full Void Jar cannot be used to empty Alembic

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#705]
Clicking on an Alembic that contains (for example) 7 Terra, with a Void Jar (labeled, if that's important) full of 250 Terra, does nothing at all. 

I would expect the jar to empty the Alembic and discarding the excess.

**Comment by androshalforc** [comment]
is this a void jar or a warded jar?

**Comment by Geethebluesky** [comment]
Labeled Void jar, full (250 units).

**Comment by matix931** [comment]
Is there any other way to empty alembic? At this moment i am just breaking it and placing again.
Shift + RMB or LMB is not working.
