### ISSUE TITLE
B13: Invalid recipe for making clay in Thauminomicon

### ISSUE THREAD

**Issue by clubpetey** [Azanor/thaumcraft-beta#706]
Since this is required from progression through hedge alchemy, its a bigger issue than normal.

I checked ThaumicJEI, no valid recipe there either.  The entry is there, showing the dirt, but the essentia part is missing. Screenshot attached.

![2018-05-09_21 45 42](https://user-images.githubusercontent.com/2221486/39852762-2e8df47a-53d3-11e8-9747-c521268fb6dd.png)

**Comment by Geethebluesky** [comment]
Possibly a mod compatibility issue, can you try to isolate which mod is causing this? Any of them modify clay recipes, off the top of your head?

**Comment by clubpetey** [comment]
I have a few mods that add a recipe for clay:
Botania
Blood Magic
Astral Sorcery

I'll see what I can isolate

**Comment by clubpetey** [comment]
Confirmed the conflict is with Dooglamoo Jr. Archaeology:
https://minecraft.curseforge.com/projects/dooglamoo-jr-archaeology

The mod has a few crafting recipes that use clay.

**Comment by UncleCrustyMC** [comment]
Not sure what mod would be at issue- Thermal Foundation has a different clay recipe . I am running the latest FTB Revelation , with Thaumcraft added

**Comment by UncleCrustyMC** [comment]
I did not have the latest version of Thermal Foundation- I updated, and it works now!

**Comment by Geethebluesky** [comment]
Thanks for checking :)
