### ISSUE TITLE
[B13, B14] Elemental Tools Research Quest not detecting axe or sword

### ISSUE THREAD

**Issue by KH007** [Azanor/thaumcraft-beta#708]
As the title says, there was a problem where I was unable to progress without using the /tc research <player> <RESEARCH> command, with the Crafting component not detecting that the Thaumium Sword or the Thaumium Axe had been crafted, even when they'd been crafted exactly as shown in the book.

Of note is that I crafted the axe and sword before being able to start the quest.

If it's important, I was using other mods alongside it, and here's the entire list of mods and the versions of the modfiles:
Astral Sorcery 1.8.8, Baubles 1.5.2, BedrockBG 5.0-b7, Ceramics 1.3.4, CoFHCore 4.4.1.12-universal, CoFHWorld 1.1.1.12-universal, Deep Resonance 1.6.0, ElecCore 1.8.434, Geolosys 1.8.10c, Immersive Engineering 0.12-81, Journeymap 5.5.2, Mantle 1.3.2.24, mcjtylib 2.6.7, Optifine HD_U_C9, RedstoneFlux 2.0.1.2-universal, Redstone Paste 1.7.5, Refined Storage 1.5.33, SilentLib 2.2.18-10, Silent's Gems 2.6.9b-265, Tinkers Construct 2.9.1.65, Thaumcraft 6.1.BETA13, Thermal Dynamics 2.4.1.10-universal, Thermal Expansion 5.4.2.27-universal, Thermal Foundation 2.4.1.15-universal, and Tinker's Complement 0.2.3b.

All of the mods are for 1.12.2, and the forge version I was using is Forge 1.12.2-14.23.3.2678.

**Comment by CandiceJoy** [comment]
Confirmed.  I've tried crafting them again, cheating them in, dropping them and picking them back up, etc etc etc.  I didn't craft it before I started the quest, either.  It detected the others just fine.  What research is the elemental tools with the /tc research command?

**Comment by KH007** [comment]
It's /tc research <username> ELEMENTALTOOLS for me.

**Comment by Lohoydo** [comment]
I can corroborate this report.  Axe and sword did not work, all other tools did. (using modified DW20 pack, and beta13)

**Comment by TheCharles13** [comment]
This just happened to me with beta 14.

**Comment by KH007** [comment]
Thank you for the notification that this bug exists in B14, too; title will be updated to reflect this development.

**Comment by wamc2017** [comment]
#644,

should be an issue with Astral Sorcery or and other mod which adds nbt tags to swords/axes. (see my last comment there for more info)

**Comment by Geethebluesky** [comment]
[Straum on the Minecraft Forum](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta16?comment=40260) described the issue is also present in Beta 16.

**Comment by Geethebluesky** [comment]
Oh so if it's 100% on their side this issue should be closed?

**Comment by Yadokingu** [comment]
Can confirm this also being present in Beta 16.
