### ISSUE TITLE
[B13] Wonky golem pathfinding

### ISSUE THREAD

**Issue by 00jaydon** [Azanor/thaumcraft-beta#709]
Golems get stuck when blocks are placed diagonally next to eachother like this:
BX
XB
Where B is a block and X in air.
In this case, the golem will try to get to the top-right X from the bottom-left X even though it can't due to the blocks.

Golems also get stuck on the edges of blocks sometimes. I'm guessing this is also because it wants to go diagonally but gets stuck on a block that's partly in the way.

Also, wheeled golems still try to pathfind up onto 1-high blocks even though as far as I know they should only be able to go up slabs and stuff like that. Sometimes they even succeed in going up those blocks.

**Comment by 00jaydon** [comment]
Also, golems can't really pathfind up properly, one just kept jumping and going in circles while it just had to go walk around and up the stairs I made for them.

**Comment by Geethebluesky** [comment]
Some people have had luck fixing pathfinding issues in previous versions by using half-slabs and such. I know it's not a fix, but it may help in the meantime.
