### ISSUE TITLE
Graphical is failure when using The Thaumonomicon 

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#713]
![default](https://user-images.githubusercontent.com/37004902/39887778-7d9f4ac6-54ac-11e8-9457-fe2d6be8ead2.jpeg)

**Comment by AlekseiVoronin** [comment]
![2018-05-10_21 39 45](https://user-images.githubusercontent.com/37004902/39889053-312c334e-54b0-11e8-80b2-9f401852d737.png)

**Comment by Azanor** [comment]
This seems to be a different issue - your model's normals are inverted even when not holding the book and the book itself is just a vanilla item as far as rendering is concerned - it uses no special rendering code so in theory it cannot be causing this.
