### ISSUE TITLE
More world generation parameters

### ISSUE THREAD

**Issue by VonZeeple** [Azanor/thaumcraft-beta#719]
This is a personal preference, but I'd like to scarce the generation of silverwood and greatwood trees. Also I'd like to scarce amber generation but not crystals. I think i can also be useful for modpack makers to have more control on world gen with more detailed parameters in the config file.
Thanks for reading!

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#383
