### ISSUE TITLE
Split target and trajectory

### ISSUE THREAD

**Issue by gravityfox** [Azanor/thaumcraft-beta#720]
Currently, you can split a target OR a trajectory to get two of each, however, what I would like to see is a way to split a combo trajectory/target into a target AND a trajectory path.

Maybe combine the trajectory and target splitter into one, and then you can simply put a medium OR an effect if the splitter was placed on a trajectory/target slot.

This would let you do things like making a focus that that shoots a bolt that damages an entity (using a target) AS WELL AS spawns a projectile that keeps going (using a trajectory).

**Comment by Geethebluesky** [comment]
https://github.com/Azanor/thaumcraft-suggestions
