### ISSUE TITLE
Game Crashes At Startup (1.12.2) (TC6.1B13)

### ISSUE THREAD

**Issue by kenijey** [Azanor/thaumcraft-beta#721]
i just put thaumcraft in my modpack, then it crashed on launch. is there a way to learn why from the logs?
[crash-2018-05-11_11.42.33-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1994579/crash-2018-05-11_11.42.33-client.txt)
[debug.log](https://github.com/Azanor/thaumcraft-beta/files/1994580/debug.log)
using Forge 2681

**Comment by Azanor** [comment]
Something in your modpack is using an older version of the thaumcraft API
