### ISSUE TITLE
[B12] Hoppers and Infusion Altar

### ISSUE THREAD

**Issue by Discomanco** [Azanor/thaumcraft-beta#723]
If you pipe items into the Arcane Pedestals with a Hopper, it will place more than 1 Item on Pedestal. Was hoping to do a tiny bit of automation with it.
When starting the Infusion, it will craft 1 item, but will consume every item stack on the Pedestals, voiding any extras you had intended for next craft.

I know I'm a version behind, but didn't see it mentioned in the changelog

**Comment by codewarrior0** [comment]
Issue confirmed in B13
