### ISSUE TITLE
Banners are destroyed when using proper tool.

### ISSUE THREAD

**Issue by Xules01** [Azanor/thaumcraft-beta#726]
Thaumcraft-1.12.2-6.1.BETA12

I don't think it's intentional, so reporting it as a bug.  When I try to take down a banner, it is destroyed instead of returned to a floating entity.

**Comment by Geethebluesky** [comment]
Does this happen with beta 13 as well?

**Comment by Xules01** [comment]
Tested with beta 13, still happening.  I will add that it works in single player on both version, just on my multiplayer server does it fail.

**Comment by Geethebluesky** [comment]
Finally made a bunch of banners myself and experienced it too on a local server.

**Comment by EightOneFive** [comment]
Have a slightly different version of this bug. When breaking the banner it appears to destroy it and not drop it's floating entity. However on server refresh the banner shows back up where it was placed again. Unable to destroy the banner

**Comment by NeuroTypicalCure** [comment]
I've got the same kind of bug @EightOneFive has, I've had some tries to get rid of them:
- destroying the block beneath doesn't work, if you place on that block it overlaps the banners with the the top one invisible
- burning the banners updates them but doesn't destroy and if you have them overlapped will show both of them overlapping

I made it worse ;_;

**Comment by Geethebluesky** [comment]
There are no non-betas of Thaumcraft 6 yet. Latest is 13.

**Comment by DarcClan** [comment]
Is there currently any way to get them back after breaking them? I haven't got any of mine back yet in the ways I've tried.

**Comment by Geethebluesky** [comment]
Nope, not fixed yet.

**Comment by Azanor** [comment]
Does this still happen in b17 onwards?

**Comment by Xules01** [comment]
I'm still having the issue with the banners being destroyed.  I did have one break that did drop the banner ,but it seems to be a fluke.  This is on a multiplayer server.  I can test on a single player game if you like.


I'm using forge-1.12.2-14.23.4.2739 and both  b19 and b17 of Thaumcraft.  


I would like to point out too that issue #727 was fixed in b17, but is not working again for me in b19.

**Comment by Azanor** [comment]
Is this problem still occurring?
