### ISSUE TITLE
B0:  Thaumonomicon minor errors

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#73]
Alchemical Automation entry, second page:
"Once I have don this I can choose which recipe you wish to craft with..."
should presumably read:
"Once I have **done** this I can choose which recipe **I** wish to craft with..."

In the same entry, for consistency,
"...by attaching a Mnemonic Matrix to its side **I** can increase the number of formulas..."

**Comment by fingersome** [comment]
In addition to the above, there entry in fundamentals that talks about ores uses the old sprite for vis "shards"
