### ISSUE TITLE
Suggestion: Thaumic symbols with OpenBlocks

### ISSUE THREAD

**Issue by Xules01** [Azanor/thaumcraft-beta#730]
I don't know if it's possible, but would love to be able to use the Thauamic symbols with Open Blocks painting system.  

Perhaps this suggestion should go to OpenBlocks instead though, not sure which side would be easier to implement on.

**Comment by Geethebluesky** [comment]
https://github.com/Azanor/thaumcraft-suggestions

**Comment by Xules01** [comment]
Thanks, posted over in the suggestions site.
