### ISSUE TITLE
(Thaumcraft 6.1.beta13) Incompadability with drawers

### ISSUE THREAD

**Issue by larskr96** [Azanor/thaumcraft-beta#732]
Not able to Place the provider seal on a drawer

**Comment by Geethebluesky** [comment]
Drawers? What mod are they from?

**Comment by larskr96** [comment]
Storage drawers

**Comment by larskr96** [comment]
and it does not work With Storage Interface in ancient warfare

**Comment by wrincewind** [comment]
I can add that this is the case for quite a few different mods - the RFTools Storage Scanner and the Extra Utilities Indexer both don't work. On the Scanner, you can place a 'provider' seal, but it only notices the one slot that you can put items into - all of the 'virtual' inventory that the scanner presents to the player is not shown.  

In much the same way, the seal won't go onto the Drawer Controller from Storage Drawers. The controller allows for other piping systems to pull things in and out of it - even a hopper can extract from it - but it doesn't provide an inventory/GUI for the player to interact with. Is that how it detects what inventories are able to be provided from?

Being able to use the Storage Drawers controller with the provider seal would be *astoundingly* useful in terms of automation and logistics, so i'm eager to see this feature implemented.
