### ISSUE TITLE
[B13] Large FPS drop when using Thaumometer

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-beta#733]
Normally the FPS is rather stable at 60, but when looking through the Thaumometer, it drops to around 11, with very few exceptions. I cannot figure out why. I don't see anything different when looking through it (I don't see anything different when wearing the Goggles of Revealing either, for that matter).

**Comment by Geethebluesky** [comment]
Probably a duplicate of #478, please check if that matches your case (and use search next time :)

**Comment by Zsashas** [comment]
Ah, that explains why I didn't see it when I searched (Thaumeter/Thaumometer)
