### ISSUE TITLE
Item aspects visible without completing any research

### ISSUE THREAD

**Issue by Jo10843** [Azanor/thaumcraft-beta#736]
I'm not sure if this is a bug, but it seems like it probably is.
![javaw_2018-05-11_21-23-01](https://user-images.githubusercontent.com/10383773/39952935-06e2d132-556f-11e8-9a63-2b3f7573b338.png)

**Comment by nickeb96** [comment]
It's not a bug.  That's intended behavior in Thaumcraft 6, you don't need to scan items anymore to see the aspects on them.
