### ISSUE TITLE
(TC 6.1beta13) Crash with tubes?

### ISSUE THREAD

**Issue by Zeitheron** [Azanor/thaumcraft-beta#738]
So I encountered a crash while transporting essentia through tubes.

[crash-2018-05-12_13.01.00-server.txt](https://github.com/Azanor/thaumcraft-beta/files/1997492/crash-2018-05-12_13.01.00-server.txt)

**Comment by aso001** [comment]
@EndieDargon Is it possible to screenshot the setup that caused the crash?

**Comment by EndieDargon** [comment]
Not really... I can't log back in that world.
