### ISSUE TITLE
Still don't know how to get different shards/crystals

### ISSUE THREAD

**Issue by FrankieRozsa1** [Azanor/thaumcraft-beta#739]
I know how to get the basic crystals and shards from just around the world, like aqua, terra, aer... but in theory crafting and other things, it needs different crystals that I can't find how to make them or get them. 
sorry about this post because its about my ignorance on shards but I really can't find somewhere else to find how to make them.

**Comment by Geethebluesky** [comment]
Please ask on the [Minecraft forum thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta13) for help with the game itself, this is more a place to file bug reports.

**Comment by FrankieRozsa1** [comment]
yeah problem is in the forums hardly anyone listens and in here there is a lot of people actually listening. And it may be a bug, because Im putting the quart sliver in the crucble after I make my nitor, and then I should get whatever is left like some ignis. but its just not giving it to me so idk if its a bug or im doing wrong

**Comment by Geethebluesky** [comment]
To get a Vis crystal from the crucible, you need at least 2 points of essentia in there. The Goggles will tell you if there's enough, before crafting those it's meant to be kind of uncertain I believe.

There has been a reported issue crafting with the Crucible (#716). I know sometimes I have to shift-click on it multiple times at different angles (like above the waterline) for it to register, but it eventually does. That, or throwing items in can work when shift-clicking doesn't (and vice-versa).

**Comment by chklhead** [comment]
Just wanted to bump this because I am experiencing the same sort of issue creating vis crystal.  No issues clicking to create Nitor, is this click/throw issue unique to using the crystal slivers to create crystals?

**Comment by larskr96** [comment]
When im creating Crystals im clicking the quartz sliver on the water in the Crucible
and its working just fine

**Comment by FrankieRozsa1** [comment]
turns out I needed to discover more stuff before actually doing it. alright thx for the help anyway boys. my bad, I will use other forums to ask questions next time, just wasn't sure if it was a glitch it was just me being stupid

**Comment by Natesky9** [comment]
Some recipes need to be unlocked by unlocking the research tab, and then opening up the research node at least once to "unlock" the recipe. The book has to register that you've "learned" the recipe by you visiting the page
