### ISSUE TITLE
A16/B0:  Compatibility issue with True Type Font Replacer

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#74]
FYI, the fix added in A16 for readability of essentia counts in alchemy recipes appears to have introduced a compatibility issue with TTFR (True Type Font Replacer, formerly known as — or a successor to, I'm not quite clear — Better Fonts).  The effect is that fonts set with TTFR work perfectly up until the first interaction with anything Thaumcraft that results in seeing an essentia count (simply looking at a warded jar is sufficient).  You can do anything that does not involve essentia, but as soon as you **see** the first essentia count of any kind, all characters throughout Minecraft become unreadable rectangular blobs.  Once that has happened, the only way to make anything readable again is to close and restart the Minecraft client.

I'm totally aware of course that you cannot guarantee compatibility with everything, nor is it your job to do so.  But it does seem this is related to the essentia visibility fix since it seems to be seeing essentia counts that triggers it.

TTFR/Better Fonts is not an essential mod, but it's a huge improvement to Minecraft text readability on high-resolution monitors, not so much because TTFR is _Really All That_ as because Minecraft's own built-in text/font rendering is so crude.

**Comment by Azanor** [comment]
I had a look and I do not believe it is something that can be fixed on my side. I do not do anything unusual when rendering those tags - at least I don't think I do. Obviously something is being set or unset in the TTFR font render, but I do not have control over resetting it. You might want to bring this to the attention of that mods author so he can take a look at it. If it is something I need to fix I will take a look again.

**Comment by UnixRonin** [comment]
Will do.

**Comment by UnixRonin** [comment]
Just submitted issue #24 in TTFR at https://github.com/cubex2/BetterFonts/issues/24

**Comment by UnixRonin** [comment]
Additional information:  I have determined that this happens only with the Goggles of Revealing.
