### ISSUE TITLE
Thaumometer not craftable?

### ISSUE THREAD

**Issue by drinfernoo** [Azanor/thaumcraft-beta#740]
First off, I have a mod list [here](https://hastebin.com/ekixanusab.hs).

My issue is that I am unable to craft the Thaumometer, with the required ingredients. I can give it to myself through JEI, and it functions just fine (minus known FPS drop), but doesn't unlock the research.

I was able to give myself the research using `/tc research drinfernoo FIRSTSTEPS`, but I thought there might be a bigger issue.

**Comment by AlekseiVoronin** [comment]
Can you show me a complete list of all the commands for The Thaumcraft?

**Comment by drinfernoo** [comment]
The closest I can get is [this page](http://thaumcraft-4.wikia.com/wiki/Commands), which hasn't been updated in *quite* a while.

However, using `/tc help` will show them all to you.

**Comment by larskr96** [comment]
can you show me a Picture of the crafting grid when you try to make it?

**Comment by Geethebluesky** [comment]
In the Thaumonomicon Fundamentals page, did you actually click on "Artifice" in the circle at the bottom, or is it still blinking?

**Comment by drinfernoo** [comment]
@larskr96 I can later... the recipe requires a Glass Pane surrounded by four Gold Ingots, which I did, along with all of the crystal slots being filled. Also, according to the Arcane Workbench, there is 139 Vis available.

@Geethebluesky I'm not exactly sure what you mean. After forcing the research via `/tc`, I was able to unlock a few more categories, but the Thaumometer is still uncraftable.

**Comment by bookerthegeek** [comment]
![Proof](https://i.imgur.com/PvLDgvP.png)
It is craftable, Just make sure you have the crystals in the slots

![Thaumcraft Recipe](https://i.imgur.com/ABjiusP.png)
![ThaumicJEI Recipe](https://i.imgur.com/4MiV7TY.png)

**Comment by drinfernoo** [comment]
You know what, I'm not sure what happened but it *is* working now.

@bookerthegeek My recipes did look just like that, and it still wasn't working. However, it is now, so I'll consider this "fixed"?

**Comment by SmookePL** [comment]
I open this forum now, i have problem with Thaumometer, because i dont craft this, but i dont why
![bez tytulu](https://user-images.githubusercontent.com/39461629/40279966-9fc42af2-5c4c-11e8-8f90-31ec1cb13419.png)
i have crystal in slots but not working, how to repair it or command

**Comment by caspaas** [comment]
For people still struggling 
I put the glass pane in the middle instead of the glass block.
And it crafted it for me.

**Comment by Majkl-J** [comment]
I believe I have found the culprit. Check the amount of tags on the crystals. For some reason, there can be 2 tags instead of 1.
