### ISSUE TITLE
Incompatibility with Akashic Tome

### ISSUE THREAD

**Issue by drinfernoo** [Azanor/thaumcraft-beta#742]
I'm not sure if this is a bug with Akashic Tome or Thaumcraft, so I'm reporting it in both places.

Mod list [here](https://hastebin.com/ekixanusab.hs)

With both mods installed, *only* the Thaumonomicon is able to be added to Akashic Tome, and all other books become Entropy Crystals, regardless of what mod they're from, or in what order they were added. This happens even if the Thaumonomicon isn't even added to it.

**Comment by generrosity** [comment]
Link to the other issue?

**Comment by drinfernoo** [comment]
https://github.com/Vazkii/AkashicTome/issues/34

**Comment by Azanor** [comment]
That would be a problem with AkashicTime I would think
