### ISSUE TITLE
Fix the location of the aspects and signs.

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#743]
1 - change the location of the aspects, at best down.
2 - Remove unwanted characters
![default](https://user-images.githubusercontent.com/37004902/39960239-97305812-5638-11e8-978a-c31f8934f468.jpg)

**Comment by Geethebluesky** [comment]
Point 2 is addressed in #508. 
Why do you want to move aspect locations (point 1?)
