### ISSUE TITLE
[B13] No recipe for Arcane Stone in the Thaumonomicon

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-beta#744]
I guessed the recipe just based on what it was in TC4, but couldn't find it anywhere at all in the book, and clicking on it in the other book recipes doesn't show it like it does for other components.

**Comment by Geethebluesky** [comment]
Yeah there really isn't. Just double-checked, the Stone is mentioned in a number of places but clicking on it from the Thaumonomicon yields no recipe page. I was convinced that was wrong, it's not :)

**Comment by aso001** [comment]
@Geethebluesky  just as confirmation can you post the screen shot of your Thaumonomicon or do you not have ThamicJEI installed?

**Comment by Geethebluesky** [comment]
I do have Thaumic JEI, but you want me to screenshot.... what exactly?

What's missing is the "click here for recipe" in the Thaumonomicon, it never appears below any reference to Arcane Stone, and clicking does nothing. Onlgly way to see a recipe for it is to search it in JEI.

**Comment by Geethebluesky** [comment]
Hover over each of the Arcane Stone blocks in that recipe. Does it show you how to make the **Arcane Stone** itself?

**Comment by aso001** [comment]
@Geethebluesky  Your right ... I don't see the Arcane Stone recipe anywhere in the Thaumonomicon.

**Comment by enderger** [comment]
Sometimes, you can just click on the block in a recipe to find that recipe

**Comment by enderger** [comment]
For the block

**Comment by enderger** [comment]
Thaumic JEI: https://minecraft.curseforge.com/projects/thaumic-jei
Fixes it

**Comment by Geethebluesky** [comment]
You don't understand. We're saying **Thaumcraft itself** should be providing a recipe for this in the Thaumonomicon.

Some people do not use JEI at all, it doesn't make sense for them to not have access to the recipes the mod uses anyways.

**Comment by enderger** [comment]
I was replying to Zsashas
