### ISSUE TITLE
(suggestion) Barrier stone

### ISSUE THREAD

**Issue by larskr96** [Azanor/thaumcraft-beta#747]
Can you make it so you could Place the barrier stone under a Block and still Block the Blocks above?
![2018-05-13_01 23 24](https://user-images.githubusercontent.com/10383027/39962356-6a9839be-564c-11e8-8bf2-79c6cbe1cefd.png)

**Comment by bookerthegeek** [comment]
A different approach would to have a variant that is disguisable as any other full size block.

**Comment by enderger** [comment]
This should go in the thaumcraft suggestions thread at https://github.com/Azanor/thaumcraft-suggestions

**Comment by Azanor** [comment]
unfortunately barrier stone actually place invisible blocks above them, so it will not be possible
