### ISSUE TITLE
[B13] Curse focus effect Pech Wand requirement nonexistent?

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-beta#750]
Wasn's sure exactly how to word the title, but basically the Focus Effect: Curse page talks about having found a wand from a pech, but I haven't even seen a pech yet. Seems like that should be a requirement, right now it's just flavor text.

**Comment by withercrusher** [comment]
They spawn in magical forest, and I've seen them

**Comment by Geethebluesky** [comment]
The mobs are in the Forest, yeah, but do they drop wands?

And the text in the Thaumonomicon mentions the narrator (?) seeing Pechs even when the player hasn't seen them yet.

I agree that the way the text is worded currently makes it confusing, a bit like "Oh, I've seen a mob I haven't seen, what is all this about?"

**Comment by withercrusher** [comment]
If I remember then drop wands very rarely, and it's better to trade with them

**Comment by Zsashas** [comment]
That makes sense, that's how it was in TC4. However, that's not the issue here.

**Comment by xenxero1** [comment]
This is especially weird considering there is a Pech research you complete by scanning one. It looks like an slight oversight in ordering or flow of research.

**Comment by Azanor** [comment]
Yeah, the pech scanning research should be a requisite.
