### ISSUE TITLE
Causing cascading worldgen lag Problem

### ISSUE THREAD

**Issue by Jacky10X** [Azanor/thaumcraft-beta#752]
Version: 1.12.2
Mod version: Thaumcraft-1.12.2-6.1.BETA13
Problem: it can cause the lag when you playing

it seem the this problem has the solution below:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=ed7b244b28db485aa0e244a3d3a6b4eb&utm_source=embedly&utm_term=5x0twz

**Comment by racinmat** [comment]
So we can expect the cascading worldgen lag still won't be fixed? I am using Thaumcraft-1.12.2-6.1.BETA26.jar, and still experience this lag.

**Comment by ghost** [comment]
> So we can expect the cascading worldgen lag still won't be fixed? I am using Thaumcraft-1.12.2-6.1.BETA26.jar, and still experience this lag.

I am as well, I thought it was Recurrent Complex, and Doom Dungeons but it ended up actually being Thaumcraft, newest version. Have you tried rolling back to an older release? I think I'm going try that because the server is on a very nicely spec'd Dell R710 and never encountered this until now.
