### ISSUE TITLE
Missing Flux study ...

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#754]
![default](https://user-images.githubusercontent.com/37004902/39971681-ac880da0-5718-11e8-9645-74e0bdf7c356.jpg)
Many times release the flux in the atmosphere.

**Comment by AlekseiVoronin** [comment]
Azanor, don't look my mistake ...

**Comment by Geethebluesky** [comment]
The author is busy and will look when he can.
