### ISSUE TITLE
An infinite number of Flux in chunks

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#755]
![default](https://user-images.githubusercontent.com/37004902/39972015-e0f553b6-571f-11e8-9441-e8c12eaff6d7.jpg)

**Comment by Gammaboy45** [comment]
It may be flowing in from other outside chunks. With a 9x9 area, you have 36 directly neighboring chunks for flux to flow from. Are you sure that there isn't flux generated or present in those chunks?

**Comment by AlekseiVoronin** [comment]
I many times the clean up The Flux from atmosphere.
Clean up The Flux 10 minute.

**Comment by Azanor** [comment]
Yeah, flux is flowing in from surrounding chunks
