### ISSUE TITLE
Item dulpcation and salis mundus recipe

### ISSUE THREAD

**Issue by red360** [Azanor/thaumcraft-beta#756]
Crafting salis mundus does not require 3 types of Vis crystals.
Can be crafted with just one Vis crystal in the arcane workbench and it consumes flint, redstone and bowls. Any items in table left over get duplicated in multiple stacks when shift clicking them out.
Using Thaumcraft-1.12.2-6.1.Beta and forge 14.23.3.2681.

**Comment by Geethebluesky** [comment]
Same as #655?

**Comment by red360** [comment]
Yes except “Crafting salis mundus does not require 3 types of Vis crystals.” it can be crafted with one or two.

**Comment by withercrusher** [comment]
It consumes bowl and flint when I try to craft it in arcane workbench
