### ISSUE TITLE
Thaumcraft does not load 

### ISSUE THREAD

**Issue by baibai0909** [Azanor/thaumcraft-beta#757]
I'm trying to get thaumcraft into my singleplayer game, but the mod doesn't load.
The game went through initialization finely without any crashes. I have optifine, TiC, forestry and other little mods like journey map, iron chest, etc that run without any issues.

Thaumcraft -1.12.2-6.1.BETA13.jar
Minecraft - 1.12.2
Forge - 14.23.3.2655

**Comment by Geethebluesky** [comment]
No crashes, but what do the logs have to say about the mod, can you post a clean latest.log where allyou do is start the game? (Please use [Gist](http://gist.github.com) for that.)

**Comment by baibai0909** [comment]
https://gist.github.com/baibai0909/c333862bb25bb61ef75145bebb1d6fe7 is this the right format.

**Comment by AlekseiVoronin** [comment]
Add the Baubles for correct operation the thaumcraft mod

**Comment by baibai0909** [comment]
I do have baubles. And it does run.

**Comment by Geethebluesky** [comment]
> FML has found a non-mod file Thaumcraft-1.8.9-5.2.4.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

Okay. You either have a stray mod file in your folder, or you're somehow trying to get a version of TC5 for Minecraft 1.8.9 to run on Minecraft 1.12.2. :) Not going to happen.

Delete the old file and be sure you're using the newest TC beta for 1.12 [from here](https://minecraft.curseforge.com/projects/thaumcraft?gameCategorySlug=mc-mods&projectID=223628).

**Comment by baibai0909** [comment]
https://minecraft.curseforge.com/projects/thaumcraft/files/2558648 
I downloaded it from here. I now noticed the file say "1.8.9-5.2.4.jar"
The "Thaumcraft-1.12.2-6.1.BETA13.jar" and "Thaumcraft-1.12.2-6.1.BETA12.jar" are both 1.8.9.
I just redownloaded the Thaumcraft-1.12.2-6.1.BETA11.jar and it worked.
Thank you for rechecking the file.
And yes, there are some other mods I don't need anymore so I just left them.

**Comment by Geethebluesky** [comment]
Thaumcraft-1.12.2-6.1.BETA13.jar is 10,657,278 bytes long--that's a 1.12.2 mod, not 1.8.9. Not sure what you're downloading but the link provided works to get the Beta 13.

You'll be experiencing some bugs that have already been fixed if you use Beta 11, just be aware.
