### ISSUE TITLE
[B13] Golem Logistics screen can not show more than 127 of an item in SMP

### ISSUE THREAD

**Issue by dansze** [Azanor/thaumcraft-beta#758]
When using Golem Logistics connected to an SMP server, the GUI fails to render stacks of over 127, instead leaving a blank slot. The stack can not be selected when this happens.

The issue doesn't appear to happen in single player.

![Logistics](https://i.imgur.com/KO0RkcH.png)
![Actual Inventory](https://i.imgur.com/z0YoHDJ.png)

**Comment by Azanor** [comment]
Is this still happening in the latest versions?

**Comment by Ajores** [comment]
I was having the same issue in 6.1.BETA24 of Thaum on FTB Revelations, for what that's worth. I came to report this very thing.
