### ISSUE TITLE
Visit the highest peaks / lowest depths

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#76]
How long do you have to stay at these depths? Have they been changed? Is a specific biome required? I've stayed at y4 and y200+ for about 5 minutes and neither have caused the research requirement to be checked off...

**Comment by UnixRonin** [comment]
Lowest depths:  You have to **see** bedrock.  (If you have a thaumometer, scan it too while you're there.)

**Comment by Azanor** [comment]
Nope it is bugged. With the recent rename of thaumaturgy to auromancy I must have forgot to change the requirements for those unlocks.
