### ISSUE TITLE
Some translation entries do not work in SMP

### ISSUE THREAD

**Issue by HakureiHyouga** [Azanor/thaumcraft-beta#760]
These translation entries do not work in SMP，but there is no problem in SSP

- got.crystals
- got.dream
- false.start
- book.start.title
- book.start.1
- book.start.2
- book.start.3

And......maybe other entries also have this problem......I haven't found it yet
I'm Chinese so...Sorry for my bad english 😓

Mod version: 6.1.BETA13
Forge version: 14.23.3.2689

![image](https://user-images.githubusercontent.com/12714574/40010598-cf3c1304-57d7-11e8-8c2f-d8c0f7211d28.png)
![image](https://user-images.githubusercontent.com/12714574/40010662-fbf66e44-57d7-11e8-8d12-baf5d4f83faf.png)
![image](https://user-images.githubusercontent.com/12714574/40010930-d2fab60c-57d8-11e8-831a-c14ffd66e8ef.png)

**Comment by AlekseiVoronin** [comment]
For correct works words, use UTF-8 and INS in NotePad++ program.
Azanor already wrote about this.
![screenshot_20180515013243](https://user-images.githubusercontent.com/37004902/40021939-e35cfdbe-57df-11e8-8040-9703c98d8e10.jpeg)

**Comment by HakureiHyouga** [comment]
![image](https://user-images.githubusercontent.com/12714574/40048049-d1090688-5863-11e8-9822-9d6e6656a2af.png)
I've checked it and it has been set to UTF-8 and INS already. Em.... Maybe the EOL should be set to Unix?
