### ISSUE TITLE
Disappearing Foci/Caster Glove

### ISSUE THREAD

**Issue by tylerwiegand** [Azanor/thaumcraft-beta#762]
Alright so here's what I had in the Focus Pouch:

Touch->Earth pwr 5
Touch->Fire pwr 5
Bolt->Fire pwr 5
Plan->Exchange (no silk/no fortune)

And I had this on my caster glove:
Bolt->Curse duration 5 pwr 5 (adv focus)

While having the inventory open, never having casted the curse, but with the curse equipped onto my basic caster glove, I clicked on the caster glove (somewhere in inventory), then clicked onto the focus pouch (which was in inventory slot 4, to switch them), and it immediately crashed my single player world. I then logged back in to find the caster glove and all foci from the focus pouch missing, but the pouch was still in inventory. I cheated myself back in my glove and some foci and recreated the curse, then casted it, no problem (again, duration 5, power 5). It lingered on the floor for awhile, and I finally moved on to make other foci -- but I couldn't swap off FROM the curse. It wouldn't even pull up the inventory of foci when I pressed "f" to switch around as I had previously. I deleted the glove, cheated in another, and have been using other foci no problem since.

Not sure if this is INTENTIONAL behavior, like ha-ha I'm cursed so now I lose items...but yeah there ya go.

**Comment by Geethebluesky** [comment]
Sounds similar to #753 but in your case, everything disappeared, you didn't get any duplicates at all right?

**Comment by tylerwiegand** [comment]
Correct, I did not gain any items throughout the process. The only item i was left with was the focus pouch, and not a dupe of that.
