### ISSUE TITLE
bug graphic beta 12 essentia displays behind jars

### ISSUE THREAD

**Issue by androshalforc** [Azanor/thaumcraft-beta#765]
when viewing essentia with goggles of revealing while appearing above the jar you are looking at it will also appear behind any other jars that overlap where the essentia is displayed

![2018-05-14_19 39 15](https://user-images.githubusercontent.com/38366094/40028866-4aa4ae4e-57af-11e8-8eff-4d4bcdb4976d.png)

**Comment by CurePindal** [comment]
Why on earth is somebody reporting bugs from an outdated version?
Whats this madness..!?!

**Comment by androshalforc** [comment]
Because i have not had a chance to update to b13 and since i havent seen this bug posted it is likely that it still persists

**Comment by Azanor** [comment]
Unfortunately this is a rendering order issue in MC itself - no easy way to fix this.
