### ISSUE TITLE
Crucible Recipe Dirt to Clay is missing aspects

### ISSUE THREAD

**Issue by UncleCrustyMC** [Azanor/thaumcraft-beta#768]
In Hedge Alchemy 3/4 , Clay recipe does not show any Aspects, and clay is not craft able in the crucible.
![image](https://user-images.githubusercontent.com/33909946/40036669-940060c0-57bd-11e8-8ed5-a8d38ef62df1.png)

**Comment by Geethebluesky** [comment]
If this is the same issue as 706, it seems you've fixed it by updating Thermal Foundation. Could you close this issue please?
