### ISSUE TITLE
flux rift crash

### ISSUE THREAD

**Issue by mxnmnm** [Azanor/thaumcraft-beta#769]
versions:
Thaumcraft-1.12.2-6.1.BETA13
forge-1.12.2-14.23.3.2676

this happened when I summoned a flux rift
https://pastebin.com/Y1EViZ8i
this happened when I tried to log back in the world
https://pastebin.com/9YHBCgSj

**Comment by Geethebluesky** [comment]
One or more of your mods is/are using a custom graphics library. I see you have CTM in there but you might have others I don't recognize. 

Can you try again after removing CTM and other mods that change graphics? It's to find which one is incompatible.

**Comment by TimeConqueror** [comment]
The same thing with Flux Rift. I wrote /summon thaumcraft:fluxrift and after that got crash-report.
But there was ArrayIndexOutOfBoundsException.
https://pastebin.com/btEMJT4T

Also happened when I tried to enter the world again.

Thaumcraft-1.12.2-6.1.BETA13
forge-1.12.2-14.23.3.2655

**Comment by Geethebluesky** [comment]
Like I said, one of your mods is changing the way Minecraft does its graphics and Thaumcraft doesn't support it, so there's an incompatibility.

For now the solution is to find which mod does this and remove it.

**Comment by TimeConqueror** [comment]
@Geethebluesky This lib is used by Thaumcraft itself :)
![image](https://user-images.githubusercontent.com/25156941/40145497-beffe9f4-596a-11e8-8aaa-816c6d8547fa.png)

**Comment by Geethebluesky** [comment]
Duh. Pretty damn obvious huh!? I must be high on life.

**Comment by Orinai** [comment]
Did we ever establish the solution to this? i have the same thing reoccurring in beta16, and would rather nto lose the world i have been working on.

"Duh. Pretty damn obvious huh!? I must be high on life." seems rather rude and entirely unhelpful in solving the problem. What is obvious ot some people may not be so to others

**Comment by Geethebluesky** [comment]
@Orinai That wasn't meant as a general comment, it was in reply to my own comment that wondered about something that was pointed out as obvious after the fact.
