### ISSUE TITLE
B0:  Taint might be too aggressive...?

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#77]
About two hours ago I accidentally right-clicked a full jar of Perditio.  Moments later, I got attacked by a tainted crawler.  I've cleaned up four small patched of taint since then.  Now I am watching as taint devours my base before my eyes in real time, spreading as I watch.  I'm helpless to do anything about it because any time I get near the taint, the game slows to 1-3 frames per second.  I can barely even move.  It's taken about ten minutes to take over a twelve-block swathe the entire way across the front of my base, and the growth rate is accelerating as tainted rock spawns tainted crawlers, which spawn more tainted rock, which spawn more tainted crawlers...  I'm fully expecting most of my base to be gone by morning at the rate it's going.

This might just be a little too aggressive?  And the frame rate any time fibrous taint is in view is definitely a problem.

**Comment by Azanor** [comment]
It is strange that a single jar could cause enough flux to spawn taint. Was you flux already high?
The framerate loss is unlikely to be due to the fibres - they are basically just normal blocks. What happens if you turn down your particle settings?

**Comment by UnixRonin** [comment]
I'll try the particle settings.

I don't **think** my flux was overly high, though a lot of flux seems pretty inevitable when getting started in TC6, especially when learning.  The Thaumonomicon refers to flux as "visible as an ominous dark bar" in the thaumometer, but I haven't seen any such dark bar.  (However, several other things also don't seem to be working right.  I tried to infuse a nimbus ring yesterday and couldn't get the infusion to start.)  Could retrogen maybe have spawned a tainted node under my base and it took until now for taint to reach the surface?

**Comment by UnixRonin** [comment]
OK, so ... I've turned graphics from fancy down to fast, and particles from decreased down to minimal.  It took me about seven tries to live long enough to get outside the tainted area because on initial load, the frame rate is 0-2 FPS within the tainted area, and took nearly 10 minutes after teleporting out by command-line before it recovered enough for me to be able to cautiously return and do some non-contact excavation using WorldEdit to measure the depth of the taint.

Another thing that may be relevant to the performance is that I'm using a 64-bit texture pack.  Then again I'm also running an nVidia GT980Ti.

The taint has entirely consumed a 5-chunk radius around my base, at least 5 blocks down into the ground and up to about 30 blocks up.  It has climbed trees faster than buildings.  It stopped at 5 chunks radius because that's where my chunkloader stopped.  Inside this area, taint has consumed almost every solid block except glass and water, and most non-solid blocks, vanilla or mod-added.  The taint appears to be unable to consume ArchitectureCraft, Project Red, Thermal Expansion, Ender Storage or Router Reborn blocks, or any kind of microblock, and some large Mo'Creatures mobs such as elephants appear to possibly be immune.  (Perhaps their hitboxes are so far from the ground they're unaffected.)  Warded jars, essentia smelter, bellows etc, infernal furnace are untouched, though some are covered in taint; my infusion altar was entirely consumed except for the matrix itself and a couple of the pedestals.

**Comment by UnixRonin** [comment]
Addendum:  In the last hour or so that I was sitting on a conference call, it's spread about another 2 chunks in every direction.

**Comment by Azanor** [comment]
The rate of spread seems about right - taint is way easier to get rid of now if you kill the seeds. What worries me more is the FPS loss. I do most of my development on a what is basically a potato and my FPS never dips unusually low. I will play around a bit and see if I can figure it out.

**Comment by Azanor** [comment]
I tracked down the FPS issues. I updated the way they render which should gain you some FPS in the next release.
