### ISSUE TITLE
Provider seal and crate from actually additions

### ISSUE THREAD

**Issue by withercrusher** [Azanor/thaumcraft-beta#771]
I can't put provider seal on a crate.
I have to put seal on a chest, then break the chest, and put crate in it's place

**Comment by Geethebluesky** [comment]
The seal stays in the world even if the chest is broken?

**Comment by withercrusher** [comment]
It's wired, but yes they do

**Comment by Azanor** [comment]
What version of TC are you using?

**Comment by withercrusher** [comment]
Beta 13
