### ISSUE TITLE
[Request] - New seal: Requester

### ISSUE THREAD

**Issue by wrincewind** [Azanor/thaumcraft-beta#772]
the Requester seal would be a counterpart to the provider seal - it acts like a 'fill' seal but calls from Provider seals like how the 'use' seal does. I'd imagine it'd default to whitelist and support stacks - e.g. if you had a 3x3 whitelist grid and you told it to keep 64 saplings in one slot and 16 in the next, it'd add them together and keep 80 saplings in the connected inventory. 

In effect, it's similar to using the Golemancer's Bell to pull items into the chest, but automatically.

**Comment by Geethebluesky** [comment]
https://github.com/Azanor/thaumcraft-suggestions

**Comment by wrincewind** [comment]
Ah, I thought that the 'suggestions' area was just for non-beta Thaumcraft - given the Readme for this repository says "Location for Thaumcraft beta testers to report problems, *suggestions* and errors."  (Emphasis mine)

**Comment by Geethebluesky** [comment]
Is the suggestion related to a feature that's in the beta _as it is now_ though, or is it a request for an entirely new feature? There hasn't ever been a Requester seal in the game before AFAIK, so I believe this (along with suggestions and requests for other new stuff) belong in the Suggestions repo. If I'm wrong, I'm pretty sure Azanor will mention that.

**Comment by wrincewind** [comment]
Hm, a good point. The provider seal is new for 6, isn't it? the golem logistics certainly is, and i figured this to be an extension of that. I guess we'll wait and see if this gets moved, then? :P

**Comment by Geethebluesky** [comment]
Nope, provider seal was in TC5.

**Comment by Ulysses2** [comment]
Use seal has a 'request items from whitelist' option - it would be simpler to give that option to the Fill seal as well.

**Comment by wrincewind** [comment]
the 'stock' seal seems to cover this pretty well, from what I've seen!

**Comment by Azanor** [comment]
Yup, the stock seal is what you want.
