### ISSUE TITLE
Strange multi crystal thing in workbench

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#776]
When the arcane workbench is empty, I can pull a strange multi crystal thing out of the bench. It seems useless and costs nothing.

**Comment by enderger** [comment]
And flux needs to be nerfed because it is a pain in the butt to kill taint seeds off of a village church

**Comment by Geethebluesky** [comment]
Couple things here. 

1. Take screenshots / provide logs of the issue happening, or it didn't happen. :)

2. One problem per issue thread please. Use the Search bar before you submit anything, for example there's a thread about current balance for taint in the beta at #681

**Comment by enderger** [comment]
To reproduce the bug...
1: Install journeymap and thaumcraft
2: Create a world with cheats enabled
3: Create an arcane workbench
4: Create 2 waypoints in journeymap and teleport to one
5: Look inside the workbench and you will see the crystal

**Comment by enderger** [comment]
It may be just not done yet

**Comment by enderger** [comment]
Thaumcraft 5 version: http://thaumcraft-5.wikia.com/wiki/Vis_shards

**Comment by enderger** [comment]
![2018-05-16_16 06 15](https://user-images.githubusercontent.com/36283171/40144191-5f0f5ed6-5923-11e8-9c1a-50e0519c64af.png)

**Comment by enderger** [comment]
Try with the mcmage modpack with manually updated Thaumcraft ams thaumic jei

**Comment by Azanor** [comment]
Not reproducable on my side either. I think you need to report this to the modpack creator. I suspect something is messing up TC recipes. The fact that the item created is called "item.combined_" (rest was hidden) means that it isn't from thaumcraft itself. I'm guessing its an addon mod.

**Comment by enderger** [comment]
Item.combined_crystal.name

**Comment by enderger** [comment]
Not an addon: no extra tabs are in the thauminomicon, and the only addon is thaumic jei

**Comment by enderger** [comment]
I’ll try to check if it is on a chunk border: it seems locational

**Comment by enderger** [comment]
And the table was placed in B10 before I updated to B13

**Comment by enderger** [comment]
Ill debug when I can play minecraft again

**Comment by enderger** [comment]
Potential replication fix:
1: place an arcane workbench in beta 10
2: open the world in beta 13
3: look in the workbench

If this theory is correct, the crystal should now be in the workbench

**Comment by enderger** [comment]
If the theory expressed above does not work, try loading from multi MC: that could be the cause of this and bug #804

**Comment by Geethebluesky** [comment]
If it's dependent on starting with beta 10 anyways it's not going to be a problem for too much longer.

**Comment by enderger** [comment]
They seem to have a use: arcane stone crafting

**Comment by enderger** [comment]
Their oreDictionary entry is most likely thaumcraft:vis_crystal

**Comment by enderger** [comment]
If it is from an addon, then vis crystals use a system that is the same as Minecraft’s enchantment system.

**Comment by Azanor** [comment]
I just double checked and nowhere in my code do the words "combined_crystal" appear, so this must definitely be the result of something else. Thaumic JEI maybe?

**Comment by enderger** [comment]
Combined crystal seems similar to the old balenced shards... regardless, the crystal is not available in any other workbench in my SMP lan. I’ll close this, as it could not be thaumcraft itself if the crystal is nowhere in the code.
