### ISSUE TITLE
[Question] What are the dimensional limits of the Infusion Altar - Stability Check.

### ISSUE THREAD

**Issue by joelou1** [Azanor/thaumcraft-beta#778]
I've been wondering, ever since TC4, the altar's range for detecting stabilizing objects has changed, items considered as stabilizing has changed and etc. My question here is, at how much blocks of Distance Above, Under and on the sides of the Infusion Matrix do I have on TC6? I would like to avoid having unnecessary items within it's range and add stabilizing items accordingly. 

[https://www.reddit.com/r/feedthebeast/comments/1z57dg/want_to_know_how_thaumcraft_infusion_symmetry_is/?st=jh973s96&sh=efc72089](url)

This link is the closest I got from an anwser, but it uses TC4's maths. I'd like to make sure it's still the same.

**Comment by enderger** [comment]
A way to find a similar answer would be this: on a creative world, move arcane pedistals slosly away from the altar and run a test infusion. In theory, if a pedistal is in range, stabilizers should be in range.
