### ISSUE TITLE
Where can I contribute some code for thaumcraft?

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#780]
I was just wondering if I could help provide some javascript, textures, and such to help with the development of thaumcraft

**Comment by Geethebluesky** [comment]
You can always make an addon? And nothing's keeping you from releasing an alternative texture pack for TC :)

**Comment by enderger** [comment]
Where should I look to find what I need to begin working on one for tc6

**Comment by Geethebluesky** [comment]
Do you already know how to mod though?

**Comment by enderger** [comment]
I know a bit about how to make a mod, but I don't know how thaumcraft's crafting mechanics use recipe registry

**Comment by enderger** [comment]
And I am comfortable in front of a command line interface (CLI), as proven by my full installation of Arch Linux
