### ISSUE TITLE
Pure Pracantatio

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#781]
Where can I get a pracantatio - only item?

**Comment by Alcamore** [comment]
Salis mundus is a good source of praecantatio. You could melt some in an essentia smelter and fill glass phials with praecantatio essentia for a praecantatio-only item. You can also throw some into a crucible with some quartz shards to get praecantatio-only vis crystals.

**Comment by enderger** [comment]
Ok, thanks!
