### ISSUE TITLE
Is there supposed to be a cross-linked/clickable recipe for the Mundane Belt?

### ISSUE THREAD

**Issue by applebaps** [Azanor/thaumcraft-beta#785]
![2018-05-16_22 18 03](https://user-images.githubusercontent.com/39362356/40159745-1d906958-5957-11e8-97f9-d8f6d35c7342.png)

Similar to Arcane Stone, there does not seem to be a clickable recipe here.

**Comment by enderger** [comment]
The same applies to the mundane ring: does the thaumonomicon show vanilla recipes?
