### ISSUE TITLE
Thaumcraft loads but can,t do anything related too thaumcraft

### ISSUE THREAD

**Issue by tiger39m9** [Azanor/thaumcraft-beta#788]
I am using the dw20 pack version 1.12.2    1.11.0

**Comment by applebaps** [comment]
What do you mean, specifically?  What have you tried to do that didn't work?

**Comment by tiger39m9** [comment]
like I put the recipe for the thuameter  but nothing shows up on the right side of crafting table

**Comment by Brainslime1** [comment]
remember this Thaumcraft 6 Is completely different in how you unlock stuff

**Comment by tiger39m9** [comment]
I see the problem now   I was baseing every thing from thaumcraft 4

**Comment by AlekseiVoronin** [comment]
It is now other mod, don't TC 4, and 6. And read the Thaumonomicon

**Comment by enderger** [comment]
Get some salis mundus
