### ISSUE TITLE
Botania and Thaumcraft oddness

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#789]
This glitch is simple: while mystical petals show the aspects herba, tenebrae, ignis, and sensus in thaumic jei, they do not contain such aspects. I know enough about mods to know that the aspects must exist in some form of metadata, as that is the only way that thaumic jei could be compatible with other mods. Furthermore, the code for thaumic jei must use the new system of aspects to remain compatible with thaumcraft itself.
![peek 2018-05-17 12-45](https://user-images.githubusercontent.com/36283171/40194611-a75fda32-59d0-11e8-95ef-124f5fd4665a.gif)
![2018-05-17_12 36 04](https://user-images.githubusercontent.com/36283171/40194634-c0e588bc-59d0-11e8-9373-5251b228ee72.png)
![2018-05-17_12 36 07](https://user-images.githubusercontent.com/36283171/40194637-c1e59888-59d0-11e8-9fa2-24eb64c7c98f.png)
The red petal appears in both aspect groups in thaumic jei but not when holding shift or in the cauldron

**Comment by AlekseiVoronin** [comment]
Maybe he hasn't done it yet. Didn't have time ...

**Comment by Ushupiuck** [comment]
another odd thing, (although this might be more related to Botania than thaumcraft) is that combining any Botania helmet with the googles of revealing does not gives you discount, as it should...

**Comment by enderger** [comment]
That is the helmet added by botania

**Comment by Azanor** [comment]
I do not add aspects for anything other than vanilla and tc items unless I can calculate the aspects somehow via crafting recipes. Something else must be assigning those petals essentia and I suspect that the petals have less than 1 essentia assigned to them somehow. TJEI is picking them up, but I do not display or count anything unless it has at least 1 essentia.

**Comment by enderger** [comment]
That is not the issue: they gain their aspects when the lexicon botania is in your inventory and loose them when they leave it
