### ISSUE TITLE
Research Table tweak

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#79]
Can I suggest that putting a chest adjacent to the table would allow the table to search the chest for needed items? It's a massive pain to leave the gui and rummage for items and then come back to the desk to complete certain research tasks - especially the essentia crystal ones, when I already have the supplies to hand.

Better yet, perhaps allow golems to recognise when the table needs a certain item and go and fetch it for you.

**Comment by fingersome** [comment]
Whilst we're on the subject of the research table, i'd like it if the research path that each draw leads down was a bit easier to discern, maybe just use the icons from the thaumonomicon at the top of the page or something to indicate at a glance which is which rather than having to read through the text (which is already quite small)

**Comment by Azanor** [comment]
Actually cards linked to specific categories already display them as a watermark  on the page. It is not super obvious, but is relatively clear.
