### ISSUE TITLE
[B13] Duplicate celestial notes in theorycrafting

### ISSUE THREAD

**Issue by eschatonic** [Azanor/thaumcraft-beta#791]
**Environment:**

Beta 13, no other mods installed.

**Steps to reproduce:**

1. Perform theorycrafting until a card requesting two celestial notes of the same type shows up
2. Have only one celestial note of the required type in your inventory
3. Click on the card

**Expected result:**

The theorycraft should not succeed.

**Actual result:**

The theorycraft succeeds, and only consumes one of the note.

**Comment by enderger** [comment]
Bug
