### ISSUE TITLE
Goggles of revealing show amount of xp in brainjars

### ISSUE THREAD

**Issue by Morinor** [Azanor/thaumcraft-beta#794]
When lookin at a brain in a jar with goggles of revealing equipped, it could show the amount of xp stored in it, similar to essentia jar.

**Comment by enderger** [comment]
Please put this in the suggestions thread(
bit.ly/TCSuggestions)

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#382
