### ISSUE TITLE
Silverwood saplings drop issue (25 saplings per tree)

### ISSUE THREAD

**Issue by Rykzu** [Azanor/thaumcraft-beta#795]
The silverwood sapling drop rate is the same as vanilla trees, and work the same way, so fortune 4 break focus make a single tree drop 25 saplings even without breaking all the leaves with the focus. Absolutely busted.

**Comment by Geethebluesky** [comment]
That's not so much of an issue with TC6 as it was with TC5 and the node system though. Silverwoods don't have nodes anymore, so planting 150 of them only has limited benefits.

**Comment by applebaps** [comment]
Are they still used to cleanse the taint?

**Comment by Azanor** [comment]
Well, I say solved, but the problem actually lies in how the drop chance is changed with fortune. That is something I can't change. I could reduce the base drop chance, but that will seriously nerf how much you get WITHOUT fortune without really changing how much you get WITH fortune.

**Comment by MalkContent** [comment]
Fortune drops are customizable, could just lower the bonus chance given by it
