### ISSUE TITLE
Celestial Scans don't work (due to different world handler for overworld)?

### ISSUE THREAD

**Issue by Darkmega18** [Azanor/thaumcraft-beta#801]
G'day. I've got the mod Just enough Dimensions installed, and i use it to manage a number of my dimensions because it allows me to change the time scales and various other things of the dimension to suit a story of sorts that I have in my modpack. However I've come across an issue.

I've got the research unlocked to do Celestial Scans but celestial scans will not happen, no matter where I try to scan in the sky. Just says that can't be scanned. Not even the sky quadrants get scanned.

At first i thought it was Astral sorcery or botania's pretty skybox, but I realized I have astral's skybox turned off and just set to render constellations in the standard sky, and nothing changed with botania's off aswell just as a test.

So I figured the most likely cause was that JED uses a special generator replacement and world handler that can make overworlds and other dimensions with different colors and styles like super flats etc based on the config and this is just causing thaumcraft to not recognize the sky or something. Would it be possible to look into fixing this?

Thaumcraft version in Beta 13.

edit: Ok, yeah, just made sure it was bugged by taking out JED and doing the first stuff. I immediately got the solar scan. so... yup, incompatible, unless some thaumaturgy is worked on it. :<

gimme a spoiler, do I absolutely require celestial scans for anything important like a hidden chain when I get later on or have hit all of them atleast once? or are they just there as situational research bonuses? Cause I can probably just deal with it if thats the case. otherwise. I may just have to do some shonky business and cheat the scan pages at the very least as I pretend to scan the skies. :V

**Comment by Azanor** [comment]
I doubt I will be able to account for whatever that mod does to the normal world time handler vOv.
Celestial scanning is currently not required - it is just a way to get theorycrafting done a bit quicker, but is defintely not required.

**Comment by maruohon** [comment]
What does Thaumcraft check for to allow this scanning to work? Does it require a specific `DimensionType` (ie. `DimensionType.OVERWORLD`), or is it hard-coded to dimension 0, or does it check for `WorldProvierSurface` exactly? And it it based on the `getWorldTme()` output instead of the `getCelestialAngle()` output?

There may be a way to get the mods be compatible from one or the other side. But a Forge PR adding a methods that would indicate the day cycle and/or day and night lengths would definitely also help resolve these type of issues between mods that use custom day cycle lengths... I'll probably try to submit one when I get the chance.

**Comment by Darkmega18** [comment]
Alright, I'll just carry on, Azanor. I've got the power of true alchemy (projectE) at my side regardless. Resources should be no issue when it comes to getting drops for other research points.

**Comment by Azanor** [comment]
I use getCelestialAngle, since some of the other methods had proven unreliable. I guess it isn't foolproof either.

**Comment by Azanor** [comment]
I might work in other 'overworld' dimensions, but the only one I can guarantee is the real overworld.

**Comment by maruohon** [comment]
How exactly are you checking for the "real overworld" though? Are you checking for the exact `DimensionType.OVERWORLD` reference? Or checking the type of the WorldProvider?

**Comment by Azanor** [comment]
I had to go check my code, but I look at DimensionType.OVERWORLD. Anything else is ignored.

**Comment by maruohon** [comment]
Alright, thank you. I guess I'll add a new option to JED to allow replacing the WorldProvider separately/"after the fact" to hopefully make customized-by-JED overworlds compatible with Thaumcraft. Currently I just let vanilla/Forge handle the WorldProvider creation by letting it be created from the class in the registered custom `DimensionType` entry.
