### ISSUE TITLE
Item aspects should only be visible after the first research

### ISSUE THREAD

**Issue by EnderiumSmith** [Azanor/thaumcraft-beta#803]
One shouldnt know what essentia items are made of before starting thaumcraft

Also it would be nice if the aspects tab in the book showed which items have that aspect. it did in previous versions

**Comment by Geethebluesky** [comment]
I also find it strange that we can see aspects without scanning anything, it makes it less obvious that scanning actually brings benefits (the inspiration in the research table, for example).

**Comment by redgoblin88** [comment]
yeah it is essentially a "cheat sheet" because you can immediately see what items are best for certain aspects and what items to avoid. for example, enchanted books are perfect for praecantatio however as JEI shows most of them have other, possibly undesirable, additional aspects.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#381
