### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by grydian** [Azanor/thaumcraft-beta#804]
Using Thaumcraft-1.12.2-6.1.BETA13 and forge 2698

https://pastebin.com/NqSvCbP9

I have tried to figure out why this is suddenly an issue.  Tried recreating configs.  Any ideas?

**Comment by Geethebluesky** [comment]
Have you updated Forge recently, did it work before?

**Comment by Geethebluesky** [comment]
Points to a modpack issue then. I'm on 2691 myself and don't experience this.

You guys seem to be using the same modpack though.

**Comment by Geethebluesky** [comment]
Possibly a modpack issue then because I'm on 2691 and not experiencing this.

Try removing mods in groups to isolate the culprit?

**Comment by enderger** [comment]
It looks like mindcraft itself is somehow messed up

**Comment by enderger** [comment]
Try copying the “mods”, “config”, and “saves” folders to a new profile with the new forge version

**Comment by grydian** [comment]
I did that before I made the original bug report.

**Comment by grydian** [comment]
It looks like trying another launcher has found the problem.  It worked with twitch/curse launcher.  Then I realized I forgot to add liteloader as a mod file since its built into multimc.  Then I went and got the most recent release of liteloader added it to the mods folder and got this crash.

https://pastebin.com/Gv4XM5Cu

**Comment by redgoblin88** [comment]
i think multiMC loads minecraft differently to how forge does, i have heard other isues within the modded community of other mods crashing due to multimc (but they all tested with twitch andare fine with that)

**Comment by enderger** [comment]
I am loading thaumcraft from multi MC and have no issues (unless that is why I am experiencing bug #776)

**Comment by enderger** [comment]
And try to find if they are using the newest LiteLoader: it may be a case of a bug introduced in the new LiteLoader

**Comment by enderger** [comment]
And as a FYI, you can put the download link for a twitch modpack into the “import from zip” field and it may fix the issue

**Comment by enderger** [comment]
In the crash SPOUNGE is the most likely culprit... did not see that coming

**Comment by enderger** [comment]
And give the game more RAM...
https://m.youtube.com/watch?v=gGyHhqgw9dE

**Comment by enderger** [comment]
1 Gigabyte won’t cut the mustard

**Comment by grydian** [comment]
Ok I give my pack 8 gigs of ram.  I also added liteloader into the twitch launcher and it still crashed.  Its crashing with liteloader with both launchers.  The issue is the latest version of liteloader.  I do not know why it says sponge in the crash report as I am not using it at all this is a single player pack I made myself and have rebuilt with several launchers.  The only way I can play is by not using liteloader and my fav minimap voxelmap.

**Comment by grydian** [comment]
Fyi when you install liteloader into a forge profile it just adds it into the mods folder like I do.

**Comment by enderger** [comment]
You can use an older LiteLoader through MultiMC

**Comment by grydian** [comment]
Just double checked.  When I try to install liteloader there is only one version listed.

**Comment by enderger** [comment]
Odd, try putting the LiteLoader jar on their Jenkins page into the mods folder

**Comment by enderger** [comment]
Sift through the versions until you get one that works

**Comment by enderger** [comment]
And, just making sure, you did use multiMC to up the ram, right?

**Comment by Geethebluesky** [comment]
To install Liteloader you need to grab the executable from here (assuming you're on Windows, sorry that obviously won't help if you're on anything else): grab the [LiteLoader installer](http://www.liteloader.com/download#snapshot_11220)

**Comment by Geethebluesky** [comment]
Probably a silly question but @grydian you're using Java 8, right?

**Comment by Geethebluesky** [comment]
@grydian Glad you found it, sorry to not be helpful. Close the issue if you're done please!

**Comment by enderger** [comment]
So I did read that crash report right!
