### ISSUE TITLE
 [TC6.1-B13] Non-Vanilla/TC Native Clusters lack alchemic recipe

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#809]
Say for people that play with immersive engineering, you can't create native copper/silver cluster by means of the crucible. Tried throwing the ores into a crucible with 5 ordo and 5 metallum, just to see if the recipe just wasn't listed, but that just added more aspects to the soup.

**Comment by Geethebluesky** [comment]
Do you know if cluster creation works with other mods that add copper and silver, by any chance? (anyone else?)

**Comment by Azanor** [comment]
This was fixed in B14
