### ISSUE TITLE
Exchangeable Faceplates

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#810]
I really wish the faceplates of the fortress armor where exchangable. The way it is now, you have to create 3 different helmets if you want to change it up, which wouldn't be super bad, if it wasn't for the fact that you also have to enchant them all individually, which is when it turns into a real chore.

Also I'd like to resubmit this https://github.com/Azanor/thaumcraft-suggestions/issues/36

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#380
