### ISSUE TITLE
Thaumometer not craftable

### ISSUE THREAD

**Issue by SmookePL** [Azanor/thaumcraft-beta#812]
I open this forum now, i have problem with Thaumometer, because i dont craft this, but i dont why
![bez tytulu](https://user-images.githubusercontent.com/39461629/40280470-575a5f04-5c54-11e8-8029-0c7d20ffa0b8.png)

i have crystal in slots but not working, how to repair it or command

**Comment by SmookePL** [comment]
i have Thaumometer with game mode 1

**Comment by Dusty-Sprinkles** [comment]
What version are you running? I don't have this issue and I'm on B13.

**Comment by SmookePL** [comment]
B13 on Minecraft 1.12.2

**Comment by SmookePL** [comment]
And i have no idea what happen

**Comment by Geethebluesky** [comment]
Post your mod list, someone may be able to ID a conflict

**Comment by SmookePL** [comment]
![1](https://user-images.githubusercontent.com/39461629/40281015-062a50f0-5c5c-11e8-8cc6-2f42da3923ea.png)
![2](https://user-images.githubusercontent.com/39461629/40281016-085f39da-5c5c-11e8-80e1-4bdb28427f7a.png)
![3](https://user-images.githubusercontent.com/39461629/40281017-0a07036c-5c5c-11e8-915e-dbb3b9a30d29.png)

**Comment by bookerthegeek** [comment]
That is odd. On starting a new world the Thaumometer is craftable.
![Proof](https://i.imgur.com/BOzTmqC.png)

Are you using a texture pack of some sort? Can you please try shift clicking the output slot of the worktable?

**Comment by SmookePL** [comment]
I have my texturepack Faithfull

**Comment by SmookePL** [comment]
This working on a new world, but my older save not working :/

**Comment by SmookePL** [comment]
On a new world in tab Thaumcraft item is sorted, but on my old save in thaumcraft tab item is not sorted :/

**Comment by Geethebluesky** [comment]
In the old world, did you use an older beta (like Beta 10, 11)?

Did you update the beta version for the new world?

**Comment by applebaps** [comment]
That is a TON of mods, wow.  I wouldn't expect to be able to run all that alongside a beta WIP mod and not have some kind of problem tbh

**Comment by redgoblin88** [comment]
maybe its a forge issue or that "no recipe conflict" mod (the arrow) is causing the issue since the arcane worktable is both vanilla and a custom crafting mechanic so its getting confused if its craftable (thaumic recipe) or not (well, im prety sure that recipe isnt how you make a clock)

**Comment by SmookePL** [comment]
But its works when i copy new level.dat and pastę in my old save, but on my world my lampa change on Ore block :/

**Comment by SmookePL** [comment]
And i have no idea what i have Thauncraft-Beta before B13 :/

**Comment by enderger** [comment]
Try breaking and replacing the workbench

**Comment by enderger** [comment]
I think that this and #776 are both manifestations of a lack of backward compatibility between thaumcraft betas

**Comment by McAlphaTester** [comment]
You have to open Your Thauminomicon or however its spelled and complete the First quest of getting the book :)
