### ISSUE TITLE
About Focus: as soon step 2

### ISSUE THREAD

**Issue by AlekseiVoronin** [Azanor/thaumcraft-beta#815]
Learning a focus doesn't start with stage 1
![default](https://user-images.githubusercontent.com/37004902/40283191-a3f81e34-5c93-11e8-81d2-ced586087fa6.jpeg)
![default](https://user-images.githubusercontent.com/37004902/40283160-5c4c821e-5c93-11e8-8c0d-ed599d3ef235.jpg)

**Comment by Azanor** [comment]
What version of TC is this? It works fine in B16
