### ISSUE TITLE
[TC6.1-B13][Minor] Enchanted Pickaxes in ArcaneBore don't display correctly

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#817]
Basically just loses all texture of the actual pickaxe and just shows the enchantment effect over the pickaxe's silhouette. Don't know if that's a missing alpha thing or a lighting thing, maybe, but I am not one to know at this point.

Edit:
![](https://camo.githubusercontent.com/b2f460d87664bbb2d0c5a16356f61bfc4dbbad78/68747470733a2f2f692e696d6775722e636f6d2f4d566f6e4633772e706e67) (thanks booker)
JEI x179
TC6.1-B13
forge x2702

**Comment by Geethebluesky** [comment]
Is a screenshot possible? Using any shaders, Optifine etc.?

**Comment by MalkContent** [comment]
is this not happening for you?

**Comment by Geethebluesky** [comment]
I can't test, still haven't unlocked the Break seal (no luck with enchants.)

**Comment by Geethebluesky** [comment]
Fair enough :)

**Comment by bookerthegeek** [comment]
Here.

![Proof](https://i.imgur.com/MVonF3w.png)

**Comment by Geethebluesky** [comment]
That's... not what the guy above was talking about. Or that screenshot was REALLY needed after all because I was imagining something 100% different.

**Comment by Geethebluesky** [comment]
You do know people post bugs that are Optifine-related, mod-related, produced by all sorts of reasons, and it's up to whoever submits to prove they've done due diligence in isolating why it occurs, right?

Anyone else pitching in is a bonus but not required?

**Comment by MalkContent** [comment]
guess I've grown more minimalist at bugreport no. 5 today
should have spent 15 minutes to write a full report so aza doesn't have to do a 30 second check on a thing that happened before and to indulge anyone else that doesn't want to spend their 30 seconds and wants to know what is going on because of reasons.

**Comment by Geethebluesky** [comment]
You *could* have said, in your initial report, that this was also present in versions before because this isn't a private line of communication between you and the author, but instead you're wasting all this time having an ego. Just cut it out and go back to playing, you should know better than to do this.

**Comment by Geethebluesky** [comment]
Your username suits you, and you are spoiling for a fight, I'm not your punching bag, so prove you're the bigger guy here by focusing your replies on the actual purpose of the forum.

**Comment by MalkContent** [comment]
Why thank you. To concede a point, this would have been a prettier bug report with a screenshot, mod list, etc. But you don't get to walk away here with your head high either. You took the time to post the request for the things I was missing, during which you could have easily recreated the issue, which you then still didn't do when I asked if the issue wasn't present for you. Then you see a screenshot and continue the spam by affirming that that, in fact, is a screenshot and you were "imagining something 100% different". Thank you, that was an important point for the issue. You could have left then and there, but you gotta keep on the spam and get personal. Luckily, I am always spoiling for a fight with selfimportant people like you. You can take your "bigger guy" and "actual purpose of the forum" and shove it right back where it came from.

**Comment by Geethebluesky** [comment]
Do you not understand that some of us have jobs and I can't exactly setup Minecraft at work, but I can at least try to eliminate possible causes on a forum I do have access to? Do you not understand that writing literally one more sentence: "Btw this is a bug from previous versions too" would have meant there was no need to even try to eliminate basic causes?

Do I need to quote where YOU got personal on me, first??? Wtf. You have reality-bending issues going on or what? 

And you're *still* not following your own advice to keep on topic, or does that not matter somehow?

I don't need to "hold my bead high,", I haven't lost anything here and neither have you (I hope??), everyone makes mistakes now and again, but you seem to have a real way of gnawing on a bone here.

**Comment by MalkContent** [comment]
I am not freaking posting an issue for YOU to understand, I am posting it for the dev.
And if pointing out that you are spamming the issue feels like a personal attack to you, you probably feel personally attacked a lot.
And you can bugger off with that "following my own advice" here, this issue has gone off the rails some 2-3 posts ago. YOU feel free to stop the train anytime you feel like it. I for one don't if it means that you get the last word, bigger guy.

**Comment by Geethebluesky** [comment]
[Here is some reading](http://todogroup.org/opencodeofconduct/) I suggest you give a bit of time to. Now, have a good night.

**Comment by MalkContent** [comment]
You're selling bibles you never finished reading yourself. Same to you.

**Comment by Geethebluesky** [comment]
Considering I've been friendly and respectful throughout, yet you accused me of getting personal on you when you were the one doing so, and I doubt you're willing to follow your own advice about keeping on topic at all, yes, I can say I have read this, but I'm sure you haven't, or you don't care.

**Comment by MalkContent** [comment]
Well that's just not true. And once again bugger off with the "follow your own advice", that's just "shut up" coming from you. The best part of this is, that this all would have been over, but you can't let this go, can you. You might argue that neither can I, but you are in this because you can't take not having the last word on that level. I can't take not having the last word just to spite you.

**Comment by MalkContent** [comment]
Well okay, I am so glad that pointing out that I am not following my own advice (and the fact that I adviced something is you putting words in my mouth) wasn't meant as a "shut it". I am glad that you are so very interested in my betterment by trying to help out my selfawareness, you friendly, respectful, bigger guy.
However I can assure you that you are very much the object of my anger here. You added nothing to the issue and as far as i can see, your ideal is just being as full of yourself as humanly possible. As said before, I don't like people like you, so there's my reasons.
And I swear to god this is gonna end in us both just posting "No u." (I know, I know, you're above that, you'll post some more eloquent version of this) in a loop.

**Comment by Geethebluesky** [comment]
the fact that you advised something is putting words in your mouth.... Okay, not following there.

It's kind of stunning that I would have so much power over you though, but alright? I'm the target of your anger right now. Why choose to be angry? Why not do something else that, I dunno, just _feels _? If we're gonna keep doing this I may as well try to understand your motivations here. 

You do realize your anger isn't really going to do much to me? Isn't going to solve your "problem" with me?

I'm sorry that you can't believe someone would choose to try to be empathetic instead of using this to boost themselves.  This is kind of an over-the-top reaction to a random miscommunication on a game's issues forum. That's why I have trouble believing little old me is somehow ALL responsible for you feeling _spiteful_.

The "No u" was done about 45 minutes ago, and it went nowhere. Not going to revisit that. :)

**Comment by MalkContent** [comment]
yea, being angry at you is not much of a choice. and it does make me feel better.
especially when it obviously has impact.
I'd tell you to read over this comment chain in about a week and look at yourself in the mirror, but you done gone and deleted a good chunk of it.
So I'd say my anger did do something. How about you give being empathetic a try. Some jackass just added questions to my 2 sentence issues without checking, which were perfectly legitimate. Then I didn't feel like going through the motions, so told him to go see the issue for himself, which admittedly isn't helpful. Then luckily someone that had a screenshot handy from another issue came along so finally said jackass could have a look at the issue. Finally! He could visualize the issue from his position of absolute powerlessness in regards to what to do with it now. How could he have been so confused about it? The world must know he interpreted the description of what this would look like way different, akin to an IKEA manual without pictures. There. But what is that? someone pointed out that he added nothing to the issue so far? Ohno, better tell him about all the possibilites that have gone unhandled. Whatwhatwhat? He doesn't care about me? Nonono, I, the friendly, respectful, bigger man can't let this stand

> "You _could_ have said, in your initial report, that this was also present in versions before because this isn't a private line of communication between you and the author, but instead you're wasting all this time having an ego. Just cut it out and go back to playing, you should know better than to do this."

and so on and so forth
How about you deal with the fact that you added nothing here, but had to play issue-correctness-police for your own ego and when it got scratched even in the slightest, you feel the need to defend just about everything you do and make other peoples egos,them "obviously being pissed at something overall" and them having "reality-bending issues". You friendly respectful guy, you. You are a condescending selfimportant jackass that reaches for technicalities to deflect any critique of your conduct while just shotgunning diagnosises onto other guys to see what sticks, stunned by "so much power". You are the worst kind of people, you could be fucking president of the usa.

**Comment by Geethebluesky** [comment]
Oh hey, being empathetic doesn't mean being a doormat, and you're still not behaving like someone rational, so I'll just let you finish your tirade which I would have assumed would have died down after sleep, but meh.

I'm really not responsible for your choice to be angry, despite what you think. And I'm not the one who needs to throw barges of insults at someone in a futile attempt at making them feel _something_.

Have fun though!

**Comment by MalkContent** [comment]
Why it wasn't quite the first thing, but I was pretty sure that you wouldn't stop, because it would be so unlike someone like you. So yea, really. And keep trying to tell me that I am chosing to be angry. I am still just here ~so I don't get fined~ because you're a jackass and I am enjoying myself thoroughly in the process.

**Comment by Geethebluesky** [comment]
Hey, I decorated your posts so there's more love and joy emanating from them, I hope you like it :1st_place_medal:

**Comment by MalkContent** [comment]
♡
