### ISSUE TITLE
Thaumcraft and ftb utilities (use seal) thaumcraft b13

### ISSUE THREAD

**Issue by larskr96** [Azanor/thaumcraft-beta#818]
When i have ftb Utilities and thaumcraft installed the golem will not Place a Block or anything on the seal

not sure if its thaumcraft or ftb so i posted on for each of you
https://github.com/LatvianModder/FTBUtilities/issues/734

**Comment by LatvianModder** [comment]
I don't see azanor ever replying to issues, I'm guessing its Thaumcraft issue. Most likely not using fake players correctly, so Im gonna close it here

**Comment by larskr96** [comment]
With the ftb Utilities the use seal does not even work in a unclamied chuck

**Comment by enderger** [comment]
Do you have mobGreafing turned off(do creepers leave craters?)

**Comment by larskr96** [comment]
yes i have mobgreafing turned off
but i have come around it i just turned of the chunk claiming feature for ftb utilities

**Comment by enderger** [comment]
Mongreiefing effects thaumcraft golems

**Comment by Azanor** [comment]
This should be working in b15, but re-open this if it doesnt.

**Comment by 016Nojr** [comment]
@Azanor It doesnt, a server crash happens when an arcane bore tries to dig  will provide crash log in a few hours.

**Comment by LatvianModder** [comment]
@Azanor Why do you use FakeNetHandlerPlayServer? Please don't add that to your fake player. FakePlayer's connection is supposed to be null. And FakePlayer UUID never should be null. Use something like UUID.fromBytes("FakeThaumcraftBore".getBytes()) as UUID

**Comment by LatvianModder** [comment]
I fixed it on my end with nullcheck for UUID but that's not how it's supposed to be. Some other mod might crash again later
