### ISSUE TITLE
Thamatorium issue selecting new recipe

### ISSUE THREAD

**Issue by Lohoydo** [Azanor/thaumcraft-beta#819]
I've noticed that if you have a recipe selected in the thaumatorium, and insert a different catalyst, you may not be able to select the last recipe for the new catalyst.

Version: B13
Pack:  modified DW20 1.12
Steps to reproduce:
1) Make a nitor
2) Put it an iron ingot
3) deselect the nitor recipe, scroll down and try to select the thaumium recipe (can't select)
4) close and reopen thaumatorium to select thaumium recipe.

**Comment by Geethebluesky** [comment]
This has been raised in #652 if I'm not mistaken, but explained differently.

**Comment by Lohoydo** [comment]
these are actually separate issues (though possibly linked).  #652 has to do with preventing autocrafting another of the previous item, this one is the inability to select a new item to craft.
