### ISSUE TITLE
Forbidden Research Ideas

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#82]
- **Wisp in a Jar**
*Research aid for Auromancy. Drains vis from the aura. Occasionally produces arcane curiosities. "So it IS possible! You knew the warded jar could hold almost anything inside it, but you weren't sure it would be able to trap a wisp, even after double and triple checking your math..."*

- **Taintacle in a Jar**
*Research aid for Eldritch magic. Produces Flux in the aura, and occasionally produces twisted curiosities. "You managed to jar one of the taintacles for study. The way it squirms is kind of cute... you've become oddly fond of it." *

- **Totem of Dusk**
*Decorative block that is unaffected by Taint. It glows faintly. Flux Crystals grow very slowly on this material regardless of the level of flux in the aura, and they grow x2 speed when there is flux present.*

- **Brazier of Souls**
*Increases the spawn rate of dangerous mobs and ignores light sources nearby. Mobs that are killed in the light of the Brazier of Souls drop **Soul Fragments** as a rare drop. Phantasmal entities such as wisps and ghasts have a much higher percentage chance to drop. Villagers and players have a 100% chance to drop.*

- **Soul Fragment**
*Placable like Nitor. Emits a quiet moaning noise. Crafting material used for the **Think-Tank**, as well as other constructs and devices that require more than programming, but actual sentience in order to function as intended.*

- **Mask of Cruelty**
*Gives you the 'Deadly Gaze' status effect. Has warping I.*

- **Charm of Souls**
*Chance for slain mobs to drop their souls, much like the brazier of souls. Has Warping I.*

- **Nightmare Fuel**
*As yet unsure what this would be used for... but it's such a cool concept. Maybe this is one of the last reagents / end game research items needed to unlock the truth. "By crafting a void-seed with a soul fragment, you create a twisted, tormented soul, burning in everlasting agony."*

- **Hellfire Furnace**
*A blackened version of the Infernal furnace, with green flames. Hellishly efficient and devilishly quick.*

- **Dark Infusion Matrix**
*Dark infusion allows you to create recipes with the "ludicrious" instability tag (instability that is impossible to craft using the normal altar). Instead of fighting against the instability, you choose to embrace it. The dark infusion altar drains flux from the aura as the infusion progresses. If you run out of flux the infusion fails and it explodes CATASTROPHICALLY, as well as firing off several instability effects such as damaging your armor, draining your experience, summoning monsters, increasing your warp, generating taint, etc. it is possible to dampen the instability of Dark infusions using artifacts (soul fragments, taintacles in a jar, etc). I like to think of this as like trying to soothe an angry beast rather than cage it) These artifacts would simply lessen the severity of the instability events, not their frequency. When crafting using this altar You just have to contend with the erratic nature of the infusion and keep the flux level above that which is required or else fail in your attempt.*
  
*"This matrix is the final piece of the puzzle in creating what other thaumaturges churlishly call a 'dark' infusion altar. This experimental altar uses asymmetry and the instability it generates as a power source! You used to think of Flux as merely as a by-product of haphazard magic... but it can be so much more. In order to bend the rules of reality itself, much like a form of quantum-judo, with this matrix you can now use the weight of reality against itself. The harder it tries to buck your attempts to meddle with its rules, the easier it will be to break them."*

- **Warded Tank**
*"Much like a warded jar these larger constructions are reinforced with void metal and can hold all manner of things - not just essentia by the barrel, but the souls of the damned and much more besides! You've even been toying with the idea of trapping... one of **them.**"*

- **Think Tank**
*Basically a central-nervous-system for your golems. Keeps a record of all seals, golems, and inventories it can see. It has a range of 16 blocks. 
"One zombie brain can't think very hard... but a collection of zombie-brains infused with the souls of the damned? They can do so much more. You have decided to put this "think-tank" as you call it to work, cataloguing your vast stores of essentia and raw materials. What new wonders can you uncover now that you can micromanage your golems activities from the comfort of your study!"*

- **Eyeball in a Jar**
*Point one of these at a seal, golem or inventory with the golemancers bell. It has a range of 16 blocks. Anything it can see, the Think-Tank it's attached to can also see.
"It's a big eyeball, floating in a jar. It never blinks, and you get the feeling it sees... more than it lets on."*

- **Necromancy Focus**
*Converts a Zombie / Brainy Zombie / Husk / Skeleton / Wither Skeleton / Stray to your cause. Using this on a pig creates a zombie pigman. Using it on a horse creates a zombie or skeletal horse (these can be saddled and ridden). Using it on a villager creates a zombie villager (maybe friendly zombie villagers will trade with you for unique swag?). "Using this focus you can pervert the circle of life and death and create a puppet to use for your own ends."*

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#164
