### ISSUE TITLE
Golemancy issue: are whitelists broken?

### ISSUE THREAD

**Issue by Maniklas** [Azanor/thaumcraft-beta#824]
I was trying to automate my thaumatorium's production of leather and alumentum, however when I made a fill seal, selected whitelist and put in rotten flesh and coal, it didn't work for some reason.

I have a chest 5 blocks away with a provider seal and filled it with one stack of flesh and one of coal.
I have a deft and smart greatwood golem in control of the system.

**Comment by larskr96** [comment]
that is not going to work look at this
![skjermbilde](https://user-images.githubusercontent.com/10383027/40306531-512c3c14-5cff-11e8-9c7d-56773ee5f270.PNG)

**Comment by Azanor** [comment]
Yup, but check out the stock seal added in B14 - it does exactly what you want.
