### ISSUE TITLE
Game completely crashes when coming near a magic forest(?)

### ISSUE THREAD

**Issue by karaneesama** [Azanor/thaumcraft-beta#826]
I installed a bunch of mods to get into a magic run and when I started a new world, I spawned close to, what I think is, a magic forest. The leafs turn a bit blue-ish and it's a fairly packed tree line. My game will crash almost instantly from just being near it or looking towards it.

I tried to turn Thaumcraft off, move into the forest, then turn it back on, which lead to some interesting events(Silver trees were re-constructed in the same spots, but not correctly), but my game didn't crash anymore. Though I assume that certain ores or something were removed because there were holes in the ground left and right.

The pic below was a screenshot I took after my game crashed. Moving closer crashed my game again. I am not getting a specific error when the game shuts down, except the standard "Minecraft has run into an unforeseen issue"
Pic of the area/biome I'm talking about:
![2018-05-21_15 02 35](https://user-images.githubusercontent.com/39488467/40308911-06e8513e-5d08-11e8-9749-bcab9d681919.png)

Most recent logs:
https://pastebin.com/ru0FWjmN
https://pastebin.com/4kkHK88b
https://pastebin.com/2kne34rN

All from today

I hope this will be enough information

**Comment by AlekseiVoronin** [comment]
Known Issues: There currently seems to be a conflict with the Hats mod and pech. If you are having problems you can either disable pech spawning in the configs, or switch off modded mob hats in the Hats mod.

**Comment by Azanor** [comment]
Yup, this is a known compatibility issue with the hats mod.
