### ISSUE TITLE
[Suggestion] non-creative "staged/tier" Flux Sponges

### ISSUE THREAD

**Issue by Thunder-Nova** [Azanor/thaumcraft-beta#827]
## Moved to Thaumcraft-Suggestion
**please do Reply there** https://github.com/Azanor/thaumcraft-suggestions/issues/278
##

I do love on how Thaumcraft is growing up to be, yet would love to see a non-creative way to thin out the flux without being too Over powered. When I saw the Creative Flux Sponge and how it works, it got me thinking.

Having a stage/tier type flux sponge. Each with their own limit.

Plus adding to the equation, 2 types of Flux tanks

And variations of the already existing Tubes as Flux Tubes

For this, 

## Crafting and Ability
One obvious way to create a flux sponge is using Sponges, but the lowest tier would use Yellow Wool. (I will say shards, but it's Vis Crystals)

I have 4 tiers in mind.

-  **Tier 1**: 1 Use sponge, it gets destroyed as soon as it is used, Flux gathered is destroyed. As for crafting it uses a lot of Ordo, Aqua, and Ignis.  1 yellow sponge at the center, and 3 Vacuos Shard same crafting shape as a bucket.

-  **Tier 2**: 1 use Sponge, but gathers double the flux then Tier 1, and stores it, but destroys once emptied. Same recipe as Tier 1, but uses a minecraft sponge, instead of the yellow wool. Reason which I won't change the recipe much is that to get sponges usually we get them in underwater temples. Unless a mod that makes them easier to get.

- **Tier 3**: Low Storage Sponge, won't be destroyed. Stores as much as a tier 2 sponge. Crafted using the Infusion Altar, Sponge in the center, 3 Vacuos Shards, 1 bucket, and 2 Praecantatio shards. Uses 1 whole Jar of Ordo, Aqua, and Ignis' Essentia.

-  **Tier 4**: High Storage Sponge, won't be destroyed. Stores 10 times more then a tier 2 sponge. Crafted using the Infusion Altar, Tier 3 Flux Sponge in the center, 3 Tier 1 Flux Tank. Uses 2 whole Jar of Ordo, Aqua, Ignis' Essentia. and 1 whole Jar of Vacuos, and Praecantatio Essentia.

- **Tank Tier 1**: Can fill up with flux Gas, it will let out all it's contained flux if broken, or moved. Can't be piped. Usually for quick cleanup. Crafted using Arcane Workbench, Magic Tallow Surrounded with 4 Vacuos Shards in the corners, a crucible at the bottom, and 3 Glass blocks. Giving more use to the Magic Tallow, as a way to store the flux as an sort of a seal.

- **Tank Tier 2**: Same as above, but won't lose it's contained flux. Can be piped with pipes specified to move flux. Crafted using an Infusion Altar, Tier 1 Flux Tank in the center, 4 Directional Flux Tubes, and 2 Mirrored Glass, 1 Thaumometer, 1 redstone comparator. The idea behind the Mirrored Glass is that it's a magical glass, can be used to prevent flux from escaping, as with the Thaumometer, plus the effect of the Thaumometer makes it easier to monitor the Tank with diverse ways to for redstone signals (Such as emit when empty, full, 1/2 full and so on). Plus it's the only See-Through object.

- **Flux Tube Variety**: Making it simple: Just add any Essentia Tube with a Vishroom, and Silverwood Plank.

## Reason for using Gas instead of Liquid

Mainly due that many mods does use liquids mostly for pipes, in case of Gas, It's less used and even rarer to pipe, though I would think it's still possible so I am stretch in using the "Essentia" instead of Gas, but it can't be used for Infusion Crafting.

Anyhow, I want to avoid using other mod piping. And perhaps a way to convert the flux into it's liquid form. Using only Thaumcraft system.

**Comment by Tyrion216** [comment]
I love this idea and think maybe there can be an addition as well. Since vitium essentia is kind of hard to get and pretty much requires tainted land somewhere and for you to go mine it and smelt it and get a little bit of vitium, one could refine the gathered flux. The easiest way I can think of would just be with the crystalizer. This would avoid having to put a new machine in the mod that turns flux into liquid vitium. This may defeat the purpose and be just as much work as mining taint, but that is just a thought. Perhaps the centrifuge could be of help in turning flux into vitium. That way its still in liquid form and doesn't require any smelting. But its output would be very small. Only maybe like 20% of flux actually turns into liquid vitium. I feel like this is a good exchange since vitium is useful later on, and requires that you pump lots of flux into the aura to get even a usable amount of vitium.

**Comment by Thunder-Nova** [comment]
Yea
The main idea is both, cleaning flux and even using the flux itself, I also though that in early game it shouldn't be a too OP method, in which that it cost more then later on in-games, but it at least helps in clearing out the flux in the environment.

Plus taking your idea into account, it does improve on the idea of having the 2 tanks, 1 for storage only, the other which can be used for a production system.

**Comment by enderger** [comment]
Please put this [bit.ly/TCSuggestions](Here)

**Comment by Thunder-Nova** [comment]
Ok, moved it, with the reply
