### ISSUE TITLE
[Suggestion] Deeper Green Magical Forests

### ISSUE THREAD

**Issue by Tanto17** [Azanor/thaumcraft-beta#831]
Hello,
First thank you for an amazing mod! Really enjoying the feel of the new research. 
One thing I would really like to see looked at is the color of the Magical Forest Biome. For me the current light color of the biome does not sit well with the rest of the mod. We have accumulated more dark and warped things in Thaumcraft over the years and I think the color of the biome just is not as good as it use to be. In my opinion Thaumcraft has an somewhat gritty/eerie and dark feel to it. I would really like to be able to settle in one of the beautiful magical forests but I always find my base clashes with the grass and foliage colors. Yes, I know, I am being picky. However, I do already see that there is a config to enable the old blue textures. Would it be difficult to add a deeper green config option?

For example #1a6d1b (hexadecimal - can see via "color picker" on google) as grass and #09601c as leaves (would need some testing).

I think the deeper richer color would make the magical forests more popular base locations and fit better with the rest of the mod.

Thanks for the consideration. 
Thanks for the mod.
Enjoy creating.

**Comment by AnrDaemon** [comment]
You can change biome color map with resource pack.

**Comment by ViciousVinnyD** [comment]
I agree, I always felt the ideal "thaumcraft" biome would be that of a dark green, greatwood populated forest. Similar to the roofed forest but a lighter shade of green from that.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#379
