### ISSUE TITLE
How do you get essentia phials without essentia tubing?

### ISSUE THREAD

**Issue by lokiwolf** [Azanor/thaumcraft-beta#837]
Apparently I need the phials to learn how to make the tubing, but I don't know how to get the phials without the tubing.

I'd try the FTB Wiki but its skeletal and I strongly doubt I'd find anything helpful.

**Comment by nop277** [comment]
i think you can phial the stuff right out of the arcane alembics

**Comment by Trigition** [comment]
You can right click with a phial on an alembic (or any container for essentia as long as there's more than 10 of it).
