### ISSUE TITLE
Bore/turret enhancements

### ISSUE THREAD

**Issue by GeneralStukov** [Azanor/thaumcraft-beta#839]
When working with the arcane bore I notice it has no real way to deal with lava, I have a suggestion to let it be upgraded through the golem press to allow for some upgrades for finer control.perhaps using aqua crystals to allow it to use vis and turn lava source blocks in the beams area to turn to obsidian and to void flowing lava or allow for a tank to be attached that holds a certain amount before voiding the rest.

Another suggestion is the automated turret can allow foci upgrades allowing for spells to be cast by the automated turret. Also would love to see essentia mirrors to have an end rank that allows for dimensional rift travel in addition or a separate rank. You could use an upgraded mirror to link and it could use the sweet rift textures.

**Comment by GeneralStukov** [comment]
Also with the way vis is rechargeable with the boots of the traveler and other objects, could the thaumostatic harness come back? And allow it to be attached to the thaumcraft armor (fortress,crimson,thaumium,void) would be cool, could also have cool graphics to add to it. Would also like to see a way to "work" with flux, aka being an evil thaumaturgist, securing rifts and manipulating taint.

More spells like poison, life drain, turn undead (limited control of undead) animate the inanimate (summoning golems from blocks like a stone golem, flesh golem and gives more of a use for insane amounts of flesh a minecrafter accrues) a foci for it could require the simple mechanism or higher for its construction. More uses for Amber perhaps such as a prison foci,using the ward blocks as a base.

Primordial pearls feel good now,having a damage bar feels like it's more precious. More multiblock construction perhaps for opening or controlling rifts to use them to make it to the outer lands. An item piping system would be nice too, I love essentia tubes but they feel short lived once gaining access to the "wireless" essentia system.

I've got tons more ideas but I didn't mean to rant on,I just feel like there should be an option for going good or evil and working with either flux or aura with one's alignment. Would allow for varied paths on server play and give each player a sense of identity.

**Comment by Wotzinator** [comment]
yes but thaumic horizons is on 1.7.10 and it doesnt seem like its being maintained

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#378
