### ISSUE TITLE
Beta0; Vis Cystals Disappearing from chests

### ISSUE THREAD

**Issue by LordPinkerton** [Azanor/thaumcraft-beta#84]
I've noticed this for the past few builds, but I haven't been able to find any correlation with what's been causing it, so I've refrained from posting the issue. However, seeing as it's still present, here's the issue.

Basically, stacks, and not always whole stacks, of vis crystals are reduced to a single crystal within chests. I can't find exactly what's causing this. This doesn't affect every stack, just some. Sorry I can't provide more information as to the cause. What I can say is I'm running a pretty bare bones modpack with Thaumcraft. Here are my mods.

Appleskin 1.0.9
Chameleon 2.3.0
CodeChickenCore 2.4.1.102
CodeChickenLib 2.5.9.320
compaylayer 0.3.0
Gravestones 1.5.13
InventoryTweaks 1.61-58
IronBackpacks 2.2.33
IronChest 7.0.15.804
JEI 3.14.7.420
Journeymap 5.5.2
MoreOverlays 1.11
StorageDrawers 3.7.10

I'll try and pay more attention to every interaction with the chest containing the crystals to find the cause. Hopefully others have had the same issue with more information.

**Comment by Goof245** [comment]
FWIW, I've seen this happen on servers with very similar modlists, only it's happened to random stacks of any item.

Seems to be a desync issue then, re-opening the inventory and / or sorting it with R or middle click kinda fixed it then for me.

**Comment by LordPinkerton** [comment]
Sorry, I should have added that this is happening in my single player game, so I doubt my particular issue has anything to do with desync. And, it's only happening with vis crystals.

**Comment by Goof245** [comment]
SSP still runs a client / server system, so it's very possible to have desync issues if someone's screwed something up while coding a mod or maybe forge itself.

**Comment by LordPinkerton** [comment]
Was speaking more in reference to actual server desync due to packet loss, etc. I truly don't believe any of this has to do with this issue.

**Comment by Azanor** [comment]
Vis crystals are just a normal item like any other. There is no code that interacts with them in inventories at all on my side. Whatever is causing this should probably be effecting all items. 

I will keep this open however - maybe someone else is experiencing the same thing.

**Comment by 755437985** [comment]
I think I have experienced the similar thing for times. When I hold the Shift key to check what the vis crystals contain, some of those stacks may reduce to a single one. This randomly happen in my inventory(not sure if in the chest).
I am running thaumcraft along with the following mods.
CodeChickenCore-2.4.1.102
CodeChickenLib-2.5.9.320
JEI-3.14.7.419
NotEnoughItems-2.1.3.220
OptiFine_1.10.2_HD_U_E7

**Comment by UnixRonin** [comment]
@LordPinkerton, my modpack has a number of those mods in common — CodeChickenCore, CodeChickenLib, InventoryTweaks, IronChest, JEI, Journeymap — and I am not experiencing any such problem.  InventoryTweaks does have a long and undistinguished record of sync problems, but usually they only impact player inventory.  (Though not always — last night IT kept **insistently** shoving a stack of SlashBlade mod BladeSouls into my hand every time I sorted a specific chest, which by coincidence also happens to hold all of my vis crystals.)

**Comment by ArtOfCombat** [comment]
Bigger modpack, same issue. I'm running FTB Beyond+TC 6.0.Beta2 and all the vis crystal stacks in one chest were reduced to 1. No other items or chests have been affected yet.

**Comment by ArtOfCombat** [comment]
Ah- I scanned that chest before they vanished. Will test if that was the cause.

**Comment by ArtOfCombat** [comment]
YES IT WAS. Scanning a chest containing Vis crystals reduces the stack size to one!

**Comment by LordPinkerton** [comment]
I was actually thinking along these lines as well, but every time I tried, it would get inconsistent results. Still, awesome that you confirmed the link.

**Comment by LordPinkerton** [comment]
Also seems to affect Block of Flesh.

**Comment by UnixRonin** [comment]
Vanilla chests:  Confirmed.

And since I had a few other storage methods around to test and see how widespread the issue is:

Iron Chests:  Confirmed.
Ender Storage mod Ender Chest:  Confirmed.
Router Reborn mod Storage Units (a barrel type, not a chest):  Confirmed.
Bibliocraft shelf:  Confirmed.
Bibliocraft potion shelf:  Confirmed, with the note that I'm not totally certain the shards on the potion shelf were "read" correctly.  But I might have just held the mouse button down a fraction too long, or it  might be that the shards were read but I didn't learn anything new from the potion shelf itself.

**Comment by UnixRonin** [comment]
A post on the Thaumcraft 6 forum suggests this may also happen if you drop a stack of crystals on the ground and scan them.  Is it perhaps not strictly limited to inventories, but a **general** bug relating to scanning stacks of vis crystals?

I just tested this as follows:
— Spawned a stack of essentia into my inventory using NEI
— Threw it on the ground from my inventory
At this point one of two things will happen.  **Either** the stack will look like a cluster of crystals all rotating together, **or** it will look like one single crystal.  Either way, if I pick it back up **without** scanning it first, I will pick up the full 64 crystals, the whole stack.  If it looks like a stack when dropped on the ground, then I can also scan it and safely pick the entire stack back up.

However, if it **LOOKS** like a single crystal, if I **scan** it and then pick it back up, it will **BE** a single crystal when picked back up.

The "looks like a single crystal when dropped" state _seems_ to occur only if I put the stack in my inventory **from somewhere else** (a chest for example) and then immediately drop it on the ground.  If I pick the stack back up and then drop it again, it appears to always drop as a whole stack.

**Comment by Azanor** [comment]
I have managed to replicate it myself by simply hovering over a stack of crystals. Now to figure out what is causing this.

**Comment by Azanor** [comment]
Turns out certain recipe items (usually crusible recipes) where having their stacksize set to 1 and specific circumstance. Doh.
