### ISSUE TITLE
B13:  Taint outbreak:  Questions/suggestions

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#853]
So, I got my first taint outbreak in 1.12.  Small outbreak that satisfied the flux research objective, right by my essentia smelter.  Fairly readily overcome with a good bow to kill the taint seed from a survivable distance.  I need to make a better bow though.

Observations:
1.  Tainted soil is **really** hard to break.  Harder than obsidian.  Is it really **meant** to be that hard to break?  It's almost the only source I've found so far of vitium.  (Mycelium has vitium, but I haven't found any mycelium yet.)
2.  Sand gets turned into tainted soil which, as the taint dies and fades, reverts back to ... dirt.  Perhaps there should be a separate tainted sand block as well?

**Comment by apemanzilla** [comment]
Using a focus with plan and break or exchange is a good way to collect tainted soil pretty quickly. If you're using it, Tinkers Construct knightslime also makes short work of it, especially combined with haste modifiers.

**Comment by Geethebluesky** [comment]
Point 2 was discussed at #607 if you're interested.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#377
