### ISSUE TITLE
taint geysers do not act like monster spawners.

### ISSUE THREAD

**Issue by MACMAN2003** [Azanor/thaumcraft-beta#857]
When I speed up stuff with the randomtickspeed gamerule taint geysers spawn a lot of taint swarms which eventually overload and crash my game. so I propose that you can make the taint geysers act like monster spawners and only spawn limited amounts and only when players are near.

**Comment by Azanor** [comment]
They already only spawn when the player is near, but I did not limit their amounts. I will fix this for b17.
