### ISSUE TITLE
[B15] Using Salis Mundus to create any in-world object crashes

### ISSUE THREAD

**Issue by kd8lvt** [Azanor/thaumcraft-beta#860]
All the crashlogs are the same, so here is one that came from the Arcane Worktable. [https://pastebin.com/40U0PkT1](https://pastebin.com/40U0PkT1) It might be a conflict with TexFix, as I haven't tested without it one yet, but I know for a fact it isn't an issue with Optifine or FoamFix as I've tested without those mods, and the log was the same. Other than TexFix, I'm not sure what would be causing it. I'll look further into the error, and edit with my findings as I go.

Edit 1: It's still occurring with TexFix. On to the next mod!

**Comment by Osiris554** [comment]
It seems to be an issue with the particles. It happens when you use the cloudsteppers ring, and when you use the crucible.

**Comment by kd8lvt** [comment]
Ah ok, so it's not a mod conflict. Gotcha. Does reverting to B14 fix it?

**Comment by enderger** [comment]
@azanor, this bug is game breaking. Please release a patch ASAP

**Comment by kd8lvt** [comment]
Duplicate of #858
