### ISSUE TITLE
Beta1; Basic Thaumaturgy research stage 2 issue 

### ISSUE THREAD

**Issue by Zebia** [Azanor/thaumcraft-beta#87]
Basic Thaumaturgy stage 2 requires the crafting of a focal manipulator but doesn't unlock said crafting. Even using the cheat sheet to skip to stage 3 doesn't unlock focal manipulator crafting

**Comment by LordPinkerton** [comment]
Jump into a fire to satisfy the research requirement and see if that allows it.

**Comment by Zebia** [comment]
While I'm happy to try that again, it doesn't address the bit where the cheat sheet does not unlock the focal manipulator recipe even though it's supposed to unlock everything in the Thaumonomicon

**Comment by Zebia** [comment]
Just burnt my character to death, no change.

**Comment by Azanor** [comment]
It was a missed research entry still referring to thaumaturgy instead of auromancy that was hiding the recipe.

**Comment by Goof245** [comment]
@Azanor note there were 5 of them that I found in the Beta1 jarfile: 
![screenshot 128](https://user-images.githubusercontent.com/3851003/35209454-c5b827a0-ff99-11e7-9ca1-5c41fd678a06.png)
