### ISSUE TITLE
Server crash when doing research

### ISSUE THREAD

**Issue by alexanderniebuhr** [Azanor/thaumcraft-beta#88]
Hey,

We used the research table and then the server well "crashed",  more than that we do get a time out dc. And have to force shutdown the server. Unfortanly we don't get any crash-reports this way. So I try to attach all logs I can access.

[fml-server-3.log](https://github.com/Azanor/thaumcraft-beta/files/1649648/fml-server-3.log)
[fml-junk-earlystartup.log](https://github.com/Azanor/thaumcraft-beta/files/1649649/fml-junk-earlystartup.log)
[2018-01-21-1.log](https://github.com/Azanor/thaumcraft-beta/files/1649650/2018-01-21-1.log)
[fml-server-latest.log](https://github.com/Azanor/thaumcraft-beta/files/1649651/fml-server-latest.log)
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/1649652/latest.log)
[serverlog.txt](https://github.com/Azanor/thaumcraft-beta/files/1649653/serverlog.txt)
![timed out](https://user-images.githubusercontent.com/15894713/35192807-2c553b30-fe99-11e7-886c-f47b1bdd99c5.PNG)

Any ideas how to fix this? Any help please?

Cheers
Alex

**Comment by Azanor** [comment]
Hmmm, unfortunately nothing useful in those logs. Please let me know if and when this happens again and post the logs if you can.

**Comment by Azanor** [comment]
Actually that does help - it means something is going into a infinite loop somewhere. I will take a look.

**Comment by EcmaXp** [comment]
I think somebody should process dump or thread status.
My server also affected by this bug.

**Comment by hanakocz** [comment]
@Azanor Actually, on my server we managed to get crash report.
https://gist.github.com/hanakocz/66aeaa6536ea67d09a7caf0643700605
https://gist.github.com/hanakocz/ae0062d2176ed1829490505048210698
It was happening on "rethink" chose, probably when one got additional draw.
