### ISSUE TITLE
Crash in dev environment

### ISSUE THREAD

**Issue by Sunconure11** [Azanor/thaumcraft-beta#885]
https://pastebin.com/yVimtgEq

**Comment by yunruiwatts** [comment]
@Sunconure11 can you give a little bit more detail? What version of Thaumcraft are you running? Did you by chance try out B14/B15, then switch back to an earlier version due to the crashes everyone's been seeing in those versions?

**Comment by Sunconure11** [comment]
B15 in the dev environment

**Comment by enderger** [comment]
Um, @yunruiwatts, the crash report says the loaded jar in the crash

**Comment by enderger** [comment]
Anyhow, the deobf thaumcraft requires codeChickenLib to run.

**Comment by enderger** [comment]
I believe

**Comment by Azanor** [comment]
I believe your API code is out of date as the field mentioned was added.
