### ISSUE TITLE
No more golem automation?

### ISSUE THREAD

**Issue by TheZedi** [Azanor/thaumcraft-beta#886]
I haven't player Thaumcraft in a hot minute so I'm not sure if this was removed a while ago, but I can't seem to get my golem to craft a Thaumium Ingot for me. I know I can just use the Thaumitorium, but I would prefer to use golems because I think it looks cooler and is simpler to setup with a RS/ME system. Its fine though if I can't have my cute little golems spring to life when I request an alchemy recipe. 
__Disclaimer, I have never used GitHub before, so I'm not sure if this is taboo__

**Comment by AnrDaemon** [comment]
That was never the case to the best of my knowledge.

**Comment by TheZedi** [comment]
You used to be able to use golems to automate things like Essentia smelting. I guess that's what I'm referring to

**Comment by AnrDaemon** [comment]
Not smelting, but retrieving distilled essentia from alembics and sort it into jars.
Alchemy core.

**Comment by TheZedi** [comment]
You're probably right. Like I said it has been a while since I've done Thaumcraft. Maybe it could be implemented to allow for golems to use the crucible. They can throw items in, but they can't right click like a player can. Although, this is probably intentional to force players to use the Thaumitorium.

**Comment by Azanor** [comment]
Alchemy golems do not exist in the current version, but if you have suggestions for specific seal ideas please post it on the suggestions git.
