### ISSUE TITLE
[FIX] Infusion Altar still uses old arcane stone textures

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft-beta#888]
I included a resource pack containing updated textures that match the new arcane stone:
[InfusionFix.zip](https://github.com/Azanor/thaumcraft-beta/files/2041878/InfusionFix.zip)

![2018-05-26_20 05 06](https://user-images.githubusercontent.com/10350888/40579496-2dddec10-6120-11e8-9023-ddb078ce89b7.png)

**Comment by AlekseiVoronin** [comment]
It is textures is azanor'a, and don't other texture the minecraft

**Comment by ViciousVinnyD** [comment]
I'm a bit confused, what is it you're trying to say?

**Comment by ViciousVinnyD** [comment]
If you're asking if the textures were made by azanor then no. I just copied the arcane stone texture and stretched it to fit the blocks correctly.

**Comment by enderger** [comment]
This pack breaks Silverwood planks

**Comment by ViciousVinnyD** [comment]
It does, and I'm not sure why this is. The pack modifies 4 textures:

infuser_normal.png
pedestal_side.png
pedestal_top.png
pillar_normal.png

Somwhow silverwood planks are affected by this, despite the pack not modifying anything related to silverwood planks. Therefore this appears to be an issue with thaumcraft.

**Comment by Azanor** [comment]
@ViciousVinnyD Do you have an issues if I use these textures as the base textures?

**Comment by ViciousVinnyD** [comment]
@Azanor Nope, I indended on this being the base textures.

I can also help with future texturing if that helps update the mod faster.
