### ISSUE TITLE
[Question] Flux Scrubber

### ISSUE THREAD

**Issue by Mr3DAlien** [Azanor/thaumcraft-beta#889]
Will the Flux Scrubber return in the next update? 

Because I am playing my own Modpack called TheZeroProject, and I love Thaumcraft. So the Problem is, that I don't really want to use Thaumcraft at the Moment because I already create Taint 2 times already. I don't want to move because I think Minecraft is a game where you should be able to build where ever you want. So I really would like to get rid of Flux.

Or is there already a way to remove Flux?

**Comment by Geethebluesky** [comment]
There's a sponge in Creative mode, but not in survival at the moment.

**Comment by Mr3DAlien** [comment]
Yes I know that one, I already used that one, but I want to play Thaumcraft without cheating so I hope that a way to get rid of flux will be added to Thaumcraft in the next release. Because without it you can't really use Thaumcraft for a lot of stuff, my plan was to make an ore Automation only with Thaumcraft. But it would create much Flux so I have to do Technic instead.

**Comment by Mr3DAlien** [comment]
Ok sorry maybe I don't really understand that but what do you mean with tear a rift, And also wich Item Should stabilize a rift ? there is an Infusion Stabilizer this is only for stabilizing Infusion Crafting.

**Comment by FoxMcloud5655** [comment]
What he means by "tear a rift" is let your flux build up to the point where it creates a tear in space-time; that void-looking tentacle-like thing that you can see through walls.  Then, you use the item that was added last update to stabilize the rift so it continually drains flux from your area without spawning taint related mobs and such.

**Comment by Mr3DAlien** [comment]
But that sucks I mean you can't decide where this rift should go, and then you have it in the mitten of your base.

**Comment by FoxMcloud5655** [comment]
I mean, isn't that the nature of volatile magic?  Also, I believe that the
rift always spawns as high up as you can get it, so you could always build
a platform high up in the sky before you try to summon a rift for
stabilization.

>

**Comment by Geethebluesky** [comment]
I've had a rift spawn at ~y=110 with several structures at y>130, nevermind Twilight Forest canopy trees reaching up all the way to 256 or something... not sure if that theory truly holds up.

**Comment by Mr3DAlien** [comment]
I mean Thaumcraft 4 is still my favourite and I know Thaumcraft 6 has nothing to do with it. But I think there should be an easy way to get rid of flux without creating a rift.

**Comment by wamc2017** [comment]
Don't know if azanor adds an alternative option to clean flux, but Planar Artifice (Flux Scrubber) and Thaumic Additions (Puriflower) both are adding options to clean flux more easy... ;)

**Comment by Mr3DAlien** [comment]
I mean I am a fan of Thaumcraft but it just doesn't feel right. I think Azanor will add something to remove Flux in a better way. So I don't want to install a Addons for Thaumcraft which would add an Item to remove Flux in a good way. Because if Azanor finally adds a way to remove Flux on his own, I then would have 2 Mods who would do so. So I personally will wait that Azanor adds this on his own. But my Hope is, that we will see something like that in the next Updates.

**Comment by Azanor** [comment]
Yup stuff is coming soon to handle flux and the rifts
