### ISSUE TITLE
[Beta 14] Casting Gauntlet Render Bug

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#891]
I'm using beta 14 because of bug #858
When I hold the casting gauntlet in the my survival world the skybox seems to glitch out, making a black square around the sun, sometimes some scattered black dots in the sky and the horizon line becomes orange, it doesn't make the game umplayable, just makes it a bit offseting and weird.

**Comment by Geethebluesky** [comment]
Are you using Optifine or shaders?

**Comment by AzraelTWC** [comment]
disable AA from optifine

**Comment by SirKastic** [comment]
AA is disabled, still getting this bug
