### ISSUE TITLE
break focus bug

### ISSUE THREAD

**Issue by gabeernie** [Azanor/thaumcraft-beta#9]
I made a focus with the "bolt" medium, the "break" function, and the "chain" modifier. Attempting to use this focus instantly crashes the game, but upon restarting the world, the block that i was aiming at was indeed broken, however it did not seem to chain to any nearby blocks. I have reproduced this crash 3 times.

Another note on the break focus, if you use it in creative mode, the targeted block is completely destroyed with no drop similar to the normal way of breaking a block in creative. In survival, it works as intended and drops the appropriate block.

**Comment by Azanor** [comment]
Currently chaining doesn't work for blocks. I still need to find a good, lag-free way of doing it, but it is planned.
