### ISSUE TITLE
[compatibility] All chunks with 0 Vis with Cubic Chunks mod

### ISSUE THREAD

**Issue by Velken** [Azanor/thaumcraft-beta#901]
All chunks have 0 Vis with Cubic Chunks. Perhaps addon to fix that?
NOTE: This is not a request for Azanor to fix. This is just to document the issue. If anyone wants to make a fix, that would be welcome. 

[Issue on CC's github](https://github.com/OpenCubicChunks/CubicChunks/issues/378)

**Comment by BaccarWozat** [comment]
Cubic Chunks is a mod allowing much higher and deeper worlds (and more elaborate custom terrain) through 16x16x16 stackable chunks.
CC builds: http://jenkins.daporkchop.net/job/CubicChunks/
Requires MalisisCore to make custom worldtype:  https://minecraft.curseforge.com/projects/malisiscore
CC Discord: https://discord.gg/8QrUYzz

**Comment by Velken** [comment]
Recommended balance: Vis stored in each 16x16x16 chunk and make each chunk 1.5x less vis than normal chunks and make the recipe for the upgrade (which allows to get vis from adjacent chunks) harder to craft (since it goes from 8 neighbor chunks to 26)

**Comment by Barteks2x** [comment]
This is an issue with CubicChunks, because currently it doesn't save chunk capabilities (because last time I updated chunk saving code, chunk capabilities didn't exist yet). I don't think there is anything TC can easily do to use 16x16x16 cubes for storage, so I think the best thing would be if I just made chunk capabilities work, and have everything worm like in vanilla.

**Comment by Azanor** [comment]
Yeah, unfortunately this is not really I thing I can solve.

**Comment by Barteks2x** [comment]
I already added support for storing chunk capabilities, and some people reported that it mostly works, with some of them saying it doesn't quite work beyond vanilla height range. As it is, I don't think there is more either mod could easily do for compatibility.
