### ISSUE TITLE
Crystals being used when not needed

### ISSUE THREAD

**Issue by isaacsbees** [Azanor/thaumcraft-beta#908]
When I craft an item that does not require vis crystals on the arcane workbench, it takes one of each available type of crystal from the slots on the table.

**Comment by Gravityowl** [comment]
Beta 15 is very hard to use right now btw so it may be favorable to stick with the one you have if you wish to continue crash free

**Comment by Lukas45** [comment]
Beta13 is pretty crash free (except the conflict with Ice & Fire). Beta14 should be good as well, as long as you're playing Single Player. Beta15 should you stay away from.

**Comment by enderger** [comment]
Ice and fire works for me

**Comment by enderger** [comment]
With TC

**Comment by enderger** [comment]
B13

**Comment by Azanor** [comment]
This should be have been solved already. Try again in B16
