### ISSUE TITLE
Wrong unlocalized name in .lang file

### ISSUE THREAD

**Issue by TimeConqueror** [Azanor/thaumcraft-beta#909]
So we can see unlocalized name in research "METALLURGY":
![image](https://user-images.githubusercontent.com/25156941/40712864-5f7dc88c-6407-11e8-9152-767e3c932a5e.png)
This takes place because in lang file the key-name is ''research.voidstuff.text=A strange metal" (''c_" is missed).

**Comment by enderger** [comment]
That and the texture

**Comment by enderger** [comment]
And the voidmetal... wait, ELDRICH IS NOT DONE YET! It may be intentional to block accidental eldrich in survival

**Comment by TimeConqueror** [comment]
@enderger This is in lang file: 
![image](https://user-images.githubusercontent.com/25156941/40723160-e1a59884-6426-11e8-8321-1ec57f69f6f6.png)

**Comment by Geethebluesky** [comment]
Reported in #55 a long time ago in a galaxy far away. Probably still is this way because the author isn't done with the Eldritch content.

**Comment by enderger** [comment]
That could be different to allow azanor to test but avoid letting survival players from unlocking unfinished content.
