### ISSUE TITLE
[Suggestion] Allow Flux to travel through Nether Portals

### ISSUE THREAD

**Issue by isaacsbees** [Azanor/thaumcraft-beta#920]
I think it would be interesting to have flux spill through portals, and then to add in another item which can be attached to a portal to prevent this.  This would allow flux to dissipate much faster than normal, flowing into the Nether and equalizing, or the other way around if your nether is full of flux.

**Comment by Geethebluesky** [comment]
https://github.com/Azanor/thaumcraft-suggestions

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#376
