### ISSUE TITLE
Those cracks.

### ISSUE THREAD

**Issue by mystlynx** [Azanor/thaumcraft-beta#922]
So question, 
We just started a world (my BF and i)  and doing things with thaumcraft. Now we got one of those weird starry tendrils. 
It spawned at a point a funky looking thing spewing stuff and we killed it. 
And the world underneath was pretty much drained. (porrous stone and such)

But it won't go away! how do those things go away because the world is kind of not playable anymore now. 
:(
With kind regards, 
Mystlynx
![2018-06-01_00 55 30](https://user-images.githubusercontent.com/28847677/40812369-d004084e-6535-11e8-9801-ed74f816a783.png)

**Comment by Geethebluesky** [comment]
This is a forum for technical issues and bugs. What you're experiencing is a normal part of the game, please read up on the [Minecraft forum thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta15) for help with gameplay.

**Comment by mystlynx** [comment]
I understand but if there is no possible way in the game to remove it and it destroys the world i can consider it a bug right? As it is not acting as intended... and making gameplay nigh impossible

**Comment by Geethebluesky** [comment]
Currently rifts spawn seeds after a while, which you have to find ways to destroy. That's not a bug although lots of suggestions have been made on how to rebalance that. Please use search, it's been discussed in a few issues already.

**Comment by Ulysses2** [comment]
The rift should go away when flux reaches 0, but if this doesn't happen, try running `/kill @e[r=5,type=!Player]` while standing next to the rift. If you want to drain the flux from the area you can use the flux sponge from the creative mode inventory.

**Comment by Azanor** [comment]
The next non-bug fixing update will add ways to remove these.
