### ISSUE TITLE
[Beta 14] Crash when creating focus

### ISSUE THREAD

**Issue by TonyMestre** [Azanor/thaumcraft-beta#923]
When i try to create a new focus, the Lesser Blank Focus becomes invisible and i need to take it and replace or exit and enter the Focal Manipulator. This resets the focus creation and after some tries the game crashes.

**Comment by Geethebluesky** [comment]
Does your issue look similar to #821?

**Comment by TonyMestre** [comment]
No, in that issue, the crafting can be done, but in my case the Blank Focus "vanish" before i can craft it.

**Comment by TonyMestre** [comment]
I changed to Beta 13 but the problem still happens

**Comment by TonyMestre** [comment]
Looks like some mod that i have makes items disappear if i let the storage open, can someone say what mod does this?
![captura de tela 171](https://user-images.githubusercontent.com/39807789/40816799-3ae5d6f8-6525-11e8-9543-8b2d8e83037b.png)

**Comment by Geethebluesky** [comment]
Try using search to find anyone else who may have raised a similar issue in the past, might be a bit faster.

**Comment by TonyMestre** [comment]
Ok, i think this is the bad part of using too much mods

**Comment by Azanor** [comment]
I will need a crash log to try and solve this.
Did you find out what mod was causing it?

**Comment by redgoblin88** [comment]
i have also noticed focal manipulator issues. not crashing but similar to your "having to put out and in several times" issue. when i tried to make a basic focus bolt>fire spell for some reason it wouldent let me craft, and upon closing and reopening (or even removing and putting back in the focus) it would forget what i had "put in" for the spell parts.
