### ISSUE TITLE
Thaumcraft not getting past loading screen.

### ISSUE THREAD

**Issue by PlatinumFox** [Azanor/thaumcraft-beta#924]
have tried beta13, beta14, beta15
have tried default forge version 2681 and latest 2705
have tried forge version + liteloader for 2681 and 2705

mods i am using are:
![screenshot 1034](https://user-images.githubusercontent.com/23727270/40814346-b7bcc3ca-650d-11e8-8572-4718dd7fc358.png)

have never had a problem with any of these mods until i tried adding thaumcraft into the mix.

i try loading the fresh mod folder i made and it crashes halfway through and i keep getting the same error.
"The game crashed whilst initializing game
Error: java.lang.NoSuchFieldError: visBattery"

a bunch of crash logs:
[crash-2018-05-31_19.45.56-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060531/crash-2018-05-31_19.45.56-client.txt)
[crash-2018-05-31_19.43.26-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060532/crash-2018-05-31_19.43.26-client.txt)
[crash-2018-05-31_19.41.09-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060533/crash-2018-05-31_19.41.09-client.txt)
[crash-2018-05-31_19.37.58-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060535/crash-2018-05-31_19.37.58-client.txt)
[crash-2018-05-31_19.26.53-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060536/crash-2018-05-31_19.26.53-client.txt)
[crash-2018-05-31_19.20.33-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060537/crash-2018-05-31_19.20.33-client.txt)
[crash-2018-05-31_19.11.56-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060538/crash-2018-05-31_19.11.56-client.txt)
[crash-2018-05-31_19.08.44-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2060539/crash-2018-05-31_19.08.44-client.txt)

any help would be appreciated lol, havent touched thaumcraft since 1.7.10 and even then alls i did was scan stuff . i would like to get back into it for 1.12.2 and give it another shot and go more indepth with it.

**Comment by TonyMestre** [comment]
It's something about the Vis Battey, one of the machines of the mod

**Comment by Geethebluesky** [comment]
It's possible you have a mod conflict. Try removing all mods and launching without any except for Forge, Baubles and Thaumcraft (try Beta 13; versions 14 and 15 are pretty buggy.) Make sure that works first.

See if that works, then start adding mods back in until you find the one that causes the crash.

**Comment by PlatinumFox** [comment]
@Geethebluesky ill try it right now, although the crash logs all say its thaumcraft but give me a few min to test it out

**Comment by Geethebluesky** [comment]
Oh one other thing, make sure you aren't using a config file from any previous version of TC, let it generate new.

**Comment by PlatinumFox** [comment]
i got it to work thank you, i was using an unsupported version of Ice/Fire dragon mod that fixes a big bug that that mod had, the unsupported one was causing the crash. i switched to the official version and it loaded up to the main menu screen just fine.

**Comment by Geethebluesky** [comment]
Glad that worked :) If you're confident that's the solution, please close the issue.
