### ISSUE TITLE
[Thaumcraft 6 Beta 13] Infusion Enchanting only can use plain enchanted books

### ISSUE THREAD

**Issue by ncpalmie** [Azanor/thaumcraft-beta#928]
When trying to do infusion enchanting with the special enchantments from the thaumonomicon, you need a completely plain Enchanted Book like the one obtainable through /give "player" enchanted_book other wise the infusion won't go through. No other enchanted books work whether they're from vanilla or other mods.

**Comment by wamc2017** [comment]
Hmm, I'm using a self modified beta 15 because the normal one is crashing because of the particle error, but on my side all enchanted books work without problems when using the infusion enchantment. Do you have other mods installed?

**Comment by ncpalmie** [comment]
I'm sorry that was a typo, I've edited it to say Beta 13, must've had 15 on the brain from trying to get it to work. Thanks for noticing, I guess it's been fixed from 13 to 15.

**Comment by wamc2017** [comment]
Hmm, is your tool/sword at 100% health? I think I read somewhere about a bug where it doesn't work with damaged items but can't find the issue anymore...

**Comment by ncpalmie** [comment]
The tool was damaged already, but it worked once I used the command for the enchanted book and put that in instead of a naturally obtained one.

**Comment by Azanor** [comment]
So is this still an issue?

**Comment by ncpalmie** [comment]
As of beta 16, yes and no. It looks like I can now use vanilla enchantments but modded enchantments won't be taken.

**Comment by EnderofGames** [comment]
This is still a problem in Beta 26. Mods that alter vanilla enchants, even though they don't alter the books (such as Apotheosis) seem to cause all the books to not work, again. Only the book from "/give @p enchanted_book" works.
