### ISSUE TITLE
[Suggestion] Anti-griefing for flux - change in behavior

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#929]
I've recently heard of some going to other's bases and flushing ingredients in a crucible or the like to cause flux buildup and rift events to ruin and destroy their base/stuff. While this is not the intention of the mod (as far as I am aware) I'm curious if flux can be built up on a person instead of in the aura. For example, if I am near machines that cause flux slowly as a byproduct then it would slowly build up on me being the closest. If I were the one flushing a crucible (or similar item) of a lot of essentia, it would all effect me. When I've built up enough flux on my person, the rift even would happen in the chunk I'm in or right in front of me causing me to stop moving to witness it. Just a thought. :)

**Comment by androshalforc** [comment]
that wouldnt change anything really.
just set up a crucible with an item dropper underneath their base and walk away

**Comment by VallenFrostweaver** [comment]
Ok so not the best idea but you see this is another example of griefing that is very simple to do.

**Comment by withercrusher** [comment]
Hi Vallen!

**Comment by F9Alejandro** [comment]
@androshalforc if that is the case, then there can be a block place event to see who placed the block and check if it is dropping the items in the crucible or not, if so then apply the negative effects to the player, even if they go offline >:3

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#353
