### ISSUE TITLE
Essence ends up where it should have never been able to go

### ISSUE THREAD

**Issue by AnrDaemon** [Azanor/thaumcraft-beta#931]
A very, very, very old bug.
![javaw-20180601-225105 23](https://user-images.githubusercontent.com/6532485/40868449-a66882cc-6615-11e8-9943-f88f85e35947.jpg)

**Comment by AnrDaemon** [comment]
To explain the image, the tube atop the Vacuos jar contains Praecantatio essentia, which should have never been able to end up there in first place, according to suction rules.

**Comment by Azanor** [comment]
Did you place the jars first, or the tubes first?

**Comment by AnrDaemon** [comment]
You may assume it was tubes first, since I had to juggle jars around multiple times to get crafting going.
But either way it was well before the crafting started.
