### ISSUE TITLE
Holding the Thaumometer crashes my game

### ISSUE THREAD

**Issue by George0079** [Azanor/thaumcraft-beta#932]
I don't know why, but simply holding the thaumometer crashes the game. I'm getting no crash reports, for some reason, but the server always goes kaput.

**Comment by yunruiwatts** [comment]
@George0079 please provide a crash log and mention which version of Thaumcraft you've got.

If you're running beta 15, chances are you ran into issue 858, and it has been reported many times already. I posted earlier on how to check if it's the same issue or not - https://github.com/Azanor/thaumcraft-beta/issues/884#issuecomment-392299593

If it is the same as 858, go ahead and close this issue.
