### ISSUE TITLE
Arcane Bellows: "Ghast shoots" subtitle visible as long as chunk is still loaded

### ISSUE THREAD

**Issue by Broam** [Azanor/thaumcraft-beta#940]
No matter how far away you are from an actively pumping arcane bellows, you can see the "Ghast Shoots" subtitle it produces as long as the chunk is loaded.

As I play with subtitles, this makes me have to use redstone to disable (or break) my bellows when not in use.

**Comment by Azanor** [comment]
Unfortunately nothing I can do to stop this. I simply play the sound effect, but obviously minecraft doesn't check what is causing the sound and simply triggers off the audio itself.
