### ISSUE TITLE
[Possible Bug] Pechs not spawning

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#944]
So, I started a world with TC6 beta 14, and from the beggining I lived in a Magical Forest, however, I never came across a Pech, I can't even hear the sounds they make, so it seems they are not spawning
Is this a bug or do I only have bad luck?

**Comment by Azanor** [comment]
Yup, they are semi-rare. They do indeed spawn, but aren't particularly plentiful.

**Comment by AnrDaemon** [comment]
Additionally, they may spawn underground, if there's a dungeon or ravine hidden under your feet.

**Comment by SirKastic** [comment]
Thanks, that just seemed very unfortunate since I have this world for some weeks now
