### ISSUE TITLE
[B13] Server - AURAS TAKING Xms LONGER THAN NORMAL

### ISSUE THREAD

**Issue by MMFQDEATH** [Azanor/thaumcraft-beta#946]
It happens in all active dimensions at about an hour of play. Running forge 1.12.2-14.23.4.2707. Here's a pastebin of the console errors. https://pastebin.com/gJ0r3i6a

**Comment by Azanor** [comment]
This will occasionally happen if there is a lag spike on the server, but unless the console is being constantly spammed by this it is not a problem.
