### ISSUE TITLE
[Suggestion] Make one of the Essentia Smeltery inputs go to the fuel slot

### ISSUE THREAD

**Issue by CubeWrench202** [Azanor/thaumcraft-beta#948]
As the title says, i would suggest making one of the input sides of the Essentia Smeltery (maybe right side) direct items into the fuel slot, so we can auto-fill it using hoppers.

**Comment by Gravityowl** [comment]
At the moment i believe you can fill the fuel slot from the bottom via golemancy also put suggestions [here](https://github.com/Azanor/thaumcraft-suggestions/issues)
