### ISSUE TITLE
[B16] Crash when placing Nitor in World

### ISSUE THREAD

**Issue by WJK2002** [Azanor/thaumcraft-beta#949]
It seems that the crash from #858 was not fixed completely in this beta. This happened when placing (white) nitor on the ground.

Crash Report:
https://pastebin.com/a3Q6SNJJ

**Comment by Raumis** [comment]
Your log shows you have beta15.
    | UCHIJAAAA | thaumcraft                           | 6.1.BETA15               | Thaumcraft-1.12.2-6.1.BETA15.jar                  | None                                     |
