### ISSUE TITLE
[1.12.2] [B16] FTB Utilities and Use seal 

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#956]
Hi,

don't know if this is related to #818 but if FTB Utilities is present (the area don't need to be claimed) the use seal doesn't work and the log throws the following error every time the golem tries to right click a block (in this case a cauldron with a bucket, filled with water):

https://gist.github.com/wamc2017/5985748b1db25115413711fb59cfb040

Everything works fine if FTB Utilities is not present. Also tried other blocks (like the lightwell from Astral Sorcery with aquamarines) with the same result.

Mods I used to test this issue (no other mods installed):
Baubles-1.12-1.5.2
FTBLib-5.1.0.21
FTBUtilities-5.1.0.26
jei_1.12.2-4.9.2.196
Thaumcraft-1.12.2-6.1.BETA16
Forge-14.23.4.2707

Issue on FTB Utilities tracker: https://github.com/LatvianModder/FTBUtilities/issues/764

Thanks for looking into it.

Best regards,
wamc

**Comment by Azanor** [comment]
I'm using the normal forge fake player for the use seal. This might be something I need to fix, but I will wait for the FTB Utils guys to chime in first. Maybe they can let me know what I am missing.

**Comment by wamc2017** [comment]
Fixed in beta 17! :)
