### ISSUE TITLE
[1.12.2] [B16] Ore clusters and Embers

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#957]
Hi,

Thaumcraft doesn't recognize the ores from the Embers mod (copper, lead and silver) for the ore clusters. The ores/ingots from Embers have proper ore dictionary entries. Don't know if this is related to #809. There's also an issue on Soot's issue tracker (which is an addon to Embers) about this: https://github.com/DaedalusGame/Soot/issues/45

Mods used to test this issue (no other mods installed):
Baubles-1.12-1.5.2
embers-0.230
jei_1.12.2-4.9.2.196
Thaumcraft-1.12.2-6.1.BETA16
Forge-14.23.4.2707

Thanks for looking into it.

Best regards
wamc

**Comment by Azanor** [comment]
This might have something to do with when embers adds their ores to the ore dictionary. I check for other ores in the recipe RegistryEvent, since I need it just before my recipes are created.

**Comment by Sunconure11** [comment]
Embers is being picked up again.

**Comment by DaedalusGame** [comment]
in Embers Rekindled i moved oredict registry to the RecipeRegistry event but still no dice, and I can't identify where oredict ores are gathered in beta 16 (i have it in my dev environment)

**Comment by HenryLoenwind** [comment]
Forge's javadoc says to register with the oreDict in the FMLInitializationEvent...

We had the same issues and had to move our recipe registration into the IMC event...
