### ISSUE TITLE
Thaumcraft Crashes

### ISSUE THREAD

**Issue by princessbinas** [Azanor/thaumcraft-beta#958]
The Thaumcraft (version 1.12.2-6.1.BETA15) I am using is part of the modpack, Dark MagicTeach by iamtpage. He has it set for Forge version 2705. I have added Optifine, WorldEdit and TrashSlots on my own for more functionality and to increase FPS.

The issue I have is that whenever I use the Thaumometer or Salis Mundis, my game crashes entirely. I am not sure if this issue was fixed in BETA16, but if need be, I will test for it and post the results here.

Salis Mundis Crashs:
https://pastebin.com/PvZrTXJy
https://pastebin.com/L2KxQf1k
Thaumometer Crash:
https://pastebin.com/YJtGK9rE

**Comment by NillerMedDild** [comment]
Remember to close the issue :)
