### ISSUE TITLE
Massive frame drop

### ISSUE THREAD

**Issue by DrEthan77** [Azanor/thaumcraft-beta#959]
I have been playing a survival 1.12.2 save and I just barely got the thaumometer in my game and I noticed that whenever it is in my main hand the frames drop from like 40 to about 2, this got me interested so I experimented. 
Other than that frame drop there is one other when the thaumometer is in my off hand the frames remain fine, but when I hover over the first slot in my hotbar the frames once again drop to about 2, this got me very confused. If you need any more info I will be happy to oblige.  
( https://drive.google.com/open?id=15EUVsHV0vaV02eRifo_TkWFMCBjbjl56  here is the link to a video I made showing this bug in effect, the first part has me holding it in my off hand, then I switch to the first hotbar slot, then I take the thaumometer into my main hand and switch to my first slot)

**Comment by DrEthan77** [comment]
here is a screenshot of all my mods 
![screen shot 2018-06-05 at 10 31 28 am](https://user-images.githubusercontent.com/20546072/40989633-ac9efe80-68ab-11e8-806d-93a30e225059.png)

**Comment by yunruiwatts** [comment]
Try updating to beta 16 - this is probably a duplicate of #478

**Comment by Geethebluesky** [comment]
Duplicate of #656; should be solved in Beta 16, you're still using 13 if that list is accurate. Please update your version and try again.

(Next time you can also save yourself some time by searching for issues by keyword :)

**Comment by DrEthan77** [comment]
oops sorry I tried looking by keyword but i guess i didnt look hard enough XD.

**Comment by DrEthan77** [comment]
...... still broke ;-;

**Comment by DrEthan77** [comment]
and because the other one was closed i had to post here

**Comment by DragonOfStendarr** [comment]
I also has this issue.

**Comment by DragonOfStendarr** [comment]
All tho if used in another hand, it doesn't lose the fps.

**Comment by DragonOfStendarr** [comment]
Im not sure yet what mod conflict it is, but im closing in, i hope.

**Comment by SirKastic** [comment]
Yeah, it is impossible to use the thaumometer, and I'm using beta 16
I thought it could be a Twiligth Forest incompatibility problem, because my fps started dropping when I tried to scan a TF block but now I can't even hold it that the game lags

**Comment by wamc2017** [comment]
I also got some fps drops, but only when I'm looking on my golems, everything else is fine on my side using beta 16.

@DrEthan77,

have you tried it without Optifine?

**Comment by DragonOfStendarr** [comment]
It is not Optifine atleast.

**Comment by DragonOfStendarr** [comment]
![image](https://user-images.githubusercontent.com/11031465/41001697-fbd1cfc6-6911-11e8-817a-d2f8e1615a23.png)
ive come this far, lagging when adding these mods. I'll work on it more tomorrow.

**Comment by DrEthan77** [comment]
@wamc2017 no i have not tried it but because it is still happening to dragon i wont try it

**Comment by androshalforc** [comment]
I believe the last time this happened it was due to the number of mods not a specific mod azonor had tweaked some things to try and make it better.

**Comment by DragonOfStendarr** [comment]
does make sense @androshalforc, but that means there are an issue which needs fixing

**Comment by DrEthan77** [comment]
ok, they reopened #478 and the creator said that this problem might be fixed in a17 so ima close this duplicate for now.
