### ISSUE TITLE
Alchemical Metallurgy step 3 missing text description. Blocks advancement.

### ISSUE THREAD

**Issue by DelfCo** [Azanor/thaumcraft-beta#965]
Hover over the treasure chest icon, and all it shows is "research.c_voidstuff.text". Hard to know how to satisfy the requirement in order to advance.

This was added to an existing "missing text" bug, but that hasn't been acted upon, and the fact that this missing description blocks advancement in Alchemy wasn't mentioned.

**Comment by wamc2017** [comment]
Step 3 is wip, because the eldritch stuff isn't completed yet...

**Comment by DelfCo** [comment]
Then research.c_voidstuff.text should be set to something that makes that clear. Leaving it unset leaves the question up in the air.

**Comment by Geethebluesky** [comment]
The mod is still in beta, and this has already been addressed before in #55. There are going to be plenty more questions left up in the air until a release.

**Comment by DelfCo** [comment]
OK. My beef would be with the modpack creators who didn't make it clear that they were using prerelease mods, not with the mod maker who's still working.
