### ISSUE TITLE
[B16] Snow has no Aspects

### ISSUE THREAD

**Issue by NillerMedDild** [Azanor/thaumcraft-beta#967]
Hey! I'm not sure whether this is intentional or not, but Snow, Snow Layer and Snowballs have no Aspects.

Thaumcraft 6 BETA16
Forge 1.12.2-14.23.4.2705

**Comment by Azanor** [comment]
It might be a mod interaction on your side - they all have aspects when I look at them. Are you running any other mods?

**Comment by NillerMedDild** [comment]
Over 200 other mods, I'll see if I can isolate the one causing it.
