### ISSUE TITLE
(1.10.2-6.0.BETA2) Research bug

### ISSUE THREAD

**Issue by thanasishadow** [Azanor/thaumcraft-beta#97]
Some times, when you select a research sheet to continue your research, you become unable to interact with blocks, break blocks, drop items etc.
First time this happened, I had selected "rethink" many times in a row and I had many inspiration points and the second time I was extensively researching the same research. I'm not sure what is causing it.

Edit: After a while, the client crashes and nothing special seems to be showing up in the console

**Comment by alexanderniebuhr** [comment]
@Azanor This is the same as my issue #88

Glad that i am not alone

**Comment by AzraelTWC** [comment]
Hungry chest has no animation when it eats an item.
