### ISSUE TITLE
[Possible Bug] Arcane Infusions Always Unstable

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#974]
So, I was going to do my firat infusion in this New tc world, boots of the traveller, fairly easy, and not a very high instablity, negligeble ad the book says
However, I had my setup, all symetrical by the altar (I did had no candles and stuff, but since it was of negligeble instability I thought that's okay)
Then it got very unstable, I died from taint poisoning, it consumed all my essentia, the items blew up and some taint started spawning
Later I tries the same infusion, same symmetry, same everything, but with 40 candles and some skulls (I wemt on a creative world) and the samw thing happened, Is this okay? It certainly doesn't feel okay
Also, not that this matter very much but as a linguistics enthusiast it surely does annoy me, the thaumanomicon isn't consistent, for example, in the Arcane Infusion entry it goes from first person to third, I really like the new first person thaumanomicon, but there some incosistences scatterwd around

**Comment by luminousinsect** [comment]
I know for a fact that skulls/candles/etc. have to be as symmetric as possible as well. Perfectly symmetric ingredient/table placement with asymmetric skulls/candles will be as unstable as an unstable ingredient/table arrangement. However for me with a few candles and skulls (4 skulls and 12 candles) the  infusion altar will still say its unstable as soon as you start infusing even if you have the stabilizer underneath the central table underneath the infusion matrix (not sure if this is the correct spot, I think the thaumonomicon should be clearer about this), however that will only destroy/blow off items at an insignificant probability if at all.

**Comment by Geethebluesky** [comment]
> Also, not that this matter very much but as a linguistics enthusiast it surely does annoy me, the thaumanomicon isn't consistent, for example, in the Arcane Infusion entry it goes from first person to third, I really like the new first person thaumanomicon, but there some incosistences scatterwd around

It annoys me too, I'm working on that at the moment.

**Comment by luminousinsect** [comment]
Not sure if the stabilizer is working at all. I used it attached/pointed to the bottom of the central altar pedestal (under the matrix) and powered with a vis generator, as well as pointed to the infusion matrix from above also powered with a vis generator. "Minor" instability infusions (so far the thaumium fortress helm and chestpiece) go dangerously unstable for both. If neither of these are the correct positions, the research entry in the thaumonomicon definitely needs to be clearer about this. Also as a suggestion I think the particles from the stabilizer could be less subtle it took me a while to notice it was even on.

Additionally, all of my candles & skulls are between the outer pedestals & the central columns/altar, not sure if this does anything because I never really noticed an effect from this in TC4/5 since infusion was far less unstable.

**Comment by Raumis** [comment]
Basic setup for Boots Of The Traveler:
![traveler_itemposition](https://user-images.githubusercontent.com/7782127/41106846-f4932678-6a3e-11e8-989c-3efbd2286f88.jpg)
Without tallow or skulls this will go unstable.

Stable configuration throughout infusion
![traveler_stableuntilend](https://user-images.githubusercontent.com/7782127/41106907-1c8ca6b8-6a3f-11e8-93e9-c4e21717d83b.jpg)

**Comment by luminousinsect** [comment]
Just tested that exact setup with the Thaumium Fortress Leggings, a Minor instability, with the stabilizer on and pointing directly at the infusion matrix, still goes dangerously unstable. Might work fine with Negligible but not Minor or above. I'll try my next one with an arcane stone floor since everyone seems to do that even though the Thaumonomicon doesn't mention it.

**Comment by SirKastic** [comment]
Yea, that seems weird tho...
I got scared when everyting started blowing up, I'll try and  move the infusion altar somewere clearer, cange te floor to arcane stone, currently it is greatwood planks, and make te setup that Raumis showed... hope that this works

**Comment by red360** [comment]
All you need is a bunch of stuff around your altar to make a very high instability very stable.
![2018-06-09_15 01 46](https://user-images.githubusercontent.com/38801399/41196527-ff4f64b4-6bf6-11e8-8c61-142996a0dd46.png)
![2018-06-09_15 01 59](https://user-images.githubusercontent.com/38801399/41196528-01ce59de-6bf7-11e8-8142-bc024cb4a2d3.png)
![2018-06-09_15 02 48](https://user-images.githubusercontent.com/38801399/41196529-03be026c-6bf7-11e8-8e73-e4b22570d465.png)

**Comment by SirKastic** [comment]
Yeah, thay still feels like too much, I don't want to have a floating floor filled with candles and skulls (which I can't get in survival) just to be able to craft
I have 32 candles, and a Stabilizer, and still I can't do crafting witout it becoming dangerously unstable
I tried doing te vis amulet with this setup and it still got unstable and blew my items up, I tougth that the Stabilizer would be there to fix that

**Comment by Geethebluesky** [comment]
There's a Reddit post out there with all the math, suggesting formulas that can be useful to achieve complete stability. According to @AnrDaemon it's on the order of 400 candles or such...!

**Comment by SirKastic** [comment]
That's ridiculous '-'
I'm gonna have to make a hidden layer bellow the altar with a bunch of candles then (good thing my basic math skills aren't all that good, and I ended up crafting 2 stacks of candles when I just wanted to craft half a stack)

**Comment by red360** [comment]
You can also fill the the spaces down on the same level out in a radius of 2 blocks with just candles. Thats not creative i have more mods. I just put them up there so the flux doesn't was them away.

**Comment by SirKastic** [comment]
Yeah, the stabilizer works for me... kind of, no crashes, it just barely helps with stabilization
like, without candles every infusion would get unstable
with some candles I can make negligeble instability infusions
and with the stabilizer now I can make minor instability infusions I believe

**Comment by AnrDaemon** [comment]
Unless something has changed (I know, this may feel dull by now, but it's a necessary disclaimer), the active area from which runic matrix drawing essentia and in which it looking for stabilizer is 5 blocks above, 10 below and 12 across to the sides. Again, I emphasize the role of Runic Matrix as an anchor point for all calculations.
Plenty of space to hide your stabilizers, if you are inclined to make your infusions completely stable.
And the [relevant reddit post](https://www.reddit.com/r/feedthebeast/comments/1z57dg/want_to_know_how_thaumcraft_infusion_symmetry_is/).

**Comment by Azanor** [comment]
The rules behind the scenes have changed quite a bit since b14. For example 10 candles/skulls/whatever is now the cap - more than that is pointless. There is a bug in b14-b16 which ignores that cap, but it is fixed for b17.

Stability is now a resource that gets used every craft cycle. Think of it like hit points. Candles and such adds a small amount of passive 'regen' to that hit point pool every cycle, while Stabilizers adds a much bugger chunk. Stabilizers also allow you to add a buffer of stability before crafting even starts.
You can use multiple Stabilizers and they can accept a lot more power than a single vis generator can generate.

Saying that I have been tweaking the numbers and candles and such will offer a lot more stability out of the box.

**Comment by SirKastic** [comment]
Oh, I don't think I can suply a stabilizer with more than the power of a single vis generator since I'm only playing with Thaumcraft (well, some other non-game changing mods as well)
And, I believe the thaumonomicon isn't very clear on this: do the stabilizers have to placed symmetrically as well?

**Comment by AnrDaemon** [comment]
You can connect multiple genrators to the same block, you know?…

**Comment by Geethebluesky** [comment]
How? It doesn't visually attach unless it's directly behind the Stabilizer. (Caveat, I suck at energy except where conduits are involved)

**Comment by AnrDaemon** [comment]
In general, RF consupers are not sided. But… since there's no obvious ways to see is the Stabilizer is powered… also it is unclear what is its peak RF/t consumption… Testing is not easy.

**Comment by Geethebluesky** [comment]
Looking forward to these indicators in beta 17+ then I suppose. :)

**Comment by luminousinsect** [comment]
That explains it. I had only one vis generator hooked up to my stabilizer. Time to hook up my stabilizers to my TE/EnderIO power system so I don't suck the vis dry xD. Do vis generators take workbench chargers or will they in the future? Also I'm still not clear on what the stabilizer needs to be aimed at, the infusion matrix itself or just in the general area of the altar?

**Comment by Geethebluesky** [comment]
The Runic Matrix itself I believe.

**Comment by AnrDaemon** [comment]
The matrix itself. Once I reloaded the world, there was a gentle halo coming from stabilizer into the matrix' direction.
There's probably some synchronization issues there.

**Comment by luminousinsect** [comment]
Yeah there’s a couple more issues there that might be synchronization-related; the infusion matrix text (seen with goggles) doesn’t seem to update when infusion isn’t occurring, it just keeps the last stability value from the last infusion, then all of the sudden today it reverted to very stable quite some time after my last infusion (maybe after restart and/or chunks reloading).

**Comment by SirKastic** [comment]
Why are we using RF / FE to power magic again?... Never quite got that
Anyhow, I could place more than one vis generator pointing at the same stabilizer, but the stabilizer only has on inpuit in its back side

**Comment by Geethebluesky** [comment]
I'm wondering the same. Besides the obvious bonus of integrating with more technical mods, not sure how this fits in the magical theme. Hoping there's additional lore or development or stuff that explains it.

**Comment by AnrDaemon** [comment]
Consider it returning to the roots (TC1/2).

**Comment by Szasdragon** [comment]
[Suggestion] Maybe if the altar zap you first time, the Thaumonomicon gain a new Addendum at Infusion for explain some more specific stabilizing hints. What counts, what factors weighing more.
