### ISSUE TITLE
[1.12.2] [B16] Can't refill water in a partially filled crucible with waterbucket

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#978]
Filling the crucible works fine when it's empty, but I can't seem to refill it by means of waterbucket until I completely drained it. Maybe something to do with the waterbucket being a universal bucket, but that's just a really wild guess.

Botania x354
Immersive Engineering x82
forge x2707

**Comment by Raumis** [comment]
Cant have an half empty water bucket its all or none.

**Comment by MalkContent** [comment]
this worked in every previous iteration of tc though.
i will gladly waste some water and have an empty bucket if it means that i can top the crucible off before crafting

**Comment by yunruiwatts** [comment]
"this worked in every previous iteration of tc" - has it? I don't recall ever being able to do that.

**Comment by MalkContent** [comment]
well. you could do that. tc5 and 4, check it out. haven't played tc3-

**Comment by Gammaboy45** [comment]
I would greatly enjoy this if it did exist. It is pretty annoying having to wait until it empties to refill and continue.

**Comment by Azanor** [comment]
I've switched to using mostly built-in forge methods for fluid handing, but I guess they can't fill a container unless there is enough space remaining. Hmmm.

**Comment by Ulysses2** [comment]
Seems this would be the kind of thing best solved from the Forge side, especially since other mods would be able to make use of it too if they added blocks like cauldrons.
