### ISSUE TITLE
[1.12.2] [B13] Hedge Alchemy cant done after do magic tallow

### ISSUE THREAD

**Issue by wong8888** [Azanor/thaumcraft-beta#980]
after i do magic tallow
thaumonomicon not count me do magic tallow.

![image](https://user-images.githubusercontent.com/1074528/41109371-7576f142-6aa9-11e8-8d68-0f341452c8d3.png)
![image](https://user-images.githubusercontent.com/1074528/41109397-800f2be2-6aa9-11e8-999f-e2c303761659.png)

**Comment by Geethebluesky** [comment]
Update to Beta 16 and try again?

**Comment by Raumis** [comment]
It doesn't if it just in the inventory it has to be created from the crucible.

**Comment by Azanor** [comment]
Yeah, this should be fixed in b16
