### ISSUE TITLE
Golems can duplicate and disappear

### ISSUE THREAD

**Issue by spookyjuke** [Azanor/thaumcraft-beta#985]
Hope this is the place for TC6 bug reporting.

Thaumcraft golems will occasionally disappear or duplicate themselves. The disappearing only seems to happen when you've moved far enough away from the chunk but the duplication I've had happen while I was in the area. Didn't actually witness it happen but I nametagged my golems beforehand to confirm that it was duplication.

I've read the disappearing could be them falling out of the world when a chunk is unloaded and the circumstances that they poof do give some credence to that theory. None of my guard golems have had this happen to them, which just stand there still most of the time.

My farm golems on the other hand, which are constantly buzzing back and forth up and down stairs depositing/replanting crops over what I know to be more than 1 chunk, are prone to disappearance and duplication. If they ran into an unloaded chunk I would think they would fall into the void. Maybe they could change themselves to be completely still and not be affected by gravity when no one is closeby or transform into a more static form?

As far as why they duplicate, I got nothing.

**Comment by Azanor** [comment]
The joy if MC entities. This was one of the main reasons I wanted to switch to using wisps instead of golems, but people seemed really opposed to the idea.

Unfortunately nothing much I can do to solve this issue.

**Comment by spookyjuke** [comment]
Sorry to hear I know how much a development dead end sucks. But wisps would be better because they'd spawn and despawn making it a non issue or because they can't fall into the void since they fly? If the second one, could a chunk that was kept active by some means like

https://ftbwiki.org/Chunk_Loader_(MineFactory_Reloaded)

theoretically stop the cross chunk falling?

**Comment by snydej** [comment]
I've got a farm using golems right next to an animal pen with 3 cows and 3 skeleton horses. The golems disappear after a day or so while nothing ever happens with the animals; they've been there for months. Be honest. It's a bug and not one that can be attributed to Minecraft.
