### ISSUE TITLE
Uncommon and Rare loot bags don't have ID's

### ISSUE THREAD

**Issue by FatalBlade** [Azanor/thaumcraft-beta#987]
Edit:Beta16

Not sure if this is intentional or if this is a bug but when using the command /give PLAYERNAME thaumcraft:xxxx_xxxx you can only get a common lootbag there are no ID's listed for uncommon and rare. I've tried things like loot_bag:{0-3} to no avail as well. Nothing shows up with thaumcraft:loot_ and hitting the tab key either. Finally, I tried turning on advanced tooltips and using 5158:2. 

I was trying to use this to find the ID's so that I could make a few different loot tables and potentially drop those into some of the default Minecraft ones.

**Comment by FatalBlade** [comment]
Ahh okay, I do apologise for the ignorance, though this does leave inconsistencies with the rest of the "loot items" all of the crates and urnes have _common/_uncommon/_rare. Ex: loot_crate_uncommon

 This does solve how to put this into the loot_table however so I thank you.
{
                    "type": "item",
                    "name": "thaumcraft:loot_bag",
                    "weight": 2,
                    "functions": [
                        {
                            "function": "set_data",
                            "data": 2
                        }
                    ]
                }

**Comment by wamc2017** [comment]
The other loot items are blocks, the treasure bags are items, I don't see any inconsistency here, because those are two different things... ^^

Don't forget to close this issue...

**Comment by FatalBlade** [comment]
Ah okay thank you so much, I'll do that now.
