### ISSUE TITLE
Golem use seal doesn't seem to work with Astral Sorcery lightwell

### ISSUE THREAD

**Issue by drachs** [Azanor/thaumcraft-beta#990]
I thought it would be neat to use a golem instead of a mechanical user.  You have to right click the lightwell with a gem like aquamarine to put it in.  The golem fetches the gem from the chest fine and starts clicking but it doesn't get put into the well.

**Comment by wamc2017** [comment]
Do you have FTBUtilities installed? If so it could be a duplicate of #956
