### ISSUE TITLE
provide/empty seals and storage drawers

### ISSUE THREAD

**Issue by ziba1** [Azanor/thaumcraft-beta#992]
Hi, so was gonna make a golem storage system using the storage drawers mod with its controller, the store seal works on the controller, wanted to put provide seals on the drawers themselves for item retrieval and they wont attach.  With an empty seal on an actually additions crate for dumping stuff in for the golem to sort through.

The provide seal and the empty seal also doesnt attach to the actually additions small storage crates, but the storage seal will.

**Comment by Azanor** [comment]
What version of TC are you using?

**Comment by ziba1** [comment]
1.12.2-6.1.BETA13

I think, going off the twitch information
