### ISSUE TITLE
Rifts

### ISSUE THREAD

**Issue by Phiapsi** [Azanor/thaumcraft-beta#993]
I have a big problem. I have many Rifts in my base and dont know how to close them.
Is there a way to close them in the newest beta build?

**Comment by Lukas45** [comment]
Currently there's no way to close them. Azanor plans to add that, hopefully in B17
#954

**Comment by ziba1** [comment]
If you switch to creative, theres a flux scrubbing sponge, you can give yourself that, then switch back to survival, Ive just done that on my world until something gets added for survival

**Comment by AlekseiVoronin** [comment]
Sponge Flux - removes the Flux.

**Comment by Schattenn** [comment]
I'd still like a non-cheat version. I've read that rifts used to go away on their own, so I guess they not doing that now is a bug?

**Comment by Lukas45** [comment]
Actually intended, as Azanor wrote in #954.
This behavior changed in B14 I believe (I'm still running B13), and currently there's no survival way to get rid of them.

**Comment by Geethebluesky** [comment]
Just to be clear, ways of getting rid of rifts are coming in B17 or future betas, it's not intended that they stay there permanently. Just for now.

**Comment by Schattenn** [comment]
> Actually intended, as Azanor wrote in #954.
Indeed. Thank you. Ah well, I was waiting for a "fix" anyway, so I guess now I'm waiting for a regular update instead. ^^
