### ISSUE TITLE
[Beta 16] Addenduns bug

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#996]
Addenduns are getting added tosome thaumanomicon entries beforethe requiredresearch for the addendum is completed
just opening a entry, and not completing it, is leading to addedun pop-ups

**Comment by Azanor** [comment]
Could you give specifics please.

**Comment by SirKastic** [comment]
Some Research Cards have blocks that they need in other to be completed
when it requires a block, like a piston on a enchantment table, there is a weird transparency glitch, as in, the block becomes a bit transparent
As soon as I log back to play the game I'll take a screenshot
BTW, I feel like this could be optifine now that I think about it... anyhow, I'll try it with and without optifine and I'll tell my results later
