### ISSUE TITLE
Verdant Charms Recipes

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#997]
In the thaumanomicon I believe the recipeis wrong, as it seems to require a Lifegiver Verdant Charm to be able to craft a Lifegiver Verdant Charm

**Comment by LastXsile** [comment]
This is visual only as i have made both charms only using the normal Verdant Charm.

**Comment by Azanor** [comment]
Odd, for me it looks fine.

**Comment by SirKastic** [comment]
Yeah, but for me in the thaumanomicon the central item is the same as the top result item

**Comment by F9Alejandro** [comment]
It could be a config issue if it was changed in a modpack for example.
