### ISSUE TITLE
Research Table Illumination Glitch

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#998]
The blocks that are required to complete certain research cards have weird illumination and transparency glitches

**Comment by Azanor** [comment]
Could you be more specific please?

**Comment by NextdoorPsycho** [comment]
the highlight  of the rift (spacey glitter overlay) is overlayed on the pages' item if its a block/item (not all items or blocks- but few, and it's not even 100% of the time for that block)

B16- still a thing, not game-breaking, I thought it was aesthetic... but if that's not intended, oh well
