### ISSUE TITLE
Thaumanomicon Grammar

### ISSUE THREAD

**Issue by SirKastic** [Azanor/thaumcraft-beta#999]
A lot of entries in the thaumanomicon have weird grammar and ortography

**Comment by wamc2017** [comment]
I think I read somewhere that Azanor isn't a native english speaker...

You could proofread the en_us file here, if you want: https://github.com/Azanor/thaumcraft-beta/blob/master/en_us.lang

**Comment by Geethebluesky** [comment]
I'm working on this at the moment. I have to go through him to get the changes approved.

**Comment by SirKastic** [comment]
Yeah, I'm also not a native english speaker, but it just seems that they typed the thaumanomicon entry yoo fast and didn't proof-read it, so you got places where letters are missing, and "if" instead of "of"...

**Comment by ST-DDT** [comment]
@Geethebluesky Could you open a PR and link it here so everyone else could (re-)view the changes as well?

**Comment by Geethebluesky** [comment]
I've forked the repo on my end if you **really** want to look. The thing for now is there are inconsistencies in several directions (US vs UK spelling, capitalizations, inconsistent 1st and 3rd-person perspectives etc.) that could mean subtle and more serious changes to about 75% of the file, just for wording (I try very hard not to change meanings except to clarify instructions). Without confirming those major decisions first, I would be giving everyone else a bad file to start commenting on.

I messaged Azanor to take a look at it first and check if the most general stuff is going in the right direction at least. After that's settled I'll make a pull request.

**Comment by AnrDaemon** [comment]
Just go with the most likely meaning. I'm no native English speaker either, but it was irking me for quite a while. Haven't had the time to get to the translation myself.
I'd suggest you start with US one, unless you're UK native.

**Comment by Geethebluesky** [comment]
I have some professional experience with editing, should be fine. ;)

**Comment by AnrDaemon** [comment]
Don't pose it as a problem. There's not many wrong //wordings// per se. It's mostly "it's" and wrong addressing of subjects.
Also, you could always create MORE language files, if needed. The current one is clearly labeled as en_us, so, just go with that.

**Comment by AnrDaemon** [comment]
Also Azanor/thaumcraft-suggestions#246

**Comment by Geethebluesky** [comment]
@AnrDaemon You're welcome to post on my repo if you want to discuss this further!
